ACP - Autonomous Command Protocol: acp_crypto.c File Reference
acp_crypto.c File Reference
ACP cryptographic functions - SHA-256 and HMAC-SHA256.
#include "acp_crypto.h"
#include <string.h>
Macros
#define ROTR(x, n)
#define CH(x, y, z)
#define MAJ(x, y, z)
#define EP0(x)
#define EP1(x)
#define SIG0(x)
#define SIG1(x)
Functions
void acp_sha256_init (acp_sha256_ctx_t *ctx)
Initialize SHA-256 context.
static void acp_sha256_process_block (acp_sha256_ctx_t *ctx, const uint8_t *data)
Process a single 512-bit block.
void acp_sha256_update (acp_sha256_ctx_t *ctx, const uint8_t *data, size_t len)
Update SHA-256 with additional data.
void acp_sha256_final (acp_sha256_ctx_t *ctx, uint8_t *hash)
Finalize SHA-256 and output hash.
void acp_sha256 (const uint8_t *data, size_t len, uint8_t *hash)
Compute SHA-256 hash in one call.
void acp_hmac_sha256 (const uint8_t *key, size_t key_len, const uint8_t *data, size_t data_len, uint8_t *mac)
Compute HMAC-SHA256 in one operation.
int acp_crypto_memcmp_ct (const void *a, const void *b, size_t len)
Constant-time memory comparison.
int acp_hmac_verify (const uint8_t *expected, const uint8_t *received, size_t len)
Verify HMAC-SHA256 authentication tag.
void acp_crypto_clear (void *data, size_t len)
Clear sensitive data from memory.
int acp_sha256_self_test (void)
Run SHA-256 self-tests with known test vectors.
int acp_hmac_self_test (void)
Run HMAC-SHA256 self-tests with known test vectors.
int acp_crypto_self_test (void)
Run all cryptographic self-tests.
Variables
static const uint32_t K [64]
SHA-256 constants (first 32 bits of the fractional parts of the cube roots of the first 64 primes).
static const uint32_t H0 [8]
SHA-256 initial hash values (first 32 bits of the fractional parts of the square roots of the first 8 primes).
Detailed Description
ACP cryptographic functions - SHA-256 and HMAC-SHA256.
This module provides portable HMAC-SHA256 and SHA-256 implementations for the ACP protocol authentication system.
All functions are implemented in pure C99 without external dependencies, implementing RFC 2104 (HMAC) and FIPS 180-4 (SHA-256).
Definition in file acp_crypto.c.
Macro Definition Documentation
CH
#define CH (x, y, z)
Value:
(((x) & (y)) ^ (~(x) & (z)))
Definition at line 59 of file acp_crypto.c.
EP0
#define EP0 (x)
Value:
(ROTR(x, 2) ^ ROTR(x, 13) ^ ROTR(x, 22))
Definition at line 61 of file acp_crypto.c.
EP1
#define EP1 (x)
Value:
(ROTR(x, 6) ^ ROTR(x, 11) ^ ROTR(x, 25))
Definition at line 62 of file acp_crypto.c.
MAJ
#define MAJ (x, y, z)
Value:
(((x) & (y)) ^ ((x) & (z)) ^ ((y) & (z)))
Definition at line 60 of file acp_crypto.c.
ROTR
#define ROTR (x, n)
Value:
(((x) >> (n)) | ((x) << (32 - (n))))
Definition at line 58 of file acp_crypto.c.
SIG0
#define SIG0 (x)
Value:
(ROTR(x, 7) ^ ROTR(x, 18) ^ ((x) >> 3))
Definition at line 63 of file acp_crypto.c.
SIG1
#define SIG1 (x)
Value:
(ROTR(x, 17) ^ ROTR(x, 19) ^ ((x) >> 10))
Definition at line 64 of file acp_crypto.c.
Function Documentation
acp_crypto_clear()
void acp_crypto_clear (void * data, size_t len)
Clear sensitive data from memory.
Securely clears memory containing sensitive data like keys or contexts. Prevents compiler optimization from eliminating the clear operation.
Parameters
data Memory to clear
len Number of bytes to clear
Definition at line 331 of file acp_crypto.c.
Referenced by acp_hmac_sha256(), acp_session_rotate(), acp_session_terminate(), and acp_sha256().
acp_crypto_memcmp_ct()
int acp_crypto_memcmp_ct (const void * a, const void * b, size_t len)
Constant-time memory comparison.
Constant-time memory comparison for cryptographic operations.
Compares two memory regions in constant time to prevent timing attacks. This is critical for MAC verification.
Parameters
a First memory region
b Second memory region
len Number of bytes to compare
Returns
0 if equal, non-zero if different
Definition at line 307 of file acp_crypto.c.
Referenced by acp_decode_frame(), acp_hmac_self_test(), acp_hmac_verify(), acp_sha256_self_test(), test_constant_time_comparison(), and validate_truncation_properties().
acp_crypto_self_test()
int acp_crypto_self_test (void)
Run all cryptographic self-tests.
Run comprehensive crypto self-tests.
Returns
0 if all tests pass, non-zero if any test fails
Definition at line 378 of file acp_crypto.c.
References acp_hmac_self_test(), and acp_sha256_self_test().
acp_hmac_self_test()
int acp_hmac_self_test (void)
Run HMAC-SHA256 self-tests with known test vectors.
Returns
0 if all tests pass, non-zero if any test fails
Definition at line 361 of file acp_crypto.c.
References acp_crypto_memcmp_ct(), acp_hmac_sha256(), and ACP_SHA256_SIZE.
Referenced by acp_crypto_self_test().
acp_hmac_sha256()
void acp_hmac_sha256 (const uint8_t * key, size_t key_len, const uint8_t * data, size_t data_len, uint8_t * mac)
Compute HMAC-SHA256 in one operation.
Compute HMAC-SHA256.
Parameters
key HMAC key
key_len Length of key in bytes
data Input data to authenticate
data_len Length of input data
mac Output MAC (16 bytes)
Definition at line 246 of file acp_crypto.c.
References acp_crypto_clear(), acp_sha256(), ACP_SHA256_BLOCK_SIZE, acp_sha256_final(), acp_sha256_init(), ACP_SHA256_SIZE, and acp_sha256_update().
Referenced by acp_decode_frame(), acp_encode_frame(), acp_hmac_self_test(), acp_session_compute_hmac(), test_acp_hmac_truncation(), test_hmac_consistency(), test_hmac_key_lengths(), test_rfc4231_vectors(), test_vector_1(), test_vector_2(), test_vector_3(), test_vector_4(), test_vector_5(), and validate_truncation_properties().
acp_hmac_verify()
int acp_hmac_verify (const uint8_t * expected, const uint8_t * received, size_t len)
Verify HMAC-SHA256 authentication tag.
Performs constant-time verification of HMAC tag to prevent timing attacks.
Parameters
expected Expected MAC value
received Received MAC value to verify
len Length of MAC (typically 16 bytes for ACP)
Returns
0 if verification succeeds, non-zero if fails
Definition at line 326 of file acp_crypto.c.
References acp_crypto_memcmp_ct().
Referenced by acp_session_verify_hmac().
acp_sha256()
void acp_sha256 (const uint8_t * data, size_t len, uint8_t * hash)
Compute SHA-256 hash in one call.
Compute SHA-256 hash in one operation.
Definition at line 231 of file acp_crypto.c.
References acp_crypto_clear(), acp_sha256_final(), acp_sha256_init(), and acp_sha256_update().
Referenced by acp_hmac_sha256(), and acp_sha256_self_test().
acp_sha256_final()
void acp_sha256_final (acp_sha256_ctx_t * ctx, uint8_t * hash)
Finalize SHA-256 and output hash.
Finalize SHA-256 hash and produce output.
Definition at line 182 of file acp_crypto.c.
References ACP_SHA256_BLOCK_SIZE, acp_sha256_process_block(), acp_sha256_ctx_t::bit_len, acp_sha256_ctx_t::buffer, acp_sha256_ctx_t::buffer_len, and acp_sha256_ctx_t::state.
Referenced by acp_hmac_sha256(), and acp_sha256().
acp_sha256_init()
void acp_sha256_init (acp_sha256_ctx_t * ctx)
Initialize SHA-256 context.
Parameters
ctx Context to initialize
Definition at line 69 of file acp_crypto.c.
References acp_sha256_ctx_t::bit_len, acp_sha256_ctx_t::buffer, acp_sha256_ctx_t::buffer_len, H0, and acp_sha256_ctx_t::state.
Referenced by acp_hmac_sha256(), and acp_sha256().
acp_sha256_process_block()
void acp_sha256_process_block (acp_sha256_ctx_t * ctx, const uint8_t * data) static
Process a single 512-bit block.
Definition at line 83 of file acp_crypto.c.
References K, and acp_sha256_ctx_t::state.
Referenced by acp_sha256_final(), and acp_sha256_update().
acp_sha256_self_test()
int acp_sha256_self_test (void)
Run SHA-256 self-tests with known test vectors.
Returns
0 if all tests pass, non-zero if any test fails
Definition at line 344 of file acp_crypto.c.
References acp_crypto_memcmp_ct(), acp_sha256(), and ACP_SHA256_SIZE.
Referenced by acp_crypto_self_test().
acp_sha256_update()
void acp_sha256_update (acp_sha256_ctx_t * ctx, const uint8_t * data, size_t len)
Update SHA-256 with additional data.
Update SHA-256 hash with new data.
Definition at line 144 of file acp_crypto.c.
References ACP_SHA256_BLOCK_SIZE, acp_sha256_process_block(), acp_sha256_ctx_t::bit_len, acp_sha256_ctx_t::buffer, and acp_sha256_ctx_t::buffer_len.
Referenced by acp_hmac_sha256(), and acp_sha256().
Variable Documentation
H0
const uint32_t H0[8] static
Initial value:
= {
    0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
    0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19}
SHA-256 initial hash values (first 32 bits of the fractional parts of the square roots of the first 8 primes).
Definition at line 53 of file acp_crypto.c.
Referenced by acp_sha256_init().
K
const uint32_t K[64] static
Initial value:
= {
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
    0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
    0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
    0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
    0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2}
SHA-256 constants (first 32 bits of the fractional parts of the cube roots of the first 64 primes).
Definition at line 42 of file acp_crypto.c.
Referenced by acp_sha256_process_block().