ACP - Autonomous Command Protocol: acp_session.c File Reference
acp_session.c File Reference
ACP Session Management - Authentication and Replay Protection.
#include "acp_protocol.h"
#include "acp_crypto.h"
#include <string.h>
Functions
acp_result_t acp_session_init (acp_session_t *session, uint32_t key_id, const uint8_t *key, size_t key_len, uint64_t nonce)
Initialize a new ACP session.
acp_result_t acp_session_rotate (acp_session_t *session, const uint8_t *new_key, size_t new_key_len, uint64_t new_nonce)
Rotate session key and nonce.
void acp_session_terminate (acp_session_t *session)
Terminate session and clear sensitive data.
int acp_session_is_expired (const acp_session_t *session)
Check if session is expired (simplified).
acp_result_t acp_session_compute_hmac (const acp_session_t *session, const uint8_t *frame_data, size_t frame_len, uint8_t *hmac_out)
Compute HMAC for frame authentication.
acp_result_t acp_session_verify_hmac (const acp_session_t *session, const uint8_t *frame_data, size_t frame_len, const uint8_t *expected_hmac)
Verify HMAC for frame authentication.
acp_result_t acp_session_get_tx_seq (acp_session_t *session, uint32_t *seq_out)
Get next sequence number for transmission.
acp_result_t acp_session_check_rx_seq (acp_session_t *session, uint32_t rx_seq)
Simple sequence validation without full replay protection.
int acp_session_is_initialized (const acp_session_t *session)
Check if session is initialized.
Detailed Description
ACP Session Management - Authentication and Replay Protection.
Version
0.3.0
Date
2025-10-27
This module manages ACP session state, sequence numbers, and replay protection. It provides authentication context for secure frame processing.
Definition in file acp_session.c.
Function Documentation
acp_session_check_rx_seq()
acp_result_t acp_session_check_rx_seq (acp_session_t * session, uint32_t rx_seq)
Simple sequence validation without full replay protection.
Definition at line 267 of file acp_session.c.
References ACP_ERR_INVALID_PARAM, ACP_ERR_REPLAY, ACP_ERR_SESSION_NOT_INIT, ACP_OK, acp_session_t::initialized, and acp_session_t::last_accepted_seq.
acp_session_compute_hmac()
acp_result_t acp_session_compute_hmac (const acp_session_t * session, const uint8_t * frame_data, size_t frame_len, uint8_t * hmac_out)
Compute HMAC for frame authentication.
Parameters
session Session context containing auth key
frame_data Frame data to authenticate
frame_len Length of frame data
hmac_out Output HMAC buffer (16 bytes)
Returns
ACP_OK on success, error code on failure
Definition at line 166 of file acp_session.c.
References ACP_ERR_INVALID_PARAM, ACP_ERR_SESSION_NOT_INIT, acp_hmac_sha256(), ACP_OK, acp_session_t::initialized, and acp_session_t::key.
Referenced by acp_session_verify_hmac().
acp_session_get_tx_seq()
acp_result_t acp_session_get_tx_seq (acp_session_t * session, uint32_t * seq_out)
Get next sequence number for transmission.
Definition at line 240 of file acp_session.c.
References ACP_ERR_INVALID_PARAM, ACP_ERR_SESSION_NOT_INIT, ACP_OK, acp_session_t::initialized, and acp_session_t::next_sequence.
acp_session_init()
acp_result_t acp_session_init (acp_session_t * session, uint32_t key_id, const uint8_t * key, size_t key_len, uint64_t nonce)
Initialize a new ACP session.
Initialize an ACP session.
Parameters
session Session context to initialize
session_id Unique session identifier
key Authentication key (32 bytes)
nonce Session nonce (16 bytes)
Returns
ACP_OK on success, error code on failure
Definition at line 49 of file acp_session.c.
References ACP_ERR_INVALID_PARAM, ACP_OK, acp_session_t::initialized, acp_session_t::key, acp_session_t::key_id, acp_session_t::last_accepted_seq, acp_session_t::next_sequence, and acp_session_t::nonce.
Referenced by acp_keystore_init_session(), and demo_authenticated_command().
acp_session_is_expired()
int acp_session_is_expired (const acp_session_t * session)
Check if session is expired (simplified).
Parameters
session Session context
Returns
1 if expired, 0 if still valid
Definition at line 144 of file acp_session.c.
References acp_session_t::initialized.
acp_session_is_initialized()
int acp_session_is_initialized (const acp_session_t * session)
Check if session is initialized.
Definition at line 298 of file acp_session.c.
References acp_session_t::initialized.
acp_session_rotate()
acp_result_t acp_session_rotate (acp_session_t * session, const uint8_t * new_key, size_t new_key_len, uint64_t new_nonce)
Rotate session key and nonce.
Rotate session key or nonce.
Parameters
session Session context
new_key New authentication key (32 bytes)
new_nonce New session nonce (16 bytes)
Returns
ACP_OK on success, error code on failure
Definition at line 83 of file acp_session.c.
References acp_crypto_clear(), ACP_ERR_INVALID_PARAM, ACP_ERR_SESSION_NOT_INIT, ACP_OK, acp_session_t::initialized, acp_session_t::key, acp_session_t::last_accepted_seq, acp_session_t::next_sequence, and acp_session_t::nonce.
acp_session_terminate()
void acp_session_terminate (acp_session_t * session)
Terminate session and clear sensitive data.
Parameters
session Session context to terminate
Definition at line 121 of file acp_session.c.
References acp_crypto_clear(), acp_session_t::initialized, acp_session_t::key, acp_session_t::key_id, acp_session_t::last_accepted_seq, acp_session_t::next_sequence, acp_session_t::nonce, and acp_session_t::policy_flags.
acp_session_verify_hmac()
acp_result_t acp_session_verify_hmac (const acp_session_t * session, const uint8_t * frame_data, size_t frame_len, const uint8_t * expected_hmac)
Verify HMAC for frame authentication.
Parameters
session Session context containing auth key
frame_data Frame data to verify
frame_len Length of frame data
expected_hmac Expected HMAC value (16 bytes)
Returns
ACP_OK if verification succeeds, error code on failure
< Truncated to 16 bytes per ACP spec
< Truncated to 16 bytes per ACP spec
Definition at line 195 of file acp_session.c.
References ACP_ERR_AUTH_FAILED, ACP_ERR_INVALID_PARAM, ACP_ERR_SESSION_NOT_INIT, ACP_HMAC_SIZE, acp_hmac_verify(), ACP_OK, acp_session_compute_hmac(), and acp_session_t::initialized.