ACP - Autonomous Command Protocol: acp_nvs.c File Reference
acp_nvs.c File Reference
Non-volatile storage (keystore) implementation for ACP.
#include "acp_protocol.h"
#include "acp_platform_keystore.h"
#include "acp_errors.h"
#include <stdio.h>
#include <string.h>
#include <errno.h>
Classes
struct acp_keystore_header_t
Keystore file header.
struct acp_keystore_entry_t
Keystore entry.
Macros
#define ACP_KEYSTORE_PATH "./acp_keystore.bin"
Default keystore file path.
#define ACP_KEYSTORE_MAGIC 0x41435046 /* "ACPF" */
Keystore file magic number.
#define ACP_KEYSTORE_VERSION 1
Keystore file version.
Functions
acp_result_t acp_keystore_init (void)
Initialize keystore.
acp_result_t acp_keystore_get (uint32_t key_id, uint8_t *key_data, size_t key_size)
Get key from keystore.
acp_result_t acp_keystore_set (uint32_t key_id, const uint8_t *key_data, size_t key_size)
Set key in keystore.
acp_result_t acp_keystore_delete (uint32_t key_id)
acp_result_t acp_keystore_clear (void)
Clear all keys from keystore.
acp_result_t acp_keystore_init_session (acp_session_t *session, uint32_t key_id, uint64_t nonce)
Initialize session with key from keystore.
Detailed Description
Non-volatile storage (keystore) implementation for ACP.
This module provides file-based keystore functionality for the ACP protocol. Keys are stored in a simple binary format on disk.
Definition in file acp_nvs.c.
Macro Definition Documentation
ACP_KEYSTORE_MAGIC
#define ACP_KEYSTORE_MAGIC 0x41435046 /* "ACPF" */
Keystore file magic number.
Definition at line 48 of file acp_nvs.c.
Referenced by acp_keystore_get(), acp_keystore_init(), and acp_keystore_set().
ACP_KEYSTORE_PATH
#define ACP_KEYSTORE_PATH "./acp_keystore.bin"
Default keystore file path.
Definition at line 42 of file acp_nvs.c.
Referenced by acp_keystore_clear(), acp_keystore_get(), acp_keystore_init(), and acp_keystore_set().
ACP_KEYSTORE_VERSION
#define ACP_KEYSTORE_VERSION 1
Keystore file version.
Definition at line 53 of file acp_nvs.c.
Referenced by acp_keystore_get(), acp_keystore_init(), and acp_keystore_set().
Function Documentation
acp_keystore_clear()
acp_result_t acp_keystore_clear (void)
Clear all keys from keystore.
Returns
ACP_OK on success, error code on failure
< Operation successful
< Operation successful
Definition at line 257 of file acp_nvs.c.
References ACP_ERR_IO, ACP_KEYSTORE_PATH, and ACP_OK.
acp_keystore_delete()
acp_result_t acp_keystore_delete (uint32_t key_id)
< Feature not implemented
Definition at line 250 of file acp_nvs.c.
References ACP_ERR_NOT_IMPLEMENTED.
acp_keystore_get()
acp_result_t acp_keystore_get (uint32_t key_id, uint8_t * key_data, size_t key_size)
Get key from keystore.
Parameters
[in] key_id Key identifier
[out] key_data Buffer to receive key data
[in] key_size Size of key buffer (must be >= ACP_KEY_SIZE)
Returns
ACP_OK on success, ACP_ERR_KEY_NOT_FOUND if not found, other error codes on failure
< Invalid parameter passed
< Key not found in keystore
< Operation successful
< Key not found in keystore
Definition at line 111 of file acp_nvs.c.
References ACP_ERR_INVALID_FORMAT, ACP_ERR_INVALID_PARAM, ACP_ERR_IO, ACP_ERR_KEY_NOT_FOUND, ACP_KEY_SIZE, ACP_KEYSTORE_MAGIC, ACP_KEYSTORE_PATH, ACP_KEYSTORE_VERSION, ACP_OK, acp_keystore_header_t::key_count, acp_keystore_entry_t::key_data, acp_keystore_entry_t::key_id, acp_keystore_header_t::magic, and acp_keystore_header_t::version.
Referenced by acp_keystore_init_session().
acp_keystore_init()
acp_result_t acp_keystore_init (void)
Initialize keystore.
Returns
ACP_OK on success, error code on failure
< Operation successful
< Operation successful
Definition at line 77 of file acp_nvs.c.
References ACP_ERR_IO, ACP_KEYSTORE_MAGIC, ACP_KEYSTORE_PATH, ACP_KEYSTORE_VERSION, and ACP_OK.
Referenced by acp_keystore_set().
acp_keystore_init_session()
acp_result_t acp_keystore_init_session (acp_session_t * session, uint32_t key_id, uint64_t nonce)
Initialize session with key from keystore.
This is the "default keystore get_key()" function that automatically retrieves the key material from the keystore based on key_id.
Parameters
[out] session Session to initialize
[in] key_id Key identifier to look up
[in] nonce Session nonce
Returns
ACP_OK on success, error code on failure
< Invalid parameter passed
< Operation successful
Definition at line 284 of file acp_nvs.c.
References ACP_ERR_INVALID_PARAM, ACP_KEY_SIZE, acp_keystore_get(), ACP_OK, and acp_session_init().
acp_keystore_set()
acp_result_t acp_keystore_set (uint32_t key_id, const uint8_t * key_data, size_t key_size)
Set key in keystore.
Parameters
[in] key_id Key identifier
[in] key_data Key data to store
[in] key_size Size of key data (must be ACP_KEY_SIZE)
Returns
ACP_OK on success, error code on failure
< Invalid parameter passed
< Operation successful
< Operation successful
< Operation successful
Definition at line 161 of file acp_nvs.c.
References ACP_ERR_INVALID_FORMAT, ACP_ERR_INVALID_PARAM, ACP_ERR_IO, ACP_KEY_SIZE, acp_keystore_init(), ACP_KEYSTORE_MAGIC, ACP_KEYSTORE_PATH, ACP_KEYSTORE_VERSION, ACP_OK, acp_keystore_header_t::key_count, acp_keystore_entry_t::key_data, acp_keystore_entry_t::key_id, acp_keystore_header_t::magic, and acp_keystore_header_t::version.