ACP - Autonomous Command Protocol: examples/acp_client.c File Reference
acp_client.c File Reference
Example ACP client demonstrating frame encoding, authentication, and decoding.
#include "acp_protocol.h"
#include "acp_errors.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
Classes
struct telemetry_data_t
Example telemetry payload structure.
struct command_data_t
Example command payload structure.
Functions
static void print_frame_info (const acp_frame_t *frame)
Print frame contents for debugging.
static int demo_telemetry_frame (void)
Demonstrate telemetry frame encoding/decoding (unauthenticated).
static int demo_authenticated_command (void)
Demonstrate authenticated command frame.
int main (void)
Main example program.
Detailed Description
Example ACP client demonstrating frame encoding, authentication, and decoding.
This example shows how to:
Initialize an ACP session with authentication
Encode telemetry and command frames
Decode received frames with integrity/authentication validation
Handle errors and edge cases
Definition in file acp_client.c.
Function Documentation
demo_authenticated_command()
int demo_authenticated_command (void) static
Demonstrate authenticated command frame.
Definition at line 156 of file acp_client.c.
References acp_decode_frame(), acp_encode_frame(), ACP_ERR_REPLAY, ACP_FLAG_AUTHENTICATED, ACP_FRAME_TYPE_COMMAND, ACP_MAX_FRAME_SIZE, ACP_OK, acp_session_init(), and print_frame_info().
Referenced by main().
demo_telemetry_frame()
int demo_telemetry_frame (void) static
Demonstrate telemetry frame encoding/decoding (unauthenticated).
Definition at line 84 of file acp_client.c.
References acp_decode_frame(), acp_encode_frame(), ACP_FRAME_TYPE_TELEMETRY, ACP_MAX_FRAME_SIZE, ACP_OK, acp_frame_t::length, acp_frame_t::payload, and print_frame_info().
Referenced by main().
main()
int main (void)
Main example program.
Definition at line 257 of file acp_client.c.
References acp_cleanup(), acp_init(), ACP_OK, demo_authenticated_command(), and demo_telemetry_frame().
print_frame_info()
void print_frame_info (const acp_frame_t * frame) static
Print frame contents for debugging.
Definition at line 64 of file acp_client.c.
References acp_frame_t::flags, acp_frame_t::length, acp_frame_t::payload, acp_frame_t::sequence, and acp_frame_t::type.
Referenced by demo_authenticated_command(), and demo_telemetry_frame().