ACP - Autonomous Command Protocol: /Users/paulzanna/Github/acp/acp_crypto.h File Reference
/Users/paulzanna/Github/acp/acp_crypto.h File Reference
ACP cryptographic functions - SHA-256 and HMAC-SHA256.
#include <stdint.h>
#include <stddef.h>
Classes
struct acp_sha256_ctx_t
SHA-256 context structure for incremental hashing.
struct acp_hmac_ctx_t
HMAC-SHA256 context structure for incremental authentication.
Macros
#define ACP_SHA256_SIZE 32
SHA-256 hash output size in bytes.
#define ACP_SHA256_BLOCK_SIZE 64
SHA-256 block size in bytes.
#define ACP_HMAC_SIZE 16
HMAC-SHA256 output size in bytes.
#define ACP_HMAC_FULL_SIZE 32
HMAC-SHA256 full output size (before truncation).
#define ACP_HMAC_MAX_KEY_SIZE 64
Maximum key length for HMAC.
Functions
void acp_sha256_init (acp_sha256_ctx_t *ctx)
Initialize SHA-256 context.
void acp_sha256_update (acp_sha256_ctx_t *ctx, const uint8_t *data, size_t len)
Update SHA-256 hash with new data.
void acp_sha256_final (acp_sha256_ctx_t *ctx, uint8_t *hash)
Finalize SHA-256 hash and produce output.
void acp_sha256 (const uint8_t *data, size_t len, uint8_t *hash)
Compute SHA-256 hash in one operation.
void acp_hmac_init (acp_hmac_ctx_t *ctx, const uint8_t *key, size_t key_len)
Initialize HMAC-SHA256 context.
void acp_hmac_update (acp_hmac_ctx_t *ctx, const uint8_t *data, size_t len)
Update HMAC with new data.
void acp_hmac_final (acp_hmac_ctx_t *ctx, uint8_t *mac, int truncated)
Finalize HMAC and produce authentication tag.
void acp_hmac_sha256 (const uint8_t *key, size_t key_len, const uint8_t *data, size_t data_len, uint8_t *mac)
Compute HMAC-SHA256 in one operation.
int acp_crypto_memcmp_ct (const void *a, const void *b, size_t len)
Constant-time memory comparison.
int acp_hmac_verify (const uint8_t *expected, const uint8_t *received, size_t len)
Verify HMAC-SHA256 authentication tag.
void acp_crypto_clear (void *data, size_t len)
Clear sensitive data from memory.
int acp_sha256_self_test (void)
Run SHA-256 self-tests with known test vectors.
int acp_hmac_self_test (void)
Run HMAC-SHA256 self-tests with known test vectors.
int acp_crypto_self_test (void)
Run all cryptographic self-tests.
Detailed Description
ACP cryptographic functions - SHA-256 and HMAC-SHA256.
Provides portable implementations of SHA-256 hash and HMAC-SHA256 message authentication code functions for the ACP protocol.
Features:
Pure C99 implementation, no external dependencies
Constant-time operations for security-critical functions
Self-test vectors for validation
Optimized for embedded and cross-platform use
Version
0.3.0
Date
2025-10-27
Definition in file acp_crypto.h.
Macro Definition Documentation
ACP_HMAC_FULL_SIZE
#define ACP_HMAC_FULL_SIZE 32
HMAC-SHA256 full output size (before truncation).
Definition at line 65 of file acp_crypto.h.
ACP_HMAC_MAX_KEY_SIZE
#define ACP_HMAC_MAX_KEY_SIZE 64
Maximum key length for HMAC.
Definition at line 68 of file acp_crypto.h.
ACP_HMAC_SIZE
#define ACP_HMAC_SIZE 16
HMAC-SHA256 output size in bytes.
Truncated to 16 bytes per ACP spec
Definition at line 62 of file acp_crypto.h.
Referenced by acp_session_verify_hmac().
ACP_SHA256_BLOCK_SIZE
#define ACP_SHA256_BLOCK_SIZE 64
SHA-256 block size in bytes.
Definition at line 59 of file acp_crypto.h.
Referenced by acp_hmac_sha256(), acp_sha256_final(), and acp_sha256_update().
ACP_SHA256_SIZE
#define ACP_SHA256_SIZE 32
SHA-256 hash output size in bytes.
Definition at line 56 of file acp_crypto.h.
Referenced by acp_hmac_self_test(), acp_hmac_sha256(), and acp_sha256_self_test().
Function Documentation
acp_crypto_clear()
void acp_crypto_clear (void * data, size_t len)
Clear sensitive data from memory.
Securely clears memory containing sensitive data like keys or contexts. Prevents compiler optimization from eliminating the clear operation.
Parameters
data Memory to clear
len Number of bytes to clear
Definition at line 331 of file acp_crypto.c.
Referenced by acp_hmac_sha256(), acp_session_rotate(), acp_session_terminate(), and acp_sha256().
acp_crypto_memcmp_ct()
int acp_crypto_memcmp_ct (const void * a, const void * b, size_t len)
Constant-time memory comparison.
Compares two memory regions in constant time to prevent timing attacks. This is critical for MAC verification.
Parameters
a First memory region
b Second memory region
len Number of bytes to compare
Returns
0 if equal, non-zero if different
Definition at line 307 of file acp_crypto.c.
acp_crypto_self_test()
int acp_crypto_self_test (void)
Run all cryptographic self-tests.
Returns
0 if all tests pass, non-zero if any test fails
Definition at line 378 of file acp_crypto.c.
acp_hmac_final()
void acp_hmac_final (acp_hmac_ctx_t * ctx, uint8_t * mac, int truncated)
Finalize HMAC and produce authentication tag.
Parameters
ctx HMAC context
mac Output MAC (16 bytes truncated, or 32 bytes full)
truncated If true, output 16-byte truncated MAC
acp_hmac_init()
void acp_hmac_init (acp_hmac_ctx_t * ctx, const uint8_t * key, size_t key_len)
Initialize HMAC-SHA256 context.
Parameters
ctx HMAC context to initialize
key HMAC key
key_len Length of key in bytes
acp_hmac_self_test()
int acp_hmac_self_test (void)
Run HMAC-SHA256 self-tests with known test vectors.
Returns
0 if all tests pass, non-zero if any test fails
Definition at line 361 of file acp_crypto.c.
References acp_crypto_memcmp_ct(), acp_hmac_sha256(), and ACP_SHA256_SIZE.
Referenced by acp_crypto_self_test().
acp_hmac_sha256()
void acp_hmac_sha256 (const uint8_t * key, size_t key_len, const uint8_t * data, size_t data_len, uint8_t * mac)
Compute HMAC-SHA256 in one operation.
Parameters
key HMAC key
key_len Length of key in bytes
data Input data to authenticate
data_len Length of input data
mac Output MAC (16 bytes)
Definition at line 246 of file acp_crypto.c.
acp_hmac_update()
void acp_hmac_update (acp_hmac_ctx_t * ctx, const uint8_t * data, size_t len)
Update HMAC with new data.
Parameters
ctx HMAC context
data Input data to authenticate
len Length of input data in bytes
acp_hmac_verify()
int acp_hmac_verify (const uint8_t * expected, const uint8_t * received, size_t len)
Verify HMAC-SHA256 authentication tag.
Performs constant-time verification of HMAC tag to prevent timing attacks.
Parameters
expected Expected MAC value
received Received MAC value to verify
len Length of MAC (typically 16 bytes for ACP)
Returns
0 if verification succeeds, non-zero if fails
Definition at line 326 of file acp_crypto.c.
References acp_crypto_memcmp_ct().
Referenced by acp_session_verify_hmac().
acp_sha256()
void acp_sha256 (const uint8_t * data, size_t len, uint8_t * hash)
Compute SHA-256 hash in one operation.
Parameters
data Input data to hash
len Length of input data
hash Output hash (32 bytes)
Compute SHA-256 hash in one operation.
Definition at line 231 of file acp_crypto.c.
References acp_crypto_clear(), acp_sha256_final(), acp_sha256_init(), and acp_sha256_update().
Referenced by acp_hmac_sha256(), and acp_sha256_self_test().
acp_sha256_final()
void acp_sha256_final (acp_sha256_ctx_t * ctx, uint8_t * hash)
Finalize SHA-256 hash and produce output.
Parameters
ctx SHA-256 context
hash Output buffer (must be at least 32 bytes)
Finalize SHA-256 hash and produce output.
Definition at line 182 of file acp_crypto.c.
References ACP_SHA256_BLOCK_SIZE, acp_sha256_process_block(), acp_sha256_ctx_t::bit_len, acp_sha256_ctx_t::buffer, acp_sha256_ctx_t::buffer_len, and acp_sha256_ctx_t::state.
Referenced by acp_hmac_sha256(), and acp_sha256().
acp_sha256_init()
void acp_sha256_init (acp_sha256_ctx_t * ctx)
Initialize SHA-256 context.
Parameters
ctx Context to initialize
Definition at line 69 of file acp_crypto.c.
References acp_sha256_ctx_t::bit_len, acp_sha256_ctx_t::buffer, acp_sha256_ctx_t::buffer_len, H0, and acp_sha256_ctx_t::state.
Referenced by acp_hmac_sha256(), and acp_sha256().
acp_sha256_self_test()
int acp_sha256_self_test (void)
Run SHA-256 self-tests with known test vectors.
Returns
0 if all tests pass, non-zero if any test fails
Definition at line 344 of file acp_crypto.c.
References acp_crypto_memcmp_ct(), acp_sha256(), and ACP_SHA256_SIZE.
Referenced by acp_crypto_self_test().
acp_sha256_update()
void acp_sha256_update (acp_sha256_ctx_t * ctx, const uint8_t * data, size_t len)
Update SHA-256 hash with new data.
Parameters
ctx SHA-256 context
data Input data to hash
len Length of input data in bytes
Update SHA-256 hash with new data.
Definition at line 144 of file acp_crypto.c.
References ACP_SHA256_BLOCK_SIZE, acp_sha256_process_block(), acp_sha256_ctx_t::bit_len, acp_sha256_ctx_t::buffer, and acp_sha256_ctx_t::buffer_len.
Referenced by acp_hmac_sha256(), and acp_sha256().