ACP - Autonomous Command Protocol: /Users/paulzanna/Github/acp/acp_crc16.c File Reference
/Users/paulzanna/Github/acp/acp_crc16.c File Reference
CRC16-CCITT implementation for ACP frame integrity.
#include "acp_crc16.h"
#include <string.h>
Functions
void acp_crc16_init_table (void)
Initialize CRC16 lookup table.
const uint16_t * acp_crc16_get_table (void)
Get CRC16 lookup table.
uint16_t acp_crc16_init (void)
Initialize CRC16 calculation state.
uint16_t acp_crc16_update_byte (uint16_t crc, uint8_t byte)
Update CRC16 with a single byte.
uint16_t acp_crc16_update (uint16_t crc, const uint8_t *data, size_t length)
Update CRC16 calculation with new data.
uint16_t acp_crc16_finalize (uint16_t crc)
Finalize CRC16 calculation.
uint16_t acp_crc16_calculate (const uint8_t *data, size_t length)
Calculate CRC16-CCITT for a buffer.
int acp_crc16_verify (const uint8_t *data, size_t length, uint16_t expected_crc)
Verify CRC16 checksum.
const acp_crc16_test_vector_t * acp_crc16_get_test_vectors (size_t *count)
Get CRC16 test vectors.
int acp_crc16_self_test (void)
Run CRC16 self-test.
Variables
static uint16_t crc16_table [256]
CRC16-CCITT lookup table (computed at runtime or compile-time).
static int table_initialized = 0
static const char test_empty [] = ""
Test data strings.
static const char test_a [] = "A"
static const char test_123 [] = "123456789"
static const char test_hello [] = "Hello, World!"
static const char test_acp [] = "ACP Protocol Test Vector"
static const acp_crc16_test_vector_t test_vectors []
CRC16-CCITT test vectors.
Detailed Description
CRC16-CCITT implementation for ACP frame integrity.
This module implements CRC16-CCITT (ITU-T X.25) with polynomial 0x1021, initial value 0xFFFF, and no final XOR.
Version
0.3.0
Date
2025-10-27
Definition in file acp_crc16.c.
Function Documentation
acp_crc16_calculate()
uint16_t acp_crc16_calculate (const uint8_t * data, size_t length)
Calculate CRC16-CCITT for a buffer.
Calculates CRC16-CCITT checksum for the given data buffer using polynomial 0x1021, initial value 0xFFFF.
Parameters
[in] data Pointer to data buffer
[in] length Length of data in bytes
Returns
CRC16 checksum (16-bit value)
Definition at line 141 of file acp_crc16.c.
References acp_crc16_finalize(), acp_crc16_init(), and acp_crc16_update().
Referenced by acp_crc16_self_test(), acp_crc16_verify(), acp_frame_decode(), and acp_frame_encode().
acp_crc16_finalize()
uint16_t acp_crc16_finalize (uint16_t crc)
Finalize CRC16 calculation.
Applies final XOR to complete CRC16 calculation. For CRC16-CCITT, this is a no-op (final XOR is 0).
Parameters
[in] crc CRC16 state from update operations
Returns
Final CRC16 checksum
Definition at line 132 of file acp_crc16.c.
References ACP_CRC16_FINAL_XOR.
Referenced by acp_crc16_calculate().
acp_crc16_get_table()
const uint16_t * acp_crc16_get_table (void)
Get CRC16 lookup table.
Returns pointer to the 256-entry CRC16 lookup table for table-based implementations. The table is computed at compile time or runtime.
Returns
Pointer to CRC16 lookup table (256 entries)
Definition at line 80 of file acp_crc16.c.
References acp_crc16_init_table(), and crc16_table.
acp_crc16_get_test_vectors()
const acp_crc16_test_vector_t * acp_crc16_get_test_vectors (size_t * count)
Get CRC16 test vectors.
Returns array of test vectors for validating CRC16 implementation.
Parameters
[out] count Number of test vectors returned
Returns
Pointer to array of test vectors
Definition at line 209 of file acp_crc16.c.
References test_vectors.
Referenced by acp_crc16_self_test().
acp_crc16_init()
uint16_t acp_crc16_init (void)
Initialize CRC16 calculation state.
Initializes CRC16 state for incremental calculation.
Returns
Initial CRC16 state value
Definition at line 93 of file acp_crc16.c.
References ACP_CRC16_INIT.
Referenced by acp_crc16_calculate().
acp_crc16_init_table()
void acp_crc16_init_table (void)
Initialize CRC16 lookup table.
Initializes the CRC16 lookup table. Called automatically by other CRC functions, but can be called explicitly for performance.
This function is thread-safe and idempotent.
Definition at line 48 of file acp_crc16.c.
References ACP_CRC16_POLY, and crc16_table.
Referenced by acp_crc16_get_table(), acp_crc16_update(), acp_crc16_update_byte(), and acp_init().
acp_crc16_self_test()
int acp_crc16_self_test (void)
Run CRC16 self-test.
Runs built-in test vectors to validate CRC16 implementation.
Returns
Number of test failures (0 = all tests passed)
Definition at line 221 of file acp_crc16.c.
References acp_crc16_calculate(), and acp_crc16_get_test_vectors().
acp_crc16_update()
uint16_t acp_crc16_update (uint16_t crc, const uint8_t * data, size_t length)
Update CRC16 calculation with new data.
Updates CRC16 checksum with additional data. This allows for incremental calculation over multiple data chunks.
Parameters
[in] crc Current CRC16 state
[in] data Pointer to data buffer
[in] length Length of data in bytes
Returns
Updated CRC16 state
Definition at line 112 of file acp_crc16.c.
References acp_crc16_init_table(), and acp_crc16_update_byte().
Referenced by acp_crc16_calculate().
acp_crc16_update_byte()
uint16_t acp_crc16_update_byte (uint16_t crc, uint8_t byte)
Update CRC16 with a single byte.
Optimized function to update CRC16 with a single byte.
Parameters
[in] crc Current CRC16 state
[in] byte Data byte to process
Returns
Updated CRC16 state
Definition at line 101 of file acp_crc16.c.
References acp_crc16_init_table(), and crc16_table.
Referenced by acp_crc16_update().
acp_crc16_verify()
int acp_crc16_verify (const uint8_t * data, size_t length, uint16_t expected_crc)
Verify CRC16 checksum.
Verifies that the CRC16 checksum of data matches the expected value.
Parameters
[in] data Pointer to data buffer
[in] length Length of data in bytes
[in] expected_crc Expected CRC16 value
Returns
1 if CRC matches, 0 if mismatch
Definition at line 156 of file acp_crc16.c.
References acp_crc16_calculate().
Variable Documentation
crc16_table
uint16_t crc16_table[256] static
CRC16-CCITT lookup table (computed at runtime or compile-time).
Definition at line 42 of file acp_crc16.c.
Referenced by acp_crc16_get_table(), acp_crc16_init_table(), and acp_crc16_update_byte().
table_initialized
int table_initialized = 0 static
Definition at line 43 of file acp_crc16.c.
test_123
const char test_123[] = "123456789" static
Definition at line 169 of file acp_crc16.c.
test_a
const char test_a[] = "A" static
Definition at line 168 of file acp_crc16.c.
test_acp
const char test_acp[] = "ACP Protocol Test Vector" static
Definition at line 171 of file acp_crc16.c.
test_empty
const char test_empty[] = "" static
Test data strings.
Definition at line 167 of file acp_crc16.c.
test_hello
const char test_hello[] = "Hello, World!" static
Definition at line 170 of file acp_crc16.c.
test_vectors
const acp_crc16_test_vector_t test_vectors[] static
CRC16-CCITT test vectors.
Definition at line 174 of file acp_crc16.c.
Referenced by acp_crc16_get_test_vectors().