ACP - Autonomous Command Protocol: acp.c File Reference
acp.c File Reference
ACP core API implementation.
#include "acp_protocol.h"
#include "acp_version.h"
#include "acp_errors.h"
#include "acp_crc16.h"
#include "acp_cobs.h"
#include <string.h>
#include <stdio.h>
Functions
acp_result_t acp_init (void)
Initialize the ACP library.
void acp_cleanup (void)
Cleanup the ACP library.
acp_result_t acp_encode_frame (uint8_t type, uint8_t flags, const uint8_t *payload, size_t payload_len, acp_session_t *session, uint8_t *output, size_t *output_len)
Encode an ACP frame.
acp_result_t acp_decode_frame (const uint8_t *input, size_t input_len, acp_frame_t *frame, size_t *consumed, acp_session_t *session)
Decode an ACP frame from stream.
bool acp_is_valid_frame_type (uint8_t type)
Validate frame type.
bool acp_frame_requires_auth (uint8_t type)
Check if frame type requires authentication.
uint16_t acp_htons (uint16_t host_val)
Convert host uint16 to network byte order.
uint16_t acp_ntohs (uint16_t net_val)
Convert network uint16 to host byte order.
uint32_t acp_htonl (uint32_t host_val)
Convert host uint32 to network byte order.
uint32_t acp_ntohl (uint32_t net_val)
Convert network uint32 to host byte order.
Variables
static int acp_initialized = 0
Global library initialization flag.
Detailed Description
ACP core API implementation.
This module implements the core ACP protocol functions for frame encoding, decoding, and session management. Currently contains stubs that will be filled in during subsequent implementation phases.
Version
0.3.0
Date
2025-10-27
Definition in file acp.c.
Function Documentation
acp_cleanup()
void acp_cleanup (void)
Cleanup the ACP library.
Should be called when finished using the ACP library.
Definition at line 79 of file acp.c.
References acp_initialized.
Referenced by main().
acp_decode_frame()
acp_result_t acp_decode_frame (const uint8_t * input, size_t input_len, acp_frame_t * frame, size_t * consumed, acp_session_t * session)
Decode an ACP frame from stream.
Attempts to decode one complete ACP frame from input stream, handling COBS framing, CRC16 verification, and optional HMAC validation.
Parameters
[in] input Input stream buffer
[in] input_len Length of input data
[out] frame Decoded frame structure
[out] consumed Number of input bytes consumed
[in] session Session for authentication (NULL for unauthenticated)
Returns
ACP_OK on success, ACP_ERR_NEED_MORE_DATA if incomplete, other error codes on failure
< Invalid parameter passed
< Need more input data
< Frame structure is malformed
< Need more input data
< Operation successful
< Frame includes HMAC authentication
< Session not initialized
< Need more input data
< HMAC authentication failed
< Replay attack detected
< Authentication required but missing
< Operation successful
Definition at line 192 of file acp.c.
References ACP_COBS_DELIMITER, acp_crypto_memcmp_ct(), ACP_ERR_AUTH_FAILED, ACP_ERR_AUTH_REQUIRED, ACP_ERR_INVALID_PARAM, ACP_ERR_MALFORMED_FRAME, ACP_ERR_NEED_MORE_DATA, ACP_ERR_REPLAY, ACP_ERR_SESSION_NOT_INIT, ACP_FLAG_AUTHENTICATED, acp_frame_decode(), acp_frame_requires_auth(), acp_hmac_sha256(), ACP_HMAC_TAG_LEN, ACP_KEY_SIZE, ACP_OK, acp_frame_t::flags, acp_session_t::initialized, acp_session_t::key, acp_session_t::last_accepted_seq, acp_frame_t::sequence, and acp_frame_t::type.
Referenced by demo_authenticated_command(), demo_telemetry_frame(), receive_frames(), and test_partial_reads().
acp_encode_frame()
acp_result_t acp_encode_frame (uint8_t type, uint8_t flags, const uint8_t * payload, size_t payload_len, acp_session_t * session, uint8_t * output, size_t * output_len)
Encode an ACP frame.
Encodes payload data into a complete ACP frame with COBS framing, CRC16 integrity, and optional HMAC authentication.
Parameters
[in] type Frame type (acp_frame_type_t)
[in] flags Frame flags (ACP_FLAG_*)
[in] payload Payload data to encode
[in] payload_len Length of payload (0-ACP_MAX_PAYLOAD_SIZE)
[in] session Session for authentication (NULL for unauthenticated)
[out] output Output buffer for encoded frame
[in,out] output_len Input: buffer size, Output: encoded frame length
Returns
ACP_OK on success, error code on failure
< Invalid parameter passed
< Invalid parameter passed
< Payload exceeds maximum size
< Invalid frame type
< Frame includes HMAC authentication
< Authentication required but missing
< Frame includes HMAC authentication
< Session not initialized
< Frame includes HMAC authentication
< Operation successful
< Frame includes HMAC authentication
< Output buffer too small
< Operation successful
Definition at line 97 of file acp.c.
References ACP_ERR_AUTH_REQUIRED, ACP_ERR_BUFFER_TOO_SMALL, ACP_ERR_INVALID_PARAM, ACP_ERR_INVALID_TYPE, ACP_ERR_PAYLOAD_TOO_LARGE, ACP_ERR_SESSION_NOT_INIT, ACP_FLAG_AUTHENTICATED, acp_frame_encode(), acp_frame_requires_auth(), acp_hmac_sha256(), ACP_HMAC_TAG_LEN, acp_is_valid_frame_type(), ACP_KEY_SIZE, ACP_MAX_PAYLOAD_SIZE, ACP_OK, ACP_PROTOCOL_VERSION, acp_frame_t::flags, acp_session_t::key, acp_frame_t::length, acp_session_t::next_sequence, acp_frame_t::payload, acp_frame_t::sequence, acp_frame_t::type, and acp_frame_t::version.
Referenced by demo_authenticated_command(), demo_telemetry_frame(), send_sample_frames(), and test_partial_reads().
acp_frame_requires_auth()
bool acp_frame_requires_auth (uint8_t type)
Check if frame type requires authentication.
Parameters
[in] type Frame type to check
Returns
true if authentication required, false otherwise
Definition at line 330 of file acp.c.
References ACP_FRAME_TYPE_COMMAND, ACP_FRAME_TYPE_SYSTEM, and ACP_FRAME_TYPE_TELEMETRY.
Referenced by acp_decode_frame(), and acp_encode_frame().
acp_htonl()
uint32_t acp_htonl (uint32_t host_val)
Convert host uint32 to network byte order.
Parameters
[in] host_val Host byte order value
Returns
Network byte order value
Definition at line 381 of file acp.c.
Referenced by acp_ntohl().
acp_htons()
uint16_t acp_htons (uint16_t host_val)
Convert host uint16 to network byte order.
Parameters
[in] host_val Host byte order value
Returns
Network byte order value
Definition at line 351 of file acp.c.
Referenced by acp_ntohs().
acp_init()
acp_result_t acp_init (void)
Initialize the ACP library.
Must be called before using any other ACP functions.
Returns
ACP_OK on success, error code on failure
< Operation successful
< Operation successful
Definition at line 57 of file acp.c.
References acp_crc16_init_table(), acp_initialized, and ACP_OK.
Referenced by main().
acp_is_valid_frame_type()
bool acp_is_valid_frame_type (uint8_t type)
Validate frame type.
Parameters
[in] type Frame type to validate
Returns
true if valid, false otherwise
Definition at line 314 of file acp.c.
References ACP_FRAME_TYPE_COMMAND, ACP_FRAME_TYPE_SYSTEM, and ACP_FRAME_TYPE_TELEMETRY.
Referenced by acp_encode_frame().
acp_ntohl()
uint32_t acp_ntohl (uint32_t net_val)
Convert network uint32 to host byte order.
Parameters
[in] net_val Network byte order value
Returns
Host byte order value
Definition at line 405 of file acp.c.
References acp_htonl().
acp_ntohs()
uint16_t acp_ntohs (uint16_t net_val)
Convert network uint16 to host byte order.
Parameters
[in] net_val Network byte order value
Returns
Host byte order value
Definition at line 372 of file acp.c.
References acp_htons().
Variable Documentation
acp_initialized
int acp_initialized = 0 static
Global library initialization flag.
Definition at line 48 of file acp.c.
Referenced by acp_cleanup(), and acp_init().