ACP - Autonomous Command Protocol: acp_framer.c File Reference
acp_framer.c File Reference
ACP frame encoding and decoding implementation.
#include "acp_protocol.h"
#include "acp_errors.h"
#include "acp_crc16.h"
#include "acp_cobs.h"
#include "acp_platform_log.h"
#include <string.h>
Functions
int acp_frame_encode (const acp_frame_t *frame, uint8_t *output, size_t output_size, size_t *bytes_written)
Encode ACP frame to wire format.
int acp_frame_decode (const uint8_t *input, size_t input_size, acp_frame_t *frame, size_t *bytes_consumed)
Decode wire format to ACP frame.
size_t acp_frame_encoded_size (const acp_frame_t *frame)
Calculate encoded frame size.
int acp_frame_create_telemetry (acp_frame_t *frame, uint8_t msg_type, uint32_t sequence, const void *payload, size_t payload_len)
Create telemetry frame.
int acp_frame_create_command (acp_frame_t *frame, uint8_t msg_type, uint32_t sequence, uint8_t priority, const void *payload, size_t payload_len)
Create command frame.
Detailed Description
ACP frame encoding and decoding implementation.
Integrates COBS framing with CRC16 integrity checking to provide complete ACP frame processing as specified in the protocol.
Version
0.3.0
Date
2025-10-27
Definition in file acp_framer.c.
Function Documentation
acp_frame_create_command()
int acp_frame_create_command (acp_frame_t * frame, uint8_t msg_type, uint32_t sequence, uint8_t priority, const void * payload, size_t payload_len)
Create command frame.
< Invalid parameter passed
< Payload exceeds maximum size
< Operation successful
Definition at line 305 of file acp_framer.c.
References ACP_ERR_INVALID_PARAM, ACP_ERR_PAYLOAD_TOO_LARGE, ACP_MAX_PAYLOAD_SIZE, ACP_OK, ACP_PROTOCOL_VERSION, acp_frame_t::flags, acp_frame_t::length, acp_frame_t::payload, acp_frame_t::sequence, acp_frame_t::type, and acp_frame_t::version.
acp_frame_create_telemetry()
int acp_frame_create_telemetry (acp_frame_t * frame, uint8_t msg_type, uint32_t sequence, const void * payload, size_t payload_len)
Create telemetry frame.
< Invalid parameter passed
< Payload exceeds maximum size
< Operation successful
Definition at line 278 of file acp_framer.c.
References ACP_ERR_INVALID_PARAM, ACP_ERR_PAYLOAD_TOO_LARGE, ACP_MAX_PAYLOAD_SIZE, ACP_OK, ACP_PROTOCOL_VERSION, acp_frame_t::flags, acp_frame_t::length, acp_frame_t::payload, acp_frame_t::sequence, acp_frame_t::type, and acp_frame_t::version.
acp_frame_decode()
int acp_frame_decode (const uint8_t * input, size_t input_size, acp_frame_t * frame, size_t * bytes_consumed)
Decode wire format to ACP frame.
< Invalid parameter passed
< Need more input data
< Frame structure is malformed
< Need more input data
< Operation successful
< Frame structure is malformed
< Frame structure is malformed
< CRC16 verification failed
< Frame structure is malformed
< Frame includes HMAC authentication
< Payload exceeds maximum size
< Operation successful
Definition at line 131 of file acp_framer.c.
References acp_cobs_decode(), ACP_COBS_DELIMITER, acp_crc16_calculate(), ACP_ERR_CRC_MISMATCH, ACP_ERR_INVALID_PARAM, ACP_ERR_MALFORMED_FRAME, ACP_ERR_NEED_MORE_DATA, ACP_ERR_PAYLOAD_TOO_LARGE, ACP_FLAG_AUTHENTICATED, ACP_MAX_FRAME_SIZE, ACP_MAX_PAYLOAD_SIZE, ACP_OK, acp_wire_header_size(), acp_frame_t::flags, acp_frame_t::length, acp_frame_t::payload, acp_frame_t::sequence, acp_frame_t::type, and acp_frame_t::version.
Referenced by acp_decode_frame().
acp_frame_encode()
int acp_frame_encode (const acp_frame_t * frame, uint8_t * output, size_t output_size, size_t * bytes_written)
Encode ACP frame to wire format.
< Invalid parameter passed
< Output buffer too small
< Payload exceeds maximum size
< Frame includes HMAC authentication
< Operation successful
< Operation successful
Definition at line 46 of file acp_framer.c.
References ACP_COBS_DELIMITER, acp_cobs_encode(), acp_cobs_max_encoded_size(), acp_crc16_calculate(), ACP_ERR_BUFFER_TOO_SMALL, ACP_ERR_INVALID_PARAM, ACP_ERR_PAYLOAD_TOO_LARGE, ACP_FLAG_AUTHENTICATED, ACP_MAX_FRAME_SIZE, ACP_OK, acp_wire_header_size(), acp_frame_t::flags, acp_frame_t::length, acp_frame_t::payload, acp_frame_t::sequence, acp_frame_t::type, and acp_frame_t::version.
Referenced by acp_encode_frame().
acp_frame_encoded_size()
size_t acp_frame_encoded_size (const acp_frame_t * frame)
Calculate encoded frame size.
Definition at line 262 of file acp_framer.c.
References acp_cobs_max_encoded_size(), acp_wire_header_size(), acp_frame_t::flags, and acp_frame_t::length.