ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/src/services/audit.c File Reference
audit.c File Reference
Companion input mediation and audit trail service.
#include "audit.h"
#include "feature_config.h"
#include "ringbuf.h"
#include "gcs_gateway.h"
#include "mode_manager.h"
#include "safety_manager.h"
#include "failsafe.h"
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/semphr.h"
#include <string.h>
#include <stdio.h>
Functions
static esp_err_t classify_companion_input (const char *payload_summary, companion_classification_t *classification)
static esp_err_t evaluate_safety_gates (const char *payload_summary, safety_evaluation_t *evaluation)
static esp_err_t log_audit_event (const companion_input_t *input, const safety_evaluation_t *evaluation)
static bool is_source_whitelisted (const char *source_identity)
static int64_t get_timestamp_ms (void)
static void send_audit_summary (const companion_input_t *input)
esp_err_t audit_init (void)
Initialize the audit service.
void audit_deinit (void)
Shutdown the audit service.
bool audit_is_initialized (void)
Check if audit service is initialized.
esp_err_t audit_set_companion_whitelist (const char *source_identity)
Set the whitelisted companion source.
esp_err_t audit_process_companion_input (const char *source_identity, const char *payload_summary, const char *correlation_id, safety_decision_t *result)
Process companion input through safety gateway.
esp_err_t audit_get_recent_entries (companion_input_t *entries, size_t max_entries, size_t *actual_count)
Get recent audit entries.
esp_err_t audit_get_companion_whitelist (char *source_buffer, size_t buffer_size)
Get current companion whitelist.
esp_err_t audit_clear_companion_whitelist (void)
Clear the companion whitelist.
Variables
static const char * TAG = "audit"
static bool s_audit_initialized = false
static SemaphoreHandle_t s_audit_mutex = NULL
static char s_whitelisted_source [32] = {0}
static bool s_whitelist_active = false
static ringbuf_t s_audit_ringbuf
static bool s_ringbuf_initialized = false
static void * s_audit_buf_ptrs [AUDIT_EVENT_BUFFER_SIZE]
static uint8_t s_audit_data_block [AUDIT_EVENT_BUFFER_SIZE *sizeof(companion_input_t)]
Detailed Description
Companion input mediation and audit trail service.
This service implements the companion mediation gateway that ensures all external companion device inputs undergo proper safety evaluation before being allowed to affect vehicle behavior. Provides comprehensive audit trails for accountability and forensic analysis.
Core Functions:
Source whitelist enforcement (single authorized companion)
Command vs suggestion classification
Multi-layer safety gate evaluation (arming, mode, geofence, altitude)
Comprehensive audit logging with structured reason codes
Real-time operator visibility via telemetry summaries
Safety Architecture:
Input gateway blocks all non-whitelisted sources immediately
Safety evaluation includes arming state, flight mode, geofence, altitude
All decisions logged with detailed reason codes for analysis
Rate-limited telemetry prevents audit log flooding attacks
Audit Trail Properties:
Non-repudiation: All inputs logged with source identity
Chronological: Timestamp-ordered event sequence
Comprehensive: Both accepted and rejected commands logged
Structured: Machine-parseable reason codes and safety flags
Performance Characteristics:
Input evaluation: <500us typical latency
Memory footprint: ~8KB ring buffer + minimal state
No blocking operations (queued background processing)
Rate limiting: 2 msgs/sec telemetry, 500ms coalescing
Constitution Compliance:
Safety: All companion inputs mediated through safety gates
Real-time: Non-blocking evaluation with background telemetry
Observability: Operator-visible audit within 1 second
Testability: Structured outputs for automated validation
Author
Scout Firmware Team
Date
2025-10-26
Version
1.0
Definition in file audit.c.
Function Documentation
audit_clear_companion_whitelist()
esp_err_t audit_clear_companion_whitelist (void)
Clear the companion whitelist.
After clearing, all companion inputs will be rejected.
Returns
ESP_OK on success
Definition at line 340 of file audit.c.
audit_deinit()
void audit_deinit (void)
Shutdown the audit service.
Definition at line 127 of file audit.c.
audit_get_companion_whitelist()
esp_err_t audit_get_companion_whitelist (char * source_buffer, size_t buffer_size)
Get current companion whitelist.
Parameters
source_buffer Buffer to store source identity
buffer_size Size of source_buffer
Returns
ESP_OK if whitelist exists, ESP_ERR_NOT_FOUND if no whitelist set
Definition at line 316 of file audit.c.
audit_get_recent_entries()
esp_err_t audit_get_recent_entries (companion_input_t * entries, size_t max_entries, size_t * actual_count)
Get recent audit entries.
Retrieves the most recent companion input audit entries. Used by CLI 'audit show' command.
Parameters
entries Array to store audit entries
max_entries Maximum number of entries to retrieve
actual_count Pointer to store actual number retrieved
Returns
ESP_OK on success, error code otherwise
Definition at line 276 of file audit.c.
audit_init()
esp_err_t audit_init (void)
Initialize the audit service.
Sets up companion input gateway, whitelisting, and audit logging.
Returns
ESP_OK on success, error code otherwise
Definition at line 85 of file audit.c.
audit_is_initialized()
bool audit_is_initialized (void)
Check if audit service is initialized.
Returns
true if initialized, false otherwise
Definition at line 162 of file audit.c.
Referenced by gcs_gateway_log_to_audit_system(), and test_audit_system_integration_with_companion().
audit_process_companion_input()
esp_err_t audit_process_companion_input (const char * source_identity, const char * payload_summary, const char * correlation_id, safety_decision_t * result)
Process companion input through safety gateway.
This is the main entry point for all companion inputs. It performs:
Source identity verification against whitelist
Input classification (command vs suggestion)
Safety evaluation against all gates
Audit logging of decision and reasons
Parameters
source_identity Source identifier
payload_summary Human-readable command summary
correlation_id Optional correlation ID
result Pointer to store the gateway decision
Returns
ESP_OK if processed successfully, error code otherwise
Definition at line 196 of file audit.c.
Referenced by gcs_gateway_log_to_audit_system(), and test_audit_system_integration_with_companion().
audit_set_companion_whitelist()
esp_err_t audit_set_companion_whitelist (const char * source_identity)
Set the whitelisted companion source.
Only one companion source is allowed at a time. Setting a new source replaces the previous whitelist entry.
Parameters
source_identity Source identifier (e.g., "SYSID:123/COMPID:50")
Returns
ESP_OK on success, error code otherwise
Definition at line 167 of file audit.c.
classify_companion_input()
esp_err_t classify_companion_input (const char * payload_summary, companion_classification_t * classification) static
Definition at line 368 of file audit.c.
evaluate_safety_gates()
esp_err_t evaluate_safety_gates (const char * payload_summary, safety_evaluation_t * evaluation) static
Definition at line 390 of file audit.c.
get_timestamp_ms()
int64_t get_timestamp_ms (void) static
Definition at line 521 of file audit.c.
is_source_whitelisted()
bool is_source_whitelisted (const char * source_identity) static
Definition at line 363 of file audit.c.
log_audit_event()
esp_err_t log_audit_event (const companion_input_t * input, const safety_evaluation_t * evaluation) static
Definition at line 472 of file audit.c.
send_audit_summary()
void send_audit_summary (const companion_input_t * input) static
Definition at line 495 of file audit.c.
Variable Documentation
s_audit_buf_ptrs
void* s_audit_buf_ptrs[AUDIT_EVENT_BUFFER_SIZE] static
Definition at line 74 of file audit.c.
s_audit_data_block
uint8_t s_audit_data_block[AUDIT_EVENT_BUFFER_SIZE *sizeof(companion_input_t)] static
Definition at line 75 of file audit.c.
s_audit_initialized
bool s_audit_initialized = false static
Definition at line 63 of file audit.c.
s_audit_mutex
SemaphoreHandle_t s_audit_mutex = NULL static
Definition at line 64 of file audit.c.
s_audit_ringbuf
ringbuf_t s_audit_ringbuf static
Definition at line 71 of file audit.c.
s_ringbuf_initialized
bool s_ringbuf_initialized = false static
Definition at line 72 of file audit.c.
s_whitelist_active
bool s_whitelist_active = false static
Definition at line 68 of file audit.c.
s_whitelisted_source
char s_whitelisted_source[32] = {0} static
Definition at line 67 of file audit.c.
TAG
const char* TAG = "audit" static
Definition at line 60 of file audit.c.