ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/include/bmp388.h File Reference
bmp388.h File Reference
BMP388 barometric pressure sensor driver with drift filter and health checks.
#include "scout_types.h"
#include "esp_err.h"
#include "driver/spi_master.h"
#include <stdbool.h>
#include <stdint.h>
Classes
struct bmp388_raw_data_t
BMP388 raw sensor data structure.
struct bmp388_data_t
BMP388 scaled sensor data structure.
struct bmp388_t
BMP388 device structure.
Functions
esp_err_t bmp388_init (bmp388_t *dev)
Initialize BMP388 device.
esp_err_t bmp388_read_raw (bmp388_t *dev, bmp388_raw_data_t *raw_data)
Read raw sensor data from BMP388.
esp_err_t bmp388_read_scaled (bmp388_t *dev, bmp388_data_t *data)
Read scaled sensor data from BMP388.
sensor_health_t bmp388_get_health (bmp388_t *dev)
Get current health status of BMP388.
const char * bmp388_get_last_error (bmp388_t *dev)
Get last error message.
float bmp388_get_drift_rate_pa_per_min (void)
Get current pressure drift rate.
bmp388_t * bmp388_get_instance (void)
Get global BMP388 instance.
Detailed Description
BMP388 barometric pressure sensor driver with drift filter and health checks.
Driver for BMP388 barometric pressure sensor providing pressure, temperature, and altitude measurements with health monitoring and drift detection.
Definition in file bmp388.h.
Function Documentation
bmp388_get_drift_rate_pa_per_min()
float bmp388_get_drift_rate_pa_per_min (void)
Get current pressure drift rate.
Calculates pressure drift rate from the moving average filter. Used for health monitoring per SC-011 (≤1m drift over 10 minutes).
Returns
Pressure drift rate in Pa/minute, or 0.0 if insufficient data
Definition at line 330 of file bmp388.c.
bmp388_get_health()
sensor_health_t bmp388_get_health (bmp388_t * dev)
Get current health status of BMP388.
Parameters
dev BMP388 device structure
Returns
Current sensor health status
Definition at line 310 of file bmp388.c.
References bmp388_t::health, and bmp388_t::initialized.
bmp388_get_instance()
bmp388_t * bmp388_get_instance (void)
Get global BMP388 instance.
Returns pointer to the global BMP388 instance if initialized.
Returns
Pointer to global instance or NULL if not initialized
Definition at line 347 of file bmp388.c.
Referenced by blackbox_collect_evidence(), blackbox_log_sensor_summary(), and gcs_gateway_generate_tlm_status().
bmp388_get_last_error()
const char * bmp388_get_last_error (bmp388_t * dev)
Get last error message.
Parameters
dev BMP388 device structure
Returns
Pointer to last error message string
Definition at line 320 of file bmp388.c.
References bmp388_t::last_error.
bmp388_init()
esp_err_t bmp388_init (bmp388_t * dev)
Initialize BMP388 device.
Initializes SPI communication, configures the device for 16x pressure oversampling and 2x temperature oversampling, reads calibration coefficients, and performs self-test.
Parameters
dev BMP388 device structure to initialize
Returns
ESP_OK on success, error code otherwise
Definition at line 118 of file bmp388.c.
References bus_io_init_spi(), bus_io_init_spi_baro(), bmp388_t::health, bmp388_t::initialized, bmp388_t::last_error, and bmp388_t::spi_handle.
bmp388_read_raw()
esp_err_t bmp388_read_raw (bmp388_t * dev, bmp388_raw_data_t * raw_data)
Read raw sensor data from BMP388.
Reads pressure and temperature registers and checks for data ready status. Updates device health status periodically.
Parameters
dev BMP388 device structure
raw_data Output buffer for raw sensor data
Returns
ESP_OK on success, ESP_ERR_NOT_FINISHED if data not ready, error code otherwise
Definition at line 222 of file bmp388.c.
References bmp388_t::health, bmp388_t::initialized, bmp388_t::last_error, bmp388_raw_data_t::pressure, bmp388_raw_data_t::temperature, and bmp388_raw_data_t::timestamp.
Referenced by bmp388_read_scaled().
bmp388_read_scaled()
esp_err_t bmp388_read_scaled (bmp388_t * dev, bmp388_data_t * data)
Read scaled sensor data from BMP388.
Reads raw data and applies temperature compensation and pressure calibration. Calculates altitude using standard atmosphere model. Updates drift filter and performs spike detection.
Parameters
dev BMP388 device structure
data Output buffer for scaled sensor data
Returns
ESP_OK on success, error code otherwise
Definition at line 277 of file bmp388.c.
References bmp388_data_t::altitude, bmp388_read_raw(), bmp388_data_t::pressure, bmp388_raw_data_t::pressure, bmp388_data_t::temperature, bmp388_raw_data_t::temperature, bmp388_data_t::timestamp, and bmp388_raw_data_t::timestamp.
Referenced by blackbox_collect_evidence(), blackbox_log_sensor_summary(), and gcs_gateway_generate_tlm_status().