ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/src/sensors/bmp388.c File Reference
bmp388.c File Reference
BMP388 barometric pressure sensor driver with drift filter and health checks.
#include "bmp388.h"
#include "bus_io.h"
#include "scout_types.h"
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/spi_master.h"
#include <math.h>
#include <string.h>
Classes
struct bmp388_calib_t
Macros
#define BMP388_REG_CHIP_ID 0x00
#define BMP388_REG_ERR_REG 0x02
#define BMP388_REG_STATUS 0x03
#define BMP388_REG_DATA_0 0x04
#define BMP388_REG_PWR_CTRL 0x1B
#define BMP388_REG_OSR 0x1C
#define BMP388_REG_ODR 0x1D
#define BMP388_REG_CONFIG 0x1F
#define BMP388_REG_CMD 0x7E
#define BMP388_REG_CALIB_T1_LSB 0x31
#define BMP388_REG_CALIB_T1_MSB 0x32
#define BMP388_REG_CALIB_T2_LSB 0x33
#define BMP388_REG_CALIB_T2_MSB 0x34
#define BMP388_REG_CALIB_T3 0x35
#define BMP388_REG_CALIB_P1_LSB 0x36
#define BMP388_REG_CALIB_P1_MSB 0x37
#define BMP388_CHIP_ID 0x50
#define BMP388_PWR_CTRL_PRESS_EN 0x01
#define BMP388_PWR_CTRL_TEMP_EN 0x02
#define BMP388_PWR_CTRL_MODE_SLEEP 0x00
#define BMP388_PWR_CTRL_MODE_FORCED 0x10
#define BMP388_PWR_CTRL_MODE_NORMAL 0x30
#define BMP388_OSR_PRESS_x16 0x04
#define BMP388_OSR_TEMP_x2 0x01
#define BMP388_STATUS_CMD_RDY 0x10
#define BMP388_STATUS_PRESS_RDY 0x20
#define BMP388_STATUS_TEMP_RDY 0x40
#define BMP388_CMD_SOFT_RESET 0xB6
#define BMP388_SEA_LEVEL_PA 101325.0f
#define BMP388_DRIFT_FILTER_SIZE 10
#define BMP388_MAX_DRIFT_PA_PER_MIN 16.67f
#define BMP388_SPIKE_THRESHOLD_3SIGMA 3.0f
#define BMP388_MIN_TEMP_C -40.0f
#define BMP388_MAX_TEMP_C 85.0f
#define BMP388_HEALTH_CHECK_INTERVAL_MS 1000
Functions
static esp_err_t bmp388_write_register (uint8_t reg, uint8_t value)
static esp_err_t bmp388_read_register (uint8_t reg, uint8_t *value)
static esp_err_t bmp388_read_registers (uint8_t reg, uint8_t *data, size_t len)
static esp_err_t bmp388_read_calibration (void)
static void bmp388_update_health (bmp388_t *dev)
static esp_err_t bmp388_self_test (bmp388_t *dev)
static float bmp388_compensate_temperature (uint32_t raw_temp)
static float bmp388_compensate_pressure (uint32_t raw_press, float t_fine)
static float bmp388_calculate_altitude (float pressure)
static void bmp388_update_drift_filter (float pressure)
static bool bmp388_detect_spike (float pressure)
esp_err_t bmp388_init (bmp388_t *dev)
Initialize BMP388 device.
esp_err_t bmp388_read_raw (bmp388_t *dev, bmp388_raw_data_t *raw_data)
Read raw sensor data from BMP388.
esp_err_t bmp388_read_scaled (bmp388_t *dev, bmp388_data_t *data)
Read scaled sensor data from BMP388.
sensor_health_t bmp388_get_health (bmp388_t *dev)
Get current health status of BMP388.
const char * bmp388_get_last_error (bmp388_t *dev)
Get last error message.
float bmp388_get_drift_rate_pa_per_min (void)
Get current pressure drift rate.
bmp388_t * bmp388_get_instance (void)
Get global BMP388 instance.
Variables
static const char * TAG = "bmp388"
static bmp388_t g_bmp388 = {0}
static bool g_initialized = false
static uint32_t g_last_health_check = 0
static bmp388_calib_t g_calib = {0}
static float g_drift_filter [10] = {0}
static int g_filter_index = 0
static bool g_filter_full = false
Detailed Description
BMP388 barometric pressure sensor driver with drift filter and health checks.
Implements SPI communication with BMP388 barometric pressure sensor. Provides health monitoring, drift filtering, and altitude calculation.
Definition in file bmp388.c.
Macro Definition Documentation
BMP388_CHIP_ID
#define BMP388_CHIP_ID 0x50
Definition at line 45 of file bmp388.c.
BMP388_CMD_SOFT_RESET
#define BMP388_CMD_SOFT_RESET 0xB6
Definition at line 64 of file bmp388.c.
BMP388_DRIFT_FILTER_SIZE
#define BMP388_DRIFT_FILTER_SIZE 10
Definition at line 70 of file bmp388.c.
BMP388_HEALTH_CHECK_INTERVAL_MS
#define BMP388_HEALTH_CHECK_INTERVAL_MS 1000
Definition at line 75 of file bmp388.c.
BMP388_MAX_DRIFT_PA_PER_MIN
#define BMP388_MAX_DRIFT_PA_PER_MIN 16.67f
Definition at line 71 of file bmp388.c.
BMP388_MAX_TEMP_C
#define BMP388_MAX_TEMP_C 85.0f
Definition at line 74 of file bmp388.c.
BMP388_MIN_TEMP_C
#define BMP388_MIN_TEMP_C -40.0f
Definition at line 73 of file bmp388.c.
BMP388_OSR_PRESS_x16
#define BMP388_OSR_PRESS_x16 0x04
Definition at line 55 of file bmp388.c.
BMP388_OSR_TEMP_x2
#define BMP388_OSR_TEMP_x2 0x01
Definition at line 56 of file bmp388.c.
BMP388_PWR_CTRL_MODE_FORCED
#define BMP388_PWR_CTRL_MODE_FORCED 0x10
Definition at line 51 of file bmp388.c.
BMP388_PWR_CTRL_MODE_NORMAL
#define BMP388_PWR_CTRL_MODE_NORMAL 0x30
Definition at line 52 of file bmp388.c.
BMP388_PWR_CTRL_MODE_SLEEP
#define BMP388_PWR_CTRL_MODE_SLEEP 0x00
Definition at line 50 of file bmp388.c.
BMP388_PWR_CTRL_PRESS_EN
#define BMP388_PWR_CTRL_PRESS_EN 0x01
Definition at line 48 of file bmp388.c.
BMP388_PWR_CTRL_TEMP_EN
#define BMP388_PWR_CTRL_TEMP_EN 0x02
Definition at line 49 of file bmp388.c.
BMP388_REG_CALIB_P1_LSB
#define BMP388_REG_CALIB_P1_LSB 0x36
Definition at line 40 of file bmp388.c.
BMP388_REG_CALIB_P1_MSB
#define BMP388_REG_CALIB_P1_MSB 0x37
Definition at line 41 of file bmp388.c.
BMP388_REG_CALIB_T1_LSB
#define BMP388_REG_CALIB_T1_LSB 0x31
Definition at line 35 of file bmp388.c.
BMP388_REG_CALIB_T1_MSB
#define BMP388_REG_CALIB_T1_MSB 0x32
Definition at line 36 of file bmp388.c.
BMP388_REG_CALIB_T2_LSB
#define BMP388_REG_CALIB_T2_LSB 0x33
Definition at line 37 of file bmp388.c.
BMP388_REG_CALIB_T2_MSB
#define BMP388_REG_CALIB_T2_MSB 0x34
Definition at line 38 of file bmp388.c.
BMP388_REG_CALIB_T3
#define BMP388_REG_CALIB_T3 0x35
Definition at line 39 of file bmp388.c.
BMP388_REG_CHIP_ID
#define BMP388_REG_CHIP_ID 0x00
Definition at line 24 of file bmp388.c.
BMP388_REG_CMD
#define BMP388_REG_CMD 0x7E
Definition at line 32 of file bmp388.c.
BMP388_REG_CONFIG
#define BMP388_REG_CONFIG 0x1F
Definition at line 31 of file bmp388.c.
BMP388_REG_DATA_0
#define BMP388_REG_DATA_0 0x04
Definition at line 27 of file bmp388.c.
BMP388_REG_ERR_REG
#define BMP388_REG_ERR_REG 0x02
Definition at line 25 of file bmp388.c.
BMP388_REG_ODR
#define BMP388_REG_ODR 0x1D
Definition at line 30 of file bmp388.c.
BMP388_REG_OSR
#define BMP388_REG_OSR 0x1C
Definition at line 29 of file bmp388.c.
BMP388_REG_PWR_CTRL
#define BMP388_REG_PWR_CTRL 0x1B
Definition at line 28 of file bmp388.c.
BMP388_REG_STATUS
#define BMP388_REG_STATUS 0x03
Definition at line 26 of file bmp388.c.
BMP388_SEA_LEVEL_PA
#define BMP388_SEA_LEVEL_PA 101325.0f
Definition at line 67 of file bmp388.c.
BMP388_SPIKE_THRESHOLD_3SIGMA
#define BMP388_SPIKE_THRESHOLD_3SIGMA 3.0f
Definition at line 72 of file bmp388.c.
BMP388_STATUS_CMD_RDY
#define BMP388_STATUS_CMD_RDY 0x10
Definition at line 59 of file bmp388.c.
BMP388_STATUS_PRESS_RDY
#define BMP388_STATUS_PRESS_RDY 0x20
Definition at line 60 of file bmp388.c.
BMP388_STATUS_TEMP_RDY
#define BMP388_STATUS_TEMP_RDY 0x40
Definition at line 61 of file bmp388.c.
Function Documentation
bmp388_calculate_altitude()
float bmp388_calculate_altitude (float pressure) static
Definition at line 516 of file bmp388.c.
bmp388_compensate_pressure()
float bmp388_compensate_pressure (uint32_t raw_press, float t_fine) static
Definition at line 498 of file bmp388.c.
bmp388_compensate_temperature()
float bmp388_compensate_temperature (uint32_t raw_temp) static
Definition at line 488 of file bmp388.c.
bmp388_detect_spike()
bool bmp388_detect_spike (float pressure) static
Definition at line 533 of file bmp388.c.
bmp388_get_drift_rate_pa_per_min()
float bmp388_get_drift_rate_pa_per_min (void)
Get current pressure drift rate.
Calculates pressure drift rate from the moving average filter. Used for health monitoring per SC-011 (1m drift over 10 minutes).
Returns
Pressure drift rate in Pa/minute, or 0.0 if insufficient data
Definition at line 330 of file bmp388.c.
bmp388_get_health()
sensor_health_t bmp388_get_health (bmp388_t * dev)
Get current health status of BMP388.
Parameters
dev BMP388 device structure
Returns
Current sensor health status
Definition at line 310 of file bmp388.c.
References bmp388_t::health, and bmp388_t::initialized.
bmp388_get_instance()
bmp388_t * bmp388_get_instance (void)
Get global BMP388 instance.
Returns pointer to the global BMP388 instance if initialized.
Returns
Pointer to global instance or NULL if not initialized
Definition at line 347 of file bmp388.c.
Referenced by blackbox_collect_evidence(), blackbox_log_sensor_summary(), and gcs_gateway_generate_tlm_status().
bmp388_get_last_error()
const char * bmp388_get_last_error (bmp388_t * dev)
Get last error message.
Parameters
dev BMP388 device structure
Returns
Pointer to last error message string
Definition at line 320 of file bmp388.c.
References bmp388_t::last_error.
bmp388_init()
esp_err_t bmp388_init (bmp388_t * dev)
Initialize BMP388 device.
Initializes SPI communication, configures the device for 16x pressure oversampling and 2x temperature oversampling, reads calibration coefficients, and performs self-test.
Parameters
dev BMP388 device structure to initialize
Returns
ESP_OK on success, error code otherwise
Definition at line 118 of file bmp388.c.
References bus_io_init_spi(), bus_io_init_spi_baro(), bmp388_t::health, bmp388_t::initialized, bmp388_t::last_error, and bmp388_t::spi_handle.
bmp388_read_calibration()
esp_err_t bmp388_read_calibration (void) static
Definition at line 391 of file bmp388.c.
bmp388_read_raw()
esp_err_t bmp388_read_raw (bmp388_t * dev, bmp388_raw_data_t * raw_data)
Read raw sensor data from BMP388.
Reads pressure and temperature registers and checks for data ready status. Updates device health status periodically.
Parameters
dev BMP388 device structure
raw_data Output buffer for raw sensor data
Returns
ESP_OK on success, ESP_ERR_NOT_FINISHED if data not ready, error code otherwise
Definition at line 222 of file bmp388.c.
References bmp388_t::health, bmp388_t::initialized, bmp388_t::last_error, bmp388_raw_data_t::pressure, bmp388_raw_data_t::temperature, and bmp388_raw_data_t::timestamp.
Referenced by bmp388_read_scaled().
bmp388_read_register()
esp_err_t bmp388_read_register (uint8_t reg, uint8_t * value) static
Definition at line 369 of file bmp388.c.
bmp388_read_registers()
esp_err_t bmp388_read_registers (uint8_t reg, uint8_t * data, size_t len) static
Definition at line 380 of file bmp388.c.
bmp388_read_scaled()
esp_err_t bmp388_read_scaled (bmp388_t * dev, bmp388_data_t * data)
Read scaled sensor data from BMP388.
Reads raw data and applies temperature compensation and pressure calibration. Calculates altitude using standard atmosphere model. Updates drift filter and performs spike detection.
Parameters
dev BMP388 device structure
data Output buffer for scaled sensor data
Returns
ESP_OK on success, error code otherwise
Definition at line 277 of file bmp388.c.
References bmp388_data_t::altitude, bmp388_read_raw(), bmp388_data_t::pressure, bmp388_raw_data_t::pressure, bmp388_data_t::temperature, bmp388_raw_data_t::temperature, bmp388_data_t::timestamp, and bmp388_raw_data_t::timestamp.
Referenced by blackbox_collect_evidence(), blackbox_log_sensor_summary(), and gcs_gateway_generate_tlm_status().
bmp388_self_test()
esp_err_t bmp388_self_test (bmp388_t * dev) static
Definition at line 455 of file bmp388.c.
bmp388_update_drift_filter()
void bmp388_update_drift_filter (float pressure) static
Definition at line 522 of file bmp388.c.
bmp388_update_health()
void bmp388_update_health (bmp388_t * dev) static
Definition at line 420 of file bmp388.c.
bmp388_write_register()
esp_err_t bmp388_write_register (uint8_t reg, uint8_t value) static
Definition at line 358 of file bmp388.c.
Variable Documentation
g_bmp388
bmp388_t g_bmp388 = {0} static
Definition at line 97 of file bmp388.c.
g_calib
bmp388_calib_t g_calib = {0} static
Definition at line 100 of file bmp388.c.
g_drift_filter
float g_drift_filter[10] = {0} static
Definition at line 101 of file bmp388.c.
g_filter_full
bool g_filter_full = false static
Definition at line 103 of file bmp388.c.
g_filter_index
int g_filter_index = 0 static
Definition at line 102 of file bmp388.c.
g_initialized
bool g_initialized = false static
Definition at line 98 of file bmp388.c.
g_last_health_check
uint32_t g_last_health_check = 0 static
Definition at line 99 of file bmp388.c.
TAG
const char* TAG = "bmp388" static
Definition at line 19 of file bmp388.c.