ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/src/sensors/bus_io.c File Reference
bus_io.c File Reference
I2C/SPI bus initialization helper for sensors.
#include "bus_io.h"
#include "driver/i2c.h"
#include "driver/spi_master.h"
#include "driver/uart.h"
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
Macros
#define I2C_SCL_PIN 10
#define I2C_SDA_PIN 9
#define I2C_MASTER_NUM I2C_NUM_0
#define I2C_MASTER_FREQ 400000
#define SPI_MISO_PIN 13
#define SPI_MOSI_PIN 11
#define SPI_SCK_PIN 12
#define SPI_CS_BARO_PIN 7
#define UART_GPS_NUM UART_NUM_1
#define UART_GPS_TX_PIN 16
#define UART_GPS_RX_PIN 15
#define UART_GPS_BAUD 9600
#define UART_BUF_SIZE 1024
Functions
esp_err_t bus_io_init_i2c (void)
Initialize I2C bus for sensor communication.
esp_err_t bus_io_init_spi (void)
Initialize SPI bus for sensor communication.
esp_err_t bus_io_init_uart_gps (void)
Initialize UART for GPS communication.
esp_err_t bus_io_add_spi_device (spi_device_handle_t *handle, int cs_pin, int clock_speed_hz)
Add SPI device to the initialized bus.
esp_err_t bus_io_init_spi_baro (spi_device_handle_t *handle)
Initialize SPI device for barometer (BMP388).
esp_err_t bus_io_i2c_read_register (uint8_t device_addr, uint8_t reg_addr, uint8_t *data, size_t len)
Read register from I2C device.
esp_err_t bus_io_i2c_write_register (uint8_t device_addr, uint8_t reg_addr, uint8_t data)
Write register to I2C device.
esp_err_t bus_io_spi_read_register (spi_device_handle_t handle, uint8_t reg_addr, uint8_t *data, size_t len)
Read register from SPI device.
esp_err_t bus_io_spi_write_register (spi_device_handle_t handle, uint8_t reg_addr, uint8_t data)
Write register to SPI device.
esp_err_t bus_io_uart_gps_read (uint8_t *data, size_t max_len, size_t *bytes_read, uint32_t timeout_ms)
Read data from GPS UART.
void bus_io_deinit_all (void)
Deinitialize all buses and free resources.
bool bus_io_is_i2c_initialized (void)
Check if I2C bus is initialized.
bool bus_io_is_spi_initialized (void)
Check if SPI bus is initialized.
bool bus_io_is_uart_gps_initialized (void)
Check if UART GPS is initialized.
Variables
static const char * TAG = "bus_io"
static bool i2c_initialized = false
static bool spi_initialized = false
static bool uart_gps_initialized = false
static spi_device_handle_t spi_baro_handle = NULL
Detailed Description
I2C/SPI bus initialization helper for sensors.
Provides centralized bus initialization and management for sensor drivers. Follows ESP32-S3 freenove_esp32_s3_wroom pinout from docs/connections.md.
Definition in file bus_io.c.
Macro Definition Documentation
I2C_MASTER_FREQ
#define I2C_MASTER_FREQ 400000
Definition at line 23 of file bus_io.c.
I2C_MASTER_NUM
#define I2C_MASTER_NUM I2C_NUM_0
Definition at line 22 of file bus_io.c.
I2C_SCL_PIN
#define I2C_SCL_PIN 10
Definition at line 20 of file bus_io.c.
I2C_SDA_PIN
#define I2C_SDA_PIN 9
Definition at line 21 of file bus_io.c.
SPI_CS_BARO_PIN
#define SPI_CS_BARO_PIN 7
Definition at line 28 of file bus_io.c.
SPI_MISO_PIN
#define SPI_MISO_PIN 13
Definition at line 25 of file bus_io.c.
SPI_MOSI_PIN
#define SPI_MOSI_PIN 11
Definition at line 26 of file bus_io.c.
SPI_SCK_PIN
#define SPI_SCK_PIN 12
Definition at line 27 of file bus_io.c.
UART_BUF_SIZE
#define UART_BUF_SIZE 1024
Definition at line 34 of file bus_io.c.
UART_GPS_BAUD
#define UART_GPS_BAUD 9600
Definition at line 33 of file bus_io.c.
UART_GPS_NUM
#define UART_GPS_NUM UART_NUM_1
Definition at line 30 of file bus_io.c.
UART_GPS_RX_PIN
#define UART_GPS_RX_PIN 15
Definition at line 32 of file bus_io.c.
UART_GPS_TX_PIN
#define UART_GPS_TX_PIN 16
Definition at line 31 of file bus_io.c.
Function Documentation
bus_io_add_spi_device()
esp_err_t bus_io_add_spi_device (spi_device_handle_t * handle, int cs_pin, int clock_speed_hz)
Add SPI device to the initialized bus.
Parameters
handle Output handle for the SPI device
cs_pin Chip select pin number
clock_speed_hz SPI clock speed in Hz
Returns
ESP_OK on success, error code otherwise
Definition at line 149 of file bus_io.c.
Referenced by bus_io_init_spi_baro().
bus_io_deinit_all()
void bus_io_deinit_all (void)
Deinitialize all buses and free resources.
Definition at line 277 of file bus_io.c.
bus_io_i2c_read_register()
esp_err_t bus_io_i2c_read_register (uint8_t device_addr, uint8_t reg_addr, uint8_t * data, size_t len)
Read register from I2C device.
Parameters
device_addr 7-bit I2C device address
reg_addr Register address to read from
data Buffer to store read data
len Number of bytes to read
Returns
ESP_OK on success, error code otherwise
Definition at line 181 of file bus_io.c.
bus_io_i2c_write_register()
esp_err_t bus_io_i2c_write_register (uint8_t device_addr, uint8_t reg_addr, uint8_t data)
Write register to I2C device.
Parameters
device_addr 7-bit I2C device address
reg_addr Register address to write to
data Data byte to write
Returns
ESP_OK on success, error code otherwise
Definition at line 207 of file bus_io.c.
bus_io_init_i2c()
esp_err_t bus_io_init_i2c (void)
Initialize I2C bus for sensor communication.
Configures I2C master mode with 400kHz clock speed. Uses pins SCL=10, SDA=9 per ESP32-S3 freenove configuration.
Returns
ESP_OK on success, error code otherwise
Definition at line 42 of file bus_io.c.
Referenced by hmc5883l_init(), and mpu6050_init().
bus_io_init_spi()
esp_err_t bus_io_init_spi (void)
Initialize SPI bus for sensor communication.
Configures SPI2 bus for sensor communication. Uses pins MISO=13, MOSI=11, SCK=12 per ESP32-S3 configuration.
Returns
ESP_OK on success, error code otherwise
Definition at line 77 of file bus_io.c.
Referenced by bmp388_init().
bus_io_init_spi_baro()
esp_err_t bus_io_init_spi_baro (spi_device_handle_t * handle)
Initialize SPI device for barometer (BMP388).
Parameters
handle Output handle for the baro SPI device
Returns
ESP_OK on success, error code otherwise
Definition at line 176 of file bus_io.c.
References bus_io_add_spi_device().
Referenced by bmp388_init().
bus_io_init_uart_gps()
esp_err_t bus_io_init_uart_gps (void)
Initialize UART for GPS communication.
Configures UART1 for GPS NEO-6M communication at 9600 baud. Uses pins TX=16, RX=15 per ESP32-S3 configuration.
Returns
ESP_OK on success, error code otherwise
Definition at line 106 of file bus_io.c.
Referenced by neo6m_init().
bus_io_is_i2c_initialized()
bool bus_io_is_i2c_initialized (void)
Check if I2C bus is initialized.
Returns
true if initialized, false otherwise
Definition at line 302 of file bus_io.c.
bus_io_is_spi_initialized()
bool bus_io_is_spi_initialized (void)
Check if SPI bus is initialized.
Returns
true if initialized, false otherwise
Definition at line 307 of file bus_io.c.
bus_io_is_uart_gps_initialized()
bool bus_io_is_uart_gps_initialized (void)
Check if UART GPS is initialized.
Returns
true if initialized, false otherwise
Definition at line 312 of file bus_io.c.
bus_io_spi_read_register()
esp_err_t bus_io_spi_read_register (spi_device_handle_t handle, uint8_t reg_addr, uint8_t * data, size_t len)
Read register from SPI device.
Parameters
handle SPI device handle
reg_addr Register address to read from
data Buffer to store read data
len Number of bytes to read
Returns
ESP_OK on success, error code otherwise
Definition at line 227 of file bus_io.c.
bus_io_spi_write_register()
esp_err_t bus_io_spi_write_register (spi_device_handle_t handle, uint8_t reg_addr, uint8_t data)
Write register to SPI device.
Parameters
handle SPI device handle
reg_addr Register address to write to
data Data byte to write
Returns
ESP_OK on success, error code otherwise
Definition at line 243 of file bus_io.c.
bus_io_uart_gps_read()
esp_err_t bus_io_uart_gps_read (uint8_t * data, size_t max_len, size_t * bytes_read, uint32_t timeout_ms)
Read data from GPS UART.
Parameters
data Buffer to store read data
max_len Maximum bytes to read
bytes_read Actual bytes read (output)
timeout_ms Timeout in milliseconds
Returns
ESP_OK on success, ESP_ERR_TIMEOUT on timeout
Definition at line 260 of file bus_io.c.
Variable Documentation
i2c_initialized
bool i2c_initialized = false static
Definition at line 37 of file bus_io.c.
spi_baro_handle
spi_device_handle_t spi_baro_handle = NULL static
Definition at line 40 of file bus_io.c.
spi_initialized
bool spi_initialized = false static
Definition at line 38 of file bus_io.c.
TAG
const char* TAG = "bus_io" static
Definition at line 17 of file bus_io.c.
uart_gps_initialized
bool uart_gps_initialized = false static
Definition at line 39 of file bus_io.c.