ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/include/cmd_save.h File Reference
cmd_save.h File Reference
CLI save command header.
#include "cli_core.h"
#include "esp_err.h"
Functions
esp_err_t cmd_save_persist_config (void)
Persist current configuration to NVS storage.
esp_err_t cmd_save_handler (int argc, char **argv)
CLI save command handler.
Detailed Description
CLI save command header.
Configuration persistence with atomic NVS operations per CLI contracts. Provides reliable storage of current configuration parameters.
Definition in file cmd_save.h.
Function Documentation
cmd_save_handler()
esp_err_t cmd_save_handler (int argc, char ** argv)
CLI save command handler.
Implements the 'save' command per CLI contracts:
Input: none
Output: SAVED (on success)
Errors: 507 insufficient storage; 500 persistence error
Parameters
argc Argument count (should be 1)
argv Argument vector
Returns
ESP_OK on success, error code on failure
Definition at line 133 of file cmd_save.c.
References cmd_save_persist_config().
cmd_save_persist_config()
esp_err_t cmd_save_persist_config (void)
Persist current configuration to NVS storage.
Atomically commits all writable configuration parameters to NVS. Skips read-only parameters as they represent runtime/system state.
Returns
ESP_OK on success, error code on failure
Definition at line 30 of file cmd_save.c.
References config_get_param_value_string(), and config_get_parameter_registry().
Referenced by cmd_save_handler().