ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/include/cmd_get_set.h File Reference
cmd_get_set.h File Reference
CLI get/set commands for configuration management.
#include "cli_core.h"
#include <esp_err.h>
Classes
struct config_param_def_t
Enumerations
enum config_param_type_t { PARAM_TYPE_INT , PARAM_TYPE_FLOAT , PARAM_TYPE_BOOL , PARAM_TYPE_STRING }
Functions
esp_err_t cmd_get_set_init (void)
Initialize the configuration system.
void cli_cmd_get (int argc, char **argv)
CLI get command implementation.
void cli_cmd_set (int argc, char **argv)
CLI set command implementation.
void cli_cmd_list_params (int argc, char **argv)
CLI helper command to list all available parameters.
esp_err_t config_get_parameter_registry (const config_param_def_t **params, size_t *count)
Get access to parameter registry.
esp_err_t config_get_param_value_string (const char *name, char *value_str, size_t max_len)
Get formatted parameter value as string.
Detailed Description
CLI get/set commands for configuration management.
Provides runtime configuration parameter access with schema validation.
Definition in file cmd_get_set.h.
Enumeration Type Documentation
config_param_type_t
enum config_param_type_t
Definition at line 63 of file cmd_get_set.h.
Function Documentation
cli_cmd_get()
void cli_cmd_get (int argc, char ** argv)
CLI get command implementation.
Retrieves and displays the value of a configuration parameter. Output format: PARAM=VALUE
Parameters
argc Argument count
argv Argument vector (argv[1] = parameter name)
Definition at line 108 of file cmd_get_set.c.
cli_cmd_list_params()
void cli_cmd_list_params (int argc, char ** argv)
CLI helper command to list all available parameters.
Displays all configuration parameters with their types, read/write status, and descriptions.
Parameters
argc Argument count (unused)
argv Argument vector (unused)
Definition at line 188 of file cmd_get_set.c.
cli_cmd_set()
void cli_cmd_set (int argc, char ** argv)
CLI set command implementation.
Sets the value of a configuration parameter with validation. Validates value against parameter schema before storing.
Parameters
argc Argument count
argv Argument vector (argv[1] = param name, argv[2] = value)
Definition at line 140 of file cmd_get_set.c.
cmd_get_set_init()
esp_err_t cmd_get_set_init (void)
Initialize the configuration system.
Sets up NVS storage for configuration parameters. Must be called before using get/set commands.
Returns
ESP_OK on success, error code otherwise
Definition at line 444 of file cmd_get_set.c.
config_get_param_value_string()
esp_err_t config_get_param_value_string (const char * name, char * value_str, size_t max_len)
Get formatted parameter value as string.
Retrieves the current value of a parameter formatted as a string. Used by dump and other commands that need string representations.
Parameters
name Parameter name
value_str Buffer to receive formatted value
max_len Maximum buffer length
Returns
ESP_OK on success, error code on failure
Definition at line 473 of file cmd_get_set.c.
Referenced by cmd_save_persist_config().
config_get_parameter_registry()
esp_err_t config_get_parameter_registry (const config_param_def_t ** params, size_t * count)
Get access to parameter registry.
Provides read-only access to the configuration parameter registry for iteration and inspection by other subsystems.
Parameters
params Pointer to receive parameter array pointer
count Pointer to receive parameter count
Returns
ESP_OK on success
Definition at line 461 of file cmd_get_set.c.
Referenced by cmd_dump_generate(), and cmd_save_persist_config().