ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/src/cli/cmd_get_set.c File Reference
cmd_get_set.c File Reference
CLI get/set commands for configuration management.
#include "cmd_get_set.h"
#include "cli_transport.h"
#include "nvs_flash.h"
#include "nvs.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <esp_log.h>
Macros
#define CONFIG_NVS_NAMESPACE "scout_cfg"
#define NUM_PARAMS (sizeof(g_param_registry) / sizeof(g_param_registry[0]))
Functions
static const config_param_def_t * find_param (const char *name)
static esp_err_t get_param_value (const char *name, char *value_str, size_t max_len)
static esp_err_t set_param_value (const char *name, const char *value_str)
static esp_err_t validate_param_value (const config_param_def_t *param, const char *value_str)
void cli_cmd_get (int argc, char **argv)
CLI get command implementation.
void cli_cmd_set (int argc, char **argv)
CLI set command implementation.
void cli_cmd_list_params (int argc, char **argv)
CLI helper command to list all available parameters.
esp_err_t cmd_get_set_init (void)
Initialize the configuration system.
esp_err_t config_get_parameter_registry (const config_param_def_t **params, size_t *count)
Get access to parameter registry.
esp_err_t config_get_param_value_string (const char *name, char *value_str, size_t max_len)
Get formatted parameter value as string.
Variables
static const char * TAG = "cmd_get_set"
static const config_param_def_t g_param_registry []
Detailed Description
CLI get/set commands for configuration management.
Implements runtime configuration parameter access with schema validation per CLI contracts. Supports get/set operations with proper error handling.
Definition in file cmd_get_set.c.
Macro Definition Documentation
CONFIG_NVS_NAMESPACE
#define CONFIG_NVS_NAMESPACE "scout_cfg"
Definition at line 21 of file cmd_get_set.c.
NUM_PARAMS
#define NUM_PARAMS (sizeof(g_param_registry) / sizeof(g_param_registry[0]))
Definition at line 100 of file cmd_get_set.c.
Function Documentation
cli_cmd_get()
void cli_cmd_get (int argc, char ** argv)
CLI get command implementation.
Retrieves and displays the value of a configuration parameter. Output format: PARAM=VALUE
Parameters
argc Argument count
argv Argument vector (argv[1] = parameter name)
Definition at line 108 of file cmd_get_set.c.
cli_cmd_list_params()
void cli_cmd_list_params (int argc, char ** argv)
CLI helper command to list all available parameters.
Displays all configuration parameters with their types, read/write status, and descriptions.
Parameters
argc Argument count (unused)
argv Argument vector (unused)
Definition at line 188 of file cmd_get_set.c.
cli_cmd_set()
void cli_cmd_set (int argc, char ** argv)
CLI set command implementation.
Sets the value of a configuration parameter with validation. Validates value against parameter schema before storing.
Parameters
argc Argument count
argv Argument vector (argv[1] = param name, argv[2] = value)
Definition at line 140 of file cmd_get_set.c.
cmd_get_set_init()
esp_err_t cmd_get_set_init (void)
Initialize the configuration system.
Sets up NVS storage for configuration parameters. Must be called before using get/set commands.
Returns
ESP_OK on success, error code otherwise
Definition at line 444 of file cmd_get_set.c.
config_get_param_value_string()
esp_err_t config_get_param_value_string (const char * name, char * value_str, size_t max_len)
Get formatted parameter value as string.
Retrieves the current value of a parameter formatted as a string. Used by dump and other commands that need string representations.
Parameters
name Parameter name
value_str Buffer to receive formatted value
max_len Maximum buffer length
Returns
ESP_OK on success, error code on failure
Definition at line 473 of file cmd_get_set.c.
Referenced by cmd_save_persist_config().
config_get_parameter_registry()
esp_err_t config_get_parameter_registry (const config_param_def_t ** params, size_t * count)
Get access to parameter registry.
Provides read-only access to the configuration parameter registry for iteration and inspection by other subsystems.
Parameters
params Pointer to receive parameter array pointer
count Pointer to receive parameter count
Returns
ESP_OK on success
Definition at line 461 of file cmd_get_set.c.
Referenced by cmd_dump_generate(), and cmd_save_persist_config().
find_param()
const config_param_def_t * find_param (const char * name) static
Definition at line 224 of file cmd_get_set.c.
get_param_value()
esp_err_t get_param_value (const char * name, char * value_str, size_t max_len) static
Definition at line 236 of file cmd_get_set.c.
set_param_value()
esp_err_t set_param_value (const char * name, const char * value_str) static
Definition at line 335 of file cmd_get_set.c.
validate_param_value()
esp_err_t validate_param_value (const config_param_def_t * param, const char * value_str) static
Definition at line 389 of file cmd_get_set.c.
Variable Documentation
g_param_registry
const config_param_def_t g_param_registry[] static
Definition at line 26 of file cmd_get_set.c.
TAG
const char* TAG = "cmd_get_set" static
Definition at line 18 of file cmd_get_set.c.