ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/include/cmd_dump.h File Reference
cmd_dump.h File Reference
CLI dump command header.
#include "cli_core.h"
#include "esp_err.h"
Functions
esp_err_t cmd_dump_generate (char *output_buf, size_t buf_size, size_t *output_len)
Generate complete configuration dump.
esp_err_t cmd_dump_handler (int argc, char **argv)
CLI dump command handler.
Detailed Description
CLI dump command header.
Configuration export with stable ordering and checksums per CLI contracts. Provides complete parameter representation for round-trip compatibility.
Definition in file cmd_dump.h.
Function Documentation
cmd_dump_generate()
esp_err_t cmd_dump_generate (char * output_buf, size_t buf_size, size_t * output_len)
Generate complete configuration dump.
Creates a stable, sorted configuration export with checksum header. Format: checksum=HEX count=N followed by KEY=VALUE lines.
Parameters
output_buf Buffer to store dump output
buf_size Size of output buffer (max 8KB per contracts)
output_len Pointer to store actual output length
Returns
ESP_OK on success, error code on failure
Definition at line 59 of file cmd_dump.c.
References config_get_parameter_registry().
Referenced by cmd_dump_handler().
cmd_dump_handler()
esp_err_t cmd_dump_handler (int argc, char ** argv)
CLI dump command handler.
Implements the 'dump' command per CLI contracts:
Input: none
Output: stable sorted key=value lines with checksum header
Constraints: max 8KB, round-trip importable, complete representation
Parameters
argc Argument count (should be 1)
argv Argument vector
Returns
ESP_OK on success, error code on failure
Definition at line 160 of file cmd_dump.c.
References cmd_dump_generate().