ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/src/cli/cmd_save.c File Reference
cmd_save.c File Reference
CLI save command implementation.
#include "cmd_save.h"
#include "cmd_get_set.h"
#include "cli_transport.h"
#include "nvs_flash.h"
#include "nvs.h"
#include "esp_log.h"
#include <string.h>
#include <stdio.h>
Macros
#define CONFIG_NVS_NAMESPACE "scout_cfg"
Functions
esp_err_t cmd_save_persist_config (void)
Persist current configuration to NVS storage.
esp_err_t cmd_save_handler (int argc, char **argv)
CLI save command handler.
Variables
static const char * TAG = "cmd_save"
Detailed Description
CLI save command implementation.
Provides configuration persistence functionality using NVS storage with atomic operations and proper error handling per CLI contracts.
Features:
Atomic commit of all configuration parameters
NVS storage with checksum validation
Proper error handling for storage failures
CLI contracts compliance (SAVED output)
Definition in file cmd_save.c.
Macro Definition Documentation
CONFIG_NVS_NAMESPACE
#define CONFIG_NVS_NAMESPACE "scout_cfg"
Definition at line 27 of file cmd_save.c.
Function Documentation
cmd_save_handler()
esp_err_t cmd_save_handler (int argc, char ** argv)
CLI save command handler.
Implements the 'save' command per CLI contracts:
Input: none
Output: SAVED (on success)
Errors: 507 insufficient storage; 500 persistence error
Parameters
argc Argument count (should be 1)
argv Argument vector
Returns
ESP_OK on success, error code on failure
Definition at line 133 of file cmd_save.c.
References cmd_save_persist_config().
cmd_save_persist_config()
esp_err_t cmd_save_persist_config (void)
Persist current configuration to NVS storage.
Atomically commits all writable configuration parameters to NVS. Skips read-only parameters as they represent runtime/system state.
Returns
ESP_OK on success, error code on failure
Definition at line 30 of file cmd_save.c.
References config_get_param_value_string(), and config_get_parameter_registry().
Referenced by cmd_save_handler().
Variable Documentation
TAG
const char* TAG = "cmd_save" static
Definition at line 24 of file cmd_save.c.