ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/src/cli/cmd_scp_config.c File Reference
cmd_scp_config.c File Reference
CLI SCP configuration command implementation.
#include "cmd_scp_config.h"
#include "cli_transport.h"
#include "gcs_gateway.h"
#include "scp_session.h"
#include "scp_crypto.h"
#include "scp_framer.h"
#include "scp_nvs.h"
#include "esp_log.h"
#include "esp_timer.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
Functions
static void cmd_scp_sessions (int argc, char **argv)
Handle 'scp sessions' subcommand.
static void cmd_scp_stats (int argc, char **argv)
Handle 'scp stats' subcommand.
static void cmd_scp_security (int argc, char **argv)
Handle 'scp security' subcommand.
static void cmd_scp_transport (int argc, char **argv)
Handle 'scp transport' subcommand.
static void cmd_scp_telemetry (int argc, char **argv)
Handle 'scp telemetry' subcommand (T042).
static void cmd_scp_reset (int argc, char **argv)
Handle 'scp reset' subcommand.
static void cmd_scp_selftest (int argc, char **argv)
Handle 'scp selftest' subcommand Performs an end-to-end smoke test of SCP components:
void cli_cmd_scp_config (int argc, char **argv)
Main SCP configuration command handler.
Variables
static const char * TAG = "cmd_scp_config"
Detailed Description
CLI SCP configuration command implementation.
Provides Secure Control Protocol (SCP) configuration management through CLI. Supports session management, security configuration, transport settings, and protocol statistics per CLI contracts.
Features:
Session listing and management
Security key configuration
Transport interface settings
Protocol statistics and diagnostics
Rate limiting configuration
Author
Scout ISR Project
Version
1.1
Date
2025-10-26
Definition in file cmd_scp_config.c.
Function Documentation
cli_cmd_scp_config()
void cli_cmd_scp_config (int argc, char ** argv)
Main SCP configuration command handler.
Parameters
argc Argument count
argv Argument values
Definition at line 699 of file cmd_scp_config.c.
References cmd_scp_reset(), cmd_scp_security(), cmd_scp_selftest(), cmd_scp_sessions(), cmd_scp_stats(), cmd_scp_telemetry(), and cmd_scp_transport().
cmd_scp_reset()
void cmd_scp_reset (int argc, char ** argv) static
Handle 'scp reset' subcommand.
Parameters
argc Argument count
argv Argument values
Definition at line 525 of file cmd_scp_config.c.
References gcs_gateway_reset_stats(), scp_session_close(), scp_session_get_list(), and scp_session_reset_stats().
Referenced by cli_cmd_scp_config().
cmd_scp_security()
void cmd_scp_security (int argc, char ** argv) static
Handle 'scp security' subcommand.
Parameters
argc Argument count
argv Argument values
Definition at line 153 of file cmd_scp_config.c.
References gcs_gateway_get_stats(), scp_crypto_generate_key(), and scp_session_get_stats().
Referenced by cli_cmd_scp_config().
cmd_scp_selftest()
void cmd_scp_selftest (int argc, char ** argv) static
Handle 'scp selftest' subcommand Performs an end-to-end smoke test of SCP components:
Framer encode/decode round-trip
HMAC generate/verify
Session create + authenticate
Definition at line 562 of file cmd_scp_config.c.
References scp_crypto_generate_key(), scp_crypto_hmac_generate(), scp_crypto_hmac_verify(), scp_crypto_init(), scp_framer_decode(), scp_framer_encode(), scp_framer_init(), scp_session_authenticate(), scp_session_create(), and scp_session_init().
Referenced by cli_cmd_scp_config().
cmd_scp_sessions()
void cmd_scp_sessions (int argc, char ** argv) static
Handle 'scp sessions' subcommand.
Parameters
argc Argument count
argv Argument values
Definition at line 46 of file cmd_scp_config.c.
References scp_connection_get_name(), scp_role_get_name(), scp_session_get_list(), and scp_session_get_stats().
Referenced by cli_cmd_scp_config().
cmd_scp_stats()
void cmd_scp_stats (int argc, char ** argv) static
Handle 'scp stats' subcommand.
Parameters
argc Argument count
argv Argument values
Definition at line 99 of file cmd_scp_config.c.
References gcs_gateway_get_stats().
Referenced by cli_cmd_scp_config().
cmd_scp_telemetry()
void cmd_scp_telemetry (int argc, char ** argv) static
Handle 'scp telemetry' subcommand (T042).
Parameters
argc Argument count
argv Argument values
Definition at line 315 of file cmd_scp_config.c.
References gcs_gateway_get_priority_queue_stats(), gcs_gateway_get_session_telemetry_stats(), gcs_gateway_get_telemetry_stats(), gcs_gateway_set_session_telemetry(), gcs_gateway_set_telemetry_enabled(), gcs_gateway_set_telemetry_rate(), scp_role_get_name(), and scp_session_get_list().
Referenced by cli_cmd_scp_config().
cmd_scp_transport()
void cmd_scp_transport (int argc, char ** argv) static
Handle 'scp transport' subcommand.
Parameters
argc Argument count
argv Argument values
Definition at line 290 of file cmd_scp_config.c.
Referenced by cli_cmd_scp_config().
Variable Documentation
TAG
const char* TAG = "cmd_scp_config" static
Definition at line 35 of file cmd_scp_config.c.