ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/src/services/gcs_gateway_runtime.c File Reference
gcs_gateway_runtime.c File Reference
Minimal runtime GCS Gateway implementation aligned with current SCP protocol.
#include "gcs_gateway.h"
#include "scp_protocol.h"
#include "scp_session.h"
#include "scp_framer.h"
#include "esp_log.h"
#include "esp_timer.h"
#include <string.h>
#include <stdio.h>
Classes
struct gateway_tlm_state_t
Functions
static uint32_t gw_now_ms (void)
static void tlm_update_jitter_stats (int32_t jitter_ms)
static void tlm_populate_status (scp_tlm_status_t *st)
bool gcs_gateway_init (void)
Initialize GCS Gateway.
void gcs_gateway_get_stats (gcs_gateway_stats_t *stats_out)
Get Gateway Statistics.
void gcs_gateway_reset_stats (void)
Reset Gateway Statistics.
bool gcs_gateway_set_telemetry_rate (uint8_t rate_hz)
Set Telemetry Rate.
void gcs_gateway_set_telemetry_enabled (bool enabled)
Enable/Disable Telemetry Streaming.
void gcs_gateway_get_telemetry_stats (gcs_telemetry_stats_t *stats_out)
Get Telemetry Timing Statistics (T038).
void gcs_gateway_get_priority_queue_stats (gcs_priority_queue_stats_t *stats_out)
Get Priority Queue Statistics (T040).
bool gcs_gateway_set_session_telemetry (uint32_t session_id, bool enabled, uint8_t rate_hz)
Configure Session Telemetry (T039).
bool gcs_gateway_get_session_telemetry_stats (uint32_t session_id, gcs_session_telemetry_stats_t *stats_out)
Get Session Telemetry Statistics (T039).
static uint8_t send_status_to_session (uint32_t session_id, const scp_tlm_status_t *status)
uint8_t gcs_gateway_send_tlm_status_targeted (uint32_t target_session_id)
Send TLM_STATUS to Specific Session (T039).
uint8_t gcs_gateway_send_tlm_status (void)
Send TLM_STATUS to All Active Sessions (T036).
esp_err_t gcs_gateway_log_critical_security_event (const char *violation_type, const char *details)
Log Critical System Security Event.
bool gcs_gateway_send_audit (uint8_t event_type, uint32_t source_session, uint8_t result_code, const uint8_t *details)
Send Audit Event.
Variables
static const char * TAG = "gcs_gateway"
struct {
gcs_gateway_stats_t stats
gateway_tlm_state_t tlm
uint8_t tx_buffer [SCP_MAX_FRAME_SIZE]
} s_gateway
Detailed Description
Minimal runtime GCS Gateway implementation aligned with current SCP protocol.
Implements the subset of GCS gateway APIs used by the CLI today:
Statistics getters/reset
Telemetry rate/enable controls and stats (T038)
Per-session telemetry configuration and stats (T039)
Priority queue stats stub (T040)
TLM_STATUS generation and send-to-sessions (no transport wired yet)
Notes:
Uses current scp_protocol.h header layout and scp_framer API
Frames are encoded without auth tag (flag not set). Higher-layer HMAC integration can be added later by generating SCP_AUTH_TAG and setting SCP_FLAG_AUTH_PRESENT in header->flags.
Definition in file gcs_gateway_runtime.c.
Function Documentation
gcs_gateway_get_priority_queue_stats()
void gcs_gateway_get_priority_queue_stats (gcs_priority_queue_stats_t * stats_out)
Get Priority Queue Statistics (T040).
Retrieves statistics about the priority-based telemetry message queue including queue size, priority distribution, and performance metrics.
Parameters
stats_out Output buffer for priority queue statistics
Get Priority Queue Statistics (T040).
Retrieves statistics about the priority-based telemetry queue.
Parameters
stats_out Output buffer for queue statistics
Definition at line 195 of file gcs_gateway_runtime.c.
References gcs_gateway_get_timestamp_ms().
Referenced by cmd_scp_telemetry().
gcs_gateway_get_session_telemetry_stats()
bool gcs_gateway_get_session_telemetry_stats (uint32_t session_id, gcs_session_telemetry_stats_t * stats_out)
Get Session Telemetry Statistics (T039).
Retrieves per-session telemetry performance metrics and configuration.
Parameters
session_id Target session ID
stats_out Output buffer for session telemetry statistics
Returns
true if session found, false otherwise
Get Session Telemetry Statistics (T039).
Retrieves telemetry statistics for a specific session.
Parameters
session_id Target session ID
stats_out Output buffer for session statistics
Returns
true if session found, false otherwise
Definition at line 232 of file gcs_gateway_runtime.c.
References scp_session_get_list().
Referenced by cmd_scp_telemetry().
gcs_gateway_get_stats()
void gcs_gateway_get_stats (gcs_gateway_stats_t * stats_out)
Get Gateway Statistics.
Retrieves operational statistics for monitoring.
Parameters
stats_out Output buffer for statistics
Definition at line 146 of file gcs_gateway_runtime.c.
Referenced by cmd_scp_security(), cmd_scp_stats(), test_integration_arm_safety_rejection(), test_integration_emergency_disarm(), test_integration_mode_change_command(), test_integration_rapid_commands(), test_integration_role_based_authorization(), test_multi_session_audit_trail_generation(), test_rate_limiting_security_violation_escalation(), test_security_audit_logging_integration(), test_security_invalid_session_handling(), test_security_malformed_message_rejection(), test_security_monitoring_cli_integration(), test_security_privilege_escalation_prevention(), and test_security_violation_detection_and_reporting().
gcs_gateway_get_telemetry_stats()
void gcs_gateway_get_telemetry_stats (gcs_telemetry_stats_t * stats_out)
Get Telemetry Timing Statistics (T038).
Retrieves detailed telemetry performance metrics including timing validation, jitter analysis, and rate limiting statistics.
Parameters
stats_out Output buffer for telemetry statistics
Get Telemetry Timing Statistics (T038).
Retrieves detailed timing and performance statistics for telemetry analysis.
Parameters
stats_out Output buffer for telemetry timing statistics
Definition at line 174 of file gcs_gateway_runtime.c.
Referenced by cmd_scp_telemetry().
gcs_gateway_init()
bool gcs_gateway_init (void)
Initialize GCS Gateway.
Initializes the GCS gateway subsystem including transport interfaces, FreeRTOS tasks, and protocol state.
Returns
true if initialization successful, false on error
Definition at line 138 of file gcs_gateway_runtime.c.
References gcs_gateway_get_timestamp_ms(), gcs_gateway_task(), and scp_framer_init().
gcs_gateway_log_critical_security_event()
esp_err_t gcs_gateway_log_critical_security_event (const char * violation_type, const char * details)
Log Critical System Security Event.
Public interface for logging system-level security events to persistent FATFS storage. Used by other components to report security violations that require forensic analysis.
Parameters
violation_type Type of security violation (e.g., "CRYPTO_FAILURE", "TAMPER_DETECTED")
details Additional violation details and context
Returns
ESP_OK on success, error code on failure
Log Critical System Security Event.
Public interface for logging system-level security events from other components. Used for security violations detected outside of normal command processing.
Parameters
violation_type Type of security violation
details Additional violation details
Returns
ESP_OK on success, error code on failure
Definition at line 367 of file gcs_gateway_runtime.c.
References gcs_gateway_log_security_violation().
Referenced by test_security_violation_fatfs_persistence().
gcs_gateway_reset_stats()
void gcs_gateway_reset_stats (void)
Reset Gateway Statistics.
Resets operational statistics counters.
Definition at line 153 of file gcs_gateway_runtime.c.
Referenced by cmd_scp_reset().
gcs_gateway_send_audit()
bool gcs_gateway_send_audit (uint8_t event_type, uint32_t source_session, uint8_t result_code, const uint8_t * details)
Send Audit Event.
Sends security audit event to all authorized operators.
Parameters
event_type Audit event type (SCP_AUDIT_*)
source_session Originating session (0 if system event)
result_code Event result code
details Event-specific details (16 bytes max)
Returns
true if audit sent successfully, false on error
Definition at line 374 of file gcs_gateway_runtime.c.
References scp_framer_encode(), and scp_session_get_list().
gcs_gateway_send_tlm_status()
uint8_t gcs_gateway_send_tlm_status (void)
Send TLM_STATUS to All Active Sessions (T036).
Generates and broadcasts comprehensive system status telemetry to all authenticated GCS sessions. Integrates with existing telemetry_core and sensor systems for complete status reporting.
Returns
Number of sessions the status was sent to (0 if generation failed)
Send TLM_STATUS to All Active Sessions (T036).
Definition at line 361 of file gcs_gateway_runtime.c.
References gcs_gateway_send_tlm_status_targeted().
gcs_gateway_send_tlm_status_targeted()
uint8_t gcs_gateway_send_tlm_status_targeted (uint32_t target_session_id)
Send TLM_STATUS to Specific Session (T039).
Sends status telemetry to a specific session or all eligible sessions based on role-based filtering and per-session configuration.
Parameters
target_session_id Specific session (0 = broadcast to all eligible)
Returns
Number of sessions the status was sent to
Send TLM_STATUS to Specific Session (T039).
Generates and broadcasts current system status to authenticated GCS sessions based on operator roles and per-session telemetry configuration.
Parameters
target_session_id Specific session to target (0 = all eligible sessions)
Returns
Number of sessions the status was sent to
Definition at line 297 of file gcs_gateway_runtime.c.
References gcs_gateway_generate_tlm_status(), gcs_gateway_get_timestamp_ms(), scp_framer_encode(), scp_role_get_name(), and scp_session_get_list().
Referenced by gcs_gateway_send_tlm_status().
gcs_gateway_set_session_telemetry()
bool gcs_gateway_set_session_telemetry (uint32_t session_id, bool enabled, uint8_t rate_hz)
Configure Session Telemetry (T039).
Sets per-session telemetry configuration including enable/disable and custom rate settings for multi-operator scenarios.
Parameters
session_id Target session ID
enabled Enable/disable telemetry for this session
rate_hz Session-specific rate (0 = use global rate, max 10)
Returns
true if session found and configured, false otherwise
Configure Session Telemetry (T039).
Sets telemetry configuration for a specific operator session, enabling customized telemetry rates and filtering per operator role.
Parameters
session_id Target session ID
enabled Enable/disable telemetry for this session
rate_hz Session-specific rate (0 = use global rate)
Returns
true if session found and configured, false otherwise
Definition at line 208 of file gcs_gateway_runtime.c.
References scp_session_get_by_id(), and scp_session_get_list().
Referenced by cmd_scp_telemetry().
gcs_gateway_set_telemetry_enabled()
void gcs_gateway_set_telemetry_enabled (bool enabled)
Enable/Disable Telemetry Streaming.
Controls whether TLM_STATUS messages are periodically sent to GCS.
Parameters
enabled true to enable streaming, false to disable
Enable/Disable Telemetry Streaming.
Controls whether TLM_STATUS messages are periodically sent to GCS.
Parameters
enabled true to enable streaming, false to disable
Definition at line 168 of file gcs_gateway_runtime.c.
Referenced by cmd_scp_telemetry().
gcs_gateway_set_telemetry_rate()
bool gcs_gateway_set_telemetry_rate (uint8_t rate_hz)
Set Telemetry Rate.
Configures telemetry transmission rate for status updates.
Parameters
rate_hz Telemetry rate in Hz (1-10)
Returns
true if rate set successfully, false if invalid
Set Telemetry Rate.
Configures the rate at which TLM_STATUS messages are sent to GCS. Rate is applied globally to all active sessions.
Parameters
rate_hz Desired telemetry rate in Hz (1-10)
Returns
true if rate set successfully, false if invalid
Definition at line 158 of file gcs_gateway_runtime.c.
Referenced by cmd_scp_telemetry().
gw_now_ms()
uint32_t gw_now_ms (void) inline static
Definition at line 91 of file gcs_gateway_runtime.c.
send_status_to_session()
uint8_t send_status_to_session (uint32_t session_id, const scp_tlm_status_t * status) static
Definition at line 257 of file gcs_gateway_runtime.c.
tlm_populate_status()
void tlm_populate_status (scp_tlm_status_t * st) static
Definition at line 125 of file gcs_gateway_runtime.c.
tlm_update_jitter_stats()
void tlm_update_jitter_stats (int32_t jitter_ms) static
Definition at line 100 of file gcs_gateway_runtime.c.
Variable Documentation
[struct]
struct { ... } s_gateway
Initial value:
= {
    .stats = {0},
    .tlm = {
        .rate_hz = 2,
        .enabled = true,
        .target_interval_ms = 500,
        .last_status_send_ms = 0,
        .total_transmissions = 0,
        .on_time_transmissions = 0,
        .late_transmissions = 0,
        .rate_limit_drops = 0,
        .max_jitter_ms = 0,
        .min_jitter_ms = 0,
        .avg_jitter_ms = 0,
        .jitter_samples = {0},
        .jitter_idx = 0,
        .session = {{0}}},
    .tx_buffer = {0}}
stats
gcs_gateway_stats_t stats
Definition at line 69 of file gcs_gateway_runtime.c.
TAG
const char* TAG = "gcs_gateway" static
Definition at line 30 of file gcs_gateway_runtime.c.
tlm
gateway_tlm_state_t tlm
Definition at line 70 of file gcs_gateway_runtime.c.
tx_buffer
uint8_t tx_buffer[SCP_MAX_FRAME_SIZE]
Definition at line 71 of file gcs_gateway_runtime.c.