ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/include/gcs_gateway.h File Reference
gcs_gateway.h File Reference
GCS Gateway Interface for Secure Control Protocol (SCP) v1.1.
#include <stdint.h>
#include <stdbool.h>
#include "esp_err.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include "freertos/semphr.h"
#include "scp_protocol.h"
#include "scp_session.h"
Classes
struct gcs_transport_interface
Transport Interface Function Pointers.
struct gcs_incoming_message_t
Incoming Message Context.
struct gcs_outgoing_message_t
Outgoing Message Context.
struct gcs_telemetry_stats_t
Telemetry Timing Statistics.
struct gcs_session_telemetry_stats_t
Session Telemetry Statistics (T039).
struct gcs_priority_queue_stats_t
Priority Queue Statistics (T040).
struct gcs_gateway_stats_t
Gateway Statistics.
struct gcs_gateway_state_t
Gateway State.
Macros
#define GCS_GATEWAY_TASK_STACK_SIZE 4096
#define GCS_GATEWAY_TASK_PRIORITY 5
#define GCS_GATEWAY_QUEUE_SIZE 16
#define GCS_GATEWAY_BUFFER_SIZE 512
#define GCS_MAX_TRANSPORTS 3
#define GCS_UART_BUFFER_SIZE 1024
#define GCS_SPI_BUFFER_SIZE 512
#define GCS_USB_BUFFER_SIZE 1024
#define GCS_ACK_TIMEOUT_MS 100
#define GCS_HEARTBEAT_INTERVAL_MS 1000
#define GCS_SESSION_CHECK_INTERVAL_MS 5000
#define GCS_TELEMETRY_MAX_RATE_HZ 10
Typedefs
typedef struct gcs_transport_interface gcs_transport_interface_t
Transport Interface Function Pointers.
Enumerations
enum gcs_transport_type_t { GCS_TRANSPORT_UART = 0 , GCS_TRANSPORT_USB = 1 , GCS_TRANSPORT_SPI = 2 , GCS_TRANSPORT_COUNT = 3 }
Transport Interface Types.
Functions
bool gcs_gateway_init (void)
Initialize GCS Gateway.
bool gcs_gateway_start (void)
Start Gateway Operation.
bool gcs_gateway_stop (void)
Stop Gateway Operation.
void gcs_gateway_deinit (void)
Deinitialize GCS Gateway.
bool gcs_gateway_process_message (const gcs_incoming_message_t *message)
Process Incoming Message.
bool gcs_gateway_send_telemetry (uint8_t msg_type, const void *payload, uint16_t payload_len, uint32_t target_session)
Send Telemetry Message.
bool gcs_gateway_send_response (uint32_t session_id, uint8_t seq_num, uint8_t result_code, uint16_t execution_time_ms)
Send Command Response.
bool gcs_gateway_send_audit (uint8_t event_type, uint32_t source_session, uint8_t result_code, const uint8_t *details)
Send Audit Event.
bool gcs_gateway_register_transport (const gcs_transport_interface_t *transport)
Register Transport Interface.
bool gcs_gateway_enable_transport (gcs_transport_type_t transport_type)
Enable Transport.
bool gcs_gateway_disable_transport (gcs_transport_type_t transport_type)
Disable Transport.
bool gcs_gateway_get_status (gcs_gateway_state_t *state_out)
Get Gateway Status.
void gcs_gateway_get_stats (gcs_gateway_stats_t *stats_out)
Get Gateway Statistics.
void gcs_gateway_reset_stats (void)
Reset Gateway Statistics.
void gcs_gateway_update_time (uint32_t uptime_ms)
Update System Time.
uint8_t gcs_gateway_execute_arm (uint32_t session_id, const scp_cmd_control_t *command)
Execute ARM Command.
uint8_t gcs_gateway_execute_disarm (uint32_t session_id, const scp_cmd_control_t *command)
Execute DISARM Command.
uint8_t gcs_gateway_execute_mode_change (uint32_t session_id, const scp_cmd_control_t *command)
Execute Mode Change Command.
bool gcs_gateway_get_current_status (scp_tlm_status_t *status_out)
Get Current Status Telemetry.
uint8_t gcs_gateway_send_tlm_status (void)
Send TLM_STATUS to All Active Sessions (T036).
bool gcs_gateway_set_telemetry_rate (uint8_t rate_hz)
Set Telemetry Rate.
void gcs_gateway_set_telemetry_enabled (bool enabled)
Enable/Disable Telemetry Streaming.
void gcs_gateway_get_telemetry_stats (gcs_telemetry_stats_t *stats_out)
Get Telemetry Timing Statistics (T038).
uint8_t gcs_gateway_send_tlm_status_targeted (uint32_t target_session_id)
Send TLM_STATUS to Specific Session (T039).
bool gcs_gateway_set_session_telemetry (uint32_t session_id, bool enabled, uint8_t rate_hz)
Configure Session Telemetry (T039).
bool gcs_gateway_get_session_telemetry_stats (uint32_t session_id, gcs_session_telemetry_stats_t *stats_out)
Get Session Telemetry Statistics (T039).
void gcs_gateway_get_priority_queue_stats (gcs_priority_queue_stats_t *stats_out)
Get Priority Queue Statistics (T040).
void gcs_gateway_set_debug_logging (bool enable)
Enable Debug Logging.
const char * gcs_gateway_get_version (void)
Get Version Information.
esp_err_t gcs_gateway_log_critical_security_event (const char *violation_type, const char *details)
Log Critical System Security Event.
Detailed Description
GCS Gateway Interface for Secure Control Protocol (SCP) v1.1.
Main interface for Ground Control Station communication using the SCP protocol. Manages message routing, session handling, and integration with existing Scout drone subsystems.
Author
Scout ISR Project
Version
1.1
Date
2025-10-26
Definition in file gcs_gateway.h.
Macro Definition Documentation
GCS_ACK_TIMEOUT_MS
#define GCS_ACK_TIMEOUT_MS 100
Definition at line 48 of file gcs_gateway.h.
GCS_GATEWAY_BUFFER_SIZE
#define GCS_GATEWAY_BUFFER_SIZE 512
Definition at line 39 of file gcs_gateway.h.
GCS_GATEWAY_QUEUE_SIZE
#define GCS_GATEWAY_QUEUE_SIZE 16
Definition at line 38 of file gcs_gateway.h.
GCS_GATEWAY_TASK_PRIORITY
#define GCS_GATEWAY_TASK_PRIORITY 5
Definition at line 37 of file gcs_gateway.h.
GCS_GATEWAY_TASK_STACK_SIZE
#define GCS_GATEWAY_TASK_STACK_SIZE 4096
Definition at line 36 of file gcs_gateway.h.
GCS_HEARTBEAT_INTERVAL_MS
#define GCS_HEARTBEAT_INTERVAL_MS 1000
Definition at line 49 of file gcs_gateway.h.
GCS_MAX_TRANSPORTS
#define GCS_MAX_TRANSPORTS 3
Definition at line 42 of file gcs_gateway.h.
GCS_SESSION_CHECK_INTERVAL_MS
#define GCS_SESSION_CHECK_INTERVAL_MS 5000
Definition at line 50 of file gcs_gateway.h.
GCS_SPI_BUFFER_SIZE
#define GCS_SPI_BUFFER_SIZE 512
Definition at line 44 of file gcs_gateway.h.
GCS_TELEMETRY_MAX_RATE_HZ
#define GCS_TELEMETRY_MAX_RATE_HZ 10
Definition at line 51 of file gcs_gateway.h.
GCS_UART_BUFFER_SIZE
#define GCS_UART_BUFFER_SIZE 1024
Definition at line 43 of file gcs_gateway.h.
GCS_USB_BUFFER_SIZE
#define GCS_USB_BUFFER_SIZE 1024
Definition at line 45 of file gcs_gateway.h.
Typedef Documentation
gcs_transport_interface_t
typedef struct gcs_transport_interface gcs_transport_interface_t
Transport Interface Function Pointers.
Function pointers for transport-specific operations (UART/USB/SPI).
Enumeration Type Documentation
gcs_transport_type_t
enum gcs_transport_type_t
Transport Interface Types.
Definition at line 60 of file gcs_gateway.h.
Function Documentation
gcs_gateway_deinit()
void gcs_gateway_deinit (void)
Deinitialize GCS Gateway.
Cleans up all gateway resources and FreeRTOS objects.
gcs_gateway_disable_transport()
bool gcs_gateway_disable_transport (gcs_transport_type_t transport_type)
Disable Transport.
Disables specific transport interface.
Parameters
transport_type Transport type to disable
Returns
true if disabled successfully, false on error
gcs_gateway_enable_transport()
bool gcs_gateway_enable_transport (gcs_transport_type_t transport_type)
Enable Transport.
Enables specific transport interface for communication.
Parameters
transport_type Transport type to enable
Returns
true if enabled successfully, false on error
gcs_gateway_execute_arm()
uint8_t gcs_gateway_execute_arm (uint32_t session_id, const scp_cmd_control_t * command)
Execute ARM Command.
Integrates with existing safety_manager to execute ARM command.
Parameters
session_id Originating session
command ARM command data
Returns
SCP_RESULT_* code for response
gcs_gateway_execute_disarm()
uint8_t gcs_gateway_execute_disarm (uint32_t session_id, const scp_cmd_control_t * command)
Execute DISARM Command.
Integrates with existing safety_manager to execute DISARM command.
Parameters
session_id Originating session
command DISARM command data
Returns
SCP_RESULT_* code for response
gcs_gateway_execute_mode_change()
uint8_t gcs_gateway_execute_mode_change (uint32_t session_id, const scp_cmd_control_t * command)
Execute Mode Change Command.
Integrates with existing mode_manager to execute flight mode change.
Parameters
session_id Originating session
command Mode change command data
Returns
SCP_RESULT_* code for response
gcs_gateway_get_current_status()
bool gcs_gateway_get_current_status (scp_tlm_status_t * status_out)
Get Current Status Telemetry.
Retrieves current drone status for telemetry transmission.
Parameters
status_out Output buffer for status telemetry
Returns
true if status retrieved successfully
gcs_gateway_get_priority_queue_stats()
void gcs_gateway_get_priority_queue_stats (gcs_priority_queue_stats_t * stats_out)
Get Priority Queue Statistics (T040).
Retrieves statistics about the priority-based telemetry message queue including queue size, priority distribution, and performance metrics.
Parameters
stats_out Output buffer for priority queue statistics
Get Priority Queue Statistics (T040).
Retrieves statistics about the priority-based telemetry queue.
Parameters
stats_out Output buffer for queue statistics
Definition at line 2050 of file gcs_gateway.c.
References gcs_gateway_get_timestamp_ms().
Referenced by cmd_scp_telemetry().
gcs_gateway_get_session_telemetry_stats()
bool gcs_gateway_get_session_telemetry_stats (uint32_t session_id, gcs_session_telemetry_stats_t * stats_out)
Get Session Telemetry Statistics (T039).
Retrieves per-session telemetry performance metrics and configuration.
Parameters
session_id Target session ID
stats_out Output buffer for session telemetry statistics
Returns
true if session found, false otherwise
Get Session Telemetry Statistics (T039).
Retrieves telemetry statistics for a specific session.
Parameters
session_id Target session ID
stats_out Output buffer for session statistics
Returns
true if session found, false otherwise
Definition at line 1880 of file gcs_gateway.c.
References scp_session_get_list().
Referenced by cmd_scp_telemetry().
gcs_gateway_get_stats()
void gcs_gateway_get_stats (gcs_gateway_stats_t * stats_out)
Get Gateway Statistics.
Retrieves operational statistics for monitoring.
Parameters
stats_out Output buffer for statistics
Definition at line 1192 of file gcs_gateway.c.
Referenced by cmd_scp_security(), cmd_scp_stats(), gcs_gateway_log_security_violation(), test_integration_arm_safety_rejection(), test_integration_emergency_disarm(), test_integration_mode_change_command(), test_integration_rapid_commands(), test_integration_role_based_authorization(), test_multi_session_audit_trail_generation(), test_rate_limiting_security_violation_escalation(), test_security_audit_logging_integration(), test_security_invalid_session_handling(), test_security_malformed_message_rejection(), test_security_monitoring_cli_integration(), test_security_privilege_escalation_prevention(), and test_security_violation_detection_and_reporting().
gcs_gateway_get_status()
bool gcs_gateway_get_status (gcs_gateway_state_t * state_out)
Get Gateway Status.
Retrieves current gateway operational status.
Parameters
state_out Output buffer for gateway state
Returns
true if status retrieved successfully
gcs_gateway_get_telemetry_stats()
void gcs_gateway_get_telemetry_stats (gcs_telemetry_stats_t * stats_out)
Get Telemetry Timing Statistics (T038).
Retrieves detailed telemetry performance metrics including timing validation, jitter analysis, and rate limiting statistics.
Parameters
stats_out Output buffer for telemetry statistics
Get Telemetry Timing Statistics (T038).
Retrieves detailed timing and performance statistics for telemetry analysis.
Parameters
stats_out Output buffer for telemetry timing statistics
Definition at line 1788 of file gcs_gateway.c.
Referenced by cmd_scp_telemetry().
gcs_gateway_get_version()
const char * gcs_gateway_get_version (void)
Get Version Information.
Returns gateway and protocol version information.
Returns
Version string for display/logging
gcs_gateway_init()
bool gcs_gateway_init (void)
Initialize GCS Gateway.
Initializes the GCS gateway subsystem including transport interfaces, FreeRTOS tasks, and protocol state.
Returns
true if initialization successful, false on error
Definition at line 1069 of file gcs_gateway.c.
References gcs_gateway_get_timestamp_ms(), gcs_gateway_task(), and scp_framer_init().
gcs_gateway_log_critical_security_event()
esp_err_t gcs_gateway_log_critical_security_event (const char * violation_type, const char * details)
Log Critical System Security Event.
Public interface for logging system-level security events to persistent FATFS storage. Used by other components to report security violations that require forensic analysis.
Parameters
violation_type Type of security violation (e.g., "CRYPTO_FAILURE", "TAMPER_DETECTED")
details Additional violation details and context
Returns
ESP_OK on success, error code on failure
Log Critical System Security Event.
Public interface for logging system-level security events from other components. Used for security violations detected outside of normal command processing.
Parameters
violation_type Type of security violation
details Additional violation details
Returns
ESP_OK on success, error code on failure
Definition at line 2038 of file gcs_gateway.c.
References gcs_gateway_log_security_violation().
Referenced by test_security_violation_fatfs_persistence().
gcs_gateway_process_message()
bool gcs_gateway_process_message (const gcs_incoming_message_t * message)
Process Incoming Message.
Processes incoming message from GCS including authentication, authorization, and routing to appropriate handlers.
Parameters
message Incoming message context
Returns
true if message processed successfully, false on error
gcs_gateway_register_transport()
bool gcs_gateway_register_transport (const gcs_transport_interface_t * transport)
Register Transport Interface.
Registers a transport interface (UART/USB/SPI) for GCS communication.
Parameters
transport Transport interface structure
Returns
true if registered successfully, false if no slots available
gcs_gateway_reset_stats()
void gcs_gateway_reset_stats (void)
Reset Gateway Statistics.
Resets operational statistics counters.
Definition at line 1206 of file gcs_gateway.c.
Referenced by cmd_scp_reset().
gcs_gateway_send_audit()
bool gcs_gateway_send_audit (uint8_t event_type, uint32_t source_session, uint8_t result_code, const uint8_t * details)
Send Audit Event.
Sends security audit event to all authorized operators.
Parameters
event_type Audit event type (SCP_AUDIT_*)
source_session Originating session (0 if system event)
result_code Event result code
details Event-specific details (16 bytes max)
Returns
true if audit sent successfully, false on error
Definition at line 374 of file gcs_gateway_runtime.c.
References scp_framer_encode(), and scp_session_get_list().
gcs_gateway_send_response()
bool gcs_gateway_send_response (uint32_t session_id, uint8_t seq_num, uint8_t result_code, uint16_t execution_time_ms)
Send Command Response.
Sends acknowledgment or error response to command originator.
Parameters
session_id Originating session ID
seq_num Command sequence number being acknowledged
result_code Result code (SCP_RESULT_* or SCP_ERR_*)
execution_time_ms Command processing time
Returns
true if response sent successfully, false on error
gcs_gateway_send_telemetry()
bool gcs_gateway_send_telemetry (uint8_t msg_type, const void * payload, uint16_t payload_len, uint32_t target_session)
Send Telemetry Message.
Sends telemetry message to one or more GCS operators based on session roles.
Parameters
msg_type Telemetry message type (SCP_TLM_*)
payload Telemetry payload data
payload_len Payload length
target_session Target session (0 for broadcast to all)
Returns
true if message queued successfully, false on error
gcs_gateway_send_tlm_status()
uint8_t gcs_gateway_send_tlm_status (void)
Send TLM_STATUS to All Active Sessions (T036).
Generates and broadcasts comprehensive system status telemetry to all authenticated GCS sessions. Integrates with existing telemetry_core and sensor systems for complete status reporting.
Returns
Number of sessions the status was sent to (0 if generation failed)
Send TLM_STATUS to All Active Sessions (T036).
Definition at line 1737 of file gcs_gateway.c.
References gcs_gateway_send_tlm_status_targeted().
Referenced by gcs_gateway_update_telemetry().
gcs_gateway_send_tlm_status_targeted()
uint8_t gcs_gateway_send_tlm_status_targeted (uint32_t target_session_id)
Send TLM_STATUS to Specific Session (T039).
Sends status telemetry to a specific session or all eligible sessions based on role-based filtering and per-session configuration.
Parameters
target_session_id Specific session (0 = broadcast to all eligible)
Returns
Number of sessions the status was sent to
Send TLM_STATUS to Specific Session (T039).
Generates and broadcasts current system status to authenticated GCS sessions based on operator roles and per-session telemetry configuration.
Parameters
target_session_id Specific session to target (0 = all eligible sessions)
Returns
Number of sessions the status was sent to
Definition at line 1619 of file gcs_gateway.c.
References gcs_gateway_generate_tlm_status(), gcs_gateway_get_timestamp_ms(), scp_framer_encode(), scp_role_get_name(), and scp_session_get_list().
Referenced by gcs_gateway_process_priority_queue(), and gcs_gateway_send_tlm_status().
gcs_gateway_set_debug_logging()
void gcs_gateway_set_debug_logging (bool enable)
Enable Debug Logging.
Enables detailed debug logging for protocol analysis.
Parameters
enable true to enable debug logging, false to disable
gcs_gateway_set_session_telemetry()
bool gcs_gateway_set_session_telemetry (uint32_t session_id, bool enabled, uint8_t rate_hz)
Configure Session Telemetry (T039).
Sets per-session telemetry configuration including enable/disable and custom rate settings for multi-operator scenarios.
Parameters
session_id Target session ID
enabled Enable/disable telemetry for this session
rate_hz Session-specific rate (0 = use global rate, max 10)
Returns
true if session found and configured, false otherwise
Configure Session Telemetry (T039).
Sets telemetry configuration for a specific operator session, enabling customized telemetry rates and filtering per operator role.
Parameters
session_id Target session ID
enabled Enable/disable telemetry for this session
rate_hz Session-specific rate (0 = use global rate)
Returns
true if session found and configured, false otherwise
Definition at line 1833 of file gcs_gateway.c.
References scp_session_get_by_id(), and scp_session_get_list().
Referenced by cmd_scp_telemetry().
gcs_gateway_set_telemetry_enabled()
void gcs_gateway_set_telemetry_enabled (bool enabled)
Enable/Disable Telemetry Streaming.
Controls whether TLM_STATUS messages are periodically sent to GCS.
Parameters
enabled true to enable streaming, false to disable
Enable/Disable Telemetry Streaming.
Controls whether TLM_STATUS messages are periodically sent to GCS.
Parameters
enabled true to enable streaming, false to disable
Definition at line 1775 of file gcs_gateway.c.
Referenced by cmd_scp_telemetry().
gcs_gateway_set_telemetry_rate()
bool gcs_gateway_set_telemetry_rate (uint8_t rate_hz)
Set Telemetry Rate.
Configures telemetry transmission rate for status updates.
Parameters
rate_hz Telemetry rate in Hz (1-10)
Returns
true if rate set successfully, false if invalid
Set Telemetry Rate.
Configures the rate at which TLM_STATUS messages are sent to GCS. Rate is applied globally to all active sessions.
Parameters
rate_hz Desired telemetry rate in Hz (1-10)
Returns
true if rate set successfully, false if invalid
Definition at line 1751 of file gcs_gateway.c.
Referenced by cmd_scp_telemetry().
gcs_gateway_start()
bool gcs_gateway_start (void)
Start Gateway Operation.
Starts the main gateway task and begins message processing.
Returns
true if started successfully, false on error
gcs_gateway_stop()
bool gcs_gateway_stop (void)
Stop Gateway Operation.
Stops the gateway task and closes all transport interfaces.
Returns
true if stopped successfully, false on error
gcs_gateway_update_time()
void gcs_gateway_update_time (uint32_t uptime_ms)
Update System Time.
Updates gateway system time reference for timestamps. Should be called periodically from main system time source.
Parameters
uptime_ms Current system uptime in milliseconds