ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/src/services/gcs_gateway.c File Reference
gcs_gateway.c File Reference
GCS Gateway Service Implementation.
#include "gcs_gateway.h"
#include "scp_protocol.h"
#include "scp_session.h"
#include "scp_framer.h"
#include "scp_crypto.h"
#include "safety_manager.h"
#include "mode_manager.h"
#include "telemetry_core.h"
#include "audit.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include "freertos/semphr.h"
#include "esp_log.h"
#include "esp_timer.h"
#include "blackbox.h"
#include "mpu6050.h"
#include "hmc5883l.h"
#include "bmp388.h"
#include "neo6m.h"
#include "health_aggregate.h"
#include <string.h>
#include <math.h>
Classes
struct gcs_gateway_state_t
Gateway State.
struct gateway_message_t
Enumerations
enum gcs_command_result_t {
GCS_CMD_OK = 0 , GCS_CMD_ERR_UNAUTHORIZED = 1 , GCS_CMD_ERR_SAFETY_BLOCK = 2 , GCS_CMD_ERR_MODE_UNAVAILABLE = 3 ,
GCS_CMD_ERR_SENSORS = 4 , GCS_CMD_ERR_SYSTEM = 5 , GCS_CMD_ERR_INVALID_PARAM = 6 , GCS_CMD_ERR_INVALID_SESSION = 7 ,
GCS_CMD_ERR_RATE_LIMITED = 8 , GCS_CMD_ERR_TIMEOUT = 9 , GCS_CMD_ERR_HARDWARE = 10 , GCS_CMD_ERR_MAX = 11
}
GCS Command Result Codes.
Functions
static uint32_t gcs_gateway_get_timestamp_ms (void)
Get current timestamp in milliseconds.
static bool gcs_gateway_send_response (uint32_t session_id, uint8_t sequence_num, scp_message_type_t message_type, const void *payload, size_t payload_size)
Send response message to GCS.
static bool gcs_gateway_send_audit_event (uint8_t event_type, uint32_t source_session, uint8_t operator_role, uint8_t result_code, const uint8_t *details)
Generate and send TLM_AUDIT message for security/operational events.
static void gcs_gateway_audit_command_attempt (uint32_t session_id, scp_message_type_t command_type, gcs_command_result_t result_code, uint32_t processing_time_ms)
Log command attempt audit event.
static void gcs_gateway_audit_auth_failure (uint32_t session_id, uint8_t auth_failure_type, uint8_t sequence_num)
Log authentication failure audit event.
static void gcs_gateway_audit_session_event (uint32_t session_id, uint8_t event_subtype, uint8_t operator_role)
Log session lifecycle audit event.
static void gcs_gateway_audit_security_violation (uint32_t session_id, uint8_t violation_type, uint8_t severity)
Log security violation audit event.
bool gcs_gateway_validate_sequence (uint32_t session_id, uint8_t sequence_num)
Enhanced replay attack detection (T029 - User Story 4).
bool gcs_gateway_check_enhanced_rate_limit (uint32_t session_id)
Rate limiting enhancement (T030 - User Story 4).
static void gcs_gateway_log_to_audit_system (uint32_t session_id, scp_message_type_t command_type, gcs_command_result_t result_code, const char *command_summary)
Integration with existing audit system (T027 - User Story 4).
static esp_err_t gcs_gateway_log_security_violation (const char *violation_type, uint32_t session_id, const char *details, const char *severity)
Log security violation to persistent FATFS storage (T032).
static gcs_command_result_t gcs_gateway_process_arm_command (scp_session_t *session, const scp_cmd_control_t *cmd_control, uint8_t sequence_num)
Process ARM command.
static gcs_command_result_t gcs_gateway_process_disarm_command (scp_session_t *session, const scp_cmd_control_t *cmd_control, uint8_t sequence_num)
Process DISARM command.
static gcs_command_result_t gcs_gateway_process_mode_change (scp_session_t *session, const scp_cmd_control_t *cmd_control, uint8_t sequence_num)
Process mode change command.
static gcs_command_result_t gcs_gateway_process_cmd_control (uint32_t session_id, uint8_t sequence_num, const uint8_t *payload, size_t payload_size)
Process CMD_CONTROL message.
static void gcs_gateway_process_message (const gateway_message_t *message)
Process received message and generate appropriate response.
static void gcs_gateway_task (void *param)
Main gateway processing task.
bool gcs_gateway_init (void)
Initialize GCS Gateway.
bool gcs_gateway_receive_message (uint32_t session_id, uint8_t sequence_num, scp_message_type_t message_type, const uint8_t *payload, size_t payload_size)
void gcs_gateway_get_stats (gcs_gateway_stats_t *stats)
Get Gateway Statistics.
void gcs_gateway_reset_stats (void)
Reset Gateway Statistics.
static esp_err_t gcs_gateway_generate_tlm_status (scp_tlm_status_t *status)
Generate TLM_STATUS message with current system state.
static uint8_t gcs_gateway_get_telemetry_priority (const scp_tlm_status_t *status)
Determine telemetry priority based on system state (T040).
static bool gcs_gateway_queue_telemetry (const scp_tlm_status_t *status, uint32_t session_id, uint8_t priority)
Add telemetry message to priority queue (T040).
static uint8_t gcs_gateway_process_priority_queue (void)
Process priority telemetry queue (T040).
uint8_t gcs_gateway_send_tlm_status_targeted (uint32_t target_session_id)
Send TLM_STATUS message to sessions with role-based filtering.
uint8_t gcs_gateway_send_tlm_status (void)
Send TLM_STATUS to all eligible sessions (backward compatibility).
bool gcs_gateway_set_telemetry_rate (uint8_t rate_hz)
Set telemetry rate (T038 - Rate Control).
void gcs_gateway_set_telemetry_enabled (bool enabled)
Enable/disable telemetry streaming.
void gcs_gateway_get_telemetry_stats (gcs_telemetry_stats_t *stats_out)
Get telemetry timing statistics (T038).
bool gcs_gateway_set_session_telemetry (uint32_t session_id, bool enabled, uint8_t rate_hz)
Configure per-session telemetry (T039).
bool gcs_gateway_get_session_telemetry_stats (uint32_t session_id, gcs_session_telemetry_stats_t *stats_out)
Get session telemetry statistics (T039).
static void gcs_gateway_update_telemetry (void)
Update telemetry system (T037/T038 - Integration with Timing Validation).
esp_err_t gcs_gateway_log_critical_security_event (const char *violation_type, const char *details)
Log critical system security event (T032 - Enhanced).
void gcs_gateway_get_priority_queue_stats (gcs_priority_queue_stats_t *stats_out)
Get priority queue statistics (T040).
Variables
static const char * TAG = "gcs_gateway"
static gcs_gateway_state_t gateway_state = {0}
struct {
uint8_t rate_hz
uint32_t last_status_send_ms
bool enabled
uint32_t target_interval_ms
uint32_t total_transmissions
uint32_t on_time_transmissions
uint32_t late_transmissions
int32_t max_jitter_ms
int32_t min_jitter_ms
int32_t avg_jitter_ms
uint32_t jitter_samples [16]
uint8_t jitter_sample_idx
uint32_t rate_limit_drops
uint32_t last_drop_timestamp_ms
struct {
bool enabled
uint8_t rate_hz
uint32_t last_send_ms
uint32_t messages_sent
} session_config [SCP_MAX_SESSIONS]
struct {
scp_tlm_status_t message
uint32_t session_id
uint8_t priority
uint32_t timestamp_ms
uint8_t retry_count
} priority_queue [16]
uint8_t queue_size
uint8_t queue_high_priority_count
uint32_t priority_drops
} telemetry_state
Detailed Description
GCS Gateway Service Implementation.
Implements the GCS gateway service for Secure Control Protocol (SCP) v1.1, providing message routing, command processing, and response handling between ground control systems and the Scout flight controller.
Features:
CMD_CONTROL message processing (ARM/DISARM, mode changes)
ACK_RESPONSE and ERR_RESPONSE generation
Integration with safety_manager for command validation
Role-based authorization enforcement
Real-time command processing (<100ms target)
Comprehensive audit logging
Author
Scout ISR Project
Version
1.1
Date
2025-10-26
Definition in file gcs_gateway.c.
Enumeration Type Documentation
gcs_command_result_t
enum gcs_command_result_t
GCS Command Result Codes.
Result codes returned by GCS command processing functions. Used for generating appropriate ACK/ERR responses.
Definition at line 62 of file gcs_gateway.c.
Function Documentation
gcs_gateway_audit_auth_failure()
void gcs_gateway_audit_auth_failure (uint32_t session_id, uint8_t auth_failure_type, uint8_t sequence_num) static
Log authentication failure audit event.
Parameters
session_id Session that failed authentication (0 if unknown)
auth_failure_type Type of authentication failure
sequence_num Sequence number that failed
Definition at line 314 of file gcs_gateway.c.
References gcs_gateway_send_audit_event(), and scp_session_get_by_id().
Referenced by gcs_gateway_process_cmd_control(), and gcs_gateway_validate_sequence().
gcs_gateway_audit_command_attempt()
void gcs_gateway_audit_command_attempt (uint32_t session_id, scp_message_type_t command_type, gcs_command_result_t result_code, uint32_t processing_time_ms) static
Log command attempt audit event.
Parameters
session_id Session that sent the command
command_type Type of command attempted
result_code Command processing result
processing_time_ms Time taken to process command
Definition at line 280 of file gcs_gateway.c.
References gcs_gateway_send_audit_event(), and scp_session_get_by_id().
Referenced by gcs_gateway_process_message().
gcs_gateway_audit_security_violation()
void gcs_gateway_audit_security_violation (uint32_t session_id, uint8_t violation_type, uint8_t severity) static
Log security violation audit event.
Parameters
session_id Session that triggered violation (0 if unknown)
violation_type Type of security violation
severity Severity level of violation
Definition at line 369 of file gcs_gateway.c.
References gcs_gateway_send_audit_event(), and scp_session_get_by_id().
Referenced by gcs_gateway_check_enhanced_rate_limit(), gcs_gateway_process_cmd_control(), and gcs_gateway_validate_sequence().
gcs_gateway_audit_session_event()
void gcs_gateway_audit_session_event (uint32_t session_id, uint8_t event_subtype, uint8_t operator_role) static
Log session lifecycle audit event.
Parameters
session_id Session ID
event_subtype Session event type (create, close, timeout)
operator_role Role of operator
Definition at line 346 of file gcs_gateway.c.
References gcs_gateway_send_audit_event().
gcs_gateway_check_enhanced_rate_limit()
bool gcs_gateway_check_enhanced_rate_limit (uint32_t session_id)
Rate limiting enhancement (T030 - User Story 4).
Enhanced rate limiting with burst allowance and security monitoring
Definition at line 444 of file gcs_gateway.c.
References gcs_gateway_audit_security_violation(), gcs_gateway_get_timestamp_ms(), gcs_gateway_log_security_violation(), gcs_gateway_log_to_audit_system(), and scp_session_check_rate_limit().
gcs_gateway_generate_tlm_status()
esp_err_t gcs_gateway_generate_tlm_status (scp_tlm_status_t * status) static
Generate TLM_STATUS message with current system state.
Integrates with existing telemetry_core and sensor systems to generate comprehensive status telemetry for GCS streaming.
Parameters
status Output buffer for status message
Returns
ESP_OK on success, error code on failure
Definition at line 1300 of file gcs_gateway.c.
References mpu6050_data_t::accel_x, mpu6050_data_t::accel_y, mpu6050_data_t::accel_z, bmp388_data_t::altitude, bmp388_get_instance(), bmp388_read_scaled(), gcs_gateway_get_timestamp_ms(), hmc5883l_data_t::heading, hmc5883l_get_instance(), hmc5883l_read_scaled(), mpu6050_t::initialized, neo6m_t::initialized, mpu6050_get_instance(), mpu6050_read_scaled(), and neo6m_get_instance().
Referenced by gcs_gateway_send_tlm_status_targeted(), and gcs_gateway_update_telemetry().
gcs_gateway_get_priority_queue_stats()
void gcs_gateway_get_priority_queue_stats (gcs_priority_queue_stats_t * stats_out)
Get priority queue statistics (T040).
Get Priority Queue Statistics (T040).
Retrieves statistics about the priority-based telemetry queue.
Parameters
stats_out Output buffer for queue statistics
Definition at line 2050 of file gcs_gateway.c.
gcs_gateway_get_session_telemetry_stats()
bool gcs_gateway_get_session_telemetry_stats (uint32_t session_id, gcs_session_telemetry_stats_t * stats_out)
Get session telemetry statistics (T039).
Get Session Telemetry Statistics (T039).
Retrieves telemetry statistics for a specific session.
Parameters
session_id Target session ID
stats_out Output buffer for session statistics
Returns
true if session found, false otherwise
Definition at line 1880 of file gcs_gateway.c.
gcs_gateway_get_stats()
void gcs_gateway_get_stats (gcs_gateway_stats_t * stats_out)
Get Gateway Statistics.
Retrieves operational statistics for monitoring.
Parameters
stats_out Output buffer for statistics
Definition at line 1192 of file gcs_gateway.c.
Referenced by gcs_gateway_log_security_violation().
gcs_gateway_get_telemetry_priority()
uint8_t gcs_gateway_get_telemetry_priority (const scp_tlm_status_t * status) static
Determine telemetry priority based on system state (T040).
Analyzes current system status to determine appropriate priority level for TLM_STATUS messages.
Parameters
status Status message to analyze
Returns
Priority level (SCP_PRIORITY_*)
Definition at line 1441 of file gcs_gateway.c.
Referenced by gcs_gateway_update_telemetry().
gcs_gateway_get_telemetry_stats()
void gcs_gateway_get_telemetry_stats (gcs_telemetry_stats_t * stats_out)
Get telemetry timing statistics (T038).
Get Telemetry Timing Statistics (T038).
Retrieves detailed timing and performance statistics for telemetry analysis.
Parameters
stats_out Output buffer for telemetry timing statistics
Definition at line 1788 of file gcs_gateway.c.
gcs_gateway_get_timestamp_ms()
uint32_t gcs_gateway_get_timestamp_ms (void) static
Get current timestamp in milliseconds.
Returns
Current system timestamp
Definition at line 122 of file gcs_gateway.c.
Referenced by gcs_gateway_check_enhanced_rate_limit(), gcs_gateway_generate_tlm_status(), gcs_gateway_get_priority_queue_stats(), gcs_gateway_init(), gcs_gateway_log_to_audit_system(), gcs_gateway_process_cmd_control(), gcs_gateway_process_message(), gcs_gateway_process_priority_queue(), gcs_gateway_queue_telemetry(), gcs_gateway_send_audit_event(), gcs_gateway_send_response(), gcs_gateway_send_tlm_status_targeted(), and gcs_gateway_update_telemetry().
gcs_gateway_init()
bool gcs_gateway_init (void)
Initialize GCS Gateway.
Initializes the GCS gateway subsystem including transport interfaces, FreeRTOS tasks, and protocol state.
Returns
true if initialization successful, false on error
Definition at line 1069 of file gcs_gateway.c.
gcs_gateway_log_critical_security_event()
esp_err_t gcs_gateway_log_critical_security_event (const char * violation_type, const char * details)
Log critical system security event (T032 - Enhanced).
Log Critical System Security Event.
Public interface for logging system-level security events from other components. Used for security violations detected outside of normal command processing.
Parameters
violation_type Type of security violation
details Additional violation details
Returns
ESP_OK on success, error code on failure
Definition at line 2038 of file gcs_gateway.c.
gcs_gateway_log_security_violation()
esp_err_t gcs_gateway_log_security_violation (const char * violation_type, uint32_t session_id, const char * details, const char * severity) static
Log security violation to persistent FATFS storage (T032).
Records critical security violations to FATFS blackbox for persistent audit trails that survive system restarts. Used for high-severity security events that require forensic analysis beyond the volatile audit system.
Parameters
violation_type Type of security violation
session_id Session ID where violation occurred (0 if system-level)
details Additional violation details
severity Violation severity level
Returns
ESP_OK on success, error code on failure
Definition at line 545 of file gcs_gateway.c.
References blackbox_is_initialized(), blackbox_log_event(), gcs_gateway_get_stats(), scp_connection_get_name(), scp_role_get_name(), and scp_session_get_by_id().
Referenced by gcs_gateway_check_enhanced_rate_limit(), gcs_gateway_log_critical_security_event(), gcs_gateway_process_cmd_control(), and gcs_gateway_validate_sequence().
gcs_gateway_log_to_audit_system()
void gcs_gateway_log_to_audit_system (uint32_t session_id, scp_message_type_t command_type, gcs_command_result_t result_code, const char * command_summary) static
Integration with existing audit system (T027 - User Story 4).
Logs SCP command to the existing companion audit system for unified audit trails
Definition at line 480 of file gcs_gateway.c.
References audit_is_initialized(), audit_process_companion_input(), gcs_gateway_get_timestamp_ms(), scp_role_get_name(), and scp_session_get_by_id().
Referenced by gcs_gateway_check_enhanced_rate_limit(), gcs_gateway_process_arm_command(), gcs_gateway_process_disarm_command(), and gcs_gateway_process_mode_change().
gcs_gateway_process_arm_command()
gcs_command_result_t gcs_gateway_process_arm_command (scp_session_t * session, const scp_cmd_control_t * cmd_control, uint8_t sequence_num) static
Process ARM command.
Parameters
session Session requesting the command
cmd_control Command control message
sequence_num Message sequence number
Returns
Command processing result
Definition at line 635 of file gcs_gateway.c.
References gcs_gateway_log_to_audit_system(), scp_role_can_execute(), and scp_role_get_name().
Referenced by gcs_gateway_process_cmd_control().
gcs_gateway_process_cmd_control()
gcs_command_result_t gcs_gateway_process_cmd_control (uint32_t session_id, uint8_t sequence_num, const uint8_t * payload, size_t payload_size) static
Process CMD_CONTROL message.
Parameters
session_id Source session ID
sequence_num Message sequence number
payload Message payload
payload_size Payload size
Returns
Command processing result
Definition at line 836 of file gcs_gateway.c.
References gcs_gateway_audit_auth_failure(), gcs_gateway_audit_security_violation(), gcs_gateway_get_timestamp_ms(), gcs_gateway_log_security_violation(), gcs_gateway_process_arm_command(), gcs_gateway_process_disarm_command(), gcs_gateway_process_mode_change(), scp_session_authorize_command(), and scp_session_get_by_id().
Referenced by gcs_gateway_process_message().
gcs_gateway_process_disarm_command()
gcs_command_result_t gcs_gateway_process_disarm_command (scp_session_t * session, const scp_cmd_control_t * cmd_control, uint8_t sequence_num) static
Process DISARM command.
Parameters
session Session requesting the command
cmd_control Command control message
sequence_num Message sequence number
Returns
Command processing result
Definition at line 715 of file gcs_gateway.c.
References gcs_gateway_log_to_audit_system(), scp_role_can_execute(), and scp_role_get_name().
Referenced by gcs_gateway_process_cmd_control().
gcs_gateway_process_message()
void gcs_gateway_process_message (const gateway_message_t * message) static
Process received message and generate appropriate response.
Parameters
message Received message to process
Definition at line 937 of file gcs_gateway.c.
References gcs_gateway_audit_command_attempt(), gcs_gateway_get_timestamp_ms(), gcs_gateway_process_cmd_control(), and gcs_gateway_send_response().
Referenced by gcs_gateway_task().
gcs_gateway_process_mode_change()
gcs_command_result_t gcs_gateway_process_mode_change (scp_session_t * session, const scp_cmd_control_t * cmd_control, uint8_t sequence_num) static
Process mode change command.
Parameters
session Session requesting the command
cmd_control Command control message
sequence_num Message sequence number
Returns
Command processing result
Definition at line 768 of file gcs_gateway.c.
References gcs_gateway_log_to_audit_system(), scp_role_can_execute(), and scp_role_get_name().
Referenced by gcs_gateway_process_cmd_control().
gcs_gateway_process_priority_queue()
uint8_t gcs_gateway_process_priority_queue (void) static
Process priority telemetry queue (T040).
Processes queued telemetry messages in priority order, handling retries and queue management.
Returns
Number of messages processed from queue
Definition at line 1533 of file gcs_gateway.c.
References gcs_gateway_get_timestamp_ms(), and gcs_gateway_send_tlm_status_targeted().
Referenced by gcs_gateway_update_telemetry().
gcs_gateway_queue_telemetry()
bool gcs_gateway_queue_telemetry (const scp_tlm_status_t * status, uint32_t session_id, uint8_t priority) static
Add telemetry message to priority queue (T040).
Queues telemetry message with appropriate priority level for burst transmission scenarios and priority-based delivery.
Parameters
status Telemetry message to queue
session_id Target session (0 = broadcast)
priority Message priority level
Returns
true if queued successfully, false if queue full
Definition at line 1476 of file gcs_gateway.c.
References gcs_gateway_get_timestamp_ms().
Referenced by gcs_gateway_update_telemetry().
gcs_gateway_receive_message()
bool gcs_gateway_receive_message (uint32_t session_id, uint8_t sequence_num, scp_message_type_t message_type, const uint8_t * payload, size_t payload_size)
Definition at line 1146 of file gcs_gateway.c.
gcs_gateway_reset_stats()
void gcs_gateway_reset_stats (void)
Reset Gateway Statistics.
Resets operational statistics counters.
Definition at line 1206 of file gcs_gateway.c.
gcs_gateway_send_audit_event()
bool gcs_gateway_send_audit_event (uint8_t event_type, uint32_t source_session, uint8_t operator_role, uint8_t result_code, const uint8_t * details) static
Generate and send TLM_AUDIT message for security/operational events.
Parameters
event_type Type of audit event (SCP_AUDIT_*)
source_session Session ID that triggered event (0 if N/A)
operator_role Role of operator (0 if N/A)
result_code Result/error code for the event
details Additional event-specific details (16 bytes max)
Returns
true if audit message sent successfully
Definition at line 197 of file gcs_gateway.c.
References gcs_gateway_get_timestamp_ms(), scp_framer_encode(), and scp_session_get_list().
Referenced by gcs_gateway_audit_auth_failure(), gcs_gateway_audit_command_attempt(), gcs_gateway_audit_security_violation(), and gcs_gateway_audit_session_event().
gcs_gateway_send_response()
bool gcs_gateway_send_response (uint32_t session_id, uint8_t sequence_num, scp_message_type_t message_type, const void * payload, size_t payload_size) static
Send response message to GCS.
Parameters
session_id Target session ID
sequence_num Original message sequence number
message_type Response message type
payload Response payload data
payload_size Size of payload data
Returns
true if response sent successfully
Definition at line 136 of file gcs_gateway.c.
References gcs_gateway_get_timestamp_ms(), scp_framer_encode(), and scp_session_get_by_id().
Referenced by gcs_gateway_process_message().
gcs_gateway_send_tlm_status()
uint8_t gcs_gateway_send_tlm_status (void)
Send TLM_STATUS to all eligible sessions (backward compatibility).
Send TLM_STATUS to All Active Sessions (T036).
Definition at line 1737 of file gcs_gateway.c.
Referenced by gcs_gateway_update_telemetry().
gcs_gateway_send_tlm_status_targeted()
uint8_t gcs_gateway_send_tlm_status_targeted (uint32_t target_session_id)
Send TLM_STATUS message to sessions with role-based filtering.
Send TLM_STATUS to Specific Session (T039).
Generates and broadcasts current system status to authenticated GCS sessions based on operator roles and per-session telemetry configuration.
Parameters
target_session_id Specific session to target (0 = all eligible sessions)
Returns
Number of sessions the status was sent to
Definition at line 1619 of file gcs_gateway.c.
Referenced by gcs_gateway_process_priority_queue(), and gcs_gateway_send_tlm_status().
gcs_gateway_set_session_telemetry()
bool gcs_gateway_set_session_telemetry (uint32_t session_id, bool enabled, uint8_t rate_hz)
Configure per-session telemetry (T039).
Configure Session Telemetry (T039).
Sets telemetry configuration for a specific operator session, enabling customized telemetry rates and filtering per operator role.
Parameters
session_id Target session ID
enabled Enable/disable telemetry for this session
rate_hz Session-specific rate (0 = use global rate)
Returns
true if session found and configured, false otherwise
Definition at line 1833 of file gcs_gateway.c.
gcs_gateway_set_telemetry_enabled()
void gcs_gateway_set_telemetry_enabled (bool enabled)
Enable/disable telemetry streaming.
Enable/Disable Telemetry Streaming.
Controls whether TLM_STATUS messages are periodically sent to GCS.
Parameters
enabled true to enable streaming, false to disable
Definition at line 1775 of file gcs_gateway.c.
gcs_gateway_set_telemetry_rate()
bool gcs_gateway_set_telemetry_rate (uint8_t rate_hz)
Set telemetry rate (T038 - Rate Control).
Set Telemetry Rate.
Configures the rate at which TLM_STATUS messages are sent to GCS. Rate is applied globally to all active sessions.
Parameters
rate_hz Desired telemetry rate in Hz (1-10)
Returns
true if rate set successfully, false if invalid
Definition at line 1751 of file gcs_gateway.c.
gcs_gateway_task()
void gcs_gateway_task (void * param) static
Main gateway processing task.
Parameters
param Task parameter (unused)
Definition at line 1042 of file gcs_gateway.c.
References gcs_gateway_process_message(), and gcs_gateway_update_telemetry().
Referenced by gcs_gateway_init().
gcs_gateway_update_telemetry()
void gcs_gateway_update_telemetry (void) static
Update telemetry system (T037/T038 - Integration with Timing Validation).
Checks if it's time to send periodic TLM_STATUS and sends if needed. Includes timing validation and jitter monitoring for performance analysis.
Definition at line 1917 of file gcs_gateway.c.
References gcs_gateway_generate_tlm_status(), gcs_gateway_get_telemetry_priority(), gcs_gateway_get_timestamp_ms(), gcs_gateway_process_priority_queue(), gcs_gateway_queue_telemetry(), and gcs_gateway_send_tlm_status().
Referenced by gcs_gateway_task().
gcs_gateway_validate_sequence()
bool gcs_gateway_validate_sequence (uint32_t session_id, uint8_t sequence_num)
Enhanced replay attack detection (T029 - User Story 4).
Validates message sequence numbers and detects potential replay attacks
Parameters
session_id Session to validate
sequence_num Received sequence number
Returns
true if sequence is valid, false if replay detected
Definition at line 404 of file gcs_gateway.c.
References gcs_gateway_audit_auth_failure(), gcs_gateway_audit_security_violation(), gcs_gateway_log_security_violation(), and scp_session_get_by_id().
Variable Documentation
avg_jitter_ms
int32_t avg_jitter_ms
Definition at line 1242 of file gcs_gateway.c.
enabled
bool enabled
Definition at line 1233 of file gcs_gateway.c.
gateway_state
gcs_gateway_state_t gateway_state = {0} static
Definition at line 101 of file gcs_gateway.c.
jitter_sample_idx
uint8_t jitter_sample_idx
Definition at line 1244 of file gcs_gateway.c.
jitter_samples
uint32_t jitter_samples[16]
Definition at line 1243 of file gcs_gateway.c.
last_drop_timestamp_ms
uint32_t last_drop_timestamp_ms
Definition at line 1248 of file gcs_gateway.c.
last_send_ms
uint32_t last_send_ms
Definition at line 1255 of file gcs_gateway.c.
last_status_send_ms
uint32_t last_status_send_ms
Definition at line 1232 of file gcs_gateway.c.
late_transmissions
uint32_t late_transmissions
Definition at line 1239 of file gcs_gateway.c.
max_jitter_ms
int32_t max_jitter_ms
Definition at line 1240 of file gcs_gateway.c.
message
scp_tlm_status_t message
Definition at line 1262 of file gcs_gateway.c.
messages_sent
uint32_t messages_sent
Definition at line 1256 of file gcs_gateway.c.
min_jitter_ms
int32_t min_jitter_ms
Definition at line 1241 of file gcs_gateway.c.
on_time_transmissions
uint32_t on_time_transmissions
Definition at line 1238 of file gcs_gateway.c.
priority
uint8_t priority
Definition at line 1264 of file gcs_gateway.c.
priority_drops
uint32_t priority_drops
Definition at line 1271 of file gcs_gateway.c.
queue_high_priority_count
uint8_t queue_high_priority_count
Definition at line 1270 of file gcs_gateway.c.
queue_size
uint8_t queue_size
Definition at line 1269 of file gcs_gateway.c.
rate_hz
uint8_t rate_hz
Definition at line 1231 of file gcs_gateway.c.
rate_limit_drops
uint32_t rate_limit_drops
Definition at line 1247 of file gcs_gateway.c.
retry_count
uint8_t retry_count
Definition at line 1266 of file gcs_gateway.c.
session_id
uint32_t session_id
Definition at line 1263 of file gcs_gateway.c.
TAG
const char* TAG = "gcs_gateway" static
Definition at line 50 of file gcs_gateway.c.
target_interval_ms
uint32_t target_interval_ms
Definition at line 1234 of file gcs_gateway.c.
[struct]
struct { ... } telemetry_state
Initial value:
= {
    .rate_hz = 2,
    .last_status_send_ms = 0,
    .enabled = true,
    .target_interval_ms = 500,
    .total_transmissions = 0,
    .on_time_transmissions = 0,
    .late_transmissions = 0,
    .max_jitter_ms = 0,
    .min_jitter_ms = 0,
    .avg_jitter_ms = 0,
    .jitter_sample_idx = 0,
    .rate_limit_drops = 0,
    .last_drop_timestamp_ms = 0,
    .queue_size = 0,
    .queue_high_priority_count = 0,
    .priority_drops = 0}
timestamp_ms
uint32_t timestamp_ms
Definition at line 1265 of file gcs_gateway.c.
total_transmissions
uint32_t total_transmissions
Definition at line 1237 of file gcs_gateway.c.