ACP - Autonomous Command Protocol: tests/hmac_test.c File Reference
hmac_test.c File Reference
HMAC test vectors with 16-byte truncated tags for ACP.
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include "acp_protocol.h"
Functions
static void print_hex (const char *label, const uint8_t *data, size_t len)
static void test_vector_1 (void)
Test vector 1: Basic 16-byte truncated HMAC.
static void test_vector_2 (void)
Test vector 2: ACP key size with frame-like data.
static void test_vector_3 (void)
Test vector 3: Edge case - empty data.
static void test_vector_4 (void)
Test vector 4: Maximum length data.
static void test_vector_5 (void)
Test vector 5: Cross-validation with known values.
static void validate_truncation_properties (void)
Validate 16-byte truncation properties.
int main (void)
Detailed Description
HMAC test vectors with 16-byte truncated tags for ACP.
Definition in file hmac_test.c.
Function Documentation
main()
int main (void)
Definition at line 230 of file hmac_test.c.
print_hex()
void print_hex (const char * label, const uint8_t * data, size_t len) static
Definition at line 11 of file hmac_test.c.
test_vector_1()
void test_vector_1 (void) static
Test vector 1: Basic 16-byte truncated HMAC.
Definition at line 24 of file hmac_test.c.
References acp_hmac_sha256(), and ACP_HMAC_TAG_LEN.
test_vector_2()
void test_vector_2 (void) static
Test vector 2: ACP key size with frame-like data.
Definition at line 62 of file hmac_test.c.
References acp_hmac_sha256(), ACP_HMAC_TAG_LEN, and ACP_KEY_SIZE.
test_vector_3()
void test_vector_3 (void) static
Test vector 3: Edge case - empty data.
Definition at line 96 of file hmac_test.c.
References acp_hmac_sha256(), ACP_HMAC_TAG_LEN, and ACP_KEY_SIZE.
test_vector_4()
void test_vector_4 (void) static
Test vector 4: Maximum length data.
Definition at line 122 of file hmac_test.c.
References acp_hmac_sha256(), ACP_HMAC_TAG_LEN, ACP_KEY_SIZE, and ACP_MAX_PAYLOAD_SIZE.
test_vector_5()
void test_vector_5 (void) static
Test vector 5: Cross-validation with known values.
Definition at line 156 of file hmac_test.c.
References acp_hmac_sha256(), and ACP_HMAC_TAG_LEN.
validate_truncation_properties()
void validate_truncation_properties (void) static
Validate 16-byte truncation properties.
Definition at line 189 of file hmac_test.c.
References acp_crypto_memcmp_ct(), acp_hmac_sha256(), ACP_HMAC_TAG_LEN, and ACP_KEY_SIZE.