ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/include/hmc5883l.h File Reference
hmc5883l.h File Reference
HMC5883L 3-axis magnetometer driver with calibration and health checks.
#include "scout_types.h"
#include "esp_err.h"
#include <stdbool.h>
#include <stdint.h>
Classes
struct hmc5883l_raw_data_t
HMC5883L raw sensor data structure.
struct hmc5883l_data_t
HMC5883L scaled sensor data structure.
struct hmc5883l_cal_sample_t
HMC5883L calibration sample for sphere fitting.
struct hmc5883l_calibration_t
HMC5883L calibration data.
struct hmc5883l_t
HMC5883L device structure.
Typedefs
typedef void(* hmc5883l_cal_callback_t) (hmc5883l_cal_step_t step, const char *message, void *user_data)
Calibration callback function type.
Enumerations
enum hmc5883l_cal_step_t {
HMC5883L_CAL_STEP_START , HMC5883L_CAL_STEP_SAMPLING , HMC5883L_CAL_STEP_PROCESSING , HMC5883L_CAL_STEP_COMPLETE ,
HMC5883L_CAL_STEP_ERROR
}
Calibration step enumeration for callback.
Functions
esp_err_t hmc5883l_init (hmc5883l_t *dev)
Initialize HMC5883L device.
esp_err_t hmc5883l_read_raw (hmc5883l_t *dev, hmc5883l_raw_data_t *raw_data)
Read raw sensor data from HMC5883L.
esp_err_t hmc5883l_read_scaled (hmc5883l_t *dev, hmc5883l_data_t *data)
Read scaled sensor data from HMC5883L.
esp_err_t hmc5883l_calibrate_sphere (hmc5883l_t *dev, hmc5883l_cal_callback_t callback, void *user_data)
Perform sphere calibration of HMC5883L.
sensor_health_t hmc5883l_get_health (hmc5883l_t *dev)
Get current health status of HMC5883L.
const char * hmc5883l_get_last_error (hmc5883l_t *dev)
Get last error message.
hmc5883l_t * hmc5883l_get_instance (void)
Get global HMC5883L instance.
Detailed Description
HMC5883L 3-axis magnetometer driver with calibration and health checks.
Driver for HMC5883L 3-axis magnetometer providing magnetic field measurements with health monitoring, sphere calibration, and heading computation.
Definition in file hmc5883l.h.
Typedef Documentation
hmc5883l_cal_callback_t
typedef void(* hmc5883l_cal_callback_t) (hmc5883l_cal_step_t step, const char *message, void *user_data)
Calibration callback function type.
Parameters
step Current calibration step
message Human-readable message for operator
user_data User data passed to calibration function
Definition at line 81 of file hmc5883l.h.
Enumeration Type Documentation
hmc5883l_cal_step_t
enum hmc5883l_cal_step_t
Calibration step enumeration for callback.
Enumerator
HMC5883L_CAL_STEP_START
Calibration starting.
HMC5883L_CAL_STEP_SAMPLING
Collecting samples.
HMC5883L_CAL_STEP_PROCESSING
Processing collected data.
HMC5883L_CAL_STEP_COMPLETE
Calibration completed successfully.
HMC5883L_CAL_STEP_ERROR
Calibration failed.
Definition at line 67 of file hmc5883l.h.
Function Documentation
hmc5883l_calibrate_sphere()
esp_err_t hmc5883l_calibrate_sphere (hmc5883l_t * dev, hmc5883l_cal_callback_t callback, void * user_data)
Perform sphere calibration of HMC5883L.
Performs 3D sphere fitting calibration to determine hard and soft iron corrections. Device should be rotated in all orientations during calibration period.
Parameters
dev HMC5883L device structure
callback Optional callback for progress updates (can be NULL)
user_data User data passed to callback
Returns
ESP_OK on success, ESP_ERR_TIMEOUT if insufficient samples, error code otherwise
Definition at line 249 of file hmc5883l.c.
References hmc5883l_t::cal, hmc5883l_calibration_t::calibrated, hmc5883l_t::health, HMC5883L_CAL_STEP_COMPLETE, HMC5883L_CAL_STEP_ERROR, HMC5883L_CAL_STEP_PROCESSING, HMC5883L_CAL_STEP_SAMPLING, HMC5883L_CAL_STEP_START, hmc5883l_read_raw(), hmc5883l_t::initialized, hmc5883l_t::last_error, hmc5883l_raw_data_t::mag_x, hmc5883l_raw_data_t::mag_y, hmc5883l_raw_data_t::mag_z, hmc5883l_calibration_t::offset_x, hmc5883l_calibration_t::offset_y, hmc5883l_calibration_t::offset_z, hmc5883l_calibration_t::scale_x, hmc5883l_calibration_t::scale_y, hmc5883l_calibration_t::scale_z, hmc5883l_calibration_t::timestamp, hmc5883l_cal_sample_t::x, hmc5883l_cal_sample_t::y, and hmc5883l_cal_sample_t::z.
hmc5883l_get_health()
sensor_health_t hmc5883l_get_health (hmc5883l_t * dev)
Get current health status of HMC5883L.
Parameters
dev HMC5883L device structure
Returns
Current sensor health status
Definition at line 349 of file hmc5883l.c.
References hmc5883l_t::health, and hmc5883l_t::initialized.
hmc5883l_get_instance()
hmc5883l_t * hmc5883l_get_instance (void)
Get global HMC5883L instance.
Returns pointer to the global HMC5883L instance if initialized.
Returns
Pointer to global instance or NULL if not initialized
Definition at line 367 of file hmc5883l.c.
Referenced by blackbox_collect_evidence(), blackbox_log_sensor_summary(), and gcs_gateway_generate_tlm_status().
hmc5883l_get_last_error()
const char * hmc5883l_get_last_error (hmc5883l_t * dev)
Get last error message.
Parameters
dev HMC5883L device structure
Returns
Pointer to last error message string
Definition at line 358 of file hmc5883l.c.
References hmc5883l_t::last_error.
hmc5883l_init()
esp_err_t hmc5883l_init (hmc5883l_t * dev)
Initialize HMC5883L device.
Initializes I2C communication, configures the device for ±1.3 Ga range, performs self-test, and sets initial health status.
Parameters
dev HMC5883L device structure to initialize
Returns
ESP_OK on success, error code otherwise
Definition at line 73 of file hmc5883l.c.
References bus_io_init_i2c(), hmc5883l_t::cal, hmc5883l_calibration_t::calibrated, hmc5883l_t::health, hmc5883l_t::initialized, hmc5883l_t::last_error, hmc5883l_calibration_t::offset_x, hmc5883l_calibration_t::offset_y, hmc5883l_calibration_t::offset_z, hmc5883l_calibration_t::scale_x, hmc5883l_calibration_t::scale_y, and hmc5883l_calibration_t::scale_z.
hmc5883l_read_raw()
esp_err_t hmc5883l_read_raw (hmc5883l_t * dev, hmc5883l_raw_data_t * raw_data)
Read raw sensor data from HMC5883L.
Reads magnetometer registers and checks for data ready status. Updates device health status periodically.
Parameters
dev HMC5883L device structure
raw_data Output buffer for raw sensor data
Returns
ESP_OK on success, ESP_ERR_NOT_FINISHED if data not ready, error code otherwise
Definition at line 160 of file hmc5883l.c.
References hmc5883l_t::health, hmc5883l_t::initialized, hmc5883l_t::last_error, hmc5883l_raw_data_t::mag_x, hmc5883l_raw_data_t::mag_y, hmc5883l_raw_data_t::mag_z, and hmc5883l_raw_data_t::timestamp.
Referenced by hmc5883l_calibrate_sphere(), and hmc5883l_read_scaled().
hmc5883l_read_scaled()
esp_err_t hmc5883l_read_scaled (hmc5883l_t * dev, hmc5883l_data_t * data)
Read scaled sensor data from HMC5883L.
Reads raw data and applies calibration corrections and scaling factors. Calculates magnetic heading from calibrated X and Y components.
Parameters
dev HMC5883L device structure
data Output buffer for scaled sensor data
Returns
ESP_OK on success, error code otherwise
Definition at line 216 of file hmc5883l.c.
References hmc5883l_t::cal, hmc5883l_data_t::heading, hmc5883l_read_raw(), hmc5883l_data_t::mag_x, hmc5883l_raw_data_t::mag_x, hmc5883l_data_t::mag_y, hmc5883l_raw_data_t::mag_y, hmc5883l_data_t::mag_z, hmc5883l_raw_data_t::mag_z, hmc5883l_calibration_t::offset_x, hmc5883l_calibration_t::offset_y, hmc5883l_calibration_t::offset_z, hmc5883l_calibration_t::scale_x, hmc5883l_calibration_t::scale_y, hmc5883l_calibration_t::scale_z, hmc5883l_data_t::timestamp, and hmc5883l_raw_data_t::timestamp.
Referenced by blackbox_collect_evidence(), blackbox_log_sensor_summary(), and gcs_gateway_generate_tlm_status().