ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/src/sensors/hmc5883l.c File Reference
hmc5883l.c File Reference
HMC5883L 3-axis magnetometer driver with calibration and health checks.
#include "hmc5883l.h"
#include "bus_io.h"
#include "scout_types.h"
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include <math.h>
#include <string.h>
Macros
#define HMC5883L_I2C_ADDR 0x1E
#define HMC5883L_REG_CONFIG_A 0x00
#define HMC5883L_REG_CONFIG_B 0x01
#define HMC5883L_REG_MODE 0x02
#define HMC5883L_REG_DATA_X_MSB 0x03
#define HMC5883L_REG_STATUS 0x09
#define HMC5883L_REG_ID_A 0x0A
#define HMC5883L_REG_ID_B 0x0B
#define HMC5883L_REG_ID_C 0x0C
#define HMC5883L_ID_A_VAL 0x48
#define HMC5883L_ID_B_VAL 0x34
#define HMC5883L_ID_C_VAL 0x33
#define HMC5883L_CONFIG_A_NORMAL 0x70
#define HMC5883L_CONFIG_B_GAIN_1_3 0x20
#define HMC5883L_MODE_CONTINUOUS 0x00
#define HMC5883L_MODE_SINGLE 0x01
#define HMC5883L_STATUS_RDY 0x01
#define HMC5883L_STATUS_LOCK 0x02
#define HMC5883L_SCALE_1_3_GA 1090.0f
#define HMC5883L_SATURATION_LIMIT 32760
#define HMC5883L_CAL_SAMPLES 200
#define HMC5883L_CAL_MIN_COVERAGE 0.8f
#define HMC5883L_CAL_MAX_RESIDUAL 0.3f
#define HMC5883L_HEALTH_CHECK_INTERVAL_MS 500
Functions
static esp_err_t hmc5883l_write_register (uint8_t reg, uint8_t value)
static esp_err_t hmc5883l_read_register (uint8_t reg, uint8_t *value)
static esp_err_t hmc5883l_read_registers (uint8_t reg, uint8_t *data, size_t len)
static void hmc5883l_update_health (hmc5883l_t *dev)
static esp_err_t hmc5883l_self_test (hmc5883l_t *dev)
static float hmc5883l_calculate_heading (const hmc5883l_data_t *data)
static esp_err_t hmc5883l_sphere_fit (const hmc5883l_cal_sample_t *samples, int count, hmc5883l_calibration_t *cal, float *residual)
esp_err_t hmc5883l_init (hmc5883l_t *dev)
Initialize HMC5883L device.
esp_err_t hmc5883l_read_raw (hmc5883l_t *dev, hmc5883l_raw_data_t *raw_data)
Read raw sensor data from HMC5883L.
esp_err_t hmc5883l_read_scaled (hmc5883l_t *dev, hmc5883l_data_t *data)
Read scaled sensor data from HMC5883L.
esp_err_t hmc5883l_calibrate_sphere (hmc5883l_t *dev, hmc5883l_cal_callback_t callback, void *user_data)
Perform sphere calibration of HMC5883L.
sensor_health_t hmc5883l_get_health (hmc5883l_t *dev)
Get current health status of HMC5883L.
const char * hmc5883l_get_last_error (hmc5883l_t *dev)
Get last error message.
hmc5883l_t * hmc5883l_get_instance (void)
Get global HMC5883L instance.
Variables
static const char * TAG = "hmc5883l"
static hmc5883l_t g_hmc5883l = {0}
static bool g_initialized = false
static uint32_t g_last_health_check = 0
Detailed Description
HMC5883L 3-axis magnetometer driver with calibration and health checks.
Implements I2C communication with HMC5883L magnetometer. Provides health monitoring, hard/soft iron calibration, and heading computation.
Definition in file hmc5883l.c.
Macro Definition Documentation
HMC5883L_CAL_MAX_RESIDUAL
#define HMC5883L_CAL_MAX_RESIDUAL 0.3f
Definition at line 55 of file hmc5883l.c.
HMC5883L_CAL_MIN_COVERAGE
#define HMC5883L_CAL_MIN_COVERAGE 0.8f
Definition at line 54 of file hmc5883l.c.
HMC5883L_CAL_SAMPLES
#define HMC5883L_CAL_SAMPLES 200
Definition at line 53 of file hmc5883l.c.
HMC5883L_CONFIG_A_NORMAL
#define HMC5883L_CONFIG_A_NORMAL 0x70
Definition at line 39 of file hmc5883l.c.
HMC5883L_CONFIG_B_GAIN_1_3
#define HMC5883L_CONFIG_B_GAIN_1_3 0x20
Definition at line 40 of file hmc5883l.c.
HMC5883L_HEALTH_CHECK_INTERVAL_MS
#define HMC5883L_HEALTH_CHECK_INTERVAL_MS 500
Definition at line 56 of file hmc5883l.c.
HMC5883L_I2C_ADDR
#define HMC5883L_I2C_ADDR 0x1E
Definition at line 21 of file hmc5883l.c.
HMC5883L_ID_A_VAL
#define HMC5883L_ID_A_VAL 0x48
Definition at line 34 of file hmc5883l.c.
HMC5883L_ID_B_VAL
#define HMC5883L_ID_B_VAL 0x34
Definition at line 35 of file hmc5883l.c.
HMC5883L_ID_C_VAL
#define HMC5883L_ID_C_VAL 0x33
Definition at line 36 of file hmc5883l.c.
HMC5883L_MODE_CONTINUOUS
#define HMC5883L_MODE_CONTINUOUS 0x00
Definition at line 41 of file hmc5883l.c.
HMC5883L_MODE_SINGLE
#define HMC5883L_MODE_SINGLE 0x01
Definition at line 42 of file hmc5883l.c.
HMC5883L_REG_CONFIG_A
#define HMC5883L_REG_CONFIG_A 0x00
Definition at line 24 of file hmc5883l.c.
HMC5883L_REG_CONFIG_B
#define HMC5883L_REG_CONFIG_B 0x01
Definition at line 25 of file hmc5883l.c.
HMC5883L_REG_DATA_X_MSB
#define HMC5883L_REG_DATA_X_MSB 0x03
Definition at line 27 of file hmc5883l.c.
HMC5883L_REG_ID_A
#define HMC5883L_REG_ID_A 0x0A
Definition at line 29 of file hmc5883l.c.
HMC5883L_REG_ID_B
#define HMC5883L_REG_ID_B 0x0B
Definition at line 30 of file hmc5883l.c.
HMC5883L_REG_ID_C
#define HMC5883L_REG_ID_C 0x0C
Definition at line 31 of file hmc5883l.c.
HMC5883L_REG_MODE
#define HMC5883L_REG_MODE 0x02
Definition at line 26 of file hmc5883l.c.
HMC5883L_REG_STATUS
#define HMC5883L_REG_STATUS 0x09
Definition at line 28 of file hmc5883l.c.
HMC5883L_SATURATION_LIMIT
#define HMC5883L_SATURATION_LIMIT 32760
Definition at line 52 of file hmc5883l.c.
HMC5883L_SCALE_1_3_GA
#define HMC5883L_SCALE_1_3_GA 1090.0f
Definition at line 49 of file hmc5883l.c.
HMC5883L_STATUS_LOCK
#define HMC5883L_STATUS_LOCK 0x02
Definition at line 46 of file hmc5883l.c.
HMC5883L_STATUS_RDY
#define HMC5883L_STATUS_RDY 0x01
Definition at line 45 of file hmc5883l.c.
Function Documentation
hmc5883l_calculate_heading()
float hmc5883l_calculate_heading (const hmc5883l_data_t * data) static
Definition at line 432 of file hmc5883l.c.
hmc5883l_calibrate_sphere()
esp_err_t hmc5883l_calibrate_sphere (hmc5883l_t * dev, hmc5883l_cal_callback_t callback, void * user_data)
Perform sphere calibration of HMC5883L.
Performs 3D sphere fitting calibration to determine hard and soft iron corrections. Device should be rotated in all orientations during calibration period.
Parameters
dev HMC5883L device structure
callback Optional callback for progress updates (can be NULL)
user_data User data passed to callback
Returns
ESP_OK on success, ESP_ERR_TIMEOUT if insufficient samples, error code otherwise
Definition at line 249 of file hmc5883l.c.
References hmc5883l_t::cal, hmc5883l_calibration_t::calibrated, hmc5883l_t::health, HMC5883L_CAL_STEP_COMPLETE, HMC5883L_CAL_STEP_ERROR, HMC5883L_CAL_STEP_PROCESSING, HMC5883L_CAL_STEP_SAMPLING, HMC5883L_CAL_STEP_START, hmc5883l_read_raw(), hmc5883l_t::initialized, hmc5883l_t::last_error, hmc5883l_raw_data_t::mag_x, hmc5883l_raw_data_t::mag_y, hmc5883l_raw_data_t::mag_z, hmc5883l_calibration_t::offset_x, hmc5883l_calibration_t::offset_y, hmc5883l_calibration_t::offset_z, hmc5883l_calibration_t::scale_x, hmc5883l_calibration_t::scale_y, hmc5883l_calibration_t::scale_z, hmc5883l_calibration_t::timestamp, hmc5883l_cal_sample_t::x, hmc5883l_cal_sample_t::y, and hmc5883l_cal_sample_t::z.
hmc5883l_get_health()
sensor_health_t hmc5883l_get_health (hmc5883l_t * dev)
Get current health status of HMC5883L.
Parameters
dev HMC5883L device structure
Returns
Current sensor health status
Definition at line 349 of file hmc5883l.c.
References hmc5883l_t::health, and hmc5883l_t::initialized.
hmc5883l_get_instance()
hmc5883l_t * hmc5883l_get_instance (void)
Get global HMC5883L instance.
Returns pointer to the global HMC5883L instance if initialized.
Returns
Pointer to global instance or NULL if not initialized
Definition at line 367 of file hmc5883l.c.
Referenced by blackbox_collect_evidence(), blackbox_log_sensor_summary(), and gcs_gateway_generate_tlm_status().
hmc5883l_get_last_error()
const char * hmc5883l_get_last_error (hmc5883l_t * dev)
Get last error message.
Parameters
dev HMC5883L device structure
Returns
Pointer to last error message string
Definition at line 358 of file hmc5883l.c.
References hmc5883l_t::last_error.
hmc5883l_init()
esp_err_t hmc5883l_init (hmc5883l_t * dev)
Initialize HMC5883L device.
Initializes I2C communication, configures the device for ±1.3 Ga range, performs self-test, and sets initial health status.
Parameters
dev HMC5883L device structure to initialize
Returns
ESP_OK on success, error code otherwise
Definition at line 73 of file hmc5883l.c.
References bus_io_init_i2c(), hmc5883l_t::cal, hmc5883l_calibration_t::calibrated, hmc5883l_t::health, hmc5883l_t::initialized, hmc5883l_t::last_error, hmc5883l_calibration_t::offset_x, hmc5883l_calibration_t::offset_y, hmc5883l_calibration_t::offset_z, hmc5883l_calibration_t::scale_x, hmc5883l_calibration_t::scale_y, and hmc5883l_calibration_t::scale_z.
hmc5883l_read_raw()
esp_err_t hmc5883l_read_raw (hmc5883l_t * dev, hmc5883l_raw_data_t * raw_data)
Read raw sensor data from HMC5883L.
Reads magnetometer registers and checks for data ready status. Updates device health status periodically.
Parameters
dev HMC5883L device structure
raw_data Output buffer for raw sensor data
Returns
ESP_OK on success, ESP_ERR_NOT_FINISHED if data not ready, error code otherwise
Definition at line 160 of file hmc5883l.c.
References hmc5883l_t::health, hmc5883l_t::initialized, hmc5883l_t::last_error, hmc5883l_raw_data_t::mag_x, hmc5883l_raw_data_t::mag_y, hmc5883l_raw_data_t::mag_z, and hmc5883l_raw_data_t::timestamp.
Referenced by hmc5883l_calibrate_sphere(), and hmc5883l_read_scaled().
hmc5883l_read_register()
esp_err_t hmc5883l_read_register (uint8_t reg, uint8_t * value) static
Definition at line 382 of file hmc5883l.c.
hmc5883l_read_registers()
esp_err_t hmc5883l_read_registers (uint8_t reg, uint8_t * data, size_t len) static
Definition at line 387 of file hmc5883l.c.
hmc5883l_read_scaled()
esp_err_t hmc5883l_read_scaled (hmc5883l_t * dev, hmc5883l_data_t * data)
Read scaled sensor data from HMC5883L.
Reads raw data and applies calibration corrections and scaling factors. Calculates magnetic heading from calibrated X and Y components.
Parameters
dev HMC5883L device structure
data Output buffer for scaled sensor data
Returns
ESP_OK on success, error code otherwise
Definition at line 216 of file hmc5883l.c.
References hmc5883l_t::cal, hmc5883l_data_t::heading, hmc5883l_read_raw(), hmc5883l_data_t::mag_x, hmc5883l_raw_data_t::mag_x, hmc5883l_data_t::mag_y, hmc5883l_raw_data_t::mag_y, hmc5883l_data_t::mag_z, hmc5883l_raw_data_t::mag_z, hmc5883l_calibration_t::offset_x, hmc5883l_calibration_t::offset_y, hmc5883l_calibration_t::offset_z, hmc5883l_calibration_t::scale_x, hmc5883l_calibration_t::scale_y, hmc5883l_calibration_t::scale_z, hmc5883l_data_t::timestamp, and hmc5883l_raw_data_t::timestamp.
Referenced by blackbox_collect_evidence(), blackbox_log_sensor_summary(), and gcs_gateway_generate_tlm_status().
hmc5883l_self_test()
esp_err_t hmc5883l_self_test (hmc5883l_t * dev) static
Definition at line 412 of file hmc5883l.c.
hmc5883l_sphere_fit()
esp_err_t hmc5883l_sphere_fit (const hmc5883l_cal_sample_t * samples, int count, hmc5883l_calibration_t * cal, float * residual) static
Definition at line 448 of file hmc5883l.c.
hmc5883l_update_health()
void hmc5883l_update_health (hmc5883l_t * dev) static
Definition at line 392 of file hmc5883l.c.
hmc5883l_write_register()
esp_err_t hmc5883l_write_register (uint8_t reg, uint8_t value) static
Definition at line 377 of file hmc5883l.c.
Variable Documentation
g_hmc5883l
hmc5883l_t g_hmc5883l = {0} static
Definition at line 59 of file hmc5883l.c.
g_initialized
bool g_initialized = false static
Definition at line 60 of file hmc5883l.c.
g_last_health_check
uint32_t g_last_health_check = 0 static
Definition at line 61 of file hmc5883l.c.
TAG
const char* TAG = "hmc5883l" static
Definition at line 18 of file hmc5883l.c.