ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/include/scp_nvs.h File Reference
scp_nvs.h File Reference
SCP NVS Storage Interface for Demonstration.
#include <stdint.h>
#include <stdbool.h>
#include "esp_err.h"
Functions
esp_err_t scp_nvs_init (void)
Initialize NVS storage for SCP configuration.
esp_err_t scp_nvs_get_config (const char *key, void *value, size_t *length)
esp_err_t scp_nvs_set_config (const char *key, const void *value, size_t length)
Detailed Description
SCP NVS Storage Interface for Demonstration.
Mock NVS interface for SCP configuration storage.
Definition in file scp_nvs.h.
Function Documentation
scp_nvs_init()
esp_err_t scp_nvs_init (void)
Initialize NVS storage for SCP configuration.
Definition at line 157 of file scp_nvs.c.
References calculate_config_checksum(), init_default_config(), scp_nvs_load_config(), and scp_nvs_save_config().