ACP - Autonomous Command Protocol: examples/mock_serial.c File Reference
mock_serial.c File Reference
Mock serial transport example for ACP frame streaming.
#include "acp_protocol.h"
#include "acp_errors.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include <unistd.h>
Classes
struct mock_serial_t
Mock serial port state.
Functions
static void mock_serial_init (mock_serial_t *serial, size_t buffer_size)
Initialize mock serial port.
static void mock_serial_cleanup (mock_serial_t *serial)
Cleanup mock serial port.
static size_t mock_serial_write (mock_serial_t *serial, const uint8_t *data, size_t len)
Write data to mock serial port.
static size_t mock_serial_read (mock_serial_t *serial, uint8_t *data, size_t len)
Read data from mock serial port.
static size_t mock_serial_available (const mock_serial_t *serial)
Get available bytes in mock serial port.
static int send_sample_frames (mock_serial_t *serial)
Create sample frames and send to mock serial.
static int receive_frames (mock_serial_t *serial)
Receive and decode frames from mock serial.
static int test_partial_reads (mock_serial_t *serial)
Test frame boundary detection with partial reads.
int main (void)
Main mock serial example.
Detailed Description
Mock serial transport example for ACP frame streaming.
This example demonstrates:
Streaming frame decode from a simulated serial port
COBS framing boundary detection
Multiple frame handling in a continuous stream
Error handling for malformed frames
Definition in file mock_serial.c.
Function Documentation
main()
int main (void)
Main mock serial example.
Definition at line 381 of file mock_serial.c.
References acp_cleanup(), acp_init(), ACP_OK, mock_serial_cleanup(), mock_serial_init(), receive_frames(), send_sample_frames(), and test_partial_reads().
mock_serial_available()
size_t mock_serial_available (const mock_serial_t * serial) static
Get available bytes in mock serial port.
Definition at line 114 of file mock_serial.c.
References mock_serial_t::available.
Referenced by receive_frames(), send_sample_frames(), and test_partial_reads().
mock_serial_cleanup()
void mock_serial_cleanup (mock_serial_t * serial) static
Cleanup mock serial port.
Definition at line 69 of file mock_serial.c.
References mock_serial_t::buffer.
Referenced by main().
mock_serial_init()
void mock_serial_init (mock_serial_t * serial, size_t buffer_size) static
Initialize mock serial port.
Definition at line 57 of file mock_serial.c.
References mock_serial_t::available, mock_serial_t::buffer, mock_serial_t::buffer_size, mock_serial_t::read_pos, and mock_serial_t::write_pos.
Referenced by main().
mock_serial_read()
size_t mock_serial_read (mock_serial_t * serial, uint8_t * data, size_t len) static
Read data from mock serial port.
Definition at line 96 of file mock_serial.c.
References mock_serial_t::available, mock_serial_t::buffer, mock_serial_t::buffer_size, and mock_serial_t::read_pos.
Referenced by receive_frames(), and test_partial_reads().
mock_serial_write()
size_t mock_serial_write (mock_serial_t * serial, const uint8_t * data, size_t len) static
Write data to mock serial port.
Definition at line 78 of file mock_serial.c.
References mock_serial_t::available, mock_serial_t::buffer, mock_serial_t::buffer_size, and mock_serial_t::write_pos.
Referenced by send_sample_frames(), and test_partial_reads().
receive_frames()
int receive_frames (mock_serial_t * serial) static
Receive and decode frames from mock serial.
Definition at line 199 of file mock_serial.c.
References acp_decode_frame(), ACP_ERR_NEED_MORE_DATA, ACP_OK, acp_frame_t::flags, acp_frame_t::length, mock_serial_available(), mock_serial_read(), acp_frame_t::payload, and acp_frame_t::type.
Referenced by main().
send_sample_frames()
int send_sample_frames (mock_serial_t * serial) static
Create sample frames and send to mock serial.
Definition at line 122 of file mock_serial.c.
References acp_encode_frame(), ACP_FRAME_TYPE_COMMAND, ACP_FRAME_TYPE_TELEMETRY, ACP_OK, mock_serial_available(), and mock_serial_write().
Referenced by main().
test_partial_reads()
int test_partial_reads (mock_serial_t * serial) static
Test frame boundary detection with partial reads.
Definition at line 310 of file mock_serial.c.
References acp_decode_frame(), acp_encode_frame(), ACP_ERR_NEED_MORE_DATA, ACP_FRAME_TYPE_SYSTEM, ACP_OK, mock_serial_available(), mock_serial_read(), and mock_serial_write().
Referenced by main().