ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/src/sensors/mpu6050.c File Reference
mpu6050.c File Reference
MPU-6050 IMU driver with health checks and calibration.
#include "mpu6050.h"
#include "bus_io.h"
#include "scout_types.h"
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include <math.h>
#include <string.h>
Macros
#define MPU6050_I2C_ADDR 0x68
#define MPU6050_I2C_ADDR_ALT 0x69
#define MPU6050_REG_WHO_AM_I 0x75
#define MPU6050_REG_PWR_MGMT_1 0x6B
#define MPU6050_REG_PWR_MGMT_2 0x6C
#define MPU6050_REG_SMPRT_DIV 0x19
#define MPU6050_REG_CONFIG 0x1A
#define MPU6050_REG_GYRO_CONFIG 0x1B
#define MPU6050_REG_ACCEL_CONFIG 0x1C
#define MPU6050_REG_TEMP_OUT_H 0x41
#define MPU6050_REG_GYRO_XOUT_H 0x43
#define MPU6050_REG_ACCEL_XOUT_H 0x3B
#define MPU6050_WHO_AM_I_VAL 0x68
#define MPU6050_GYRO_FS_250 0x00
#define MPU6050_ACCEL_FS_2G 0x00
#define MPU6050_DLPF_CFG_94HZ 0x02
#define MPU6050_GYRO_SCALE 131.0f
#define MPU6050_ACCEL_SCALE 16384.0f
#define MPU6050_TEMP_SCALE 340.0f
#define MPU6050_TEMP_OFFSET 36.53f
#define MPU6050_MAX_TEMP_C 85.0f
#define MPU6050_MIN_TEMP_C -40.0f
#define MPU6050_CAL_SAMPLES 500
#define MPU6050_CAL_VARIANCE_THRESH 0.1f
#define MPU6050_HEALTH_CHECK_INTERVAL_MS 100
Functions
static esp_err_t mpu6050_write_register (uint8_t reg, uint8_t value)
static esp_err_t mpu6050_read_register (uint8_t reg, uint8_t *value)
static esp_err_t mpu6050_read_registers (uint8_t reg, uint8_t *data, size_t len)
static void mpu6050_update_health (mpu6050_t *dev)
static esp_err_t mpu6050_self_test (mpu6050_t *dev)
esp_err_t mpu6050_init (mpu6050_t *dev)
Initialize MPU-6050 device.
esp_err_t mpu6050_read_raw (mpu6050_t *dev, mpu6050_raw_data_t *raw_data)
Read raw sensor data from MPU-6050.
esp_err_t mpu6050_read_scaled (mpu6050_t *dev, mpu6050_data_t *data)
Read scaled sensor data from MPU-6050.
esp_err_t mpu6050_calibrate_level (mpu6050_t *dev, mpu6050_cal_callback_t callback, void *user_data)
Perform level calibration of MPU-6050.
sensor_health_t mpu6050_get_health (mpu6050_t *dev)
Get current health status of MPU-6050.
const char * mpu6050_get_last_error (mpu6050_t *dev)
Get last error message.
mpu6050_t * mpu6050_get_instance (void)
Get global MPU-6050 instance.
Variables
static const char * TAG = "mpu6050"
static mpu6050_t g_mpu6050 = {0}
static bool g_initialized = false
static uint32_t g_last_health_check = 0
Detailed Description
MPU-6050 IMU driver with health checks and calibration.
Implements I2C communication with MPU-6050 6-axis IMU (gyroscope + accelerometer). Provides health monitoring, calibration workflows, and sensor fusion.
Definition in file mpu6050.c.
Macro Definition Documentation
MPU6050_ACCEL_FS_2G
#define MPU6050_ACCEL_FS_2G 0x00
Definition at line 41 of file mpu6050.c.
MPU6050_ACCEL_SCALE
#define MPU6050_ACCEL_SCALE 16384.0f
Definition at line 46 of file mpu6050.c.
MPU6050_CAL_SAMPLES
#define MPU6050_CAL_SAMPLES 500
Definition at line 53 of file mpu6050.c.
MPU6050_CAL_VARIANCE_THRESH
#define MPU6050_CAL_VARIANCE_THRESH 0.1f
Definition at line 54 of file mpu6050.c.
MPU6050_DLPF_CFG_94HZ
#define MPU6050_DLPF_CFG_94HZ 0x02
Definition at line 42 of file mpu6050.c.
MPU6050_GYRO_FS_250
#define MPU6050_GYRO_FS_250 0x00
Definition at line 40 of file mpu6050.c.
MPU6050_GYRO_SCALE
#define MPU6050_GYRO_SCALE 131.0f
Definition at line 45 of file mpu6050.c.
MPU6050_HEALTH_CHECK_INTERVAL_MS
#define MPU6050_HEALTH_CHECK_INTERVAL_MS 100
Definition at line 55 of file mpu6050.c.
MPU6050_I2C_ADDR
#define MPU6050_I2C_ADDR 0x68
Definition at line 21 of file mpu6050.c.
MPU6050_I2C_ADDR_ALT
#define MPU6050_I2C_ADDR_ALT 0x69
Definition at line 22 of file mpu6050.c.
MPU6050_MAX_TEMP_C
#define MPU6050_MAX_TEMP_C 85.0f
Definition at line 51 of file mpu6050.c.
MPU6050_MIN_TEMP_C
#define MPU6050_MIN_TEMP_C -40.0f
Definition at line 52 of file mpu6050.c.
MPU6050_REG_ACCEL_CONFIG
#define MPU6050_REG_ACCEL_CONFIG 0x1C
Definition at line 31 of file mpu6050.c.
MPU6050_REG_ACCEL_XOUT_H
#define MPU6050_REG_ACCEL_XOUT_H 0x3B
Definition at line 34 of file mpu6050.c.
MPU6050_REG_CONFIG
#define MPU6050_REG_CONFIG 0x1A
Definition at line 29 of file mpu6050.c.
MPU6050_REG_GYRO_CONFIG
#define MPU6050_REG_GYRO_CONFIG 0x1B
Definition at line 30 of file mpu6050.c.
MPU6050_REG_GYRO_XOUT_H
#define MPU6050_REG_GYRO_XOUT_H 0x43
Definition at line 33 of file mpu6050.c.
MPU6050_REG_PWR_MGMT_1
#define MPU6050_REG_PWR_MGMT_1 0x6B
Definition at line 26 of file mpu6050.c.
MPU6050_REG_PWR_MGMT_2
#define MPU6050_REG_PWR_MGMT_2 0x6C
Definition at line 27 of file mpu6050.c.
MPU6050_REG_SMPRT_DIV
#define MPU6050_REG_SMPRT_DIV 0x19
Definition at line 28 of file mpu6050.c.
MPU6050_REG_TEMP_OUT_H
#define MPU6050_REG_TEMP_OUT_H 0x41
Definition at line 32 of file mpu6050.c.
MPU6050_REG_WHO_AM_I
#define MPU6050_REG_WHO_AM_I 0x75
Definition at line 25 of file mpu6050.c.
MPU6050_TEMP_OFFSET
#define MPU6050_TEMP_OFFSET 36.53f
Definition at line 48 of file mpu6050.c.
MPU6050_TEMP_SCALE
#define MPU6050_TEMP_SCALE 340.0f
Definition at line 47 of file mpu6050.c.
MPU6050_WHO_AM_I_VAL
#define MPU6050_WHO_AM_I_VAL 0x68
Definition at line 37 of file mpu6050.c.
Function Documentation
mpu6050_calibrate_level()
esp_err_t mpu6050_calibrate_level (mpu6050_t * dev, mpu6050_cal_callback_t callback, void * user_data)
Perform level calibration of MPU-6050.
Performs stationary level calibration to determine gyro and accelerometer biases. Device must be placed on a level surface and remain stationary during calibration.
Parameters
dev MPU-6050 device structure
callback Optional callback for progress updates (can be NULL)
user_data User data passed to callback
Returns
ESP_OK on success, ESP_ERR_INVALID_STATE if motion detected
Definition at line 231 of file mpu6050.c.
References mpu6050_calibration_t::accel_offset_x, mpu6050_calibration_t::accel_offset_y, mpu6050_calibration_t::accel_offset_z, mpu6050_raw_data_t::accel_x, mpu6050_raw_data_t::accel_y, mpu6050_raw_data_t::accel_z, mpu6050_t::cal, mpu6050_calibration_t::calibrated, mpu6050_calibration_t::gyro_offset_x, mpu6050_calibration_t::gyro_offset_y, mpu6050_calibration_t::gyro_offset_z, mpu6050_raw_data_t::gyro_x, mpu6050_raw_data_t::gyro_y, mpu6050_raw_data_t::gyro_z, mpu6050_t::health, mpu6050_t::initialized, mpu6050_t::last_error, MPU6050_CAL_STEP_COMPLETE, MPU6050_CAL_STEP_ERROR, MPU6050_CAL_STEP_SAMPLING, MPU6050_CAL_STEP_START, mpu6050_read_raw(), and mpu6050_calibration_t::timestamp.
mpu6050_get_health()
sensor_health_t mpu6050_get_health (mpu6050_t * dev)
Get current health status of MPU-6050.
Parameters
dev MPU-6050 device structure
Returns
Current sensor health status
Definition at line 342 of file mpu6050.c.
References mpu6050_t::health, and mpu6050_t::initialized.
mpu6050_get_instance()
mpu6050_t * mpu6050_get_instance (void)
Get global MPU-6050 instance.
Returns pointer to the global MPU-6050 instance if initialized.
Returns
Pointer to global instance or NULL if not initialized
Definition at line 360 of file mpu6050.c.
Referenced by blackbox_collect_evidence(), blackbox_log_sensor_summary(), and gcs_gateway_generate_tlm_status().
mpu6050_get_last_error()
const char * mpu6050_get_last_error (mpu6050_t * dev)
Get last error message.
Parameters
dev MPU-6050 device structure
Returns
Pointer to last error message string
Definition at line 351 of file mpu6050.c.
References mpu6050_t::last_error.
mpu6050_init()
esp_err_t mpu6050_init (mpu6050_t * dev)
Initialize MPU-6050 device.
Initializes I2C communication, configures the device for ±250°/s gyro and ±2g accel, performs self-test, and sets initial health status.
Parameters
dev MPU-6050 device structure to initialize
Returns
ESP_OK on success, error code otherwise
Definition at line 69 of file mpu6050.c.
References bus_io_init_i2c(), mpu6050_t::health, mpu6050_t::i2c_addr, mpu6050_t::initialized, and mpu6050_t::last_error.
mpu6050_read_raw()
esp_err_t mpu6050_read_raw (mpu6050_t * dev, mpu6050_raw_data_t * raw_data)
Read raw sensor data from MPU-6050.
Reads all sensor registers in a single I2C transaction for consistency. Updates device health status periodically.
Parameters
dev MPU-6050 device structure
raw_data Output buffer for raw sensor data
Returns
ESP_OK on success, error code otherwise
Definition at line 162 of file mpu6050.c.
References mpu6050_raw_data_t::accel_x, mpu6050_raw_data_t::accel_y, mpu6050_raw_data_t::accel_z, mpu6050_raw_data_t::gyro_x, mpu6050_raw_data_t::gyro_y, mpu6050_raw_data_t::gyro_z, mpu6050_t::health, mpu6050_t::initialized, mpu6050_t::last_error, mpu6050_raw_data_t::temp, and mpu6050_raw_data_t::timestamp.
Referenced by mpu6050_calibrate_level(), and mpu6050_read_scaled().
mpu6050_read_register()
esp_err_t mpu6050_read_register (uint8_t reg, uint8_t * value) static
Definition at line 376 of file mpu6050.c.
mpu6050_read_registers()
esp_err_t mpu6050_read_registers (uint8_t reg, uint8_t * data, size_t len) static
Definition at line 382 of file mpu6050.c.
mpu6050_read_scaled()
esp_err_t mpu6050_read_scaled (mpu6050_t * dev, mpu6050_data_t * data)
Read scaled sensor data from MPU-6050.
Reads raw data and applies calibration offsets and scaling factors.
Parameters
dev MPU-6050 device structure
data Output buffer for scaled sensor data
Returns
ESP_OK on success, error code otherwise
Definition at line 204 of file mpu6050.c.
References mpu6050_calibration_t::accel_offset_x, mpu6050_calibration_t::accel_offset_y, mpu6050_calibration_t::accel_offset_z, mpu6050_data_t::accel_x, mpu6050_raw_data_t::accel_x, mpu6050_data_t::accel_y, mpu6050_raw_data_t::accel_y, mpu6050_data_t::accel_z, mpu6050_raw_data_t::accel_z, mpu6050_t::cal, mpu6050_calibration_t::gyro_offset_x, mpu6050_calibration_t::gyro_offset_y, mpu6050_calibration_t::gyro_offset_z, mpu6050_data_t::gyro_x, mpu6050_raw_data_t::gyro_x, mpu6050_data_t::gyro_y, mpu6050_raw_data_t::gyro_y, mpu6050_data_t::gyro_z, mpu6050_raw_data_t::gyro_z, mpu6050_read_raw(), mpu6050_raw_data_t::temp, mpu6050_data_t::temperature, mpu6050_data_t::timestamp, and mpu6050_raw_data_t::timestamp.
Referenced by blackbox_collect_evidence(), blackbox_log_sensor_summary(), and gcs_gateway_generate_tlm_status().
mpu6050_self_test()
esp_err_t mpu6050_self_test (mpu6050_t * dev) static
Definition at line 417 of file mpu6050.c.
mpu6050_update_health()
void mpu6050_update_health (mpu6050_t * dev) static
Definition at line 388 of file mpu6050.c.
mpu6050_write_register()
esp_err_t mpu6050_write_register (uint8_t reg, uint8_t value) static
Definition at line 370 of file mpu6050.c.
Variable Documentation
g_initialized
bool g_initialized = false static
Definition at line 59 of file mpu6050.c.
g_last_health_check
uint32_t g_last_health_check = 0 static
Definition at line 60 of file mpu6050.c.
g_mpu6050
mpu6050_t g_mpu6050 = {0} static
Definition at line 58 of file mpu6050.c.
TAG
const char* TAG = "mpu6050" static
Definition at line 18 of file mpu6050.c.