ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/include/mpu6050.h File Reference
mpu6050.h File Reference
MPU-6050 IMU driver with health checks and calibration.
#include "scout_types.h"
#include "esp_err.h"
#include <stdbool.h>
#include <stdint.h>
Classes
struct mpu6050_raw_data_t
MPU-6050 raw sensor data structure.
struct mpu6050_data_t
MPU-6050 scaled sensor data structure.
struct mpu6050_calibration_t
MPU-6050 calibration data.
struct mpu6050_t
MPU-6050 device structure.
Typedefs
typedef void(* mpu6050_cal_callback_t) (mpu6050_cal_step_t step, const char *message, void *user_data)
Calibration callback function type.
Enumerations
enum mpu6050_cal_step_t { MPU6050_CAL_STEP_START , MPU6050_CAL_STEP_SAMPLING , MPU6050_CAL_STEP_COMPLETE , MPU6050_CAL_STEP_ERROR }
Calibration step enumeration for callback.
Functions
esp_err_t mpu6050_init (mpu6050_t *dev)
Initialize MPU-6050 device.
esp_err_t mpu6050_read_raw (mpu6050_t *dev, mpu6050_raw_data_t *raw_data)
Read raw sensor data from MPU-6050.
esp_err_t mpu6050_read_scaled (mpu6050_t *dev, mpu6050_data_t *data)
Read scaled sensor data from MPU-6050.
esp_err_t mpu6050_calibrate_level (mpu6050_t *dev, mpu6050_cal_callback_t callback, void *user_data)
Perform level calibration of MPU-6050.
sensor_health_t mpu6050_get_health (mpu6050_t *dev)
Get current health status of MPU-6050.
const char * mpu6050_get_last_error (mpu6050_t *dev)
Get last error message.
mpu6050_t * mpu6050_get_instance (void)
Get global MPU-6050 instance.
Detailed Description
MPU-6050 IMU driver with health checks and calibration.
Driver for MPU-6050 6-axis IMU providing gyroscope and accelerometer data with health monitoring and calibration support per Scout firmware requirements.
Definition in file mpu6050.h.
Typedef Documentation
mpu6050_cal_callback_t
typedef void(* mpu6050_cal_callback_t) (mpu6050_cal_step_t step, const char *message, void *user_data)
Calibration callback function type.
Parameters
step Current calibration step
message Human-readable message for operator
user_data User data passed to calibration function
Definition at line 78 of file mpu6050.h.
Enumeration Type Documentation
mpu6050_cal_step_t
enum mpu6050_cal_step_t
Calibration step enumeration for callback.
Enumerator
MPU6050_CAL_STEP_START
Calibration starting.
MPU6050_CAL_STEP_SAMPLING
Collecting samples.
MPU6050_CAL_STEP_COMPLETE
Calibration completed successfully.
MPU6050_CAL_STEP_ERROR
Calibration failed.
Definition at line 65 of file mpu6050.h.
Function Documentation
mpu6050_calibrate_level()
esp_err_t mpu6050_calibrate_level (mpu6050_t * dev, mpu6050_cal_callback_t callback, void * user_data)
Perform level calibration of MPU-6050.
Performs stationary level calibration to determine gyro and accelerometer biases. Device must be placed on a level surface and remain stationary during calibration.
Parameters
dev MPU-6050 device structure
callback Optional callback for progress updates (can be NULL)
user_data User data passed to callback
Returns
ESP_OK on success, ESP_ERR_INVALID_STATE if motion detected
Definition at line 231 of file mpu6050.c.
References mpu6050_calibration_t::accel_offset_x, mpu6050_calibration_t::accel_offset_y, mpu6050_calibration_t::accel_offset_z, mpu6050_raw_data_t::accel_x, mpu6050_raw_data_t::accel_y, mpu6050_raw_data_t::accel_z, mpu6050_t::cal, mpu6050_calibration_t::calibrated, mpu6050_calibration_t::gyro_offset_x, mpu6050_calibration_t::gyro_offset_y, mpu6050_calibration_t::gyro_offset_z, mpu6050_raw_data_t::gyro_x, mpu6050_raw_data_t::gyro_y, mpu6050_raw_data_t::gyro_z, mpu6050_t::health, mpu6050_t::initialized, mpu6050_t::last_error, MPU6050_CAL_STEP_COMPLETE, MPU6050_CAL_STEP_ERROR, MPU6050_CAL_STEP_SAMPLING, MPU6050_CAL_STEP_START, mpu6050_read_raw(), and mpu6050_calibration_t::timestamp.
mpu6050_get_health()
sensor_health_t mpu6050_get_health (mpu6050_t * dev)
Get current health status of MPU-6050.
Parameters
dev MPU-6050 device structure
Returns
Current sensor health status
Definition at line 342 of file mpu6050.c.
References mpu6050_t::health, and mpu6050_t::initialized.
mpu6050_get_instance()
mpu6050_t * mpu6050_get_instance (void)
Get global MPU-6050 instance.
Returns pointer to the global MPU-6050 instance if initialized.
Returns
Pointer to global instance or NULL if not initialized
Definition at line 360 of file mpu6050.c.
Referenced by blackbox_collect_evidence(), blackbox_log_sensor_summary(), and gcs_gateway_generate_tlm_status().
mpu6050_get_last_error()
const char * mpu6050_get_last_error (mpu6050_t * dev)
Get last error message.
Parameters
dev MPU-6050 device structure
Returns
Pointer to last error message string
Definition at line 351 of file mpu6050.c.
References mpu6050_t::last_error.
mpu6050_init()
esp_err_t mpu6050_init (mpu6050_t * dev)
Initialize MPU-6050 device.
Initializes I2C communication, configures the device for ±250°/s gyro and ±2g accel, performs self-test, and sets initial health status.
Parameters
dev MPU-6050 device structure to initialize
Returns
ESP_OK on success, error code otherwise
Definition at line 69 of file mpu6050.c.
References bus_io_init_i2c(), mpu6050_t::health, mpu6050_t::i2c_addr, mpu6050_t::initialized, and mpu6050_t::last_error.
mpu6050_read_raw()
esp_err_t mpu6050_read_raw (mpu6050_t * dev, mpu6050_raw_data_t * raw_data)
Read raw sensor data from MPU-6050.
Reads all sensor registers in a single I2C transaction for consistency. Updates device health status periodically.
Parameters
dev MPU-6050 device structure
raw_data Output buffer for raw sensor data
Returns
ESP_OK on success, error code otherwise
Definition at line 162 of file mpu6050.c.
References mpu6050_raw_data_t::accel_x, mpu6050_raw_data_t::accel_y, mpu6050_raw_data_t::accel_z, mpu6050_raw_data_t::gyro_x, mpu6050_raw_data_t::gyro_y, mpu6050_raw_data_t::gyro_z, mpu6050_t::health, mpu6050_t::initialized, mpu6050_t::last_error, mpu6050_raw_data_t::temp, and mpu6050_raw_data_t::timestamp.
Referenced by mpu6050_calibrate_level(), and mpu6050_read_scaled().
mpu6050_read_scaled()
esp_err_t mpu6050_read_scaled (mpu6050_t * dev, mpu6050_data_t * data)
Read scaled sensor data from MPU-6050.
Reads raw data and applies calibration offsets and scaling factors.
Parameters
dev MPU-6050 device structure
data Output buffer for scaled sensor data
Returns
ESP_OK on success, error code otherwise
Definition at line 204 of file mpu6050.c.
References mpu6050_calibration_t::accel_offset_x, mpu6050_calibration_t::accel_offset_y, mpu6050_calibration_t::accel_offset_z, mpu6050_data_t::accel_x, mpu6050_raw_data_t::accel_x, mpu6050_data_t::accel_y, mpu6050_raw_data_t::accel_y, mpu6050_data_t::accel_z, mpu6050_raw_data_t::accel_z, mpu6050_t::cal, mpu6050_calibration_t::gyro_offset_x, mpu6050_calibration_t::gyro_offset_y, mpu6050_calibration_t::gyro_offset_z, mpu6050_data_t::gyro_x, mpu6050_raw_data_t::gyro_x, mpu6050_data_t::gyro_y, mpu6050_raw_data_t::gyro_y, mpu6050_data_t::gyro_z, mpu6050_raw_data_t::gyro_z, mpu6050_read_raw(), mpu6050_raw_data_t::temp, mpu6050_data_t::temperature, mpu6050_data_t::timestamp, and mpu6050_raw_data_t::timestamp.
Referenced by blackbox_collect_evidence(), blackbox_log_sensor_summary(), and gcs_gateway_generate_tlm_status().