ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/include/neo6m.h File Reference
neo6m.h File Reference
NEO-6M GPS module driver with NMEA parser and fix state tracking.
#include "scout_types.h"
#include "esp_err.h"
#include <stdbool.h>
#include <stdint.h>
Classes
struct neo6m_position_t
GPS position data structure.
struct neo6m_t
NEO-6M device structure.
Enumerations
enum neo6m_fix_quality_t { NEO6M_FIX_NONE = 0 , NEO6M_FIX_GPS = 1 , NEO6M_FIX_DGPS = 2 }
GPS fix quality enumeration.
Functions
esp_err_t neo6m_init (neo6m_t *dev)
Initialize NEO-6M GPS module.
esp_err_t neo6m_update (neo6m_t *dev)
Update GPS data by processing incoming NMEA messages.
esp_err_t neo6m_get_position (neo6m_t *dev, neo6m_position_t *position)
Get current GPS position.
uint32_t neo6m_get_ttff_ms (neo6m_t *dev)
Get Time To First Fix (TTFF) in milliseconds.
sensor_health_t neo6m_get_health (neo6m_t *dev)
Get current health status of NEO-6M.
const char * neo6m_get_last_error (neo6m_t *dev)
Get last error message.
neo6m_t * neo6m_get_instance (void)
Get global NEO-6M instance.
Detailed Description
NEO-6M GPS module driver with NMEA parser and fix state tracking.
Driver for NEO-6M GPS module providing position data via NMEA parsing, fix state tracking, and TTFF (Time To First Fix) measurement.
Definition in file neo6m.h.
Enumeration Type Documentation
neo6m_fix_quality_t
enum neo6m_fix_quality_t
GPS fix quality enumeration.
Enumerator
NEO6M_FIX_NONE
No fix available.
NEO6M_FIX_GPS
GPS fix (SPS).
NEO6M_FIX_DGPS
DGPS fix.
Definition at line 23 of file neo6m.h.
Function Documentation
neo6m_get_health()
sensor_health_t neo6m_get_health (neo6m_t * dev)
Get current health status of NEO-6M.
Health status considers fix quality, satellite count, HDOP, and TTFF timeout.
Parameters
dev NEO-6M device structure
Returns
Current sensor health status
Definition at line 152 of file neo6m.c.
References neo6m_t::health, and neo6m_t::initialized.
neo6m_get_instance()
neo6m_t * neo6m_get_instance (void)
Get global NEO-6M instance.
Returns pointer to the global NEO-6M instance if initialized.
Returns
Pointer to global instance or NULL if not initialized
Definition at line 170 of file neo6m.c.
Referenced by blackbox_collect_evidence(), blackbox_log_sensor_summary(), and gcs_gateway_generate_tlm_status().
neo6m_get_last_error()
const char * neo6m_get_last_error (neo6m_t * dev)
Get last error message.
Parameters
dev NEO-6M device structure
Returns
Pointer to last error message string
Definition at line 161 of file neo6m.c.
References neo6m_t::last_error.
neo6m_get_position()
esp_err_t neo6m_get_position (neo6m_t * dev, neo6m_position_t * position)
Get current GPS position.
Returns the most recent valid GPS position if a fix is available.
Parameters
dev NEO-6M device structure
position Output buffer for position data
Returns
ESP_OK on success, ESP_ERR_NOT_FOUND if no fix available
Definition at line 118 of file neo6m.c.
References neo6m_t::fix_quality, neo6m_t::initialized, NEO6M_FIX_NONE, and neo6m_t::position.
neo6m_get_ttff_ms()
uint32_t neo6m_get_ttff_ms (neo6m_t * dev)
Get Time To First Fix (TTFF) in milliseconds.
Returns the time elapsed from GPS power-on to first valid fix. If no fix has been acquired yet, returns elapsed time since power-on.
Parameters
dev NEO-6M device structure
Returns
TTFF in milliseconds, or 0 if device not initialized
Definition at line 136 of file neo6m.c.
References neo6m_t::initialized.
neo6m_init()
esp_err_t neo6m_init (neo6m_t * dev)
Initialize NEO-6M GPS module.
Initializes UART communication for GPS module and sets up NMEA parsing. Begins TTFF (Time To First Fix) measurement from power-on.
Parameters
dev NEO-6M device structure to initialize
Returns
ESP_OK on success, error code otherwise
Definition at line 56 of file neo6m.c.
References bus_io_init_uart_gps(), neo6m_t::fix_quality, neo6m_t::hdop, neo6m_t::health, neo6m_t::initialized, neo6m_t::last_error, NEO6M_FIX_NONE, and neo6m_t::num_satellites.
neo6m_update()
esp_err_t neo6m_update (neo6m_t * dev)
Update GPS data by processing incoming NMEA messages.
Should be called regularly (e.g., in main loop) to process incoming UART data and update GPS position and status information.
Parameters
dev NEO-6M device structure
Returns
ESP_OK on success, error code otherwise
Definition at line 92 of file neo6m.c.
References neo6m_t::initialized.