ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/src/sensors/neo6m.c File Reference
neo6m.c File Reference
NEO-6M GPS module driver with NMEA parser and fix state tracking.
#include "neo6m.h"
#include "bus_io.h"
#include "scout_types.h"
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include <math.h>
#include <string.h>
#include <stdlib.h>
Macros
#define NEO6M_MAX_NMEA_LEN 82
#define NEO6M_NMEA_BUFFER_SIZE 128
#define NEO6M_MAX_FIELDS 20
#define NEO6M_MIN_SATELLITES 4
#define NEO6M_MAX_HDOP 5.0f
#define NEO6M_TTFF_TIMEOUT_MS 90000
#define NEO6M_FIX_TIMEOUT_MS 5000
#define NEO6M_HEALTH_CHECK_INTERVAL_MS 2000
#define NEO6M_MIN_UPDATE_RATE_HZ 0.5f
Functions
static esp_err_t neo6m_parse_nmea_sentence (const char *sentence, neo6m_t *dev)
static esp_err_t neo6m_parse_gga (const char *sentence, neo6m_t *dev)
static esp_err_t neo6m_parse_rmc (const char *sentence, neo6m_t *dev)
static esp_err_t neo6m_parse_gsa (const char *sentence, neo6m_t *dev)
static int neo6m_tokenize_nmea (const char *sentence, char *fields[], int max_fields)
static float neo6m_parse_coordinate (const char *coord_str, const char *direction)
static uint8_t neo6m_calculate_checksum (const char *sentence)
static void neo6m_update_health (neo6m_t *dev)
static void neo6m_process_uart_data (neo6m_t *dev)
esp_err_t neo6m_init (neo6m_t *dev)
Initialize NEO-6M GPS module.
esp_err_t neo6m_update (neo6m_t *dev)
Update GPS data by processing incoming NMEA messages.
esp_err_t neo6m_get_position (neo6m_t *dev, neo6m_position_t *position)
Get current GPS position.
uint32_t neo6m_get_ttff_ms (neo6m_t *dev)
Get Time To First Fix (TTFF) in milliseconds.
sensor_health_t neo6m_get_health (neo6m_t *dev)
Get current health status of NEO-6M.
const char * neo6m_get_last_error (neo6m_t *dev)
Get last error message.
neo6m_t * neo6m_get_instance (void)
Get global NEO-6M instance.
Variables
static const char * TAG = "neo6m"
static neo6m_t g_neo6m = {0}
static bool g_initialized = false
static uint32_t g_last_health_check = 0
static uint32_t g_power_on_time = 0
static uint32_t g_first_fix_time = 0
static char g_nmea_buffer [128]
static size_t g_buffer_pos = 0
Detailed Description
NEO-6M GPS module driver with NMEA parser and fix state tracking.
Implements UART communication with NEO-6M GPS module. Provides NMEA message parsing, fix state tracking, and TTFF measurement.
Definition in file neo6m.c.
Macro Definition Documentation
NEO6M_FIX_TIMEOUT_MS
#define NEO6M_FIX_TIMEOUT_MS 5000
Definition at line 30 of file neo6m.c.
NEO6M_HEALTH_CHECK_INTERVAL_MS
#define NEO6M_HEALTH_CHECK_INTERVAL_MS 2000
Definition at line 33 of file neo6m.c.
NEO6M_MAX_FIELDS
#define NEO6M_MAX_FIELDS 20
Definition at line 24 of file neo6m.c.
NEO6M_MAX_HDOP
#define NEO6M_MAX_HDOP 5.0f
Definition at line 28 of file neo6m.c.
NEO6M_MAX_NMEA_LEN
#define NEO6M_MAX_NMEA_LEN 82
Definition at line 22 of file neo6m.c.
NEO6M_MIN_SATELLITES
#define NEO6M_MIN_SATELLITES 4
Definition at line 27 of file neo6m.c.
NEO6M_MIN_UPDATE_RATE_HZ
#define NEO6M_MIN_UPDATE_RATE_HZ 0.5f
Definition at line 34 of file neo6m.c.
NEO6M_NMEA_BUFFER_SIZE
#define NEO6M_NMEA_BUFFER_SIZE 128
Definition at line 23 of file neo6m.c.
NEO6M_TTFF_TIMEOUT_MS
#define NEO6M_TTFF_TIMEOUT_MS 90000
Definition at line 29 of file neo6m.c.
Function Documentation
neo6m_calculate_checksum()
uint8_t neo6m_calculate_checksum (const char * sentence) static
Definition at line 381 of file neo6m.c.
neo6m_get_health()
sensor_health_t neo6m_get_health (neo6m_t * dev)
Get current health status of NEO-6M.
Health status considers fix quality, satellite count, HDOP, and TTFF timeout.
Parameters
dev NEO-6M device structure
Returns
Current sensor health status
Definition at line 152 of file neo6m.c.
References neo6m_t::health, and neo6m_t::initialized.
neo6m_get_instance()
neo6m_t * neo6m_get_instance (void)
Get global NEO-6M instance.
Returns pointer to the global NEO-6M instance if initialized.
Returns
Pointer to global instance or NULL if not initialized
Definition at line 170 of file neo6m.c.
Referenced by blackbox_collect_evidence(), blackbox_log_sensor_summary(), and gcs_gateway_generate_tlm_status().
neo6m_get_last_error()
const char * neo6m_get_last_error (neo6m_t * dev)
Get last error message.
Parameters
dev NEO-6M device structure
Returns
Pointer to last error message string
Definition at line 161 of file neo6m.c.
References neo6m_t::last_error.
neo6m_get_position()
esp_err_t neo6m_get_position (neo6m_t * dev, neo6m_position_t * position)
Get current GPS position.
Returns the most recent valid GPS position if a fix is available.
Parameters
dev NEO-6M device structure
position Output buffer for position data
Returns
ESP_OK on success, ESP_ERR_NOT_FOUND if no fix available
Definition at line 118 of file neo6m.c.
References neo6m_t::fix_quality, neo6m_t::initialized, NEO6M_FIX_NONE, and neo6m_t::position.
neo6m_get_ttff_ms()
uint32_t neo6m_get_ttff_ms (neo6m_t * dev)
Get Time To First Fix (TTFF) in milliseconds.
Returns the time elapsed from GPS power-on to first valid fix. If no fix has been acquired yet, returns elapsed time since power-on.
Parameters
dev NEO-6M device structure
Returns
TTFF in milliseconds, or 0 if device not initialized
Definition at line 136 of file neo6m.c.
References neo6m_t::initialized.
neo6m_init()
esp_err_t neo6m_init (neo6m_t * dev)
Initialize NEO-6M GPS module.
Initializes UART communication for GPS module and sets up NMEA parsing. Begins TTFF (Time To First Fix) measurement from power-on.
Parameters
dev NEO-6M device structure to initialize
Returns
ESP_OK on success, error code otherwise
Definition at line 56 of file neo6m.c.
References bus_io_init_uart_gps(), neo6m_t::fix_quality, neo6m_t::hdop, neo6m_t::health, neo6m_t::initialized, neo6m_t::last_error, NEO6M_FIX_NONE, and neo6m_t::num_satellites.
neo6m_parse_coordinate()
float neo6m_parse_coordinate (const char * coord_str, const char * direction) static
Definition at line 360 of file neo6m.c.
neo6m_parse_gga()
esp_err_t neo6m_parse_gga (const char * sentence, neo6m_t * dev) static
Definition at line 254 of file neo6m.c.
neo6m_parse_gsa()
esp_err_t neo6m_parse_gsa (const char * sentence, neo6m_t * dev) static
Definition at line 326 of file neo6m.c.
neo6m_parse_nmea_sentence()
esp_err_t neo6m_parse_nmea_sentence (const char * sentence, neo6m_t * dev) static
Definition at line 222 of file neo6m.c.
neo6m_parse_rmc()
esp_err_t neo6m_parse_rmc (const char * sentence, neo6m_t * dev) static
Definition at line 305 of file neo6m.c.
neo6m_process_uart_data()
void neo6m_process_uart_data (neo6m_t * dev) static
Definition at line 180 of file neo6m.c.
neo6m_tokenize_nmea()
int neo6m_tokenize_nmea (const char * sentence, char * fields[], int max_fields) static
Definition at line 343 of file neo6m.c.
neo6m_update()
esp_err_t neo6m_update (neo6m_t * dev)
Update GPS data by processing incoming NMEA messages.
Should be called regularly (e.g., in main loop) to process incoming UART data and update GPS position and status information.
Parameters
dev NEO-6M device structure
Returns
ESP_OK on success, error code otherwise
Definition at line 92 of file neo6m.c.
References neo6m_t::initialized.
neo6m_update_health()
void neo6m_update_health (neo6m_t * dev) static
Definition at line 393 of file neo6m.c.
Variable Documentation
g_buffer_pos
size_t g_buffer_pos = 0 static
Definition at line 43 of file neo6m.c.
g_first_fix_time
uint32_t g_first_fix_time = 0 static
Definition at line 41 of file neo6m.c.
g_initialized
bool g_initialized = false static
Definition at line 38 of file neo6m.c.
g_last_health_check
uint32_t g_last_health_check = 0 static
Definition at line 39 of file neo6m.c.
g_neo6m
neo6m_t g_neo6m = {0} static
Definition at line 37 of file neo6m.c.
g_nmea_buffer
char g_nmea_buffer[128] static
Definition at line 42 of file neo6m.c.
g_power_on_time
uint32_t g_power_on_time = 0 static
Definition at line 40 of file neo6m.c.
TAG
const char* TAG = "neo6m" static
Definition at line 19 of file neo6m.c.