ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/tests/integration/scp_protocol_test.c File Reference
scp_protocol_test.c File Reference
Integration Tests for SCP Protocol Implementation.
#include "unity.h"
#include "gcs_gateway.h"
#include "scp_protocol.h"
#include "scp_session.h"
#include "scp_crypto.h"
#include "scp_framer.h"
#include "safety_manager.h"
#include "mode_manager.h"
#include "esp_timer.h"
#include <string.h>
#include <stdio.h>
Functions
static bool mock_transport_send (const uint8_t *data, size_t size)
Mock transport layer for capturing responses This replaces the actual transport during testing.
static bool send_test_command (scp_control_action_t cmd_type, flight_mode_t flight_mode, bool emergency)
Create and send a test command message.
static bool wait_for_response (scp_message_type_t expected_type, uint32_t timeout_ms)
Wait for response and verify type.
void setUp (void)
void tearDown (void)
void test_integration_arm_command_success (void)
Test successful ARM command processing.
void test_integration_disarm_command_success (void)
Test successful DISARM command processing.
void test_integration_emergency_disarm (void)
Test emergency DISARM command.
void test_integration_mode_change_command (void)
Test mode change command.
void test_integration_arm_safety_rejection (void)
Test ARM command rejected by safety manager.
void test_integration_invalid_mode_change (void)
Test invalid mode change request.
void test_integration_role_based_authorization (void)
Test command authorization with different roles.
void test_integration_processing_timing (void)
Test command processing timing requirements.
void test_integration_rapid_commands (void)
Test multiple rapid commands (stress test).
void app_main (void)
Variables
static bool integration_test_initialized = false
Integration test configuration and state.
static uint32_t test_session_id = 0
static uint8_t test_auth_key [SCP_SESSION_KEY_SIZE]
static uint8_t test_tx_buffer [SCP_MAX_FRAME_SIZE]
static uint8_t test_rx_buffer [SCP_MAX_FRAME_SIZE]
static bool response_received = false
static scp_message_type_t last_response_type = SCP_MSG_INVALID
static uint8_t last_response_payload [SCP_MAX_PAYLOAD_SIZE]
static size_t last_response_size = 0
Detailed Description
Integration Tests for SCP Protocol Implementation.
Tests end-to-end command processing for Secure Control Protocol (SCP) v1.1, validating the complete flow from message reception through command execution and response generation.
Test Coverage:
Basic ARM/DISARM command processing
Mode change operations
Response generation (ACK/ERR)
Safety manager integration
Role-based authorization
Protocol timing requirements (<100ms)
Error handling scenarios
Author
Scout ISR Project
Version
1.1
Date
2025-10-26
Definition in file scp_protocol_test.c.
Function Documentation
app_main()
void app_main (void)
Definition at line 517 of file scp_protocol_test.c.
mock_transport_send()
bool mock_transport_send (const uint8_t * data, size_t size) static
Mock transport layer for capturing responses This replaces the actual transport during testing.
Definition at line 61 of file scp_protocol_test.c.
References scp_framer_decode().
send_test_command()
bool send_test_command (scp_control_action_t cmd_type, flight_mode_t flight_mode, bool emergency) static
Create and send a test command message.
Parameters
cmd_type Command control action
flight_mode Target flight mode
emergency Emergency flag
Returns
true if message sent successfully
Definition at line 93 of file scp_protocol_test.c.
References scp_framer_encode().
Referenced by test_integration_arm_command_success(), test_integration_arm_safety_rejection(), test_integration_disarm_command_success(), test_integration_emergency_disarm(), test_integration_mode_change_command(), test_integration_processing_timing(), and test_integration_rapid_commands().
setUp()
void setUp (void)
Definition at line 161 of file scp_protocol_test.c.
tearDown()
void tearDown (void)
Definition at line 207 of file scp_protocol_test.c.
test_integration_arm_command_success()
void test_integration_arm_command_success (void)
Test successful ARM command processing.
Definition at line 227 of file scp_protocol_test.c.
References send_test_command(), and wait_for_response().
test_integration_arm_safety_rejection()
void test_integration_arm_safety_rejection (void)
Test ARM command rejected by safety manager.
Definition at line 339 of file scp_protocol_test.c.
References gcs_gateway_get_stats(), send_test_command(), and wait_for_response().
test_integration_disarm_command_success()
void test_integration_disarm_command_success (void)
Test successful DISARM command processing.
Definition at line 257 of file scp_protocol_test.c.
References send_test_command(), and wait_for_response().
test_integration_emergency_disarm()
void test_integration_emergency_disarm (void)
Test emergency DISARM command.
Definition at line 284 of file scp_protocol_test.c.
References gcs_gateway_get_stats(), send_test_command(), and wait_for_response().
test_integration_invalid_mode_change()
void test_integration_invalid_mode_change (void)
Test invalid mode change request.
Definition at line 374 of file scp_protocol_test.c.
References wait_for_response().
test_integration_mode_change_command()
void test_integration_mode_change_command (void)
Test mode change command.
Definition at line 309 of file scp_protocol_test.c.
References gcs_gateway_get_stats(), send_test_command(), and wait_for_response().
test_integration_processing_timing()
void test_integration_processing_timing (void)
Test command processing timing requirements.
Definition at line 453 of file scp_protocol_test.c.
References send_test_command(), and wait_for_response().
test_integration_rapid_commands()
void test_integration_rapid_commands (void)
Test multiple rapid commands (stress test).
Definition at line 480 of file scp_protocol_test.c.
References gcs_gateway_get_stats(), send_test_command(), and wait_for_response().
test_integration_role_based_authorization()
void test_integration_role_based_authorization (void)
Test command authorization with different roles.
Definition at line 404 of file scp_protocol_test.c.
References gcs_gateway_get_stats(), scp_session_close(), scp_session_create(), and wait_for_response().
wait_for_response()
bool wait_for_response (scp_message_type_t expected_type, uint32_t timeout_ms) static
Wait for response and verify type.
Parameters
expected_type Expected response message type
timeout_ms Timeout in milliseconds
Returns
true if expected response received
Definition at line 141 of file scp_protocol_test.c.
Referenced by test_integration_arm_command_success(), test_integration_arm_safety_rejection(), test_integration_disarm_command_success(), test_integration_emergency_disarm(), test_integration_invalid_mode_change(), test_integration_mode_change_command(), test_integration_processing_timing(), test_integration_rapid_commands(), and test_integration_role_based_authorization().
Variable Documentation
integration_test_initialized
bool integration_test_initialized = false static
Integration test configuration and state.
Definition at line 39 of file scp_protocol_test.c.
last_response_payload
uint8_t last_response_payload[SCP_MAX_PAYLOAD_SIZE] static
Definition at line 50 of file scp_protocol_test.c.
last_response_size
size_t last_response_size = 0 static
Definition at line 51 of file scp_protocol_test.c.
last_response_type
scp_message_type_t last_response_type = SCP_MSG_INVALID static
Definition at line 49 of file scp_protocol_test.c.
response_received
bool response_received = false static
Definition at line 48 of file scp_protocol_test.c.
test_auth_key
uint8_t test_auth_key[SCP_SESSION_KEY_SIZE] static
Definition at line 41 of file scp_protocol_test.c.
test_rx_buffer
uint8_t test_rx_buffer[SCP_MAX_FRAME_SIZE] static
Definition at line 45 of file scp_protocol_test.c.
test_session_id
uint32_t test_session_id = 0 static
Definition at line 40 of file scp_protocol_test.c.
test_tx_buffer
uint8_t test_tx_buffer[SCP_MAX_FRAME_SIZE] static
Definition at line 44 of file scp_protocol_test.c.