ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/include/scp_framer.h File Reference
scp_framer.h File Reference
Public API for SCP framing (COBS) and CRC utilities.
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "scp_protocol.h"
Functions
bool scp_framer_init (void)
Initialize SCP Framing Subsystem.
bool scp_framer_encode (const scp_frame_header_t *header, const uint8_t *payload, uint16_t payload_len, const uint8_t *auth_tag, uint8_t *frame_out, uint16_t frame_len_max, uint16_t *frame_len_out)
Encode SCP Frame with COBS Framing.
bool scp_framer_decode (const uint8_t *frame_in, uint16_t frame_len, scp_frame_header_t *header_out, uint8_t *payload_out, uint16_t payload_len_max, uint16_t *payload_len_out, uint8_t *auth_tag_out)
Decode SCP Frame from COBS Encoding.
bool scp_framer_validate_crc (const uint8_t *frame_data, uint16_t frame_len)
Validate Frame CRC.
uint16_t scp_framer_calculate_crc (const uint8_t *frame_data, uint16_t frame_len)
Calculate Frame CRC.
uint16_t scp_framer_get_overhead (uint16_t payload_len, bool has_auth)
Get Frame Overhead Size.
Detailed Description
Public API for SCP framing (COBS) and CRC utilities.
Provides encode/decode helpers for SCP frames using:
Fixed header defined in scp_protocol.h
Optional auth tag (SCP_AUTH_TAG_SIZE)
CRC-16-CCITT trailer
COBS outer framing (zero-terminated)
Definition in file scp_framer.h.
Function Documentation
scp_framer_calculate_crc()
uint16_t scp_framer_calculate_crc (const uint8_t * frame_data, uint16_t frame_len)
Calculate Frame CRC.
Parameters
frame_data Frame data (without CRC)
frame_len Frame length (without CRC)
Returns
Calculated CRC-16 value
Definition at line 584 of file scp_framer.c.
References crc16_ccitt_calculate().
scp_framer_decode()
bool scp_framer_decode (const uint8_t * frame_in, uint16_t frame_len, scp_frame_header_t * header_out, uint8_t * payload_out, uint16_t payload_len_max, uint16_t * payload_len_out, uint8_t * auth_tag_out)
Decode SCP Frame from COBS Encoding.
Parameters
frame_in Encoded frame buffer
frame_len Encoded frame length
header_out Output: decoded frame header
payload_out Output buffer for payload (can be NULL if not needed)
payload_len_max Maximum payload buffer size
payload_len_out Output: actual payload length
auth_tag_out Output buffer for auth tag (can be NULL if not needed)
Returns
true if decoding successful, false on error
Definition at line 460 of file scp_framer.c.
References cobs_decode(), crc16_ccitt_calculate(), SCP_HAS_AUTH, and validate_frame_header().
Referenced by cmd_scp_selftest(), and mock_transport_send().
scp_framer_encode()
bool scp_framer_encode (const scp_frame_header_t * header, const uint8_t * payload, uint16_t payload_len, const uint8_t * auth_tag, uint8_t * frame_out, uint16_t frame_len_max, uint16_t * frame_len_out)
Encode SCP Frame with COBS Framing.
Parameters
header Frame header
payload Payload data (can be NULL if payload_len is 0)
payload_len Payload length
auth_tag Authentication tag (can be NULL if not present)
frame_out Output buffer for encoded frame
frame_len_max Maximum frame buffer size
frame_len_out Output: actual encoded frame length
Returns
true if encoding successful, false on error
Definition at line 345 of file scp_framer.c.
References cobs_encode(), crc16_ccitt_calculate(), SCP_HAS_AUTH, and validate_frame_header().
Referenced by cmd_scp_selftest(), gcs_gateway_send_audit(), gcs_gateway_send_audit_event(), gcs_gateway_send_response(), gcs_gateway_send_tlm_status_targeted(), and send_test_command().
scp_framer_get_overhead()
uint16_t scp_framer_get_overhead (uint16_t payload_len, bool has_auth)
Get Frame Overhead Size.
Calculates the total overhead bytes added by SCP framing.
Parameters
payload_len Payload length
has_auth Whether authentication tag is present
Returns
Total overhead bytes (header + auth + crc + cobs)
Definition at line 603 of file scp_framer.c.
scp_framer_init()
bool scp_framer_init (void)
Initialize SCP Framing Subsystem.
Returns
true if initialization successful
Definition at line 316 of file scp_framer.c.
References crc16_ccitt_calculate().
Referenced by cmd_scp_selftest(), and gcs_gateway_init().
scp_framer_validate_crc()
bool scp_framer_validate_crc (const uint8_t * frame_data, uint16_t frame_len)
Validate Frame CRC.
Parameters
frame_data Raw frame data (after COBS decoding)
frame_len Frame length including CRC
Returns
true if CRC is valid, false otherwise
Definition at line 563 of file scp_framer.c.
References crc16_ccitt_calculate().