ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/src/services/scp_constants.c File Reference
scp_constants.c File Reference
SCP Protocol Constants and Error Code Definitions.
#include "scp_protocol.h"
#include "scp_session.h"
#include "esp_log.h"
#include <arpa/inet.h>
Functions
const char * scp_error_to_string (uint8_t error_code)
Convert SCP error code to human-readable string.
const char * scp_result_to_string (uint8_t result_code)
Convert SCP result code to human-readable string.
const char * scp_message_type_to_string (uint8_t msg_type)
Convert SCP message type to human-readable string.
const char * scp_action_to_string (uint8_t action)
Convert SCP action type to human-readable string.
const char * scp_mode_to_string (uint8_t mode)
Convert SCP flight mode to human-readable string.
const char * scp_priority_to_string (uint8_t priority)
Convert SCP priority to human-readable string.
const char * scp_audit_event_to_string (uint8_t event_type)
Convert audit event type to human-readable string.
const char * scp_config_type_to_string (uint8_t config_type)
Convert configuration type to human-readable string.
bool scp_is_valid_message_type (uint8_t msg_type)
Validate SCP message type.
bool scp_is_command_message (uint8_t msg_type)
Check if message type is a command.
bool scp_is_telemetry_message (uint8_t msg_type)
Check if message type is telemetry.
bool scp_is_response_message (uint8_t msg_type)
Check if message type is a response.
bool scp_is_valid_role (uint8_t role)
Validate SCP operator role.
bool scp_is_valid_connection_type (uint8_t conn_type)
Validate SCP connection type.
bool scp_is_valid_priority (uint8_t priority)
Validate SCP priority level.
bool scp_is_valid_action (uint8_t action)
Validate SCP action type.
bool scp_is_valid_mode (uint8_t mode)
Validate SCP flight mode.
uint16_t scp_get_expected_payload_size (uint8_t msg_type)
Get expected payload size for message type.
bool scp_has_fixed_payload_size (uint8_t msg_type)
Check if message type has fixed payload size.
bool scp_validate_frame_limits (const scp_frame_header_t *header)
Validate frame header constraints.
uint16_t scp_get_max_frame_size (uint16_t payload_size, bool has_auth)
Get maximum frame size for given payload.
uint32_t scp_get_expected_processing_time_us (uint8_t msg_type)
Get expected processing time for message type.
bool scp_is_processing_time_acceptable (uint8_t msg_type, uint32_t actual_time_us)
Check if processing time is within acceptable limits.
bool scp_constants_init (void)
Initialize SCP constants subsystem.
void scp_log_protocol_info (void)
Log protocol configuration summary.
Variables
static const char * TAG = "scp_constants"
Detailed Description
SCP Protocol Constants and Error Code Definitions.
Provides constant definitions, error code mappings, and utility functions for the Secure Control Protocol (SCP) v1.1.
Author
Scout ISR Project
Version
1.1
Date
2025-10-26
Definition in file scp_constants.c.
Function Documentation
scp_action_to_string()
const char * scp_action_to_string (uint8_t action)
Convert SCP action type to human-readable string.
Parameters
action SCP action code (SCP_ACTION_*)
Returns
Action description string
Definition at line 123 of file scp_constants.c.
scp_audit_event_to_string()
const char * scp_audit_event_to_string (uint8_t event_type)
Convert audit event type to human-readable string.
Parameters
event_type SCP audit event type (SCP_AUDIT_*)
Returns
Event type description string
Definition at line 188 of file scp_constants.c.
scp_config_type_to_string()
const char * scp_config_type_to_string (uint8_t config_type)
Convert configuration type to human-readable string.
Parameters
config_type SCP config type (SCP_CONFIG_*)
Returns
Configuration type description string
Definition at line 211 of file scp_constants.c.
scp_constants_init()
bool scp_constants_init (void)
Initialize SCP constants subsystem.
Performs any required initialization for the constants module. Currently just validates critical constants.
Returns
true if initialization successful
Definition at line 542 of file scp_constants.c.
scp_error_to_string()
const char * scp_error_to_string (uint8_t error_code)
Convert SCP error code to human-readable string.
Parameters
error_code SCP error code (SCP_ERR_*)
Returns
Error description string
Definition at line 30 of file scp_constants.c.
scp_get_expected_payload_size()
uint16_t scp_get_expected_payload_size (uint8_t msg_type)
Get expected payload size for message type.
Parameters
msg_type SCP message type
Returns
Expected payload size in bytes, 0 if invalid/variable
Definition at line 356 of file scp_constants.c.
Referenced by scp_has_fixed_payload_size().
scp_get_expected_processing_time_us()
uint32_t scp_get_expected_processing_time_us (uint8_t msg_type)
Get expected processing time for message type.
Performance targets for different message types to ensure real-time constraints are met.
Parameters
msg_type SCP message type
Returns
Expected processing time in microseconds
Definition at line 490 of file scp_constants.c.
Referenced by scp_is_processing_time_acceptable().
scp_get_max_frame_size()
uint16_t scp_get_max_frame_size (uint16_t payload_size, bool has_auth)
Get maximum frame size for given payload.
Parameters
payload_size Payload size in bytes
has_auth Whether authentication tag is present
Returns
Maximum encoded frame size including all overhead
Definition at line 462 of file scp_constants.c.
scp_has_fixed_payload_size()
bool scp_has_fixed_payload_size (uint8_t msg_type)
Check if message type has fixed payload size.
Parameters
msg_type SCP message type
Returns
true if fixed size, false if variable
Definition at line 389 of file scp_constants.c.
References scp_get_expected_payload_size().
scp_is_command_message()
bool scp_is_command_message (uint8_t msg_type)
Check if message type is a command.
Parameters
msg_type Message type to check
Returns
true if command message, false otherwise
Definition at line 261 of file scp_constants.c.
scp_is_processing_time_acceptable()
bool scp_is_processing_time_acceptable (uint8_t msg_type, uint32_t actual_time_us)
Check if processing time is within acceptable limits.
Parameters
msg_type Message type
actual_time_us Actual processing time in microseconds
Returns
true if within limits, false if exceeded
Definition at line 522 of file scp_constants.c.
References scp_get_expected_processing_time_us().
scp_is_response_message()
bool scp_is_response_message (uint8_t msg_type)
Check if message type is a response.
Parameters
msg_type Message type to check
Returns
true if response message, false otherwise
Definition at line 283 of file scp_constants.c.
scp_is_telemetry_message()
bool scp_is_telemetry_message (uint8_t msg_type)
Check if message type is telemetry.
Parameters
msg_type Message type to check
Returns
true if telemetry message, false otherwise
Definition at line 272 of file scp_constants.c.
scp_is_valid_action()
bool scp_is_valid_action (uint8_t action)
Validate SCP action type.
Parameters
action Action type to validate
Returns
true if valid action, false otherwise
Definition at line 330 of file scp_constants.c.
scp_is_valid_connection_type()
bool scp_is_valid_connection_type (uint8_t conn_type)
Validate SCP connection type.
Parameters
conn_type Connection type to validate
Returns
true if valid connection type, false otherwise
Definition at line 306 of file scp_constants.c.
scp_is_valid_message_type()
bool scp_is_valid_message_type (uint8_t msg_type)
Validate SCP message type.
Parameters
msg_type Message type to validate
Returns
true if valid, false otherwise
Definition at line 236 of file scp_constants.c.
Referenced by scp_validate_frame_limits().
scp_is_valid_mode()
bool scp_is_valid_mode (uint8_t mode)
Validate SCP flight mode.
Parameters
mode Flight mode to validate
Returns
true if valid mode, false otherwise
Definition at line 341 of file scp_constants.c.
scp_is_valid_priority()
bool scp_is_valid_priority (uint8_t priority)
Validate SCP priority level.
Parameters
priority Priority level to validate
Returns
true if valid priority, false otherwise
Definition at line 318 of file scp_constants.c.
Referenced by scp_validate_frame_limits().
scp_is_valid_role()
bool scp_is_valid_role (uint8_t role)
Validate SCP operator role.
Parameters
role Role to validate
Returns
true if valid role, false otherwise
Definition at line 294 of file scp_constants.c.
scp_log_protocol_info()
void scp_log_protocol_info (void)
Log protocol configuration summary.
Logs key protocol parameters for verification during initialization.
Definition at line 570 of file scp_constants.c.
scp_message_type_to_string()
const char * scp_message_type_to_string (uint8_t msg_type)
Convert SCP message type to human-readable string.
Parameters
msg_type SCP message type (SCP_CMD_*, SCP_TLM_*, etc.)
Returns
Message type description string
Definition at line 84 of file scp_constants.c.
scp_mode_to_string()
const char * scp_mode_to_string (uint8_t mode)
Convert SCP flight mode to human-readable string.
Parameters
mode SCP mode code (SCP_MODE_*)
Returns
Mode description string
Definition at line 144 of file scp_constants.c.
scp_priority_to_string()
const char * scp_priority_to_string (uint8_t priority)
Convert SCP priority to human-readable string.
Parameters
priority SCP priority level (SCP_PRIORITY_*)
Returns
Priority description string
Definition at line 165 of file scp_constants.c.
scp_result_to_string()
const char * scp_result_to_string (uint8_t result_code)
Convert SCP result code to human-readable string.
Parameters
result_code SCP result code (SCP_RESULT_*)
Returns
Result description string
Definition at line 63 of file scp_constants.c.
scp_validate_frame_limits()
bool scp_validate_frame_limits (const scp_frame_header_t * header)
Validate frame header constraints.
Parameters
header Frame header to validate
Returns
true if within protocol limits, false otherwise
Definition at line 404 of file scp_constants.c.
References SCP_GET_PRIORITY, scp_is_valid_message_type(), and scp_is_valid_priority().
Variable Documentation
TAG
const char* TAG = "scp_constants" static
Definition at line 18 of file scp_constants.c.