ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/src/services/scp_nvs.c File Reference
scp_nvs.c File Reference
SCP NVS Storage Integration.
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "nvs_flash.h"
#include "nvs.h"
#include "scp_protocol.h"
#include "scp_session.h"
#include "scp_nvs.h"
Classes
struct scp_config_t
Macros
#define SCP_NVS_NAMESPACE "scp_config"
#define SCP_NVS_KEY_TELEMETRY_RATE "tlm_rate"
#define SCP_NVS_KEY_SESSION_TIMEOUT "sess_timeout"
#define SCP_NVS_KEY_RATE_LIMIT_SUSTAINED "rate_sust"
#define SCP_NVS_KEY_RATE_LIMIT_BURST "rate_burst"
#define SCP_NVS_KEY_DEBUG_ENABLED "debug_en"
#define SCP_NVS_KEY_PROTOCOL_VERSION "proto_ver"
#define SCP_NVS_KEY_CONFIG_CHECKSUM "cfg_crc"
Functions
static void init_default_config (scp_config_t *config)
Initialize configuration with safe defaults.
static uint32_t calculate_config_checksum (const scp_config_t *config)
Calculate configuration checksum for integrity verification.
static bool validate_config (const scp_config_t *config)
Validate configuration parameters.
bool scp_nvs_init (void)
Initialize NVS storage for SCP configuration.
bool scp_nvs_load_config (void)
Load SCP configuration from NVS.
bool scp_nvs_save_config (void)
Save SCP configuration to NVS.
bool scp_nvs_reset_config (void)
Reset configuration to defaults and save.
uint8_t scp_nvs_get_telemetry_rate (void)
Get current telemetry rate.
bool scp_nvs_set_telemetry_rate (uint8_t rate_hz)
Set telemetry rate.
uint32_t scp_nvs_get_session_timeout (void)
Get current session timeout.
bool scp_nvs_set_session_timeout (uint32_t timeout_ms)
Set session timeout.
uint8_t scp_nvs_get_rate_limit_sustained (void)
Get sustained rate limit.
bool scp_nvs_set_rate_limit_sustained (uint8_t rate_cps)
Set sustained rate limit.
uint8_t scp_nvs_get_rate_limit_burst (void)
Get burst rate limit.
bool scp_nvs_set_rate_limit_burst (uint8_t rate_cps)
Set burst rate limit.
bool scp_nvs_get_debug_logging (void)
Get debug logging state.
bool scp_nvs_set_debug_logging (bool enabled)
Set debug logging state.
uint8_t scp_nvs_get_protocol_version (void)
Get protocol version.
void scp_nvs_dump_config (void)
Log current configuration.
const scp_config_t * scp_nvs_get_config (void)
Get configuration as read-only structure.
bool scp_nvs_validate_storage (void)
Validate NVS storage integrity.
bool scp_nvs_erase_all (void)
Erase all SCP configuration from NVS.
Variables
static const char * TAG = "scp_nvs"
static scp_config_t current_config
static nvs_handle_t config_nvs_handle
static bool nvs_initialized = false
Detailed Description
SCP NVS Storage Integration.
Provides NVS storage integration for SCP session keys, configuration, and persistent state management.
Author
Scout ISR Project
Version
1.1
Date
2025-10-26
Definition in file scp_nvs.c.
Macro Definition Documentation
SCP_NVS_KEY_CONFIG_CHECKSUM
#define SCP_NVS_KEY_CONFIG_CHECKSUM "cfg_crc"
Definition at line 36 of file scp_nvs.c.
SCP_NVS_KEY_DEBUG_ENABLED
#define SCP_NVS_KEY_DEBUG_ENABLED "debug_en"
Definition at line 34 of file scp_nvs.c.
SCP_NVS_KEY_PROTOCOL_VERSION
#define SCP_NVS_KEY_PROTOCOL_VERSION "proto_ver"
Definition at line 35 of file scp_nvs.c.
SCP_NVS_KEY_RATE_LIMIT_BURST
#define SCP_NVS_KEY_RATE_LIMIT_BURST "rate_burst"
Definition at line 33 of file scp_nvs.c.
SCP_NVS_KEY_RATE_LIMIT_SUSTAINED
#define SCP_NVS_KEY_RATE_LIMIT_SUSTAINED "rate_sust"
Definition at line 32 of file scp_nvs.c.
SCP_NVS_KEY_SESSION_TIMEOUT
#define SCP_NVS_KEY_SESSION_TIMEOUT "sess_timeout"
Definition at line 31 of file scp_nvs.c.
SCP_NVS_KEY_TELEMETRY_RATE
#define SCP_NVS_KEY_TELEMETRY_RATE "tlm_rate"
Definition at line 30 of file scp_nvs.c.
SCP_NVS_NAMESPACE
#define SCP_NVS_NAMESPACE "scp_config"
Definition at line 29 of file scp_nvs.c.
Function Documentation
calculate_config_checksum()
uint32_t calculate_config_checksum (const scp_config_t * config) static
Calculate configuration checksum for integrity verification.
Definition at line 77 of file scp_nvs.c.
Referenced by scp_nvs_erase_all(), scp_nvs_init(), scp_nvs_reset_config(), scp_nvs_save_config(), and validate_config().
init_default_config()
void init_default_config (scp_config_t * config) static
Initialize configuration with safe defaults.
Definition at line 62 of file scp_nvs.c.
Referenced by scp_nvs_erase_all(), scp_nvs_init(), and scp_nvs_reset_config().
scp_nvs_dump_config()
void scp_nvs_dump_config (void)
Log current configuration.
Definition at line 460 of file scp_nvs.c.
scp_nvs_erase_all()
bool scp_nvs_erase_all (void)
Erase all SCP configuration from NVS.
Definition at line 528 of file scp_nvs.c.
References calculate_config_checksum(), and init_default_config().
scp_nvs_get_config()
const scp_config_t * scp_nvs_get_config (void)
Get configuration as read-only structure.
Definition at line 484 of file scp_nvs.c.
scp_nvs_get_debug_logging()
bool scp_nvs_get_debug_logging (void)
Get debug logging state.
Definition at line 426 of file scp_nvs.c.
scp_nvs_get_protocol_version()
uint8_t scp_nvs_get_protocol_version (void)
Get protocol version.
Definition at line 448 of file scp_nvs.c.
scp_nvs_get_rate_limit_burst()
uint8_t scp_nvs_get_rate_limit_burst (void)
Get burst rate limit.
Definition at line 397 of file scp_nvs.c.
scp_nvs_get_rate_limit_sustained()
uint8_t scp_nvs_get_rate_limit_sustained (void)
Get sustained rate limit.
Definition at line 363 of file scp_nvs.c.
scp_nvs_get_session_timeout()
uint32_t scp_nvs_get_session_timeout (void)
Get current session timeout.
Definition at line 335 of file scp_nvs.c.
scp_nvs_get_telemetry_rate()
uint8_t scp_nvs_get_telemetry_rate (void)
Get current telemetry rate.
Definition at line 307 of file scp_nvs.c.
scp_nvs_init()
bool scp_nvs_init (void)
Initialize NVS storage for SCP configuration.
Definition at line 157 of file scp_nvs.c.
References calculate_config_checksum(), init_default_config(), scp_nvs_load_config(), and scp_nvs_save_config().
scp_nvs_load_config()
bool scp_nvs_load_config (void)
Load SCP configuration from NVS.
Definition at line 200 of file scp_nvs.c.
References validate_config().
Referenced by scp_nvs_init().
scp_nvs_reset_config()
bool scp_nvs_reset_config (void)
Reset configuration to defaults and save.
Definition at line 284 of file scp_nvs.c.
References calculate_config_checksum(), init_default_config(), and scp_nvs_save_config().
scp_nvs_save_config()
bool scp_nvs_save_config (void)
Save SCP configuration to NVS.
Definition at line 245 of file scp_nvs.c.
References calculate_config_checksum(), and validate_config().
Referenced by scp_nvs_init(), scp_nvs_reset_config(), scp_nvs_set_debug_logging(), scp_nvs_set_rate_limit_burst(), scp_nvs_set_rate_limit_sustained(), scp_nvs_set_session_timeout(), and scp_nvs_set_telemetry_rate().
scp_nvs_set_debug_logging()
bool scp_nvs_set_debug_logging (bool enabled)
Set debug logging state.
Definition at line 434 of file scp_nvs.c.
References scp_nvs_save_config().
scp_nvs_set_rate_limit_burst()
bool scp_nvs_set_rate_limit_burst (uint8_t rate_cps)
Set burst rate limit.
Definition at line 405 of file scp_nvs.c.
References scp_nvs_save_config().
scp_nvs_set_rate_limit_sustained()
bool scp_nvs_set_rate_limit_sustained (uint8_t rate_cps)
Set sustained rate limit.
Definition at line 371 of file scp_nvs.c.
References scp_nvs_save_config().
scp_nvs_set_session_timeout()
bool scp_nvs_set_session_timeout (uint32_t timeout_ms)
Set session timeout.
Definition at line 343 of file scp_nvs.c.
References scp_nvs_save_config().
scp_nvs_set_telemetry_rate()
bool scp_nvs_set_telemetry_rate (uint8_t rate_hz)
Set telemetry rate.
Definition at line 315 of file scp_nvs.c.
References scp_nvs_save_config().
scp_nvs_validate_storage()
bool scp_nvs_validate_storage (void)
Validate NVS storage integrity.
Definition at line 492 of file scp_nvs.c.
References validate_config().
validate_config()
bool validate_config (const scp_config_t * config) static
Validate configuration parameters.
Definition at line 99 of file scp_nvs.c.
References calculate_config_checksum().
Referenced by scp_nvs_load_config(), scp_nvs_save_config(), and scp_nvs_validate_storage().
Variable Documentation
config_nvs_handle
nvs_handle_t config_nvs_handle static
Definition at line 52 of file scp_nvs.c.
current_config
scp_config_t current_config static
Definition at line 51 of file scp_nvs.c.
nvs_initialized
bool nvs_initialized = false static
Definition at line 53 of file scp_nvs.c.
TAG
const char* TAG = "scp_nvs" static
Definition at line 23 of file scp_nvs.c.