ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/include/scp_session.h File Reference
scp_session.h File Reference
SCP Session Management and Role-Based Authorization.
#include <stdint.h>
#include <stdbool.h>
#include "scp_protocol.h"
Classes
struct scp_rate_limit_t
Rate Limiting State for Session.
struct scp_session_t
SCP Session State.
struct scp_session_manager_t
Session Manager Global State.
struct scp_session_stats_t
Session Statistics Structure.
Macros
#define SCP_MAX_SESSIONS 3
#define SCP_SESSION_KEY_SIZE 32
#define SCP_SESSION_ID_INVALID 0
#define SCP_SEQ_NUM_MAX 255
#define SCP_SESSION_STATE_INACTIVE 0
#define SCP_SESSION_STATE_PENDING 1
#define SCP_SESSION_STATE_ACTIVE 2
#define SCP_SESSION_STATE_SUSPENDED 3
#define SCP_SESSION_STATE_EXPIRED 4
#define last_sequence_num last_seq_num
Typedefs
typedef int scp_crypto_result_t
Functions
bool scp_session_init (void)
Initialize Session Manager.
bool scp_session_create (uint8_t operator_role, uint8_t connection_type, const uint8_t *auth_key, uint32_t *session_id_out)
Create New Session.
bool scp_session_authenticate (uint32_t session_id, uint8_t seq_num, const uint8_t *auth_tag, const uint8_t *message_data, uint16_t message_len)
Authenticate Session Message.
bool scp_session_check_rate_limit (uint32_t session_id, uint32_t current_time_ms)
Check Rate Limiting.
bool scp_session_authorize_command (uint32_t session_id, uint8_t msg_type, const void *command_data)
Authorize Command.
bool scp_session_update_activity (uint32_t session_id, uint32_t current_time_ms)
Update Session Activity.
bool scp_session_close (uint32_t session_id)
Close Session.
uint8_t scp_session_cleanup_expired (uint32_t current_time_ms)
Cleanup Expired Sessions.
scp_session_t * scp_session_get_by_id (uint32_t session_id)
Get Session by ID.
uint8_t scp_session_get_active_count (void)
Get Active Session Count.
uint8_t scp_session_get_list (scp_session_t *sessions_out, uint8_t max_sessions)
Get Session List.
uint8_t scp_session_get_priority (uint32_t session_id, uint8_t msg_type)
Check Session Priority.
void scp_session_get_stats (scp_session_stats_t *stats_out)
Get Session Statistics.
void scp_session_reset_stats (void)
Reset Session Statistics.
bool scp_role_can_execute (uint8_t role, uint8_t msg_type)
Check if role can execute command type.
const char * scp_role_get_name (uint8_t role)
Get role name string.
const char * scp_connection_get_name (uint8_t conn_type)
Get connection type name string.
Detailed Description
SCP Session Management and Role-Based Authorization.
Manages operator sessions with role-based access control, rate limiting, and cryptographic authentication for the Secure Control Protocol (SCP) v1.1.
Author
Scout ISR Project
Version
1.1
Date
2025-10-26
Definition in file scp_session.h.
Macro Definition Documentation
last_sequence_num
#define last_sequence_num last_seq_num
Definition at line 101 of file scp_session.h.
SCP_MAX_SESSIONS
#define SCP_MAX_SESSIONS 3
Definition at line 29 of file scp_session.h.
SCP_SEQ_NUM_MAX
#define SCP_SEQ_NUM_MAX 255
Definition at line 32 of file scp_session.h.
SCP_SESSION_ID_INVALID
#define SCP_SESSION_ID_INVALID 0
Definition at line 31 of file scp_session.h.
SCP_SESSION_KEY_SIZE
#define SCP_SESSION_KEY_SIZE 32
Definition at line 30 of file scp_session.h.
SCP_SESSION_STATE_ACTIVE
#define SCP_SESSION_STATE_ACTIVE 2
Definition at line 40 of file scp_session.h.
SCP_SESSION_STATE_EXPIRED
#define SCP_SESSION_STATE_EXPIRED 4
Definition at line 42 of file scp_session.h.
SCP_SESSION_STATE_INACTIVE
#define SCP_SESSION_STATE_INACTIVE 0
Definition at line 38 of file scp_session.h.
SCP_SESSION_STATE_PENDING
#define SCP_SESSION_STATE_PENDING 1
Definition at line 39 of file scp_session.h.
SCP_SESSION_STATE_SUSPENDED
#define SCP_SESSION_STATE_SUSPENDED 3
Definition at line 41 of file scp_session.h.
Typedef Documentation
scp_crypto_result_t
typedef int scp_crypto_result_t
Definition at line 35 of file scp_session.h.
Function Documentation
scp_connection_get_name()
const char * scp_connection_get_name (uint8_t conn_type)
Get connection type name string.
Parameters
conn_type Connection type (SCP_CONN_*)
Returns
Connection type name for logging/display
Definition at line 297 of file scp_session.c.
Referenced by cmd_scp_sessions(), gcs_gateway_log_security_violation(), scp_session_create(), and test_session_creation_variants().
scp_role_can_execute()
bool scp_role_can_execute (uint8_t role, uint8_t msg_type)
Check if role can execute command type.
Parameters
role Operator role (SCP_ROLE_*)
msg_type Message type (SCP_CMD_*)
Returns
true if role authorized for message type
Definition at line 244 of file scp_session.c.
Referenced by gcs_gateway_process_arm_command(), gcs_gateway_process_disarm_command(), gcs_gateway_process_mode_change(), scp_session_authorize_command(), test_role_based_authorization(), and test_security_role_authorization_matrix().
scp_role_get_name()
const char * scp_role_get_name (uint8_t role)
Get role name string.
Parameters
role Operator role (SCP_ROLE_*)
Returns
Role name string for logging/display
Definition at line 282 of file scp_session.c.
Referenced by cmd_scp_sessions(), cmd_scp_telemetry(), gcs_gateway_log_security_violation(), gcs_gateway_log_to_audit_system(), gcs_gateway_process_arm_command(), gcs_gateway_process_disarm_command(), gcs_gateway_process_mode_change(), gcs_gateway_send_tlm_status_targeted(), scp_session_authorize_command(), scp_session_close(), scp_session_create(), and test_session_creation_variants().
scp_session_authenticate()
bool scp_session_authenticate (uint32_t session_id, uint8_t seq_num, const uint8_t * auth_tag, const uint8_t * message_data, uint16_t message_len)
Authenticate Session Message.
Validates message authentication and sequence number for an active session. Updates session activity timestamp and sequence tracking.
Parameters
session_id Session identifier
seq_num Message sequence number
auth_tag HMAC authentication tag (16 bytes, or NULL if no auth)
message_data Message data for HMAC verification
message_len Message data length
Returns
true if authentication successful, false otherwise
Definition at line 440 of file scp_session.c.
References find_session_by_id(), get_current_time_ms(), is_sequence_valid(), and scp_crypto_hmac_verify().
Referenced by cmd_scp_selftest(), test_security_hmac_tampering_detection(), test_security_invalid_hmac_rejection(), test_security_monitoring_cli_integration(), test_security_replay_attack_detection(), test_security_sequence_number_rollover(), test_security_session_isolation(), test_security_valid_hmac_authentication(), test_security_violation_detection_and_reporting(), test_session_authentication_failures(), and test_session_authentication_valid().
scp_session_authorize_command()
bool scp_session_authorize_command (uint32_t session_id, uint8_t msg_type, const void * command_data)
Authorize Command.
Checks if session has sufficient role privileges to execute the specified command.
Parameters
session_id Session identifier
msg_type Message type (SCP_CMD_*)
command_data Command-specific data for additional authorization checks
Returns
true if authorized, false if insufficient privileges
Definition at line 538 of file scp_session.c.
References find_session_by_id(), scp_role_can_execute(), and scp_role_get_name().
Referenced by gcs_gateway_process_cmd_control(), test_security_session_authorization_enforcement(), and test_session_command_authorization().
scp_session_check_rate_limit()
bool scp_session_check_rate_limit (uint32_t session_id, uint32_t current_time_ms)
Check Rate Limiting.
Verifies if session can send another command based on rate limiting rules. Updates rate limiting state if command is allowed.
Parameters
session_id Session identifier
current_time_ms Current system time (milliseconds)
Returns
true if command allowed, false if rate limited
Definition at line 514 of file scp_session.c.
References find_session_by_id(), and update_rate_limit().
Referenced by gcs_gateway_check_enhanced_rate_limit(), test_rate_limiting_basic(), test_rate_limiting_burst(), test_rate_limiting_invalid_session(), test_rate_limiting_security_violation_escalation(), test_security_monitoring_cli_integration(), test_security_rate_limit_window_reset(), and test_security_rate_limiting_enforcement().
scp_session_cleanup_expired()
uint8_t scp_session_cleanup_expired (uint32_t current_time_ms)
Cleanup Expired Sessions.
Removes sessions that have exceeded their timeout period. Should be called periodically by the main protocol task.
Parameters
current_time_ms Current system time (milliseconds)
Returns
Number of sessions cleaned up
Definition at line 659 of file scp_session.c.
References scp_session_close(), and session_manager.
Referenced by test_security_session_timeout(), and test_session_timeout().
scp_session_close()
bool scp_session_close (uint32_t session_id)
Close Session.
Terminates and cleans up the specified session.
Parameters
session_id Session identifier
Returns
true if session found and closed, false otherwise
Definition at line 601 of file scp_session.c.
References find_session_by_id(), scp_crypto_secure_memclear(), scp_role_get_name(), and session_manager.
Referenced by cmd_scp_reset(), scp_session_cleanup_expired(), test_integration_role_based_authorization(), and test_session_closure().
scp_session_create()
bool scp_session_create (uint8_t operator_role, uint8_t connection_type, const uint8_t * auth_key, uint32_t * session_id_out)
Create New Session.
Creates a new authenticated session for the specified operator role and connection type.
Parameters
operator_role Role: SCP_ROLE_COMMANDER/PILOT/OBSERVER
connection_type Transport: SCP_CONN_UART/USB/SPI
auth_key Authentication key (32 bytes)
session_id_out Output: allocated session ID
Returns
true if session created successfully, false if no slots available
Definition at line 354 of file scp_session.c.
References find_free_session_slot(), get_current_time_ms(), init_session(), scp_connection_get_name(), scp_role_get_name(), and session_manager.
Referenced by cmd_scp_selftest(), test_integration_role_based_authorization(), test_rate_limiting_basic(), test_rate_limiting_burst(), test_session_authentication_failures(), test_session_authentication_valid(), test_session_closure(), test_session_command_authorization(), test_session_creation_basic(), test_session_creation_errors(), test_session_creation_limit(), test_session_creation_variants(), test_session_list(), test_session_priority(), test_session_statistics(), and test_session_timeout().
scp_session_get_active_count()
uint8_t scp_session_get_active_count (void)
Get Active Session Count.
Returns
Number of currently active sessions
Definition at line 720 of file scp_session.c.
References session_manager.
Referenced by test_session_closure(), and test_session_creation_limit().
scp_session_get_by_id()
scp_session_t * scp_session_get_by_id (uint32_t session_id)
Get Session by ID.
Retrieves session information for the specified session ID.
Parameters
session_id Session identifier
Returns
Pointer to session structure, or NULL if not found
Definition at line 709 of file scp_session.c.
References find_session_by_id().
Referenced by gcs_gateway_audit_auth_failure(), gcs_gateway_audit_command_attempt(), gcs_gateway_audit_security_violation(), gcs_gateway_log_security_violation(), gcs_gateway_log_to_audit_system(), gcs_gateway_process_cmd_control(), gcs_gateway_send_response(), gcs_gateway_set_session_telemetry(), gcs_gateway_validate_sequence(), test_security_session_timeout(), test_session_authentication_valid(), test_session_closure(), test_session_creation_basic(), test_session_creation_variants(), and test_session_timeout().
scp_session_get_list()
uint8_t scp_session_get_list (scp_session_t * sessions_out, uint8_t max_sessions)
Get Session List.
Retrieves list of all active sessions for monitoring and debugging.
Parameters
sessions_out Output buffer for session information
max_sessions Maximum number of sessions to return
Returns
Actual number of sessions returned
Definition at line 730 of file scp_session.c.
References session_manager.
Referenced by cmd_scp_reset(), cmd_scp_sessions(), cmd_scp_telemetry(), gcs_gateway_get_session_telemetry_stats(), gcs_gateway_send_audit(), gcs_gateway_send_audit_event(), gcs_gateway_send_tlm_status_targeted(), gcs_gateway_set_session_telemetry(), and test_session_list().
scp_session_get_priority()
uint8_t scp_session_get_priority (uint32_t session_id, uint8_t msg_type)
Check Session Priority.
Determines message priority level based on operator role and message type. Used for priority-based message queuing and processing.
Parameters
session_id Session identifier
msg_type Message type
Returns
Priority level (SCP_PRIORITY_*)
Definition at line 756 of file scp_session.c.
References find_session_by_id().
Referenced by test_session_priority().
scp_session_get_stats()
void scp_session_get_stats (scp_session_stats_t * stats_out)
Get Session Statistics.
Retrieves aggregated session statistics for monitoring.
Parameters
stats_out Output buffer for statistics
Definition at line 809 of file scp_session.c.
References session_manager.
Referenced by cmd_scp_security(), cmd_scp_sessions(), test_security_invalid_hmac_rejection(), test_security_rate_limiting_enforcement(), test_security_valid_hmac_authentication(), and test_session_statistics().
scp_session_init()
bool scp_session_init (void)
Initialize Session Manager.
Initializes the session manager and clears all session state. Must be called during system startup.
Returns
true if initialization successful, false otherwise
Definition at line 316 of file scp_session.c.
References session_manager.
Referenced by cmd_scp_selftest().
scp_session_reset_stats()
void scp_session_reset_stats (void)
Reset Session Statistics.
Clears session statistics counters (does not affect active sessions).
Definition at line 828 of file scp_session.c.
Referenced by cmd_scp_reset(), and test_session_statistics().
scp_session_update_activity()
bool scp_session_update_activity (uint32_t session_id, uint32_t current_time_ms)
Update Session Activity.
Updates session activity timestamp and resets inactivity timeout.
Parameters
session_id Session identifier
current_time_ms Current system time (milliseconds)
Returns
true if session found and updated, false otherwise
Definition at line 575 of file scp_session.c.
References find_session_by_id().
Referenced by test_security_session_timeout(), and test_session_timeout().