ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/src/services/scp_framer.c File Reference
scp_framer.c File Reference
SCP Protocol Frame Processing - COBS Encoding/Decoding and Message Validation.
#include <string.h>
#include <stddef.h>
#include <arpa/inet.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "scp_protocol.h"
Functions
static uint16_t crc16_ccitt_calculate (const uint8_t *data, uint16_t length, uint16_t initial_crc)
Calculate CRC-16-CCITT checksum.
static uint16_t cobs_encode (const uint8_t *src, uint16_t src_len, uint8_t *dst, uint16_t dst_len)
COBS Encode Data.
static uint16_t cobs_decode (const uint8_t *src, uint16_t src_len, uint8_t *dst, uint16_t dst_len)
COBS Decode Data.
static bool validate_frame_header (const scp_frame_header_t *header)
Validate SCP Frame Header.
bool scp_framer_init (void)
Initialize SCP Framing Subsystem.
bool scp_framer_encode (const scp_frame_header_t *header, const uint8_t *payload, uint16_t payload_len, const uint8_t *auth_tag, uint8_t *frame_out, uint16_t frame_len_max, uint16_t *frame_len_out)
Encode SCP Frame with COBS Framing.
bool scp_framer_decode (const uint8_t *frame_in, uint16_t frame_len, scp_frame_header_t *header_out, uint8_t *payload_out, uint16_t payload_len_max, uint16_t *payload_len_out, uint8_t *auth_tag_out)
Decode SCP Frame from COBS Encoding.
bool scp_framer_validate_crc (const uint8_t *frame_data, uint16_t frame_len)
Validate Frame CRC.
uint16_t scp_framer_calculate_crc (const uint8_t *frame_data, uint16_t frame_len)
Calculate Frame CRC.
uint16_t scp_framer_get_overhead (uint16_t payload_len, bool has_auth)
Get Frame Overhead Size.
Variables
static const char * TAG = "scp_framer"
static const uint16_t crc16_table [256]
CRC-16-CCITT Lookup Table.
Detailed Description
SCP Protocol Frame Processing - COBS Encoding/Decoding and Message Validation.
Implements Consistent Overhead Byte Stuffing (COBS) framing, CRC-16-CCITT validation, and message parsing for the Secure Control Protocol (SCP) v1.1.
Author
Scout ISR Project
Version
1.1
Date
2025-10-26
Definition in file scp_framer.c.
Function Documentation
cobs_decode()
uint16_t cobs_decode (const uint8_t * src, uint16_t src_len, uint8_t * dst, uint16_t dst_len) static
COBS Decode Data.
Decodes COBS-encoded data back to original form.
Parameters
src Source encoded buffer
src_len Source buffer length
dst Destination buffer (must be at least src_len bytes)
dst_len Destination buffer size
Returns
Number of decoded bytes, or 0 on error
Definition at line 176 of file scp_framer.c.
Referenced by scp_framer_decode().
cobs_encode()
uint16_t cobs_encode (const uint8_t * src, uint16_t src_len, uint8_t * dst, uint16_t dst_len) static
COBS Encode Data.
Encodes data using Consistent Overhead Byte Stuffing to eliminate zero bytes. Adds exactly one byte overhead plus one byte per 254-byte segment.
Parameters
src Source data buffer
src_len Source data length
dst Destination buffer (must be at least src_len + (src_len/254) + 1 bytes)
dst_len Destination buffer size
Returns
Number of encoded bytes, or 0 on error
Definition at line 103 of file scp_framer.c.
Referenced by scp_framer_encode().
crc16_ccitt_calculate()
uint16_t crc16_ccitt_calculate (const uint8_t * data, uint16_t length, uint16_t initial_crc) static
Calculate CRC-16-CCITT checksum.
Parameters
data Data buffer to calculate CRC for
length Data length in bytes
initial_crc Initial CRC value (typically 0xFFFF)
Returns
Calculated CRC-16 value
Definition at line 74 of file scp_framer.c.
References crc16_table.
Referenced by scp_framer_calculate_crc(), scp_framer_decode(), scp_framer_encode(), scp_framer_init(), and scp_framer_validate_crc().
scp_framer_calculate_crc()
uint16_t scp_framer_calculate_crc (const uint8_t * frame_data, uint16_t frame_len)
Calculate Frame CRC.
Parameters
frame_data Frame data (without CRC)
frame_len Frame length (without CRC)
Returns
Calculated CRC-16 value
Definition at line 584 of file scp_framer.c.
References crc16_ccitt_calculate().
Referenced by test_crc16_ccitt_known_vectors(), and test_crc16_validation().
scp_framer_decode()
bool scp_framer_decode (const uint8_t * frame_in, uint16_t frame_len, scp_frame_header_t * header_out, uint8_t * payload_out, uint16_t payload_len_max, uint16_t * payload_len_out, uint8_t * auth_tag_out)
Decode SCP Frame from COBS Encoding.
Parameters
frame_in Encoded frame buffer
frame_len Encoded frame length
header_out Output: decoded frame header
payload_out Output buffer for payload (can be NULL if not needed)
payload_len_max Maximum payload buffer size
payload_len_out Output: actual payload length
auth_tag_out Output buffer for auth tag (can be NULL if not needed)
Returns
true if decoding successful, false on error
Definition at line 460 of file scp_framer.c.
References cobs_decode(), crc16_ccitt_calculate(), SCP_HAS_AUTH, and validate_frame_header().
Referenced by cmd_scp_selftest(), mock_transport_send(), test_frame_decode_basic(), test_frame_decode_errors(), test_frame_decode_with_auth(), test_maximum_payload_size(), and test_multiple_round_trips().
scp_framer_encode()
bool scp_framer_encode (const scp_frame_header_t * header, const uint8_t * payload, uint16_t payload_len, const uint8_t * auth_tag, uint8_t * frame_out, uint16_t frame_len_max, uint16_t * frame_len_out)
Encode SCP Frame with COBS Framing.
Parameters
header Frame header
payload Payload data (can be NULL if payload_len is 0)
payload_len Payload length
auth_tag Authentication tag (can be NULL if not present)
frame_out Output buffer for encoded frame
frame_len_max Maximum frame buffer size
frame_len_out Output: actual encoded frame length
Returns
true if encoding successful, false on error
Definition at line 345 of file scp_framer.c.
References cobs_encode(), crc16_ccitt_calculate(), SCP_HAS_AUTH, and validate_frame_header().
Referenced by cmd_scp_selftest(), gcs_gateway_send_audit(), gcs_gateway_send_audit_event(), gcs_gateway_send_response(), gcs_gateway_send_tlm_status_targeted(), send_test_command(), test_frame_decode_basic(), test_frame_decode_with_auth(), test_frame_encode_basic(), test_frame_encode_errors(), test_frame_encode_with_auth(), test_maximum_payload_size(), and test_multiple_round_trips().
scp_framer_get_overhead()
uint16_t scp_framer_get_overhead (uint16_t payload_len, bool has_auth)
Get Frame Overhead Size.
Calculates the total overhead bytes added by SCP framing.
Parameters
payload_len Payload length
has_auth Whether authentication tag is present
Returns
Total overhead bytes (header + auth + crc + cobs)
Definition at line 603 of file scp_framer.c.
Referenced by test_frame_overhead_calculation().
scp_framer_init()
bool scp_framer_init (void)
Initialize SCP Framing Subsystem.
Returns
true if initialization successful
Definition at line 316 of file scp_framer.c.
References crc16_ccitt_calculate().
Referenced by cmd_scp_selftest(), and gcs_gateway_init().
scp_framer_validate_crc()
bool scp_framer_validate_crc (const uint8_t * frame_data, uint16_t frame_len)
Validate Frame CRC.
Parameters
frame_data Raw frame data (after COBS decoding)
frame_len Frame length including CRC
Returns
true if CRC is valid, false otherwise
Definition at line 563 of file scp_framer.c.
References crc16_ccitt_calculate().
Referenced by test_crc16_validation().
validate_frame_header()
bool validate_frame_header (const scp_frame_header_t * header) static
Validate SCP Frame Header.
Validates frame header structure and field values.
Parameters
header Pointer to frame header
Returns
true if header is valid, false otherwise
Definition at line 249 of file scp_framer.c.
Referenced by scp_framer_decode(), and scp_framer_encode().
Variable Documentation
crc16_table
const uint16_t crc16_table[256] static
CRC-16-CCITT Lookup Table.
Pre-computed CRC table for polynomial 0x1021 (x^16 + x^12 + x^5 + 1)
Definition at line 32 of file scp_framer.c.
TAG
const char* TAG = "scp_framer" static
Definition at line 21 of file scp_framer.c.