ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/include/scp_crypto.h File Reference
scp_crypto.h File Reference
SCP Cryptographic Functions and Authentication.
#include <stdint.h>
#include <stdbool.h>
#include "scp_protocol.h"
Classes
struct scp_crypto_key_t
SCP Authentication Key.
struct scp_key_store_entry_t
Key Store Entry.
struct scp_crypto_stats_t
Cryptographic Statistics.
Macros
#define SCP_HMAC_KEY_SIZE 32
#define SCP_HMAC_TAG_SIZE 16
#define SCP_HMAC_FULL_SIZE 32
#define SCP_CRYPTO_BLOCK_SIZE 64
#define SCP_KEY_MATERIAL_SIZE 64
#define SCP_MASTER_KEY_SIZE 32
#define SCP_SALT_SIZE 16
#define SCP_PBKDF2_ITERATIONS 10000
#define SCP_RANDOM_SEED_SIZE 32
#define SCP_CRYPTO_OK 0
#define SCP_CRYPTO_ERR_INVALID_PARAM 1
#define SCP_CRYPTO_ERR_KEY_INVALID 2
#define SCP_CRYPTO_ERR_AUTH_FAIL 3
#define SCP_CRYPTO_ERR_MEMORY 4
#define SCP_CRYPTO_ERR_HARDWARE 5
Functions
int scp_crypto_init (void)
Initialize Cryptographic Subsystem.
int scp_crypto_hmac_generate (const uint8_t *key, const uint8_t *message, uint16_t message_len, uint8_t *tag_out)
Generate HMAC-SHA256 Authentication Tag.
int scp_crypto_hmac_verify (const uint8_t *key, const uint8_t *message, uint16_t message_len, const uint8_t *tag_expected)
Verify HMAC-SHA256 Authentication Tag.
int scp_crypto_generate_key (uint8_t *key_out)
Generate Secure Random Key.
int scp_crypto_derive_key (const char *password, uint16_t password_len, const uint8_t *salt, uint32_t iterations, uint8_t *key_out)
Derive Key from Password.
int scp_crypto_keystore_init (void)
Initialize Key Store.
int scp_crypto_keystore_store (uint32_t key_id, const scp_crypto_key_t *key)
Store Authentication Key.
int scp_crypto_keystore_load (uint32_t key_id, scp_crypto_key_t *key_out)
Load Authentication Key.
int scp_crypto_keystore_delete (uint32_t key_id)
Delete Authentication Key.
int scp_crypto_keystore_list (scp_crypto_key_t *key_list, uint8_t max_keys, uint8_t *count_out)
List Stored Keys.
int scp_crypto_keystore_clear (void)
Clear All Keys.
bool scp_crypto_key_is_valid (const scp_crypto_key_t *key, uint32_t current_time)
Validate Key Structure.
int scp_crypto_key_create (scp_crypto_key_t *key_out, const uint8_t *key_data, uint32_t key_id, uint8_t operator_role, uint32_t validity_period, uint32_t current_time)
Create Key Structure.
uint32_t scp_crypto_key_checksum (const scp_crypto_key_t *key)
Generate Key Checksum.
void scp_crypto_secure_memclear (void *ptr, uint16_t size)
Secure Memory Clear.
bool scp_crypto_secure_memcmp (const void *a, const void *b, uint16_t size)
Constant-Time Memory Compare.
int scp_crypto_get_random (uint8_t *buffer, uint16_t size)
Get Hardware Random Bytes.
int scp_crypto_seed_rng (const uint8_t *seed, uint16_t seed_size)
Seed Random Number Generator.
void scp_crypto_get_stats (scp_crypto_stats_t *stats_out)
Get Cryptographic Statistics.
void scp_crypto_reset_stats (void)
Reset Cryptographic Statistics.
int scp_crypto_self_test (void)
Self-Test Cryptographic Functions.
Detailed Description
SCP Cryptographic Functions and Authentication.
Provides HMAC-SHA256 authentication, key management, and cryptographic utilities for the Secure Control Protocol (SCP) v1.1.
Author
Scout ISR Project
Version
1.1
Date
2025-10-26
Definition in file scp_crypto.h.
Macro Definition Documentation
SCP_CRYPTO_BLOCK_SIZE
#define SCP_CRYPTO_BLOCK_SIZE 64
Definition at line 32 of file scp_crypto.h.
SCP_CRYPTO_ERR_AUTH_FAIL
#define SCP_CRYPTO_ERR_AUTH_FAIL 3
Definition at line 50 of file scp_crypto.h.
SCP_CRYPTO_ERR_HARDWARE
#define SCP_CRYPTO_ERR_HARDWARE 5
Definition at line 52 of file scp_crypto.h.
SCP_CRYPTO_ERR_INVALID_PARAM
#define SCP_CRYPTO_ERR_INVALID_PARAM 1
Definition at line 48 of file scp_crypto.h.
SCP_CRYPTO_ERR_KEY_INVALID
#define SCP_CRYPTO_ERR_KEY_INVALID 2
Definition at line 49 of file scp_crypto.h.
SCP_CRYPTO_ERR_MEMORY
#define SCP_CRYPTO_ERR_MEMORY 4
Definition at line 51 of file scp_crypto.h.
SCP_CRYPTO_OK
#define SCP_CRYPTO_OK 0
Definition at line 47 of file scp_crypto.h.
SCP_HMAC_FULL_SIZE
#define SCP_HMAC_FULL_SIZE 32
Definition at line 31 of file scp_crypto.h.
SCP_HMAC_KEY_SIZE
#define SCP_HMAC_KEY_SIZE 32
Definition at line 29 of file scp_crypto.h.
SCP_HMAC_TAG_SIZE
#define SCP_HMAC_TAG_SIZE 16
Definition at line 30 of file scp_crypto.h.
SCP_KEY_MATERIAL_SIZE
#define SCP_KEY_MATERIAL_SIZE 64
Definition at line 35 of file scp_crypto.h.
SCP_MASTER_KEY_SIZE
#define SCP_MASTER_KEY_SIZE 32
Definition at line 36 of file scp_crypto.h.
SCP_PBKDF2_ITERATIONS
#define SCP_PBKDF2_ITERATIONS 10000
Definition at line 40 of file scp_crypto.h.
SCP_RANDOM_SEED_SIZE
#define SCP_RANDOM_SEED_SIZE 32
Definition at line 41 of file scp_crypto.h.
SCP_SALT_SIZE
#define SCP_SALT_SIZE 16
Definition at line 37 of file scp_crypto.h.
Function Documentation
scp_crypto_derive_key()
int scp_crypto_derive_key (const char * password, uint16_t password_len, const uint8_t * salt, uint32_t iterations, uint8_t * key_out)
Derive Key from Password.
Derives HMAC key from password using PBKDF2-SHA256 with salt. Used for operator key provisioning from shared secrets.
Parameters
password Input password string
password_len Length of password
salt Salt value (16 bytes)
iterations PBKDF2 iteration count
key_out Output buffer for derived key (32 bytes)
Returns
SCP_CRYPTO_OK on success, error code on failure
Definition at line 278 of file scp_crypto.c.
References crypto_state.
Referenced by test_key_derivation(), and test_key_derivation_parameters().
scp_crypto_generate_key()
int scp_crypto_generate_key (uint8_t * key_out)
Generate Secure Random Key.
Generates cryptographically secure random key using hardware RNG.
Parameters
key_out Output buffer for generated key (32 bytes)
Returns
SCP_CRYPTO_OK on success, error code on failure
Definition at line 261 of file scp_crypto.c.
References crypto_state, and scp_crypto_get_random().
Referenced by cmd_scp_security(), cmd_scp_selftest(), test_crypto_statistics(), test_end_to_end_authentication(), test_key_generation(), test_key_generation_errors(), and test_security_key_generation_randomness().
scp_crypto_get_random()
int scp_crypto_get_random (uint8_t * buffer, uint16_t size)
Get Hardware Random Bytes.
Generates cryptographically secure random bytes using hardware RNG.
Parameters
buffer Output buffer for random data
size Number of random bytes to generate
Returns
SCP_CRYPTO_OK on success, error code on failure
Definition at line 126 of file scp_crypto.c.
References crypto_state.
Referenced by scp_crypto_generate_key(), scp_crypto_self_test(), test_random_generation(), and test_random_generation_errors().
scp_crypto_get_stats()
void scp_crypto_get_stats (scp_crypto_stats_t * stats_out)
Get Cryptographic Statistics.
Parameters
stats_out Output buffer for statistics
Definition at line 732 of file scp_crypto.c.
References crypto_state.
Referenced by test_crypto_statistics().
scp_crypto_hmac_generate()
int scp_crypto_hmac_generate (const uint8_t * key, const uint8_t * message, uint16_t message_len, uint8_t * tag_out)
Generate HMAC-SHA256 Authentication Tag.
Computes HMAC-SHA256 over message data using the specified key, truncated to SCP_HMAC_TAG_SIZE bytes for protocol efficiency.
Parameters
key Pointer to 32-byte HMAC key
message Message data to authenticate
message_len Length of message data
tag_out Output buffer for authentication tag (16 bytes)
Returns
SCP_CRYPTO_OK on success, error code on failure
Definition at line 174 of file scp_crypto.c.
References crypto_state, and scp_crypto_secure_memclear().
Referenced by cmd_scp_selftest(), scp_crypto_hmac_verify(), scp_crypto_self_test(), test_crypto_statistics(), test_end_to_end_authentication(), test_hmac_generation_errors(), test_hmac_key_sensitivity(), test_hmac_rfc4231_vectors(), test_hmac_various_sizes(), test_hmac_verification(), test_multi_session_audit_trail_generation(), test_rate_limiting_security_violation_escalation(), test_security_audit_logging_integration(), test_security_hmac_tampering_detection(), test_security_invalid_hmac_rejection(), test_security_replay_attack_detection(), test_security_sequence_number_rollover(), test_security_session_isolation(), test_security_valid_hmac_authentication(), test_security_violation_detection_and_reporting(), test_session_authentication_failures(), and test_session_authentication_valid().
scp_crypto_hmac_verify()
int scp_crypto_hmac_verify (const uint8_t * key, const uint8_t * message, uint16_t message_len, const uint8_t * tag_expected)
Verify HMAC-SHA256 Authentication Tag.
Verifies HMAC-SHA256 authentication tag against message data. Uses constant-time comparison to prevent timing attacks.
Parameters
key Pointer to 32-byte HMAC key
message Message data to verify
message_len Length of message data
tag_expected Expected authentication tag (16 bytes)
Returns
SCP_CRYPTO_OK if verification successful, SCP_CRYPTO_ERR_AUTH_FAIL if invalid
Definition at line 217 of file scp_crypto.c.
References crypto_state, scp_crypto_hmac_generate(), scp_crypto_secure_memclear(), and scp_crypto_secure_memcmp().
Referenced by cmd_scp_selftest(), scp_crypto_self_test(), scp_session_authenticate(), test_crypto_statistics(), test_end_to_end_authentication(), test_hmac_key_sensitivity(), and test_hmac_verification().
scp_crypto_init()
int scp_crypto_init (void)
Initialize Cryptographic Subsystem.
Initializes hardware crypto accelerators and internal state. Must be called during system startup.
Returns
SCP_CRYPTO_OK on success, error code on failure
Definition at line 634 of file scp_crypto.c.
References crypto_state, init_entropy(), scp_crypto_keystore_init(), and scp_crypto_self_test().
Referenced by cmd_scp_selftest().
scp_crypto_key_checksum()
uint32_t scp_crypto_key_checksum (const scp_crypto_key_t * key)
Generate Key Checksum.
Computes integrity checksum for key storage.
Parameters
key Pointer to key structure
Returns
32-bit checksum value
Definition at line 344 of file scp_crypto.c.
Referenced by scp_crypto_keystore_load(), and scp_crypto_keystore_store().
scp_crypto_key_create()
int scp_crypto_key_create (scp_crypto_key_t * key_out, const uint8_t * key_data, uint32_t key_id, uint8_t operator_role, uint32_t validity_period, uint32_t current_time)
Create Key Structure.
Initializes key structure with metadata.
Parameters
key_out Output key structure
key_data Raw key data (32 bytes)
key_id Unique key identifier
operator_role Associated operator role
validity_period Validity period in seconds (0 = never expires)
current_time Current system time
Returns
SCP_CRYPTO_OK on success, error code on failure
Definition at line 591 of file scp_crypto.c.
Referenced by test_key_structure().
scp_crypto_key_is_valid()
bool scp_crypto_key_is_valid (const scp_crypto_key_t * key, uint32_t current_time)
Validate Key Structure.
Validates key structure integrity and expiration.
Parameters
key Pointer to key structure
current_time Current system time for expiration check
Returns
true if key is valid, false otherwise
Definition at line 564 of file scp_crypto.c.
Referenced by test_key_structure().
scp_crypto_keystore_clear()
int scp_crypto_keystore_clear (void)
Clear All Keys.
Removes all authentication keys from NVS storage. Used for security reset or key rotation scenarios.
Returns
SCP_CRYPTO_OK on success, error code on failure
Definition at line 535 of file scp_crypto.c.
References crypto_state.
scp_crypto_keystore_delete()
int scp_crypto_keystore_delete (uint32_t key_id)
Delete Authentication Key.
Removes authentication key from NVS storage.
Parameters
key_id Key identifier to delete
Returns
SCP_CRYPTO_OK on success, error code on failure
Definition at line 454 of file scp_crypto.c.
References crypto_state.
scp_crypto_keystore_init()
int scp_crypto_keystore_init (void)
Initialize Key Store.
Initializes NVS key storage and loads existing keys.
Returns
SCP_CRYPTO_OK on success, error code on failure
Definition at line 331 of file scp_crypto.c.
References crypto_state.
Referenced by scp_crypto_init().
scp_crypto_keystore_list()
int scp_crypto_keystore_list (scp_crypto_key_t * key_list, uint8_t max_keys, uint8_t * count_out)
List Stored Keys.
Retrieves list of stored key identifiers and metadata.
Parameters
key_list Output buffer for key information
max_keys Maximum number of keys to return
count_out Output: actual number of keys returned
Returns
SCP_CRYPTO_OK on success, error code on failure
Definition at line 489 of file scp_crypto.c.
References crypto_state, and scp_crypto_keystore_load().
scp_crypto_keystore_load()
int scp_crypto_keystore_load (uint32_t key_id, scp_crypto_key_t * key_out)
Load Authentication Key.
Loads authentication key from NVS with integrity verification.
Parameters
key_id Key identifier to load
key_out Output buffer for key structure
Returns
SCP_CRYPTO_OK on success, error code if not found or corrupted
Definition at line 404 of file scp_crypto.c.
References crypto_state, and scp_crypto_key_checksum().
Referenced by scp_crypto_keystore_list().
scp_crypto_keystore_store()
int scp_crypto_keystore_store (uint32_t key_id, const scp_crypto_key_t * key)
Store Authentication Key.
Stores authentication key in NVS with integrity protection.
Parameters
key_id Unique key identifier
key Pointer to key structure
Returns
SCP_CRYPTO_OK on success, error code on failure
Definition at line 361 of file scp_crypto.c.
References crypto_state, and scp_crypto_key_checksum().
scp_crypto_reset_stats()
void scp_crypto_reset_stats (void)
Reset Cryptographic Statistics.
Definition at line 740 of file scp_crypto.c.
References crypto_state.
scp_crypto_secure_memclear()
void scp_crypto_secure_memclear (void * ptr, uint16_t size)
Secure Memory Clear.
Securely clears sensitive memory to prevent key recovery. Uses volatile operations to prevent compiler optimization.
Parameters
ptr Pointer to memory to clear
size Number of bytes to clear
Secure Memory Clear.
Uses volatile pointer to prevent compiler optimization.
Definition at line 62 of file scp_crypto.c.
Referenced by scp_crypto_hmac_generate(), scp_crypto_hmac_verify(), scp_session_close(), and test_secure_memclear().
scp_crypto_secure_memcmp()
bool scp_crypto_secure_memcmp (const void * a, const void * b, uint16_t size)
Constant-Time Memory Compare.
Compares memory contents in constant time to prevent timing attacks.
Parameters
a First memory buffer
b Second memory buffer
size Number of bytes to compare
Returns
true if buffers match, false otherwise
Constant-Time Memory Compare.
Definition at line 77 of file scp_crypto.c.
Referenced by scp_crypto_hmac_verify(), scp_crypto_self_test(), and test_secure_memcmp().
scp_crypto_seed_rng()
int scp_crypto_seed_rng (const uint8_t * seed, uint16_t seed_size)
Seed Random Number Generator.
Seeds the random number generator with entropy from multiple sources.
Parameters
seed Additional entropy data (optional, can be NULL)
seed_size Size of additional entropy
Returns
SCP_CRYPTO_OK on success, error code on failure
Definition at line 149 of file scp_crypto.c.
References crypto_state.
scp_crypto_self_test()
int scp_crypto_self_test (void)
Self-Test Cryptographic Functions.
Runs built-in self-tests for cryptographic functions. Should be called during system initialization.
Returns
SCP_CRYPTO_OK if all tests pass, error code on failure
Definition at line 675 of file scp_crypto.c.
References scp_crypto_get_random(), scp_crypto_hmac_generate(), scp_crypto_hmac_verify(), and scp_crypto_secure_memcmp().
Referenced by scp_crypto_init().