ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/tests/integration/security_test.c File Reference
security_test.c File Reference
Security Integration Tests for SCP Protocol.
#include "unity.h"
#include "gcs_gateway.h"
#include "scp_protocol.h"
#include "scp_session.h"
#include "scp_crypto.h"
#include "scp_framer.h"
#include "safety_manager.h"
#include "mode_manager.h"
#include "esp_timer.h"
#include "esp_random.h"
#include <string.h>
#include <stdio.h>
Functions
void setUp (void)
void tearDown (void)
void test_security_valid_hmac_authentication (void)
Test valid HMAC authentication.
void test_security_invalid_hmac_rejection (void)
Test invalid HMAC rejection.
void test_security_hmac_tampering_detection (void)
Test HMAC tampering detection.
void test_security_replay_attack_detection (void)
Test replay attack detection via sequence numbers.
void test_security_sequence_number_rollover (void)
Test sequence number rollover handling.
void test_security_role_authorization_matrix (void)
Test role-based command authorization matrix.
void test_security_session_authorization_enforcement (void)
Test session-based authorization enforcement.
void test_security_privilege_escalation_prevention (void)
Test privilege escalation prevention.
void test_security_rate_limiting_enforcement (void)
Test rate limiting enforcement.
void test_security_rate_limit_window_reset (void)
Test rate limiting window reset.
void test_security_session_isolation (void)
Test session isolation.
void test_security_session_timeout (void)
Test session timeout security.
void test_security_malformed_message_rejection (void)
Test malformed message rejection.
void test_security_oversized_message_rejection (void)
Test oversized message rejection.
void test_security_invalid_session_handling (void)
Test invalid session ID handling.
void test_security_key_generation_randomness (void)
Test key generation randomness.
void test_security_constant_time_comparison (void)
Test constant-time comparison security.
void test_security_audit_logging_integration (void)
Test comprehensive audit logging for security events.
void test_security_violation_detection_and_reporting (void)
Test security violation detection and reporting.
void test_multi_session_audit_trail_generation (void)
Test multi-session audit trail generation.
void test_rate_limiting_security_violation_escalation (void)
Test rate limiting security violation escalation.
void test_security_violation_fatfs_persistence (void)
Test security violation persistence to FATFS.
void test_audit_system_integration_with_companion (void)
Test audit system integration with existing companion audit.
void test_security_monitoring_cli_integration (void)
Test comprehensive security monitoring CLI integration.
void app_main (void)
Variables
static bool security_test_initialized = false
Security test configuration.
static uint32_t commander_session_id = 0
static uint32_t pilot_session_id = 0
static uint32_t observer_session_id = 0
static uint8_t commander_key [SCP_SESSION_KEY_SIZE]
static uint8_t pilot_key [SCP_SESSION_KEY_SIZE]
static uint8_t observer_key [SCP_SESSION_KEY_SIZE]
static uint32_t security_events_detected = 0
static uint32_t auth_failures_detected = 0
Detailed Description
Security Integration Tests for SCP Protocol.
Comprehensive security validation for Secure Control Protocol (SCP) v1.1, testing authentication mechanisms, authorization enforcement, and security attack resistance.
Test Coverage:
HMAC authentication validation
Replay attack detection and prevention
Session hijacking protection
Role-based authorization enforcement
Rate limiting and DoS protection
Cryptographic key management
Sequence number validation
Malformed message handling
Author
Scout ISR Project
Version
1.1
Date
2025-10-26
Definition in file security_test.c.
Function Documentation
app_main()
void app_main (void)
Definition at line 939 of file security_test.c.
setUp()
void setUp (void)
Definition at line 57 of file security_test.c.
tearDown()
void tearDown (void)
Definition at line 106 of file security_test.c.
test_audit_system_integration_with_companion()
void test_audit_system_integration_with_companion (void)
Test audit system integration with existing companion audit.
Definition at line 862 of file security_test.c.
References audit_is_initialized(), and audit_process_companion_input().
test_multi_session_audit_trail_generation()
void test_multi_session_audit_trail_generation (void)
Test multi-session audit trail generation.
Definition at line 711 of file security_test.c.
References gcs_gateway_get_stats(), and scp_crypto_hmac_generate().
test_rate_limiting_security_violation_escalation()
void test_rate_limiting_security_violation_escalation (void)
Test rate limiting security violation escalation.
Definition at line 766 of file security_test.c.
References gcs_gateway_get_stats(), scp_crypto_hmac_generate(), and scp_session_check_rate_limit().
test_security_audit_logging_integration()
void test_security_audit_logging_integration (void)
Test comprehensive audit logging for security events.
Definition at line 633 of file security_test.c.
References gcs_gateway_get_stats(), and scp_crypto_hmac_generate().
test_security_constant_time_comparison()
void test_security_constant_time_comparison (void)
Test constant-time comparison security.
Definition at line 605 of file security_test.c.
test_security_hmac_tampering_detection()
void test_security_hmac_tampering_detection (void)
Test HMAC tampering detection.
Definition at line 203 of file security_test.c.
References scp_crypto_hmac_generate(), and scp_session_authenticate().
test_security_invalid_hmac_rejection()
void test_security_invalid_hmac_rejection (void)
Test invalid HMAC rejection.
Definition at line 171 of file security_test.c.
References scp_crypto_hmac_generate(), scp_session_authenticate(), and scp_session_get_stats().
test_security_invalid_session_handling()
void test_security_invalid_session_handling (void)
Test invalid session ID handling.
Definition at line 546 of file security_test.c.
References gcs_gateway_get_stats().
test_security_key_generation_randomness()
void test_security_key_generation_randomness (void)
Test key generation randomness.
Definition at line 577 of file security_test.c.
References scp_crypto_generate_key().
test_security_malformed_message_rejection()
void test_security_malformed_message_rejection (void)
Test malformed message rejection.
Definition at line 509 of file security_test.c.
References gcs_gateway_get_stats().
test_security_monitoring_cli_integration()
void test_security_monitoring_cli_integration (void)
Test comprehensive security monitoring CLI integration.
Definition at line 894 of file security_test.c.
References gcs_gateway_get_stats(), scp_session_authenticate(), and scp_session_check_rate_limit().
test_security_oversized_message_rejection()
void test_security_oversized_message_rejection (void)
Test oversized message rejection.
Definition at line 531 of file security_test.c.
test_security_privilege_escalation_prevention()
void test_security_privilege_escalation_prevention (void)
Test privilege escalation prevention.
Definition at line 359 of file security_test.c.
References gcs_gateway_get_stats().
test_security_rate_limit_window_reset()
void test_security_rate_limit_window_reset (void)
Test rate limiting window reset.
Definition at line 422 of file security_test.c.
References scp_session_check_rate_limit().
test_security_rate_limiting_enforcement()
void test_security_rate_limiting_enforcement (void)
Test rate limiting enforcement.
Definition at line 391 of file security_test.c.
References scp_session_check_rate_limit(), and scp_session_get_stats().
test_security_replay_attack_detection()
void test_security_replay_attack_detection (void)
Test replay attack detection via sequence numbers.
Definition at line 236 of file security_test.c.
References scp_crypto_hmac_generate(), and scp_session_authenticate().
test_security_role_authorization_matrix()
void test_security_role_authorization_matrix (void)
Test role-based command authorization matrix.
Definition at line 304 of file security_test.c.
References scp_role_can_execute().
test_security_sequence_number_rollover()
void test_security_sequence_number_rollover (void)
Test sequence number rollover handling.
Definition at line 275 of file security_test.c.
References scp_crypto_hmac_generate(), and scp_session_authenticate().
test_security_session_authorization_enforcement()
void test_security_session_authorization_enforcement (void)
Test session-based authorization enforcement.
Definition at line 325 of file security_test.c.
References scp_session_authorize_command().
test_security_session_isolation()
void test_security_session_isolation (void)
Test session isolation.
Definition at line 453 of file security_test.c.
References scp_crypto_hmac_generate(), and scp_session_authenticate().
test_security_session_timeout()
void test_security_session_timeout (void)
Test session timeout security.
Definition at line 480 of file security_test.c.
References scp_session_cleanup_expired(), scp_session_get_by_id(), and scp_session_update_activity().
test_security_valid_hmac_authentication()
void test_security_valid_hmac_authentication (void)
Test valid HMAC authentication.
Definition at line 124 of file security_test.c.
References scp_crypto_hmac_generate(), scp_session_authenticate(), and scp_session_get_stats().
test_security_violation_detection_and_reporting()
void test_security_violation_detection_and_reporting (void)
Test security violation detection and reporting.
Definition at line 670 of file security_test.c.
References gcs_gateway_get_stats(), scp_crypto_hmac_generate(), and scp_session_authenticate().
test_security_violation_fatfs_persistence()
void test_security_violation_fatfs_persistence (void)
Test security violation persistence to FATFS.
Definition at line 820 of file security_test.c.
References blackbox_is_initialized(), and gcs_gateway_log_critical_security_event().
Variable Documentation
auth_failures_detected
uint32_t auth_failures_detected = 0 static
Definition at line 51 of file security_test.c.
commander_key
uint8_t commander_key[SCP_SESSION_KEY_SIZE] static
Definition at line 45 of file security_test.c.
commander_session_id
uint32_t commander_session_id = 0 static
Definition at line 42 of file security_test.c.
observer_key
uint8_t observer_key[SCP_SESSION_KEY_SIZE] static
Definition at line 47 of file security_test.c.
observer_session_id
uint32_t observer_session_id = 0 static
Definition at line 44 of file security_test.c.
pilot_key
uint8_t pilot_key[SCP_SESSION_KEY_SIZE] static
Definition at line 46 of file security_test.c.
pilot_session_id
uint32_t pilot_session_id = 0 static
Definition at line 43 of file security_test.c.
security_events_detected
uint32_t security_events_detected = 0 static
Definition at line 50 of file security_test.c.
security_test_initialized
bool security_test_initialized = false static
Security test configuration.
Definition at line 41 of file security_test.c.