ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/src/services/scp_nvs.h File Reference
scp_nvs.h File Reference
SCP NVS Storage Integration Header.
#include <stdint.h>
#include <stdbool.h>
Functions
bool scp_nvs_init (void)
Initialize NVS storage for SCP configuration.
bool scp_nvs_load_config (void)
Load SCP configuration from NVS.
bool scp_nvs_save_config (void)
Save SCP configuration to NVS.
bool scp_nvs_reset_config (void)
Reset configuration to defaults and save.
uint8_t scp_nvs_get_telemetry_rate (void)
Get current telemetry rate.
bool scp_nvs_set_telemetry_rate (uint8_t rate_hz)
Set telemetry rate.
uint32_t scp_nvs_get_session_timeout (void)
Get current session timeout.
bool scp_nvs_set_session_timeout (uint32_t timeout_ms)
Set session timeout.
uint8_t scp_nvs_get_rate_limit_sustained (void)
Get sustained rate limit.
bool scp_nvs_set_rate_limit_sustained (uint8_t rate_cps)
Set sustained rate limit.
uint8_t scp_nvs_get_rate_limit_burst (void)
Get burst rate limit.
bool scp_nvs_set_rate_limit_burst (uint8_t rate_cps)
Set burst rate limit.
bool scp_nvs_get_debug_logging (void)
Get debug logging state.
bool scp_nvs_set_debug_logging (bool enabled)
Set debug logging state.
uint8_t scp_nvs_get_protocol_version (void)
Get protocol version.
void scp_nvs_dump_config (void)
Log current configuration.
bool scp_nvs_validate_storage (void)
Validate NVS storage integrity.
bool scp_nvs_erase_all (void)
Erase all SCP configuration from NVS.
Detailed Description
SCP NVS Storage Integration Header.
Provides NVS storage integration for SCP session keys, configuration, and persistent state management.
Author
Scout ISR Project
Version
1.1
Date
2025-10-26
Definition in file scp_nvs.h.
Function Documentation
scp_nvs_dump_config()
void scp_nvs_dump_config (void)
Log current configuration.
Definition at line 460 of file scp_nvs.c.
scp_nvs_erase_all()
bool scp_nvs_erase_all (void)
Erase all SCP configuration from NVS.
Definition at line 528 of file scp_nvs.c.
References calculate_config_checksum(), and init_default_config().
scp_nvs_get_debug_logging()
bool scp_nvs_get_debug_logging (void)
Get debug logging state.
Definition at line 426 of file scp_nvs.c.
scp_nvs_get_protocol_version()
uint8_t scp_nvs_get_protocol_version (void)
Get protocol version.
Definition at line 448 of file scp_nvs.c.
scp_nvs_get_rate_limit_burst()
uint8_t scp_nvs_get_rate_limit_burst (void)
Get burst rate limit.
Definition at line 397 of file scp_nvs.c.
scp_nvs_get_rate_limit_sustained()
uint8_t scp_nvs_get_rate_limit_sustained (void)
Get sustained rate limit.
Definition at line 363 of file scp_nvs.c.
scp_nvs_get_session_timeout()
uint32_t scp_nvs_get_session_timeout (void)
Get current session timeout.
Definition at line 335 of file scp_nvs.c.
scp_nvs_get_telemetry_rate()
uint8_t scp_nvs_get_telemetry_rate (void)
Get current telemetry rate.
Definition at line 307 of file scp_nvs.c.
scp_nvs_init()
bool scp_nvs_init (void)
Initialize NVS storage for SCP configuration.
Definition at line 157 of file scp_nvs.c.
scp_nvs_load_config()
bool scp_nvs_load_config (void)
Load SCP configuration from NVS.
Definition at line 200 of file scp_nvs.c.
References validate_config().
Referenced by scp_nvs_init().
scp_nvs_reset_config()
bool scp_nvs_reset_config (void)
Reset configuration to defaults and save.
Definition at line 284 of file scp_nvs.c.
References calculate_config_checksum(), init_default_config(), and scp_nvs_save_config().
scp_nvs_save_config()
bool scp_nvs_save_config (void)
Save SCP configuration to NVS.
Definition at line 245 of file scp_nvs.c.
References calculate_config_checksum(), and validate_config().
Referenced by scp_nvs_init(), scp_nvs_reset_config(), scp_nvs_set_debug_logging(), scp_nvs_set_rate_limit_burst(), scp_nvs_set_rate_limit_sustained(), scp_nvs_set_session_timeout(), and scp_nvs_set_telemetry_rate().
scp_nvs_set_debug_logging()
bool scp_nvs_set_debug_logging (bool enabled)
Set debug logging state.
Definition at line 434 of file scp_nvs.c.
References scp_nvs_save_config().
scp_nvs_set_rate_limit_burst()
bool scp_nvs_set_rate_limit_burst (uint8_t rate_cps)
Set burst rate limit.
Definition at line 405 of file scp_nvs.c.
References scp_nvs_save_config().
scp_nvs_set_rate_limit_sustained()
bool scp_nvs_set_rate_limit_sustained (uint8_t rate_cps)
Set sustained rate limit.
Definition at line 371 of file scp_nvs.c.
References scp_nvs_save_config().
scp_nvs_set_session_timeout()
bool scp_nvs_set_session_timeout (uint32_t timeout_ms)
Set session timeout.
Definition at line 343 of file scp_nvs.c.
References scp_nvs_save_config().
scp_nvs_set_telemetry_rate()
bool scp_nvs_set_telemetry_rate (uint8_t rate_hz)
Set telemetry rate.
Definition at line 315 of file scp_nvs.c.
References scp_nvs_save_config().
scp_nvs_validate_storage()
bool scp_nvs_validate_storage (void)
Validate NVS storage integrity.
Definition at line 492 of file scp_nvs.c.
References validate_config().