ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/src/services/blackbox.c File Reference
blackbox.c File Reference
Mission blackbox logging service implementation.
#include "esp_log.h"
#include "esp_vfs_fat.h"
#include "esp_partition.h"
#include "esp_system.h"
#include "soc/rtc.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include <unistd.h>
#include <sys/stat.h>
#include <dirent.h>
#include <string.h>
#include <stdio.h>
#include <time.h>
#include "feature_config.h"
#include "blackbox_defs.h"
#include "ringbuf.h"
#include "mpu6050.h"
#include "hmc5883l.h"
#include "bmp388.h"
#include "neo6m.h"
Classes
struct blackbox_event_t
Functions
static esp_err_t blackbox_mount_fatfs (void)
static esp_err_t blackbox_ensure_mission_dir (void)
static void blackbox_writer_task (void *arg)
static esp_err_t blackbox_rotate_missions (void)
static esp_err_t blackbox_create_mission_file (const char *mission_id)
static esp_err_t blackbox_close_mission_file (void)
static int64_t blackbox_get_timestamp_ms (void)
esp_err_t blackbox_log_event (const char *event_type, const char *severity, const char *attrs)
Log a blackbox event.
esp_err_t blackbox_init (void)
Initialize the blackbox logging service.
void blackbox_deinit (void)
Shutdown the blackbox logging service.
bool blackbox_is_initialized (void)
Check if blackbox service is initialized.
esp_err_t blackbox_start_mission (const char *mission_id)
Start a new mission log.
esp_err_t blackbox_stop_mission (void)
Stop the current mission log.
bool blackbox_is_mission_active (char *mission_id, size_t mission_id_size)
Get current mission status.
esp_err_t blackbox_log_sensor_summary (void)
Generate and log sensor summary event.
esp_err_t blackbox_collect_evidence (const char *incident_type, const char *context)
Collect and log structured evidence for post-incident analysis.
esp_err_t blackbox_log_critical_fault (const char *fault_type, const char *component, const char *details)
Log critical fault condition with immediate evidence collection.
Variables
static const char * TAG = "blackbox"
static wl_handle_t s_wl_handle = WL_INVALID_HANDLE
static bool s_fatfs_mounted = false
static bool s_blackbox_initialized = false
static TaskHandle_t s_writer_task_handle = NULL
static bool s_mission_active = false
static char s_current_mission_id [32] = {0}
static FILE * s_mission_file = NULL
static char s_mission_file_path [256] = {0}
static QueueHandle_t s_event_queue = NULL
static const size_t s_event_queue_size = BLACKBOX_EVENT_QUEUE_SIZE
Detailed Description
Mission blackbox logging service implementation.
This service provides comprehensive mission logging capabilities with:
Per-flight NDJSON structured logging to FATFS flash partition
Background writer task for non-blocking real-time operation
Keep-last-1 rotation policy for storage management
HMAC-SHA256 signatures for tamper-evident log exports
Evidence collection with contextual metadata
Mission timeline replay functionality
Architecture:
Event producer API for real-time logging without blocking
Ring buffer queue between producers and background writer
FATFS filesystem for mission log persistence
Structured NDJSON format for machine parsing and human readability
Performance characteristics:
Event queuing: <100us typical latency
Background writes: 2-5ms per batch (non-blocking to control loop)
Storage efficiency: ~2-5KB per minute of flight time
Queue capacity: 256 events before backpressure
Constitution compliance:
No blocking operations in producer API (real-time requirement)
Background task priority lower than control loops
Memory bounds enforced (no dynamic allocation in hot paths)
Performance impact <10% CPU overhead per validation tests
Author
Scout Firmware Team
Date
2025-10-26
Version
1.0
Definition in file blackbox.c.
Function Documentation
blackbox_close_mission_file()
esp_err_t blackbox_close_mission_file (void) static
Definition at line 492 of file blackbox.c.
blackbox_collect_evidence()
esp_err_t blackbox_collect_evidence (const char * incident_type, const char * context)
Collect and log structured evidence for post-incident analysis.
Gathers comprehensive system state including:
Current sensor readings with health status
Safety gate states and fault conditions
Performance metrics and CPU usage
Recent audit trail entries
Flight mode and system configuration
Parameters
incident_type Type of incident triggering evidence collection
context Additional context or error details
Returns
ESP_OK on success, error code otherwise
Definition at line 618 of file blackbox.c.
References mpu6050_data_t::accel_x, mpu6050_data_t::accel_y, mpu6050_data_t::accel_z, bmp388_data_t::altitude, blackbox_log_event(), bmp388_get_instance(), bmp388_read_scaled(), neo6m_t::fix_quality, hmc5883l_data_t::heading, hmc5883l_get_instance(), hmc5883l_read_scaled(), mpu6050_t::initialized, neo6m_t::initialized, neo6m_position_t::latitude, neo6m_position_t::longitude, hmc5883l_data_t::mag_x, hmc5883l_data_t::mag_y, hmc5883l_data_t::mag_z, mpu6050_get_instance(), mpu6050_read_scaled(), neo6m_get_instance(), neo6m_t::num_satellites, neo6m_t::position, bmp388_data_t::pressure, bmp388_data_t::temperature, and mpu6050_data_t::temperature.
Referenced by blackbox_log_critical_fault().
blackbox_create_mission_file()
esp_err_t blackbox_create_mission_file (const char * mission_id) static
Definition at line 467 of file blackbox.c.
blackbox_deinit()
void blackbox_deinit (void)
Shutdown the blackbox logging service.
Stops writer task and unmounts FATFS partition.
Definition at line 264 of file blackbox.c.
blackbox_ensure_mission_dir()
esp_err_t blackbox_ensure_mission_dir (void) static
Definition at line 197 of file blackbox.c.
blackbox_get_timestamp_ms()
int64_t blackbox_get_timestamp_ms (void) static
Definition at line 613 of file blackbox.c.
blackbox_init()
esp_err_t blackbox_init (void)
Initialize the blackbox logging service.
Mounts FATFS partition, creates mission logs directory, and starts background writer task.
Returns
ESP_OK on success, error code otherwise
Definition at line 97 of file blackbox.c.
blackbox_is_initialized()
bool blackbox_is_initialized (void)
Check if blackbox service is initialized.
Returns
true if initialized, false otherwise
Definition at line 302 of file blackbox.c.
Referenced by gcs_gateway_log_security_violation(), and test_security_violation_fatfs_persistence().
blackbox_is_mission_active()
bool blackbox_is_mission_active (char * mission_id, size_t mission_id_size)
Get current mission status.
Parameters
mission_id Buffer to store current mission ID (can be NULL)
mission_id_size Size of mission_id buffer
Returns
true if mission is active, false otherwise
Definition at line 417 of file blackbox.c.
blackbox_log_critical_fault()
esp_err_t blackbox_log_critical_fault (const char * fault_type, const char * component, const char * details)
Log critical fault condition with immediate evidence collection.
Records fault event and automatically triggers comprehensive evidence collection for forensic analysis. Use for safety-critical faults.
Parameters
fault_type Classification of fault (e.g., "sensor_fault", "safety_violation")
component Component that failed (e.g., "imu", "mag", "safety_manager")
details Detailed error description or diagnostic information
Returns
ESP_OK on success, error code otherwise
Definition at line 762 of file blackbox.c.
References blackbox_collect_evidence(), and blackbox_log_event().
blackbox_log_event()
esp_err_t blackbox_log_event (const char * event_type, const char * severity, const char * attrs)
Log a blackbox event.
Serializes event to NDJSON format and queues for background writing.
Parameters
event_type Type of event (from blackbox_event_type_t)
severity Event severity (optional, can be NULL)
attrs JSON string with event attributes
Returns
ESP_OK on success, error code otherwise
Definition at line 380 of file blackbox.c.
Referenced by blackbox_collect_evidence(), blackbox_log_critical_fault(), blackbox_log_sensor_summary(), blackbox_start_mission(), blackbox_stop_mission(), and gcs_gateway_log_security_violation().
blackbox_log_sensor_summary()
esp_err_t blackbox_log_sensor_summary (void)
Generate and log sensor summary event.
Collects current sensor readings and logs them as a sensor_summary event. Should be called periodically (every 2 seconds) during missions.
Returns
ESP_OK on success, error code otherwise
Definition at line 508 of file blackbox.c.
References mpu6050_data_t::accel_x, mpu6050_data_t::accel_y, mpu6050_data_t::accel_z, bmp388_data_t::altitude, neo6m_position_t::altitude, blackbox_log_event(), bmp388_get_instance(), bmp388_read_scaled(), neo6m_t::fix_quality, mpu6050_data_t::gyro_x, mpu6050_data_t::gyro_y, mpu6050_data_t::gyro_z, hmc5883l_get_instance(), hmc5883l_read_scaled(), mpu6050_t::initialized, neo6m_t::initialized, neo6m_position_t::latitude, neo6m_position_t::longitude, hmc5883l_data_t::mag_x, hmc5883l_data_t::mag_y, hmc5883l_data_t::mag_z, mpu6050_get_instance(), mpu6050_read_scaled(), neo6m_get_instance(), neo6m_t::num_satellites, neo6m_t::position, bmp388_data_t::pressure, and mpu6050_data_t::temperature.
blackbox_mount_fatfs()
esp_err_t blackbox_mount_fatfs (void) static
Definition at line 154 of file blackbox.c.
blackbox_rotate_missions()
esp_err_t blackbox_rotate_missions (void) static
Definition at line 429 of file blackbox.c.
blackbox_start_mission()
esp_err_t blackbox_start_mission (const char * mission_id)
Start a new mission log.
Creates a new mission log file and starts logging events. Implements keep-last-1 rotation policy.
Parameters
mission_id Mission identifier (e.g., UTC timestamp)
Returns
ESP_OK on success, error code otherwise
Definition at line 307 of file blackbox.c.
References blackbox_log_event().
blackbox_stop_mission()
esp_err_t blackbox_stop_mission (void)
Stop the current mission log.
Closes the current mission log file and finalizes the log.
Returns
ESP_OK on success, error code otherwise
Definition at line 352 of file blackbox.c.
References blackbox_log_event().
blackbox_writer_task()
void blackbox_writer_task (void * arg) static
Definition at line 227 of file blackbox.c.
Variable Documentation
s_blackbox_initialized
bool s_blackbox_initialized = false static
Definition at line 71 of file blackbox.c.
s_current_mission_id
char s_current_mission_id[32] = {0} static
Definition at line 78 of file blackbox.c.
s_event_queue
QueueHandle_t s_event_queue = NULL static
Definition at line 83 of file blackbox.c.
s_event_queue_size
const size_t s_event_queue_size = BLACKBOX_EVENT_QUEUE_SIZE static
Definition at line 84 of file blackbox.c.
s_fatfs_mounted
bool s_fatfs_mounted = false static
Definition at line 70 of file blackbox.c.
s_mission_active
bool s_mission_active = false static
Definition at line 77 of file blackbox.c.
s_mission_file
FILE* s_mission_file = NULL static
Definition at line 79 of file blackbox.c.
s_mission_file_path
char s_mission_file_path[256] = {0} static
Definition at line 80 of file blackbox.c.
s_wl_handle
wl_handle_t s_wl_handle = WL_INVALID_HANDLE static
Definition at line 69 of file blackbox.c.
s_writer_task_handle
TaskHandle_t s_writer_task_handle = NULL static
Definition at line 74 of file blackbox.c.
TAG
const char* TAG = "blackbox" static
Definition at line 59 of file blackbox.c.