ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/tests/unit/test_gcs_security.c File Reference
test_gcs_security.c File Reference
Unit Tests for GCS Gateway Security Functions.
#include "unity.h"
#include "gcs_gateway.h"
#include "scp_session.h"
#include "scp_protocol.h"
#include "audit.h"
#include "blackbox.h"
#include <string.h>
#include <stdint.h>
Macros
#define TEST_SESSION_ID 0x12345678
#define TEST_SEQUENCE_NUM 42
#define TEST_OPERATOR_ROLE SCP_ROLE_PILOT
#define TEST_VIOLATION_TYPE "RATE_LIMIT_EXCEEDED"
#define TEST_VIOLATION_DETAILS "Test security violation details"
Functions
bool audit_is_initialized (void)
Check if audit service is initialized.
esp_err_t audit_process_companion_input (const char *source_identity, const char *action_summary, const char *correlation_id, safety_decision_t *decision_out)
Process companion input through safety gateway.
bool blackbox_is_initialized (void)
Check if blackbox service is initialized.
esp_err_t blackbox_log_event (const char *event_type, const char *severity, const char *attrs)
Log a blackbox event.
scp_session_t * scp_session_get_by_id (uint32_t session_id)
Get Session by ID.
const char * scp_role_get_name (uint8_t role)
Get role name string.
const char * scp_connection_get_name (uint8_t connection_type)
Get connection type name string.
bool scp_session_check_rate_limit (uint32_t session_id, uint32_t current_time)
Check Rate Limiting.
uint64_t esp_timer_get_time (void)
void setUp (void)
void tearDown (void)
void test_gcs_gateway_log_critical_security_event_success (void)
void test_gcs_gateway_log_critical_security_event_blackbox_unavailable (void)
void test_gcs_gateway_log_critical_security_event_null_parameters (void)
void test_rate_limiting_enforcement (void)
void test_replay_attack_detection_valid_sequence (void)
void test_replay_attack_detection_invalid_sequence (void)
void test_sequence_number_wraparound (void)
void test_audit_system_integration_success (void)
void test_audit_system_integration_unavailable (void)
void test_security_event_categorization (void)
void test_security_violation_context_capture (void)
void test_session_security_context (void)
void test_security_logging_performance (void)
void test_security_logging_memory_bounds (void)
int main (void)
Variables
static scp_session_t test_session
static bool mock_audit_initialized = true
static uint32_t mock_audit_call_count = 0
static char mock_last_audit_source [64] = {0}
static char mock_last_audit_action [128] = {0}
static bool mock_blackbox_initialized = true
static uint32_t mock_blackbox_call_count = 0
static char mock_last_event_type [32] = {0}
static char mock_last_event_attrs [512] = {0}
Detailed Description
Unit Tests for GCS Gateway Security Functions.
Tests security event detection, audit logging, rate limiting, replay attack detection, and security violation handling for the Secure Control Protocol (SCP) v1.1.
Author
Scout ISR Project
Version
1.1
Date
2025-10-26
Definition in file test_gcs_security.c.
Macro Definition Documentation
TEST_OPERATOR_ROLE
#define TEST_OPERATOR_ROLE SCP_ROLE_PILOT
Definition at line 36 of file test_gcs_security.c.
TEST_SEQUENCE_NUM
#define TEST_SEQUENCE_NUM 42
Definition at line 35 of file test_gcs_security.c.
TEST_SESSION_ID
#define TEST_SESSION_ID 0x12345678
Definition at line 34 of file test_gcs_security.c.
TEST_VIOLATION_DETAILS
#define TEST_VIOLATION_DETAILS "Test security violation details"
Definition at line 38 of file test_gcs_security.c.
TEST_VIOLATION_TYPE
#define TEST_VIOLATION_TYPE "RATE_LIMIT_EXCEEDED"
Definition at line 37 of file test_gcs_security.c.
Function Documentation
audit_is_initialized()
bool audit_is_initialized (void)
Check if audit service is initialized.
Returns
true if initialized, false otherwise
Definition at line 71 of file test_gcs_security.c.
audit_process_companion_input()
esp_err_t audit_process_companion_input (const char * source_identity, const char * payload_summary, const char * correlation_id, safety_decision_t * result)
Process companion input through safety gateway.
This is the main entry point for all companion inputs. It performs:
Source identity verification against whitelist
Input classification (command vs suggestion)
Safety evaluation against all gates
Audit logging of decision and reasons
Parameters
source_identity Source identifier
payload_summary Human-readable command summary
correlation_id Optional correlation ID
result Pointer to store the gateway decision
Returns
ESP_OK if processed successfully, error code otherwise
Definition at line 76 of file test_gcs_security.c.
blackbox_is_initialized()
bool blackbox_is_initialized (void)
Check if blackbox service is initialized.
Returns
true if initialized, false otherwise
Definition at line 92 of file test_gcs_security.c.
blackbox_log_event()
esp_err_t blackbox_log_event (const char * event_type, const char * severity, const char * attrs)
Log a blackbox event.
Serializes event to NDJSON format and queues for background writing.
Parameters
event_type Type of event (from blackbox_event_type_t)
severity Event severity (optional, can be NULL)
attrs JSON string with event attributes
Returns
ESP_OK on success, error code otherwise
Definition at line 97 of file test_gcs_security.c.
esp_timer_get_time()
uint64_t esp_timer_get_time (void)
Definition at line 156 of file test_gcs_security.c.
main()
int main (void)
Definition at line 456 of file test_gcs_security.c.
scp_connection_get_name()
const char * scp_connection_get_name (uint8_t conn_type)
Get connection type name string.
Parameters
conn_type Connection type (SCP_CONN_*)
Returns
Connection type name for logging/display
Definition at line 132 of file test_gcs_security.c.
Referenced by cmd_scp_sessions(), gcs_gateway_log_security_violation(), and test_session_creation_variants().
scp_role_get_name()
const char * scp_role_get_name (uint8_t role)
Get role name string.
Parameters
role Operator role (SCP_ROLE_*)
Returns
Role name string for logging/display
Definition at line 117 of file test_gcs_security.c.
Referenced by cmd_scp_sessions(), cmd_scp_telemetry(), gcs_gateway_log_security_violation(), gcs_gateway_log_to_audit_system(), gcs_gateway_process_arm_command(), gcs_gateway_process_disarm_command(), gcs_gateway_process_mode_change(), gcs_gateway_send_tlm_status_targeted(), and test_session_creation_variants().
scp_session_check_rate_limit()
bool scp_session_check_rate_limit (uint32_t session_id, uint32_t current_time_ms)
Check Rate Limiting.
Verifies if session can send another command based on rate limiting rules. Updates rate limiting state if command is allowed.
Parameters
session_id Session identifier
current_time_ms Current system time (milliseconds)
Returns
true if command allowed, false if rate limited
Definition at line 147 of file test_gcs_security.c.
References find_session_by_id(), and update_rate_limit().
Referenced by gcs_gateway_check_enhanced_rate_limit(), test_rate_limiting_basic(), test_rate_limiting_burst(), test_rate_limiting_invalid_session(), test_rate_limiting_security_violation_escalation(), test_security_monitoring_cli_integration(), test_security_rate_limit_window_reset(), and test_security_rate_limiting_enforcement().
scp_session_get_by_id()
scp_session_t * scp_session_get_by_id (uint32_t session_id)
Get Session by ID.
Retrieves session information for the specified session ID.
Parameters
session_id Session identifier
Returns
Pointer to session structure, or NULL if not found
Definition at line 108 of file test_gcs_security.c.
References find_session_by_id().
Referenced by gcs_gateway_audit_auth_failure(), gcs_gateway_audit_command_attempt(), gcs_gateway_audit_security_violation(), gcs_gateway_log_security_violation(), gcs_gateway_log_to_audit_system(), gcs_gateway_process_cmd_control(), gcs_gateway_send_response(), gcs_gateway_set_session_telemetry(), gcs_gateway_validate_sequence(), test_security_session_timeout(), test_session_authentication_valid(), test_session_closure(), test_session_creation_basic(), test_session_creation_variants(), and test_session_timeout().
setUp()
void setUp (void)
Definition at line 165 of file test_gcs_security.c.
tearDown()
void tearDown (void)
Definition at line 183 of file test_gcs_security.c.
test_audit_system_integration_success()
void test_audit_system_integration_success (void)
Definition at line 329 of file test_gcs_security.c.
test_audit_system_integration_unavailable()
void test_audit_system_integration_unavailable (void)
Definition at line 347 of file test_gcs_security.c.
test_gcs_gateway_log_critical_security_event_blackbox_unavailable()
void test_gcs_gateway_log_critical_security_event_blackbox_unavailable (void)
Definition at line 210 of file test_gcs_security.c.
test_gcs_gateway_log_critical_security_event_null_parameters()
void test_gcs_gateway_log_critical_security_event_null_parameters (void)
Definition at line 224 of file test_gcs_security.c.
test_gcs_gateway_log_critical_security_event_success()
void test_gcs_gateway_log_critical_security_event_success (void)
Definition at line 192 of file test_gcs_security.c.
test_rate_limiting_enforcement()
void test_rate_limiting_enforcement (void)
Definition at line 242 of file test_gcs_security.c.
test_replay_attack_detection_invalid_sequence()
void test_replay_attack_detection_invalid_sequence (void)
Definition at line 287 of file test_gcs_security.c.
test_replay_attack_detection_valid_sequence()
void test_replay_attack_detection_valid_sequence (void)
Definition at line 267 of file test_gcs_security.c.
test_security_event_categorization()
void test_security_event_categorization (void)
Definition at line 363 of file test_gcs_security.c.
test_security_logging_memory_bounds()
void test_security_logging_memory_bounds (void)
Definition at line 438 of file test_gcs_security.c.
test_security_logging_performance()
void test_security_logging_performance (void)
Definition at line 423 of file test_gcs_security.c.
test_security_violation_context_capture()
void test_security_violation_context_capture (void)
Definition at line 391 of file test_gcs_security.c.
test_sequence_number_wraparound()
void test_sequence_number_wraparound (void)
Definition at line 312 of file test_gcs_security.c.
test_session_security_context()
void test_session_security_context (void)
Definition at line 405 of file test_gcs_security.c.
Variable Documentation
mock_audit_call_count
uint32_t mock_audit_call_count = 0 static
Definition at line 56 of file test_gcs_security.c.
mock_audit_initialized
bool mock_audit_initialized = true static
Definition at line 55 of file test_gcs_security.c.
mock_blackbox_call_count
uint32_t mock_blackbox_call_count = 0 static
Definition at line 62 of file test_gcs_security.c.
mock_blackbox_initialized
bool mock_blackbox_initialized = true static
Definition at line 61 of file test_gcs_security.c.
mock_last_audit_action
char mock_last_audit_action[128] = {0} static
Definition at line 58 of file test_gcs_security.c.
mock_last_audit_source
char mock_last_audit_source[64] = {0} static
Definition at line 57 of file test_gcs_security.c.
mock_last_event_attrs
char mock_last_event_attrs[512] = {0} static
Definition at line 64 of file test_gcs_security.c.
mock_last_event_type
char mock_last_event_type[32] = {0} static
Definition at line 63 of file test_gcs_security.c.
test_session
scp_session_t test_session static
Initial value:
= {
    .session_id = 0x12345678 ,
    .operator_role = SCP_ROLE_PILOT ,
    .last_sequence_num = 42 - 1,
    .connection_type = SCP_CONN_UART,
    .created_time = 1000,
    .last_activity = 2000,
    .rate_limit = {
        .command_count = 0,
        .window_start = 0,
        .burst_used = 0,
        .penalty_until = 0}}
Definition at line 41 of file test_gcs_security.c.