ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/tests/unit/test_scp_crypto.c File Reference
test_scp_crypto.c File Reference
Unit Tests for SCP Cryptographic Functions.
#include "unity.h"
#include "scp_crypto.h"
#include <string.h>
#include <stdint.h>
Macros
#define TEST_KEY_SIZE 32
#define TEST_MESSAGE_MAX 256
#define TEST_HMAC_TAG_SIZE 16
#define TEST_ITERATIONS 1000
Functions
void setUp (void)
void tearDown (void)
void test_hmac_rfc4231_vectors (void)
Test HMAC generation with RFC 4231 test vectors.
void test_hmac_various_sizes (void)
Test HMAC generation with various message sizes.
void test_hmac_generation_errors (void)
Test HMAC generation error conditions.
void test_hmac_verification (void)
Test HMAC verification with correct and incorrect tags.
void test_hmac_key_sensitivity (void)
Test HMAC verification with different keys.
void test_key_generation (void)
Test cryptographic key generation.
void test_key_generation_errors (void)
Test key generation error conditions.
void test_key_derivation (void)
Test PBKDF2 key derivation.
void test_key_derivation_parameters (void)
Test key derivation with different parameters.
void test_secure_memcmp (void)
Test secure memory comparison.
void test_secure_memclear (void)
Test secure memory clearing.
void test_random_generation (void)
Test random number generation.
void test_random_generation_errors (void)
Test random generation error conditions.
void test_key_structure (void)
Test key structure creation and validation.
void test_end_to_end_authentication (void)
Test end-to-end authentication scenario.
void test_crypto_statistics (void)
Test crypto statistics.
void app_main (void)
Variables
static const uint8_t rfc4231_key1 [32]
static const char rfc4231_data1 [] = "Hi There"
static const uint8_t rfc4231_hmac1_truncated [16]
Detailed Description
Unit Tests for SCP Cryptographic Functions.
Tests HMAC-SHA256 authentication, key management, secure utilities, and cryptographic validation for the Secure Control Protocol (SCP) v1.1.
Author
Scout ISR Project
Version
1.1
Date
2025-10-26
Definition in file test_scp_crypto.c.
Macro Definition Documentation
TEST_HMAC_TAG_SIZE
#define TEST_HMAC_TAG_SIZE 16
Definition at line 21 of file test_scp_crypto.c.
TEST_ITERATIONS
#define TEST_ITERATIONS 1000
Definition at line 22 of file test_scp_crypto.c.
TEST_KEY_SIZE
#define TEST_KEY_SIZE 32
Definition at line 19 of file test_scp_crypto.c.
TEST_MESSAGE_MAX
#define TEST_MESSAGE_MAX 256
Definition at line 20 of file test_scp_crypto.c.
Function Documentation
app_main()
void app_main (void)
Definition at line 562 of file test_scp_crypto.c.
setUp()
void setUp (void)
Definition at line 39 of file test_scp_crypto.c.
tearDown()
void tearDown (void)
Definition at line 46 of file test_scp_crypto.c.
test_crypto_statistics()
void test_crypto_statistics (void)
Test crypto statistics.
Definition at line 533 of file test_scp_crypto.c.
References scp_crypto_generate_key(), scp_crypto_get_stats(), scp_crypto_hmac_generate(), and scp_crypto_hmac_verify().
test_end_to_end_authentication()
void test_end_to_end_authentication (void)
Test end-to-end authentication scenario.
Definition at line 486 of file test_scp_crypto.c.
References scp_crypto_generate_key(), scp_crypto_hmac_generate(), and scp_crypto_hmac_verify().
test_hmac_generation_errors()
void test_hmac_generation_errors (void)
Test HMAC generation error conditions.
Definition at line 118 of file test_scp_crypto.c.
References scp_crypto_hmac_generate().
test_hmac_key_sensitivity()
void test_hmac_key_sensitivity (void)
Test HMAC verification with different keys.
Definition at line 183 of file test_scp_crypto.c.
References scp_crypto_hmac_generate(), and scp_crypto_hmac_verify().
test_hmac_rfc4231_vectors()
void test_hmac_rfc4231_vectors (void)
Test HMAC generation with RFC 4231 test vectors.
Definition at line 58 of file test_scp_crypto.c.
References scp_crypto_hmac_generate().
test_hmac_various_sizes()
void test_hmac_various_sizes (void)
Test HMAC generation with various message sizes.
Definition at line 75 of file test_scp_crypto.c.
References scp_crypto_hmac_generate().
test_hmac_verification()
void test_hmac_verification (void)
Test HMAC verification with correct and incorrect tags.
Definition at line 148 of file test_scp_crypto.c.
References scp_crypto_hmac_generate(), and scp_crypto_hmac_verify().
test_key_derivation()
void test_key_derivation (void)
Test PBKDF2 key derivation.
Definition at line 265 of file test_scp_crypto.c.
References scp_crypto_derive_key().
test_key_derivation_parameters()
void test_key_derivation_parameters (void)
Test key derivation with different parameters.
Definition at line 302 of file test_scp_crypto.c.
References scp_crypto_derive_key().
test_key_generation()
void test_key_generation (void)
Test cryptographic key generation.
Definition at line 219 of file test_scp_crypto.c.
References scp_crypto_generate_key().
test_key_generation_errors()
void test_key_generation_errors (void)
Test key generation error conditions.
Definition at line 251 of file test_scp_crypto.c.
References scp_crypto_generate_key().
test_key_structure()
void test_key_structure (void)
Test key structure creation and validation.
Definition at line 447 of file test_scp_crypto.c.
References scp_crypto_key_create(), and scp_crypto_key_is_valid().
test_random_generation()
void test_random_generation (void)
Test random number generation.
Definition at line 395 of file test_scp_crypto.c.
References scp_crypto_get_random().
test_random_generation_errors()
void test_random_generation_errors (void)
Test random generation error conditions.
Definition at line 429 of file test_scp_crypto.c.
References scp_crypto_get_random().
test_secure_memclear()
void test_secure_memclear (void)
Test secure memory clearing.
Definition at line 356 of file test_scp_crypto.c.
References scp_crypto_secure_memclear().
test_secure_memcmp()
void test_secure_memcmp (void)
Test secure memory comparison.
Definition at line 335 of file test_scp_crypto.c.
References scp_crypto_secure_memcmp().
Variable Documentation
rfc4231_data1
const char rfc4231_data1[] = "Hi There" static
Definition at line 30 of file test_scp_crypto.c.
rfc4231_hmac1_truncated
const uint8_t rfc4231_hmac1_truncated[16] static
Initial value:
= {
    0xb0, 0x34, 0x4c, 0x61, 0xd8, 0xdb, 0x38, 0x53,
    0x5c, 0xa8, 0xaf, 0xce, 0xaf, 0x0b, 0xf1, 0x2b}
Definition at line 31 of file test_scp_crypto.c.
rfc4231_key1
const uint8_t rfc4231_key1[32] static
Initial value:
= {
    0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b,
    0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b,
    0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b,
    0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b}
Definition at line 25 of file test_scp_crypto.c.