ACP - Autonomous Command Protocol: tests/test_hmac_vectors.c File Reference
test_hmac_vectors.c File Reference
HMAC test vectors and validation for ACP crypto implementation.
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include "acp_protocol.h"
Functions
static void print_hex (const char *label, const uint8_t *data, size_t len)
static void test_rfc4231_vectors (void)
Test HMAC-SHA256 with RFC 4231 test vectors.
static void test_acp_hmac_truncation (void)
Test HMAC with ACP-specific parameters (16-byte truncation).
static void test_hmac_consistency (void)
Test HMAC consistency across multiple calls.
static void test_hmac_key_lengths (void)
Test HMAC with different key lengths.
static void test_constant_time_comparison (void)
Test constant-time comparison.
int main (void)
Detailed Description
HMAC test vectors and validation for ACP crypto implementation.
Definition in file test_hmac_vectors.c.
Function Documentation
main()
int main (void)
Definition at line 236 of file test_hmac_vectors.c.
print_hex()
void print_hex (const char * label, const uint8_t * data, size_t len) static
Definition at line 11 of file test_hmac_vectors.c.
test_acp_hmac_truncation()
void test_acp_hmac_truncation (void) static
Test HMAC with ACP-specific parameters (16-byte truncation).
Definition at line 99 of file test_hmac_vectors.c.
References acp_hmac_sha256(), ACP_HMAC_TAG_LEN, and ACP_KEY_SIZE.
test_constant_time_comparison()
void test_constant_time_comparison (void) static
Test constant-time comparison.
Definition at line 206 of file test_hmac_vectors.c.
References acp_crypto_memcmp_ct(), and ACP_HMAC_TAG_LEN.
test_hmac_consistency()
void test_hmac_consistency (void) static
Test HMAC consistency across multiple calls.
Definition at line 136 of file test_hmac_vectors.c.
References acp_hmac_sha256().
test_hmac_key_lengths()
void test_hmac_key_lengths (void) static
Test HMAC with different key lengths.
Definition at line 162 of file test_hmac_vectors.c.
References acp_hmac_sha256(), and ACP_HMAC_TAG_LEN.
test_rfc4231_vectors()
void test_rfc4231_vectors (void) static
Test HMAC-SHA256 with RFC 4231 test vectors.
Definition at line 24 of file test_hmac_vectors.c.
References acp_hmac_sha256().