ACP - Autonomous Command Protocol: /Users/paulzanna/Github/Scout/tests/unit/test_scp_session.c File Reference
test_scp_session.c File Reference
Unit Tests for SCP Session Management.
#include "unity.h"
#include "scp_session.h"
#include "scp_crypto.h"
#include <string.h>
#include <stdint.h>
Macros
#define TEST_SESSION_TIMEOUT 900000
#define TEST_RATE_SUSTAINED 5
#define TEST_RATE_BURST 20
Functions
static void advance_mock_time (uint32_t delta_ms)
static void reset_mock_time (void)
void setUp (void)
void tearDown (void)
void test_session_creation_basic (void)
Test basic session creation.
void test_session_creation_variants (void)
Test session creation with different roles and connections.
void test_session_creation_errors (void)
Test session creation error conditions.
void test_session_creation_limit (void)
Test maximum session limit.
void test_session_authentication_valid (void)
Test session authentication with valid credentials.
void test_session_authentication_failures (void)
Test session authentication failures.
void test_role_based_authorization (void)
Test role-based command authorization.
void test_session_command_authorization (void)
Test session-based command authorization.
void test_rate_limiting_basic (void)
Test basic rate limiting functionality.
void test_rate_limiting_burst (void)
Test rate limiting burst behavior.
void test_rate_limiting_invalid_session (void)
Test rate limiting with invalid session.
void test_session_closure (void)
Test session closure.
void test_session_timeout (void)
Test session timeout and cleanup.
void test_session_list (void)
Test session list retrieval.
void test_session_priority (void)
Test session priority calculation.
void test_session_statistics (void)
Test session statistics tracking.
void app_main (void)
Variables
static uint32_t mock_time_ms = 0
Detailed Description
Unit Tests for SCP Session Management.
Tests session creation, authentication, role-based authorization, rate limiting, and session lifecycle management for the Secure Control Protocol (SCP) v1.1.
Author
Scout ISR Project
Version
1.1
Date
2025-10-26
Definition in file test_scp_session.c.
Macro Definition Documentation
TEST_RATE_BURST
#define TEST_RATE_BURST 20
Definition at line 22 of file test_scp_session.c.
TEST_RATE_SUSTAINED
#define TEST_RATE_SUSTAINED 5
Definition at line 21 of file test_scp_session.c.
TEST_SESSION_TIMEOUT
#define TEST_SESSION_TIMEOUT 900000
Definition at line 20 of file test_scp_session.c.
Function Documentation
advance_mock_time()
void advance_mock_time (uint32_t delta_ms) static
Definition at line 28 of file test_scp_session.c.
app_main()
void app_main (void)
Definition at line 573 of file test_scp_session.c.
reset_mock_time()
void reset_mock_time (void) static
Definition at line 33 of file test_scp_session.c.
setUp()
void setUp (void)
Definition at line 42 of file test_scp_session.c.
tearDown()
void tearDown (void)
Definition at line 50 of file test_scp_session.c.
test_rate_limiting_basic()
void test_rate_limiting_basic (void)
Test basic rate limiting functionality.
Definition at line 323 of file test_scp_session.c.
References scp_session_check_rate_limit(), and scp_session_create().
test_rate_limiting_burst()
void test_rate_limiting_burst (void)
Test rate limiting burst behavior.
Definition at line 354 of file test_scp_session.c.
References scp_session_check_rate_limit(), and scp_session_create().
test_rate_limiting_invalid_session()
void test_rate_limiting_invalid_session (void)
Test rate limiting with invalid session.
Definition at line 383 of file test_scp_session.c.
References scp_session_check_rate_limit().
test_role_based_authorization()
void test_role_based_authorization (void)
Test role-based command authorization.
Definition at line 263 of file test_scp_session.c.
References scp_role_can_execute().
test_session_authentication_failures()
void test_session_authentication_failures (void)
Test session authentication failures.
Definition at line 218 of file test_scp_session.c.
References scp_crypto_hmac_generate(), scp_session_authenticate(), and scp_session_create().
test_session_authentication_valid()
void test_session_authentication_valid (void)
Test session authentication with valid credentials.
Definition at line 185 of file test_scp_session.c.
References scp_crypto_hmac_generate(), scp_session_authenticate(), scp_session_create(), and scp_session_get_by_id().
test_session_closure()
void test_session_closure (void)
Test session closure.
Definition at line 399 of file test_scp_session.c.
References scp_session_close(), scp_session_create(), scp_session_get_active_count(), and scp_session_get_by_id().
test_session_command_authorization()
void test_session_command_authorization (void)
Test session-based command authorization.
Definition at line 287 of file test_scp_session.c.
References scp_session_authorize_command(), and scp_session_create().
test_session_creation_basic()
void test_session_creation_basic (void)
Test basic session creation.
Definition at line 70 of file test_scp_session.c.
References scp_session_create(), and scp_session_get_by_id().
test_session_creation_errors()
void test_session_creation_errors (void)
Test session creation error conditions.
Definition at line 130 of file test_scp_session.c.
References scp_session_create().
test_session_creation_limit()
void test_session_creation_limit (void)
Test maximum session limit.
Definition at line 152 of file test_scp_session.c.
References scp_session_create(), and scp_session_get_active_count().
test_session_creation_variants()
void test_session_creation_variants (void)
Test session creation with different roles and connections.
Definition at line 93 of file test_scp_session.c.
References scp_connection_get_name(), scp_role_get_name(), scp_session_create(), and scp_session_get_by_id().
test_session_list()
void test_session_list (void)
Test session list retrieval.
Definition at line 459 of file test_scp_session.c.
References scp_session_create(), and scp_session_get_list().
test_session_priority()
void test_session_priority (void)
Test session priority calculation.
Definition at line 499 of file test_scp_session.c.
References scp_session_create(), and scp_session_get_priority().
test_session_statistics()
void test_session_statistics (void)
Test session statistics tracking.
Definition at line 535 of file test_scp_session.c.
References scp_session_create(), scp_session_get_stats(), and scp_session_reset_stats().
test_session_timeout()
void test_session_timeout (void)
Test session timeout and cleanup.
Definition at line 426 of file test_scp_session.c.
References scp_session_cleanup_expired(), scp_session_create(), scp_session_get_by_id(), and scp_session_update_activity().
Variable Documentation
mock_time_ms
uint32_t mock_time_ms = 0 static
Definition at line 25 of file test_scp_session.c.