ACP - Autonomous Command Protocol: /Users/paulzanna/Github/acp/acp_cobs.c File Reference
/Users/paulzanna/Github/acp/acp_cobs.c File Reference
COBS (Consistent Overhead Byte Stuffing) implementation.
#include "acp_cobs.h"
#include "acp_errors.h"
#include <string.h>
Functions
int acp_cobs_encode (const uint8_t *input, size_t input_len, uint8_t *output, size_t output_size, size_t *encoded_len)
Encode data using COBS algorithm.
int acp_cobs_decode (const uint8_t *input, size_t input_len, uint8_t *output, size_t output_size, size_t *decoded_len)
Decode COBS-encoded data.
size_t acp_cobs_max_encoded_size (size_t input_len)
Calculate maximum encoded size for given input length.
size_t acp_cobs_max_decoded_size (size_t encoded_len)
Calculate maximum decoded size for given encoded length.
int acp_cobs_validate (const uint8_t *data, size_t len)
Validate COBS-encoded data format.
int acp_cobs_decoder_init (acp_cobs_decoder_t *decoder, uint8_t *buffer, size_t buffer_size)
Initialize COBS streaming decoder.
void acp_cobs_decoder_reset (acp_cobs_decoder_t *decoder)
Reset COBS decoder to idle state.
int acp_cobs_decoder_feed_byte (acp_cobs_decoder_t *decoder, uint8_t byte)
Feed bytes to COBS streaming decoder.
int acp_cobs_decoder_get_frame (acp_cobs_decoder_t *decoder, uint8_t *output, size_t output_size, size_t *decoded_len)
Get decoded frame from streaming decoder.
acp_cobs_decoder_state_t acp_cobs_decoder_get_state (const acp_cobs_decoder_t *decoder)
Get current decoder state.
Detailed Description
COBS (Consistent Overhead Byte Stuffing) implementation.
Version
0.3.0
Date
2025-10-27
Definition in file acp_cobs.c.
Function Documentation
acp_cobs_decode()
int acp_cobs_decode (const uint8_t * input, size_t input_len, uint8_t * output, size_t output_size, size_t * decoded_len)
Decode COBS-encoded data.
Decodes COBS-encoded data back to original form. The input must be a complete COBS-encoded block without frame delimiters.
Parameters
input COBS-encoded input data
input_len Length of encoded input data
output Output buffer for decoded data
output_size Size of output buffer
decoded_len Returns the actual decoded length
Returns
0 on success, negative error code on failure
< Invalid parameter passed
< Operation successful
< COBS decode error
< COBS decode error
< Output buffer too small
< Operation successful
Definition at line 94 of file acp_cobs.c.
References ACP_COBS_BLOCK_SIZE, ACP_ERR_BUFFER_TOO_SMALL, ACP_ERR_COBS_DECODE, ACP_ERR_INVALID_PARAM, and ACP_OK.
Referenced by acp_cobs_decoder_get_frame(), and acp_frame_decode().
acp_cobs_decoder_feed_byte()
int acp_cobs_decoder_feed_byte (acp_cobs_decoder_t * decoder, uint8_t byte)
Feed bytes to COBS streaming decoder.
Processes incoming bytes and accumulates frame data. When a complete frame is received (delimiter found), the decoder state becomes COMPLETE.
Parameters
decoder Decoder context
byte Input byte to process
Returns
1 if frame complete, 0 if more data needed, negative on error
< Invalid parameter passed
< Output buffer too small
< Output buffer too small
< Internal library error
< Internal library error
Definition at line 253 of file acp_cobs.c.
References ACP_COBS_DECODER_COMPLETE, ACP_COBS_DECODER_ERROR, ACP_COBS_DECODER_IDLE, ACP_COBS_DECODER_RECEIVING, ACP_COBS_DELIMITER, ACP_ERR_BUFFER_TOO_SMALL, ACP_ERR_INTERNAL, ACP_ERR_INVALID_PARAM, acp_cobs_decoder_t::buffer, acp_cobs_decoder_t::buffer_pos, acp_cobs_decoder_t::buffer_size, acp_cobs_decoder_t::error_code, and acp_cobs_decoder_t::state.
acp_cobs_decoder_get_frame()
int acp_cobs_decoder_get_frame (acp_cobs_decoder_t * decoder, uint8_t * output, size_t output_size, size_t * decoded_len)
Get decoded frame from streaming decoder.
Should be called when decoder state is COMPLETE to retrieve the decoded frame data.
Parameters
decoder Decoder context
output Output buffer for decoded frame
output_size Size of output buffer
decoded_len Returns decoded frame length
Returns
0 on success, negative error code on failure
< Invalid parameter passed
< Invalid operation state
Definition at line 309 of file acp_cobs.c.
References acp_cobs_decode(), ACP_COBS_DECODER_COMPLETE, acp_cobs_decoder_reset(), ACP_ERR_INVALID_PARAM, ACP_ERR_INVALID_STATE, acp_cobs_decoder_t::buffer, acp_cobs_decoder_t::buffer_pos, and acp_cobs_decoder_t::state.
acp_cobs_decoder_get_state()
acp_cobs_decoder_state_t acp_cobs_decoder_get_state (const acp_cobs_decoder_t * decoder)
Get current decoder state.
Parameters
decoder Decoder context
Returns
Current decoder state
Definition at line 332 of file acp_cobs.c.
References ACP_COBS_DECODER_ERROR, and acp_cobs_decoder_t::state.
acp_cobs_decoder_init()
int acp_cobs_decoder_init (acp_cobs_decoder_t * decoder, uint8_t * buffer, size_t buffer_size)
Initialize COBS streaming decoder.
Parameters
decoder Decoder context to initialize
buffer Frame buffer for accumulating data
buffer_size Size of frame buffer
Returns
0 on success, negative error code on failure
< Invalid parameter passed
< Operation successful
< Operation successful
Definition at line 226 of file acp_cobs.c.
References ACP_COBS_DECODER_IDLE, ACP_ERR_INVALID_PARAM, ACP_OK, acp_cobs_decoder_t::buffer, acp_cobs_decoder_t::buffer_pos, acp_cobs_decoder_t::buffer_size, acp_cobs_decoder_t::error_code, and acp_cobs_decoder_t::state.
acp_cobs_decoder_reset()
void acp_cobs_decoder_reset (acp_cobs_decoder_t * decoder)
Reset COBS decoder to idle state.
Parameters
decoder Decoder context to reset
< Operation successful
Definition at line 243 of file acp_cobs.c.
References ACP_COBS_DECODER_IDLE, ACP_OK, acp_cobs_decoder_t::buffer_pos, acp_cobs_decoder_t::error_code, and acp_cobs_decoder_t::state.
Referenced by acp_cobs_decoder_get_frame().
acp_cobs_encode()
int acp_cobs_encode (const uint8_t * input, size_t input_len, uint8_t * output, size_t output_size, size_t * encoded_len)
Encode data using COBS algorithm.
Encodes input data to eliminate zero bytes, allowing zero to be used as a reliable frame delimiter. The encoded data is guaranteed to contain no zero bytes.
Parameters
input Input data to encode
input_len Length of input data in bytes
output Output buffer for encoded data (must be large enough)
output_size Size of output buffer
encoded_len Returns the actual encoded length
Returns
0 on success, negative error code on failure
< Invalid parameter passed
< Output buffer too small
< Operation successful
Definition at line 39 of file acp_cobs.c.
References ACP_COBS_BLOCK_SIZE, acp_cobs_max_encoded_size(), ACP_ERR_BUFFER_TOO_SMALL, ACP_ERR_INVALID_PARAM, and ACP_OK.
Referenced by acp_frame_encode().
acp_cobs_max_decoded_size()
size_t acp_cobs_max_decoded_size (size_t encoded_len)
Calculate maximum decoded size for given encoded length.
Parameters
encoded_len Encoded data length
Returns
Maximum possible decoded length
Definition at line 171 of file acp_cobs.c.
acp_cobs_max_encoded_size()
size_t acp_cobs_max_encoded_size (size_t input_len)
Calculate maximum encoded size for given input length.
Parameters
input_len Input data length
Returns
Maximum possible encoded length (including overhead)
Definition at line 162 of file acp_cobs.c.
References ACP_COBS_OVERHEAD.
Referenced by acp_cobs_encode(), acp_frame_encode(), and acp_frame_encoded_size().
acp_cobs_validate()
int acp_cobs_validate (const uint8_t * data, size_t len)
Validate COBS-encoded data format.
Checks if the provided data appears to be valid COBS-encoded data by verifying the overhead bytes are within valid ranges.
Parameters
data COBS-encoded data to validate
len Length of data
Returns
1 if valid, 0 if invalid
Definition at line 181 of file acp_cobs.c.
References ACP_COBS_BLOCK_SIZE.