ACP - Autonomous Command Protocol: /Users/paulzanna/Github/acp/acp_protocol.h File Reference
/Users/paulzanna/Github/acp/acp_protocol.h File Reference
ACP (Autonomous Command Protocol) - Public API Header.
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
Classes
struct acp_frame_t
ACP frame structure (host representation).
struct acp_session_t
ACP session structure for authentication state.
Macros
#define ACP_PROTOCOL_VERSION_MAJOR 0
ACP protocol version (major.minor).
#define ACP_PROTOCOL_VERSION_MINOR 3
#define ACP_MAX_PAYLOAD_SIZE 1024
Maximum payload size in bytes.
#define ACP_MAX_FRAME_SIZE (ACP_MAX_PAYLOAD_SIZE + 64)
Maximum frame size including all overhead.
#define ACP_HMAC_TAG_LEN 16
HMAC tag length (truncated to 16 bytes).
#define ACP_KEY_SIZE 32
Key size for HMAC-SHA256 (32 bytes).
#define ACP_CRC16_SIZE 2
CRC16 checksum size in bytes.
#define ACP_COBS_DELIMITER 0x00
COBS delimiter byte.
#define ACP_SYNC_BYTE_1 0xAA
Frame sync byte 1.
#define ACP_SYNC_BYTE_2 0x55
Frame sync byte 2.
#define ACP_PROTOCOL_VERSION 0x11
ACP protocol version.
#define ACP_FLAG_AUTHENTICATED 0x01
ACP frame flag bits.
#define ACP_FLAG_RESERVED_1 0x02
Reserved for future use.
#define ACP_FLAG_RESERVED_2 0x04
Reserved for future use.
#define ACP_FLAG_RESERVED_3 0x08
Reserved for future use.
#define ACP_FLAG_RESERVED_4 0x10
Reserved for future use.
#define ACP_FLAG_RESERVED_5 0x20
Reserved for future use.
#define ACP_FLAG_RESERVED_6 0x40
Reserved for future use.
#define ACP_FLAG_RESERVED_7 0x80
Reserved for future use.
#define ACP_STATIC_ASSERT(cond, msg)
#define ACP_STATIC_ASSERT2(cond, msg)
Typedefs
typedef char acp_static_assert___LINE__[(sizeof(acp_wire_header_base_t)==6) ? 1 :-1]
typedef char acp_static_assert2___LINE__[(sizeof(acp_wire_header_t)==10) ? 1 :-1]
Enumerations
enum acp_frame_type_t { ACP_FRAME_TYPE_TELEMETRY = 0x01 , ACP_FRAME_TYPE_COMMAND = 0x02 , ACP_FRAME_TYPE_SYSTEM = 0x03 , ACP_FRAME_TYPE_RESERVED = 0xFF }
ACP frame type enumeration.
enum acp_result_t {
ACP_OK = 0 , ACP_ERR_INVALID_PARAM = -1 , ACP_ERR_BUFFER_TOO_SMALL = -2 , ACP_ERR_NEED_MORE_DATA = -3 ,
ACP_ERR_INVALID_VERSION = -10 , ACP_ERR_INVALID_TYPE = -11 , ACP_ERR_PAYLOAD_TOO_LARGE = -12 , ACP_ERR_MALFORMED_FRAME = -13 ,
ACP_ERR_COBS_DECODE = -20 , ACP_ERR_COBS_ENCODE = -21 , ACP_ERR_CRC_MISMATCH = -30 , ACP_ERR_AUTH_REQUIRED = -40 ,
ACP_ERR_AUTH_FAILED = -41 , ACP_ERR_REPLAY = -42 , ACP_ERR_KEY_NOT_FOUND = -43 , ACP_ERR_SESSION_NOT_INIT = -44 ,
ACP_ERR_SESSION_EXPIRED = -45 , ACP_ERR_REPLAY_ATTACK = -42 , ACP_ERR_IO = -80 , ACP_ERR_INVALID_FORMAT = -81 ,
ACP_ERR_NOT_IMPLEMENTED = -90 , ACP_ERR_INTERNAL = -99
}
ACP result/error code enumeration.
Functions
struct __attribute__ ((packed))
Base wire frame header structure (always present).
static size_t acp_wire_header_size (uint8_t flags)
Calculate wire header size based on flags.
acp_result_t acp_init (void)
Initialize the ACP library.
void acp_cleanup (void)
Cleanup the ACP library.
acp_result_t acp_encode_frame (uint8_t type, uint8_t flags, const uint8_t *payload, size_t payload_len, acp_session_t *session, uint8_t *output, size_t *output_len)
Encode an ACP frame.
acp_result_t acp_decode_frame (const uint8_t *input, size_t input_len, acp_frame_t *frame, size_t *consumed, acp_session_t *session)
Decode an ACP frame from stream.
acp_result_t acp_session_init (acp_session_t *session, uint32_t key_id, const uint8_t *key, size_t key_len, uint64_t nonce)
Initialize an ACP session.
acp_result_t acp_session_rotate (acp_session_t *session, const uint8_t *new_key, size_t new_key_len, uint64_t new_nonce)
Rotate session key or nonce.
acp_result_t acp_session_reset_sequence (acp_session_t *session)
Reset session sequence counters.
acp_result_t acp_keystore_init_session (acp_session_t *session, uint32_t key_id, uint64_t nonce)
Initialize session with key from keystore.
acp_result_t acp_keystore_init (void)
Initialize keystore.
acp_result_t acp_keystore_get (uint32_t key_id, uint8_t *key_data, size_t key_size)
Get key from keystore.
acp_result_t acp_keystore_set (uint32_t key_id, const uint8_t *key_data, size_t key_size)
Set key in keystore.
acp_result_t acp_keystore_clear (void)
Clear all keys from keystore.
const char * acp_error_string (acp_result_t result)
Get human-readable error string.
bool acp_is_valid_frame_type (uint8_t type)
Validate frame type.
bool acp_frame_requires_auth (uint8_t type)
Check if frame type requires authentication.
uint16_t acp_htons (uint16_t host_val)
Convert host uint16 to network byte order.
uint16_t acp_ntohs (uint16_t net_val)
Convert network uint16 to host byte order.
uint32_t acp_htonl (uint32_t host_val)
Convert host uint32 to network byte order.
uint32_t acp_ntohl (uint32_t net_val)
Convert network uint32 to host byte order.
void acp_hmac_sha256 (const uint8_t *key, size_t key_len, const uint8_t *data, size_t data_len, uint8_t *mac)
Compute HMAC-SHA256.
int acp_crypto_memcmp_ct (const void *a, const void *b, size_t len)
Constant-time memory comparison for cryptographic operations.
int acp_crypto_self_test (void)
Run comprehensive crypto self-tests.
int acp_frame_encode (const acp_frame_t *frame, uint8_t *output, size_t output_size, size_t *bytes_written)
Encode ACP frame to wire format.
int acp_frame_decode (const uint8_t *input, size_t input_size, acp_frame_t *frame, size_t *bytes_consumed)
Decode wire format to ACP frame.
size_t acp_frame_encoded_size (const acp_frame_t *frame)
Calculate encoded frame size.
int acp_frame_create_telemetry (acp_frame_t *frame, uint8_t msg_type, uint32_t sequence, const void *payload, size_t payload_len)
Create telemetry frame.
int acp_frame_create_command (acp_frame_t *frame, uint8_t msg_type, uint32_t sequence, uint8_t priority, const void *payload, size_t payload_len)
Create command frame.
Variables
acp_wire_header_base_t
acp_wire_header_t
Detailed Description
ACP (Autonomous Command Protocol) - Public API Header.
This header defines the complete public interface for the ACP library, including frame encoding/decoding, session management, and error handling.
Version
0.3.0
Date
2025-10-27
Copyright
Copyright (c) 2025 Northbound Networks Pty. Ltd.
Definition in file acp_protocol.h.
Macro Definition Documentation
ACP_COBS_DELIMITER
#define ACP_COBS_DELIMITER 0x00
COBS delimiter byte.
Definition at line 71 of file acp_protocol.h.
ACP_CRC16_SIZE
#define ACP_CRC16_SIZE 2
CRC16 checksum size in bytes.
Definition at line 68 of file acp_protocol.h.
ACP_FLAG_AUTHENTICATED
#define ACP_FLAG_AUTHENTICATED 0x01
ACP frame flag bits.
Frame includes HMAC authentication
Definition at line 100 of file acp_protocol.h.
Referenced by acp_decode_frame(), acp_encode_frame(), acp_frame_decode(), acp_frame_encode(), and acp_wire_header_size().
ACP_FLAG_RESERVED_1
#define ACP_FLAG_RESERVED_1 0x02
Reserved for future use.
Definition at line 101 of file acp_protocol.h.
ACP_FLAG_RESERVED_2
#define ACP_FLAG_RESERVED_2 0x04
Reserved for future use.
Definition at line 102 of file acp_protocol.h.
ACP_FLAG_RESERVED_3
#define ACP_FLAG_RESERVED_3 0x08
Reserved for future use.
Definition at line 103 of file acp_protocol.h.
ACP_FLAG_RESERVED_4
#define ACP_FLAG_RESERVED_4 0x10
Reserved for future use.
Definition at line 104 of file acp_protocol.h.
ACP_FLAG_RESERVED_5
#define ACP_FLAG_RESERVED_5 0x20
Reserved for future use.
Definition at line 105 of file acp_protocol.h.
ACP_FLAG_RESERVED_6
#define ACP_FLAG_RESERVED_6 0x40
Reserved for future use.
Definition at line 106 of file acp_protocol.h.
ACP_FLAG_RESERVED_7
#define ACP_FLAG_RESERVED_7 0x80
Reserved for future use.
Definition at line 107 of file acp_protocol.h.
ACP_HMAC_TAG_LEN
#define ACP_HMAC_TAG_LEN 16
HMAC tag length (truncated to 16 bytes).
Definition at line 62 of file acp_protocol.h.
Referenced by acp_decode_frame(), and acp_encode_frame().
ACP_KEY_SIZE
#define ACP_KEY_SIZE 32
Key size for HMAC-SHA256 (32 bytes).
Definition at line 65 of file acp_protocol.h.
Referenced by acp_decode_frame(), acp_encode_frame(), acp_keystore_get(), acp_keystore_init_session(), and acp_keystore_set().
ACP_MAX_FRAME_SIZE
#define ACP_MAX_FRAME_SIZE (ACP_MAX_PAYLOAD_SIZE + 64)
Maximum frame size including all overhead.
Definition at line 59 of file acp_protocol.h.
Referenced by acp_frame_decode(), and acp_frame_encode().
ACP_MAX_PAYLOAD_SIZE
#define ACP_MAX_PAYLOAD_SIZE 1024
Maximum payload size in bytes.
Definition at line 56 of file acp_protocol.h.
Referenced by acp_encode_frame(), acp_frame_create_command(), acp_frame_create_telemetry(), and acp_frame_decode().
ACP_PROTOCOL_VERSION
#define ACP_PROTOCOL_VERSION 0x11
ACP protocol version.
Definition at line 80 of file acp_protocol.h.
Referenced by acp_encode_frame(), acp_frame_create_command(), and acp_frame_create_telemetry().
ACP_PROTOCOL_VERSION_MAJOR
#define ACP_PROTOCOL_VERSION_MAJOR 0
ACP protocol version (major.minor).
Definition at line 52 of file acp_protocol.h.
ACP_PROTOCOL_VERSION_MINOR
#define ACP_PROTOCOL_VERSION_MINOR 3
Definition at line 53 of file acp_protocol.h.
ACP_STATIC_ASSERT
#define ACP_STATIC_ASSERT (cond, msg)
Value:
typedef char acp_static_assert_##__LINE__[(cond) ? 1 : -1]
Definition at line 145 of file acp_protocol.h.
ACP_STATIC_ASSERT2
#define ACP_STATIC_ASSERT2 (cond, msg)
Value:
typedef char acp_static_assert2_##__LINE__[(cond) ? 1 : -1]
Definition at line 148 of file acp_protocol.h.
ACP_SYNC_BYTE_1
#define ACP_SYNC_BYTE_1 0xAA
Frame sync byte 1.
Definition at line 74 of file acp_protocol.h.
ACP_SYNC_BYTE_2
#define ACP_SYNC_BYTE_2 0x55
Frame sync byte 2.
Definition at line 77 of file acp_protocol.h.
Typedef Documentation
acp_static_assert2___LINE__
typedef char acp_static_assert2___LINE__[(sizeof(acp_wire_header_t)==10) ? 1 :-1]
Definition at line 149 of file acp_protocol.h.
acp_static_assert___LINE__
typedef char acp_static_assert___LINE__[(sizeof(acp_wire_header_base_t)==6) ? 1 :-1]
Definition at line 146 of file acp_protocol.h.
Enumeration Type Documentation
acp_frame_type_t
enum acp_frame_type_t
ACP frame type enumeration.
Enumerator
ACP_FRAME_TYPE_TELEMETRY
Telemetry data (MAY be unauthenticated).
ACP_FRAME_TYPE_COMMAND
Command data (MUST be authenticated).
ACP_FRAME_TYPE_SYSTEM
System/status messages.
ACP_FRAME_TYPE_RESERVED
Reserved for future use.
Definition at line 87 of file acp_protocol.h.
acp_result_t
enum acp_result_t
ACP result/error code enumeration.
Enumerator
ACP_OK
Success.
ACP_ERR_INVALID_PARAM
Invalid parameter.
ACP_ERR_BUFFER_TOO_SMALL
Output buffer too small.
ACP_ERR_NEED_MORE_DATA
Need more input data.
ACP_ERR_INVALID_VERSION
Unsupported protocol version.
ACP_ERR_INVALID_TYPE
Invalid frame type.
ACP_ERR_PAYLOAD_TOO_LARGE
Payload exceeds ACP_MAX_PAYLOAD_SIZE.
ACP_ERR_MALFORMED_FRAME
Frame structure is malformed.
ACP_ERR_COBS_DECODE
COBS decode error.
ACP_ERR_COBS_ENCODE
COBS encode error.
ACP_ERR_CRC_MISMATCH
CRC16 verification failed.
ACP_ERR_AUTH_REQUIRED
Authentication required but not present.
ACP_ERR_AUTH_FAILED
HMAC authentication failed.
ACP_ERR_REPLAY
Replay attack detected.
ACP_ERR_KEY_NOT_FOUND
Key not found in keystore.
ACP_ERR_SESSION_NOT_INIT
Session not initialized.
ACP_ERR_SESSION_EXPIRED
Session has expired.
ACP_ERR_REPLAY_ATTACK
Replay attack detected (alias).
ACP_ERR_IO
Input/output error.
ACP_ERR_INVALID_FORMAT
Invalid file/data format.
ACP_ERR_NOT_IMPLEMENTED
Feature not implemented.
ACP_ERR_INTERNAL
Internal error.
Definition at line 207 of file acp_protocol.h.
Function Documentation
__attribute__()
struct __attribute__ ((packed))
Base wire frame header structure (always present).
Full wire frame header structure (deprecated - use base + sequence conditionally).
This structure represents the fixed portion of all ACP frames. Additional fields may follow based on flags.
This structure represents the full header when ACP_FLAG_AUTHENTICATED is set. For backward compatibility only.
< Protocol version (ACP_PROTOCOL_VERSION_MAJOR)
< Frame type (acp_frame_type_t)
< Frame flags (ACP_FLAG_*)
< Reserved byte (must be 0 in v0.3)
< Payload length in bytes (0-1024)
< Protocol version (ACP_PROTOCOL_VERSION_MAJOR)
< Frame type (acp_frame_type_t)
< Frame flags (ACP_FLAG_*)
< Reserved byte (must be 0 in v0.3)
< Payload length in bytes (0-1024)
< Sequence number (only if ACP_FLAG_AUTHENTICATED set)
Definition at line 1 of file acp_protocol.h.
acp_cleanup()
void acp_cleanup (void)
Cleanup the ACP library.
Should be called when finished using the ACP library.
Definition at line 79 of file acp.c.
References acp_initialized.
acp_crypto_memcmp_ct()
int acp_crypto_memcmp_ct (const void * a, const void * b, size_t len)
Constant-time memory comparison for cryptographic operations.
Parameters
[in] a First buffer
[in] b Second buffer
[in] len Length to compare
Returns
0 if equal, non-zero if different
Constant-time memory comparison for cryptographic operations.
Compares two memory regions in constant time to prevent timing attacks. This is critical for MAC verification.
Parameters
a First memory region
b Second memory region
len Number of bytes to compare
Returns
0 if equal, non-zero if different
Definition at line 307 of file acp_crypto.c.
Referenced by acp_decode_frame(), acp_hmac_self_test(), acp_hmac_verify(), and acp_sha256_self_test().
acp_crypto_self_test()
int acp_crypto_self_test (void)
Run comprehensive crypto self-tests.
Returns
ACP_OK if all tests pass, error code on failure
Run comprehensive crypto self-tests.
Returns
0 if all tests pass, non-zero if any test fails
Definition at line 378 of file acp_crypto.c.
References acp_hmac_self_test(), and acp_sha256_self_test().
acp_decode_frame()
acp_result_t acp_decode_frame (const uint8_t * input, size_t input_len, acp_frame_t * frame, size_t * consumed, acp_session_t * session)
Decode an ACP frame from stream.
Attempts to decode one complete ACP frame from input stream, handling COBS framing, CRC16 verification, and optional HMAC validation.
Parameters
[in] input Input stream buffer
[in] input_len Length of input data
[out] frame Decoded frame structure
[out] consumed Number of input bytes consumed
[in] session Session for authentication (NULL for unauthenticated)
Returns
ACP_OK on success, ACP_ERR_NEED_MORE_DATA if incomplete, other error codes on failure
< Invalid parameter passed
< Need more input data
< Frame structure is malformed
< Need more input data
< Operation successful
< Frame includes HMAC authentication
< Session not initialized
< Need more input data
< HMAC authentication failed
< Replay attack detected
< Authentication required but missing
< Operation successful
Definition at line 192 of file acp.c.
References ACP_COBS_DELIMITER, acp_crypto_memcmp_ct(), ACP_ERR_AUTH_FAILED, ACP_ERR_AUTH_REQUIRED, ACP_ERR_INVALID_PARAM, ACP_ERR_MALFORMED_FRAME, ACP_ERR_NEED_MORE_DATA, ACP_ERR_REPLAY, ACP_ERR_SESSION_NOT_INIT, ACP_FLAG_AUTHENTICATED, acp_frame_decode(), acp_frame_requires_auth(), acp_hmac_sha256(), ACP_HMAC_TAG_LEN, ACP_KEY_SIZE, ACP_OK, acp_frame_t::flags, acp_session_t::initialized, acp_session_t::key, acp_session_t::last_accepted_seq, acp_frame_t::sequence, and acp_frame_t::type.
acp_encode_frame()
acp_result_t acp_encode_frame (uint8_t type, uint8_t flags, const uint8_t * payload, size_t payload_len, acp_session_t * session, uint8_t * output, size_t * output_len)
Encode an ACP frame.
Encodes payload data into a complete ACP frame with COBS framing, CRC16 integrity, and optional HMAC authentication.
Parameters
[in] type Frame type (acp_frame_type_t)
[in] flags Frame flags (ACP_FLAG_*)
[in] payload Payload data to encode
[in] payload_len Length of payload (0-ACP_MAX_PAYLOAD_SIZE)
[in] session Session for authentication (NULL for unauthenticated)
[out] output Output buffer for encoded frame
[in,out] output_len Input: buffer size, Output: encoded frame length
Returns
ACP_OK on success, error code on failure
< Invalid parameter passed
< Invalid parameter passed
< Payload exceeds maximum size
< Invalid frame type
< Frame includes HMAC authentication
< Authentication required but missing
< Frame includes HMAC authentication
< Session not initialized
< Frame includes HMAC authentication
< Operation successful
< Frame includes HMAC authentication
< Output buffer too small
< Operation successful
Definition at line 97 of file acp.c.
References ACP_ERR_AUTH_REQUIRED, ACP_ERR_BUFFER_TOO_SMALL, ACP_ERR_INVALID_PARAM, ACP_ERR_INVALID_TYPE, ACP_ERR_PAYLOAD_TOO_LARGE, ACP_ERR_SESSION_NOT_INIT, ACP_FLAG_AUTHENTICATED, acp_frame_encode(), acp_frame_requires_auth(), acp_hmac_sha256(), ACP_HMAC_TAG_LEN, acp_is_valid_frame_type(), ACP_KEY_SIZE, ACP_MAX_PAYLOAD_SIZE, ACP_OK, ACP_PROTOCOL_VERSION, acp_frame_t::flags, acp_session_t::key, acp_frame_t::length, acp_session_t::next_sequence, acp_frame_t::payload, acp_frame_t::sequence, acp_frame_t::type, and acp_frame_t::version.
acp_error_string()
const char * acp_error_string (acp_result_t result)
Get human-readable error string.
Parameters
[in] result Error code
Returns
Static string describing the error
acp_frame_create_command()
int acp_frame_create_command (acp_frame_t * frame, uint8_t msg_type, uint32_t sequence, uint8_t priority, const void * payload, size_t payload_len)
Create command frame.
< Invalid parameter passed
< Payload exceeds maximum size
< Operation successful
Definition at line 305 of file acp_framer.c.
References ACP_ERR_INVALID_PARAM, ACP_ERR_PAYLOAD_TOO_LARGE, ACP_MAX_PAYLOAD_SIZE, ACP_OK, ACP_PROTOCOL_VERSION, acp_frame_t::flags, acp_frame_t::length, acp_frame_t::payload, acp_frame_t::sequence, acp_frame_t::type, and acp_frame_t::version.
acp_frame_create_telemetry()
int acp_frame_create_telemetry (acp_frame_t * frame, uint8_t msg_type, uint32_t sequence, const void * payload, size_t payload_len)
Create telemetry frame.
< Invalid parameter passed
< Payload exceeds maximum size
< Operation successful
Definition at line 278 of file acp_framer.c.
References ACP_ERR_INVALID_PARAM, ACP_ERR_PAYLOAD_TOO_LARGE, ACP_MAX_PAYLOAD_SIZE, ACP_OK, ACP_PROTOCOL_VERSION, acp_frame_t::flags, acp_frame_t::length, acp_frame_t::payload, acp_frame_t::sequence, acp_frame_t::type, and acp_frame_t::version.
acp_frame_decode()
int acp_frame_decode (const uint8_t * input, size_t input_size, acp_frame_t * frame, size_t * bytes_consumed)
Decode wire format to ACP frame.
< Invalid parameter passed
< Need more input data
< Frame structure is malformed
< Need more input data
< Operation successful
< Frame structure is malformed
< Frame structure is malformed
< CRC16 verification failed
< Frame structure is malformed
< Frame includes HMAC authentication
< Payload exceeds maximum size
< Operation successful
Definition at line 131 of file acp_framer.c.
References acp_cobs_decode(), ACP_COBS_DELIMITER, acp_crc16_calculate(), ACP_ERR_CRC_MISMATCH, ACP_ERR_INVALID_PARAM, ACP_ERR_MALFORMED_FRAME, ACP_ERR_NEED_MORE_DATA, ACP_ERR_PAYLOAD_TOO_LARGE, ACP_FLAG_AUTHENTICATED, ACP_MAX_FRAME_SIZE, ACP_MAX_PAYLOAD_SIZE, ACP_OK, acp_wire_header_size(), acp_frame_t::flags, acp_frame_t::length, acp_frame_t::payload, acp_frame_t::sequence, acp_frame_t::type, and acp_frame_t::version.
Referenced by acp_decode_frame().
acp_frame_encode()
int acp_frame_encode (const acp_frame_t * frame, uint8_t * output, size_t output_size, size_t * bytes_written)
Encode ACP frame to wire format.
< Invalid parameter passed
< Output buffer too small
< Payload exceeds maximum size
< Frame includes HMAC authentication
< Operation successful
< Operation successful
Definition at line 46 of file acp_framer.c.
References ACP_COBS_DELIMITER, acp_cobs_encode(), acp_cobs_max_encoded_size(), acp_crc16_calculate(), ACP_ERR_BUFFER_TOO_SMALL, ACP_ERR_INVALID_PARAM, ACP_ERR_PAYLOAD_TOO_LARGE, ACP_FLAG_AUTHENTICATED, ACP_MAX_FRAME_SIZE, ACP_OK, acp_wire_header_size(), acp_frame_t::flags, acp_frame_t::length, acp_frame_t::payload, acp_frame_t::sequence, acp_frame_t::type, and acp_frame_t::version.
Referenced by acp_encode_frame().
acp_frame_encoded_size()
size_t acp_frame_encoded_size (const acp_frame_t * frame)
Calculate encoded frame size.
Definition at line 262 of file acp_framer.c.
References acp_cobs_max_encoded_size(), acp_wire_header_size(), acp_frame_t::flags, and acp_frame_t::length.
acp_frame_requires_auth()
bool acp_frame_requires_auth (uint8_t type)
Check if frame type requires authentication.
Parameters
[in] type Frame type to check
Returns
true if authentication required, false otherwise
Definition at line 330 of file acp.c.
References ACP_FRAME_TYPE_COMMAND, ACP_FRAME_TYPE_SYSTEM, and ACP_FRAME_TYPE_TELEMETRY.
Referenced by acp_decode_frame(), and acp_encode_frame().
acp_hmac_sha256()
void acp_hmac_sha256 (const uint8_t * key, size_t key_len, const uint8_t * data, size_t data_len, uint8_t * mac)
Compute HMAC-SHA256.
Parameters
[in] key HMAC key material
[in] key_len Length of key in bytes
[in] data Data to authenticate
[in] data_len Length of data in bytes
[out] mac Output buffer for MAC (32 bytes)
Compute HMAC-SHA256.
Parameters
key HMAC key
key_len Length of key in bytes
data Input data to authenticate
data_len Length of input data
mac Output MAC (16 bytes)
Definition at line 246 of file acp_crypto.c.
References acp_crypto_clear(), acp_sha256(), ACP_SHA256_BLOCK_SIZE, acp_sha256_final(), acp_sha256_init(), ACP_SHA256_SIZE, and acp_sha256_update().
Referenced by acp_decode_frame(), acp_encode_frame(), acp_hmac_self_test(), and acp_session_compute_hmac().
acp_htonl()
uint32_t acp_htonl (uint32_t host_val)
Convert host uint32 to network byte order.
Parameters
[in] host_val Host byte order value
Returns
Network byte order value
Definition at line 381 of file acp.c.
Referenced by acp_ntohl().
acp_htons()
uint16_t acp_htons (uint16_t host_val)
Convert host uint16 to network byte order.
Parameters
[in] host_val Host byte order value
Returns
Network byte order value
Definition at line 351 of file acp.c.
Referenced by acp_ntohs().
acp_init()
acp_result_t acp_init (void)
Initialize the ACP library.
Must be called before using any other ACP functions.
Returns
ACP_OK on success, error code on failure
< Operation successful
< Operation successful
Definition at line 57 of file acp.c.
References acp_crc16_init_table(), acp_initialized, and ACP_OK.
acp_is_valid_frame_type()
bool acp_is_valid_frame_type (uint8_t type)
Validate frame type.
Parameters
[in] type Frame type to validate
Returns
true if valid, false otherwise
Definition at line 314 of file acp.c.
References ACP_FRAME_TYPE_COMMAND, ACP_FRAME_TYPE_SYSTEM, and ACP_FRAME_TYPE_TELEMETRY.
Referenced by acp_encode_frame().
acp_keystore_clear()
acp_result_t acp_keystore_clear (void)
Clear all keys from keystore.
Returns
ACP_OK on success, error code on failure
< Operation successful
< Operation successful
Definition at line 257 of file acp_nvs.c.
References ACP_ERR_IO, ACP_KEYSTORE_PATH, and ACP_OK.
acp_keystore_get()
acp_result_t acp_keystore_get (uint32_t key_id, uint8_t * key_data, size_t key_size)
Get key from keystore.
Parameters
[in] key_id Key identifier
[out] key_data Buffer to receive key data
[in] key_size Size of key buffer (must be >= ACP_KEY_SIZE)
Returns
ACP_OK on success, ACP_ERR_KEY_NOT_FOUND if not found, other error codes on failure
< Invalid parameter passed
< Key not found in keystore
< Operation successful
< Key not found in keystore
Definition at line 111 of file acp_nvs.c.
References ACP_ERR_INVALID_FORMAT, ACP_ERR_INVALID_PARAM, ACP_ERR_IO, ACP_ERR_KEY_NOT_FOUND, ACP_KEY_SIZE, ACP_KEYSTORE_MAGIC, ACP_KEYSTORE_PATH, ACP_KEYSTORE_VERSION, ACP_OK, acp_keystore_header_t::key_count, acp_keystore_entry_t::key_data, acp_keystore_entry_t::key_id, acp_keystore_header_t::magic, and acp_keystore_header_t::version.
Referenced by acp_keystore_init_session().
acp_keystore_init()
acp_result_t acp_keystore_init (void)
Initialize keystore.
Returns
ACP_OK on success, error code on failure
< Operation successful
< Operation successful
Definition at line 77 of file acp_nvs.c.
References ACP_ERR_IO, ACP_KEYSTORE_MAGIC, ACP_KEYSTORE_PATH, ACP_KEYSTORE_VERSION, and ACP_OK.
Referenced by acp_keystore_set().
acp_keystore_init_session()
acp_result_t acp_keystore_init_session (acp_session_t * session, uint32_t key_id, uint64_t nonce)
Initialize session with key from keystore.
Convenience function that automatically retrieves key material from the keystore and initializes a session.
Parameters
[out] session Session to initialize
[in] key_id Key identifier to look up in keystore
[in] nonce Session nonce
Returns
ACP_OK on success, ACP_ERR_KEY_NOT_FOUND if key not found, other error codes on failure
This is the "default keystore get_key()" function that automatically retrieves the key material from the keystore based on key_id.
Parameters
[out] session Session to initialize
[in] key_id Key identifier to look up
[in] nonce Session nonce
Returns
ACP_OK on success, error code on failure
< Invalid parameter passed
< Operation successful
Definition at line 284 of file acp_nvs.c.
References ACP_ERR_INVALID_PARAM, ACP_KEY_SIZE, acp_keystore_get(), ACP_OK, and acp_session_init().
acp_keystore_set()
acp_result_t acp_keystore_set (uint32_t key_id, const uint8_t * key_data, size_t key_size)
Set key in keystore.
Parameters
[in] key_id Key identifier
[in] key_data Key data to store
[in] key_size Size of key data (must be ACP_KEY_SIZE)
Returns
ACP_OK on success, error code on failure
< Invalid parameter passed
< Operation successful
< Operation successful
< Operation successful
Definition at line 161 of file acp_nvs.c.
References ACP_ERR_INVALID_FORMAT, ACP_ERR_INVALID_PARAM, ACP_ERR_IO, ACP_KEY_SIZE, acp_keystore_init(), ACP_KEYSTORE_MAGIC, ACP_KEYSTORE_PATH, ACP_KEYSTORE_VERSION, ACP_OK, acp_keystore_header_t::key_count, acp_keystore_entry_t::key_data, acp_keystore_entry_t::key_id, acp_keystore_header_t::magic, and acp_keystore_header_t::version.
acp_ntohl()
uint32_t acp_ntohl (uint32_t net_val)
Convert network uint32 to host byte order.
Parameters
[in] net_val Network byte order value
Returns
Host byte order value
Definition at line 405 of file acp.c.
References acp_htonl().
acp_ntohs()
uint16_t acp_ntohs (uint16_t net_val)
Convert network uint16 to host byte order.
Parameters
[in] net_val Network byte order value
Returns
Host byte order value
Definition at line 372 of file acp.c.
References acp_htons().
acp_session_init()
acp_result_t acp_session_init (acp_session_t * session, uint32_t key_id, const uint8_t * key, size_t key_len, uint64_t nonce)
Initialize an ACP session.
Parameters
[out] session Session structure to initialize
[in] key_id Key identifier for keystore lookup
[in] key HMAC key material (32 bytes recommended)
[in] key_len Length of key material
[in] nonce Session nonce (should be unique)
Returns
ACP_OK on success, error code on failure
Initialize an ACP session.
Parameters
session Session context to initialize
session_id Unique session identifier
key Authentication key (32 bytes)
nonce Session nonce (16 bytes)
Returns
ACP_OK on success, error code on failure
Definition at line 49 of file acp_session.c.
References ACP_ERR_INVALID_PARAM, ACP_OK, acp_session_t::initialized, acp_session_t::key, acp_session_t::key_id, acp_session_t::last_accepted_seq, acp_session_t::next_sequence, and acp_session_t::nonce.
Referenced by acp_keystore_init_session().
acp_session_reset_sequence()
acp_result_t acp_session_reset_sequence (acp_session_t * session)
Reset session sequence counters.
Parameters
[in,out] session Session to reset
Returns
ACP_OK on success, error code on failure
acp_session_rotate()
acp_result_t acp_session_rotate (acp_session_t * session, const uint8_t * new_key, size_t new_key_len, uint64_t new_nonce)
Rotate session key or nonce.
Parameters
[in,out] session Session to rotate
[in] new_key New key material (NULL to keep current)
[in] new_key_len Length of new key
[in] new_nonce New nonce value
Returns
ACP_OK on success, error code on failure
Rotate session key or nonce.
Parameters
session Session context
new_key New authentication key (32 bytes)
new_nonce New session nonce (16 bytes)
Returns
ACP_OK on success, error code on failure
Definition at line 83 of file acp_session.c.
References acp_crypto_clear(), ACP_ERR_INVALID_PARAM, ACP_ERR_SESSION_NOT_INIT, ACP_OK, acp_session_t::initialized, acp_session_t::key, acp_session_t::last_accepted_seq, acp_session_t::next_sequence, and acp_session_t::nonce.
acp_wire_header_size()
size_t acp_wire_header_size (uint8_t flags) inline static
Calculate wire header size based on flags.
Parameters
flags Frame flags to determine header size
Returns
Size of wire header in bytes
< Frame includes HMAC authentication
Definition at line 156 of file acp_protocol.h.
References ACP_FLAG_AUTHENTICATED.
Referenced by acp_frame_decode(), acp_frame_encode(), and acp_frame_encoded_size().
Variable Documentation
acp_wire_header_base_t
acp_wire_header_base_t
Definition at line 126 of file acp_protocol.h.
acp_wire_header_t
acp_wire_header_t
Definition at line 142 of file acp_protocol.h.